"""
Illustration crop boxes, one entry per drawing.

GENERATED by find-book-illustrations.py and then REVIEWED BY EYE on a contact
sheet; only the boxes that actually contain a drawing are here. The detector
proposes, it does not decide -- on this file it offered 67 boxes and 36 were
drawings, the rest being rule lines, page numbers and stray lines of type that
happened to reach into the margin column.

Kept as plain data so any box can be nudged by hand without touching code.
Format: id -> (slug, page file, (left, top, right, bottom)).
"""

BOXES = {
    "1-common-p01-2": ("1-common", "p01.jpeg", ( 1797,  1144,  2433,  1728)),
    "1-common-p01-3": ("1-common", "p01.jpeg", ( 1797,  2006,  2433,  2344)),
    "1-common-p01-4": ("1-common", "p01.jpeg", ( 1797,  2395,  2433,  2763)),
    "1-common-p01-5": ("1-common", "p01.jpeg", ( 1802,  2827,  2431,  3158)),
    "1-common-p01-6": ("1-common", "p01.jpeg", ( 1825,  3249,  2414,  3586)),
    "1-common-p02-1": ("1-common", "p02.jpeg", ( 1326,    22,  1804,   566)),
    "1-common-p02-2": ("1-common", "p02.jpeg", ( 1326,   650,  1804,  1030)),
    "1-common-p02-3": ("1-common", "p02.jpeg", ( 1326,  1082,  1804,  1465)),
    "1-common-p02-4": ("1-common", "p02.jpeg", ( 1326,  1520,  1804,  1943)),
    "1-common-p02-5": ("1-common", "p02.jpeg", ( 1326,  1999,  1804,  2332)),
    "1-common-p02-6": ("1-common", "p02.jpeg", ( 1329,  2388,  1802,  2809)),
    "1-common-p03-1": ("1-common", "p03.jpeg", ( 2004,   150,  2710,   922)),
    "1-common-p03-2": ("1-common", "p03.jpeg", ( 2004,   992,  2710,  1410)),
    "1-common-p03-3": ("1-common", "p03.jpeg", ( 2004,  2230,  2710,  2862)),
    "1-common-p04-1": ("1-common", "p04.jpeg", ( 1809,  2581,  2447,  3050)),
    "1-common-p05-1": ("1-common", "p05.jpeg", ( 1738,   716,  2284,  1184)),
    "1-common-p05-3": ("1-common", "p05.jpeg", ( 1748,  2445,  2035,  2604)),
    "1-common-p05-4": ("1-common", "p05.jpeg", ( 1738,  3095,  2331,  3557)),
    "1-common-p07-3": ("1-common", "p07.jpeg", ( 1767,  2094,  2184,  2322)),
    "1-common-p07-4": ("1-common", "p07.jpeg", ( 1767,  2712,  2182,  3012)),
    "1-common-p09-2": ("1-common", "p09.jpeg", ( 1972,   725,  2666,  1081)),
    "1-common-p09-3": ("1-common", "p09.jpeg", ( 1972,  1316,  2666,  1788)),
    "1-common-p11-3": ("1-common", "p11.jpeg", ( 2072,   944,  2801,  1291)),
    "1-common-p11-4": ("1-common", "p11.jpeg", ( 2072,  1814,  2801,  2379)),
    "1-common-p11-6": ("1-common", "p11.jpeg", ( 2072,  3202,  2552,  3519)),
    "1-common-p11-7": ("1-common", "p11.jpeg", ( 2072,  3593,  2735,  4168)),
    "1-common-p15-2": ("1-common", "p15.jpeg", ( 1815,  2413,  2163,  2608)),
    "1-common-p15-3": ("1-common", "p15.jpeg", ( 1815,  2804,  2158,  3067)),
    "1-common-p17-3": ("1-common", "p17.jpeg", ( 1818,  3376,  2044,  3660)),
    "1-common-p21-2": ("1-common", "p21.jpeg", ( 1868,   373,  2528,   734)),
    "1-common-p21-3": ("1-common", "p21.jpeg", ( 1870,   803,  2528,  1052)),
    "1-common-p21-4": ("1-common", "p21.jpeg", ( 1868,  1140,  2528,  1536)),
    "1-common-p21-5": ("1-common", "p21.jpeg", ( 1868,  1838,  2528,  2233)),
    "1-common-p21-7": ("1-common", "p21.jpeg", ( 1868,  3375,  2499,  3924)),
    "1-common-p22-1": ("1-common", "p22.jpeg", ( 1548,  2809,  2101,  3348)),
    "1-common-p03-pranayama": ("1-common", "p03.jpeg", (   69,  3096,   723,  3760)),   # left margin; the only one this side
    # Page 20 is hand-measured. Its eight nyasa mudras march evenly down the
    # margin and the photograph carries a shadow gradient ACROSS the strip, so
    # the per-row contrast test marks 3278 of 3308 rows as inked and the whole
    # margin fuses into one run. A 2-D local estimate was tried and did worse on
    # the pages that already work, so this page is measured by eye instead.
    "1-common-p20-1": ("1-common", "p20.jpeg", ( 1597,   177,  1901,   423)),
    "1-common-p20-2": ("1-common", "p20.jpeg", ( 1606,   575,  1893,   828)),
    "1-common-p20-3": ("1-common", "p20.jpeg", ( 1682,  1039,  1901,  1318)),
    "1-common-p20-4": ("1-common", "p20.jpeg", ( 1682,  1428,  1901,  1690)),
    "1-common-p20-5": ("1-common", "p20.jpeg", ( 1682,  1673,  1901,  1927)),
    "1-common-p20-6": ("1-common", "p20.jpeg", ( 1682,  1952,  1901,  2214)),
    "1-common-p20-7": ("1-common", "p20.jpeg", ( 1682,  2248,  1901,  2501)),
    "1-common-p20-8": ("1-common", "p20.jpeg", ( 1622,  2670,  1918,  2941)),
    # Hand-measured, for the two shapes the margin detector cannot see:
    # a figure that spans the full text width (the four-panel palm-rubbing
    # sequence on p.21), and the upper-margin drawings on p.22, which the
    # shadow on that photograph swallows the same way it does on p.20.
    "1-common-p21-palms":      ("1-common", "p21.jpeg", (  124,  2760,  2338,  3337)),
    "1-common-p22-shirase":    ("1-common", "p22.jpeg", ( 1638,   255,  2075,   564)),
    "1-common-p22-shikhayai":  ("1-common", "p22.jpeg", ( 1638,   673,  2075,  1019)),
    "1-common-p22-kavachaya":  ("1-common", "p22.jpeg", ( 1629,  1147,  2075,  1538)),
    "1-common-p22-netratraya": ("1-common", "p22.jpeg", ( 1629,  1693,  2075,  2057)),
    "1-common-p22-astraya":    ("1-common", "p22.jpeg", ( 1567,  2225,  2101,  2646)),
    # Pages 24-25 set the invocation as a male/female pair of columns with the
    # mudra drawn BETWEEN them, so the drawings sit in the middle of the page
    # rather than in a margin and the detector cannot reach them at all.
    "1-common-p24-aavaahito":  ("1-common", "p24.jpeg", (  708,  2033,   924,  2264)),
    "1-common-p24-sthaapito":  ("1-common", "p24.jpeg", (  700,  2302,   924,  2541)),
    "1-common-p24-sannihito":  ("1-common", "p24.jpeg", (  693,  2587,   924,  2787)),
    "1-common-p25-sanniruddho":("1-common", "p25.jpeg", (  974,   534,  1485,   742)),
    "1-common-p25-avakunthito":("1-common", "p25.jpeg", (  974,   974,  1496,  1230)),
    "1-common-p25-supreeto":   ("1-common", "p25.jpeg", ( 1021,  1346,  1485,  1717)),
    "1-common-p25-suprasanno": ("1-common", "p25.jpeg", ( 1044,  1752,  1531,  2123)),
    "1-common-p25-sumukho":    ("1-common", "p25.jpeg", (  928,  2320,  1508,  2598)),
    "1-common-p25-varado":     ("1-common", "p25.jpeg", ( 1044,  2761,  1508,  3248)),
    "1-common-p26-ksheeram":   ("1-common", "p26.jpeg", (  490,  1270,  1209,  1989)),
    # The panchayatana arrangement is one composite diagram -- five deity
    # medallions with their compass labels -- so it is kept whole rather than
    # cut into the two pieces the margin detector found.
    "2-nitya-p01-panchayatana": ("2-nitya", "p01.jpeg", (  124,   802,  2430,  3150)),
    "2-nitya-p23-linga": ("2-nitya", "p23.jpeg", (  746,  2558,  1263,  3001)),
    "2-nitya-p26-lamps": ("2-nitya", "p26.jpeg", (  760,  3420,  1610,  4050)),
    # The only drawing in the whole Siddhivinayaka file. The margin detector
    # caught a sliver of it; this is the framed picture entire.
    "3-siddhivinayaka-p03-worship": ("3-siddhivinayaka", "p03.jpeg", (  377,  1432,  1486,  2926)),
    "3-siddhivinayaka-p27-pushpanjali": ("3-siddhivinayaka", "p27.jpeg", (  884,  3256,  1568,  3819)),
    "3-siddhivinayaka-p31-upayana": ("3-siddhivinayaka", "p31.jpeg", (  528,  2400,  1120,  2960)),
    "3-siddhivinayaka-p32-udvasanam": ("3-siddhivinayaka", "p32.jpeg", (  560,  2560,  1160,  3150)),
}
