#!/usr/bin/env node
/**
 * Generate the Tamil and roman transliteration columns from the canonical
 * Devanagari, and emit them as a migration.
 *
 * Why this exists: mantra_tamil is null on all 18 steps. Hand-typing the same
 * mantra in three scripts is how the data ended up with "ganesovaya", which is
 * not a word, and with an entirely empty Tamil layer. Devanagari is the single
 * source of truth; the other two are derived.
 *
 * Devanagari must stay canonical because Tamil cannot round-trip. Converting
 * "mahaganapataye" to plain Tamil and back yields "mahaghanabhadhaye": Tamil has
 * no separate letters for ga, kha and gha, so the information is destroyed. The
 * superscripted convention preserves it, and is what Tamil Nadu Sanskrit
 * publications print.
 *
 * Usage:
 *   node scripts/generate-scripts.mjs            # compare schemes, write nothing
 *   node scripts/generate-scripts.mjs --emit > supabase/migrations/0005_generate_scripts.sql
 *   node scripts/generate-scripts.mjs --scheme=tamil --emit
 */

import Sanscript from '@indic-transliteration/sanscript';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const REPO = fileURLToPath(new URL('..', import.meta.url));
const EXTRACT = `${REPO}/DB Extract`;

const args = process.argv.slice(2);
const emit = args.includes('--emit');
const scheme = (
  args.find((a) => a.startsWith('--scheme=')) ?? '--scheme=tamil_superscripted'
).split('=')[1];

const out = emit ? console.log : () => {};
const note = console.error;

// Placeholders such as [DYNAMIC_PANCHANGAM_DATA] must survive untouched, or the
// sankalpam template is destroyed. The danda and double danda need the same
// protection: the superscripted scheme rewrites them as "." and "..", which is
// a typographic downgrade for liturgical text.
const PLACEHOLDER = /\[[A-Z0-9_]+\]/g;
const DANDA = /[।॥]/g;

function transliterate(text, to) {
  if (!text) return null;
  const held = [];
  const hold = (m) => {
    held.push(m);
    return `${held.length - 1}`;
  };
  const masked = String(text).replace(PLACEHOLDER, hold).replace(DANDA, hold);
  const done = Sanscript.t(masked, 'devanagari', to);
  return done.replace(/(\d+)/g, (_, i) => held[Number(i)]);
}

const q = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);

const steps = JSON.parse(
  readFileSync(`${EXTRACT}/pooja_steps_rows.json`, 'utf8'),
).sort((a, b) => a.step_number - b.step_number);

const withMantra = steps.filter((s) => s.mantra_sanskrit);
note(
  `steps: ${steps.length}, with Devanagari source: ${withMantra.length}, without: ${
    steps.length - withMantra.length
  }`,
);
note(`target Tamil scheme: ${scheme}\n`);

if (!emit) {
  note('Compare the two Tamil conventions on your own mantras:\n');
  for (const s of withMantra.slice(0, 4)) {
    const src = s.mantra_sanskrit.slice(0, 64);
    note(`  ${s.step_title_en}`);
    note(`    devanagari    ${src}`);
    note(`    tamil         ${transliterate(src, 'tamil')}`);
    note(`    superscripted ${transliterate(src, 'tamil_superscripted')}`);
    note(`    iast          ${transliterate(src, 'iast')}`);
    note('');
  }
  note('Plain tamil cannot be read back: ga, kha and gha all collapse to one letter.');
  note('Superscripted keeps them apart, and keeps the visarga as the raised colon');
  note('your archana rows already use.');
  note('');
  note('Re-run with --emit to write the migration.');
}

out('-- =============================================================================');
out('-- 0005_generate_scripts.sql');
out('--');
out('-- GENERATED by scripts/generate-scripts.mjs. Do not hand-edit; re-run instead.');
out(`-- Tamil scheme: ${scheme}`);
out('--');
out('-- Derives mantra_tamil and mantra_translit from the canonical mantra_sanskrit.');
out('-- Devanagari stays the source of truth: Tamil cannot round-trip, because it');
out('-- has no separate letters for ga, kha and gha.');
out('-- =============================================================================');
out('');

// Known weak spot. In a conjunct the library places the superscript after the
// second letter when that letter is "ra", and after the first letter otherwise.
// I could not establish which placement the printed booklets use, so these are
// listed for a vaidika to check rather than silently trusted.
// NB: .test() on a /g/ regex advances lastIndex between calls and would skip
// every other row, so the predicate uses a fresh non-global regex.
const RA_CONJUNCT_G = /[गघजझडढदधबभ]्र/g;
const hasRaConjunct = (t) =>
  /[गघजझडढदधबभ]्र/.test(t);

const flagged = withMantra.filter((s) => hasRaConjunct(s.mantra_sanskrit));
if (flagged.length) {
  out('-- REVIEW BEFORE TRUSTING: conjunct superscript placement');
  out('-- A voiced consonant followed by "ra" puts the superscript after the ra.');
  out('-- Elsewhere it sits on the voiced letter itself. Check these against the');
  out('-- printed booklet; there are only a few.');
  for (const s of flagged) {
    const hits = [...new Set(s.mantra_sanskrit.match(RA_CONJUNCT_G) ?? [])];
    out(
      `--   "${s.step_title_en}": ${hits.join(' ')} -> ${hits
        .map((h) => transliterate(h, scheme))
        .join(' ')}`,
    );
  }
  out('');
}

out('begin;');
out('');

let n = 0;
for (const s of withMantra) {
  out(`-- ${s.step_number}. ${s.step_title_en}`);
  out(`update public.pooja_steps set
  mantra_tamil = ${q(transliterate(s.mantra_sanskrit, scheme))},
  mantra_translit = ${q(transliterate(s.mantra_sanskrit, 'iast'))},
  scripts_generated = true
where pooja_id = ${q(s.pooja_id)} and step_title_en = ${q(s.step_title_en)};`);
  out('');
  n++;
}

// The archana rows carry hand-entered Tamil that mixes conventions: the raised
// colon visarga from the superscripted scheme, but none of its superscripts.
// Regenerating makes all of them consistent with the steps above.
const archanaStep = steps.find((s) => s.archana_list);
if (archanaStep) {
  const items = JSON.parse(archanaStep.archana_list);
  out(`-- ${items.length} archana items, regenerated for consistency.`);
  items.forEach((it, i) => {
    if (!it.sanskrit) return;
    out(`update public.archana_items set
  invoked_name_ta = ${q(transliterate(it.sanskrit, scheme))},
  invoked_name_translit = ${q(transliterate(it.sanskrit, 'iast'))}
where seq = ${i + 1} and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = ${q(archanaStep.pooja_id)}
    and step_title_en = ${q(archanaStep.step_title_en)});`);
  });
  out('');
  note(`archana items regenerated: ${items.length}`);
}

out('commit;');
out('');
out('-- Verify:');
out('--   select count(*) from pooja_steps where mantra_tamil is null;  -- expect 2');
out('--   select count(*) from archana_items where invoked_name_ta is null;  -- expect 0');

note(`steps updated: ${n}`);
if (!emit) note('\n(no SQL written; pass --emit)');
