-- =============================================================================
-- 0005_generate_scripts.sql
--
-- GENERATED by scripts/generate-scripts.mjs. Do not hand-edit; re-run instead.
-- Tamil scheme: tamil_superscripted
--
-- Derives mantra_tamil and mantra_translit from the canonical mantra_sanskrit.
-- Safe to re-run: every statement is an idempotent UPDATE.
--
-- Corrects a transliteration library bug: the voicing superscript was being
-- deferred past a following ra or la, so bharata came out as pa-ra(4)-ta
-- instead of pa(4)-ra-ta. Verified with --selftest.
-- =============================================================================

begin;

-- 1. Achamanam
update public.pooja_steps set
  mantra_tamil = 'அச்யுதாய நம꞉ । அநந்தாய நம꞉ । கோ³விந்தா³ய நம꞉ ।',
  mantra_translit = 'acyutāya namaḥ । anantāya namaḥ । govindāya namaḥ ।',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Achamanam';

-- 3. Vighneshwara Dhyanam
update public.pooja_steps set
  mantra_tamil = 'ஶுக்லாம்ப³ரத⁴ரம்ʼ விஷ்ணும்ʼ ஶஶிவர்ணம்ʼ சதுர்பு⁴ஜம் । ப்ரஸந்நவத³நம்ʼ த்⁴யாயேத் ஸர்வவிக்⁴நோபஶாந்தயே ॥',
  mantra_translit = 'śuklāmbaradharaṃ viṣṇuṃ śaśivarṇaṃ caturbhujam । prasannavadanaṃ dhyāyet sarvavighnopaśāntaye ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Vighneshwara Dhyanam';

-- 4. Pranayamam
update public.pooja_steps set
  mantra_tamil = 'ௐ பூ⁴꞉ ௐ பு⁴வ꞉ ௐ ஸுவ꞉ ௐ மஹ꞉ ௐ ஜந꞉ ௐ தப꞉ ௐ ஸத்யம் । ௐ தத்ஸவிதுர்வரேண்யம்ʼ ப⁴ர்கோ³ தே³வஸ்ய தீ⁴மஹி தி⁴யோ யோ ந꞉ ப்ரசோத³யாத் ॥ ஓமாபோ ஜ்யோதீ ரஸோ(அ)ம்ருʼதம்ʼ ப்³ரஹ்ம பூ⁴ர்பு⁴வஸ்ஸுவரோம் ॥',
  mantra_translit = 'oṃ bhūḥ oṃ bhuvaḥ oṃ suvaḥ oṃ mahaḥ oṃ janaḥ oṃ tapaḥ oṃ satyam । oṃ tatsaviturvareṇyaṃ bhargo devasya dhīmahi dhiyo yo naḥ pracodayāt ॥ omāpo jyotī raso''mṛtaṃ brahma bhūrbhuvassuvarom ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Pranayamam';

-- 5. Sankalpam
update public.pooja_steps set
  mantra_tamil = 'ஶுபே⁴ ஶோப⁴நே முஹூர்தே ஆத்³ய ப்³ரஹ்மண꞉ த்³விதீய பரார்தே⁴ ஶ்வேத வராஹ கல்பே வைவஸ்வத மந்வந்தரே அஷ்டாவிம்ʼஶதிதமே கலியுகே³ ப்ரத²மே பாதே³ ஜம்பூ³த்³வீபே ப⁴ரத வர்ஷே ப⁴ரத க²ண்டே³ ... [DYNAMIC_PANCHANGAM_DATA] ... மம உபாத்த ஸமஸ்த து³ரித க்ஷயத்³வாரா ஶ்ரீ பரமேஶ்வர ப்ரீத்யர்த²ம்ʼ ஶ்ரீ மஹாக³ணபதி பூஜாம் கரிஷ்யே ॥',
  mantra_translit = 'śubhe śobhane muhūrte ādya brahmaṇaḥ dvitīya parārdhe śveta varāha kalpe vaivasvata manvantare aṣṭāviṃśatitame kaliyuge prathame pāde jambūdvīpe bharata varṣe bharata khaṇḍe ... [DYNAMIC_PANCHANGAM_DATA] ... mama upātta samasta durita kṣayadvārā śrī parameśvara prītyarthaṃ śrī mahāgaṇapati pūjām kariṣye ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Sankalpam';

-- 6. Kalasha Pooja
update public.pooja_steps set
  mantra_tamil = 'க³ங்கே³ ச யமுநே சைவ கோ³தா³வரி ஸரஸ்வதி । நர்மதே³ ஸிந்து⁴ காவேரி ஜலே(அ)ஸ்மிந் ஸம்ʼநிதி⁴ம்ʼ குரு ॥',
  mantra_translit = 'gaṅge ca yamune caiva godāvari sarasvati । narmade sindhu kāveri jale''smin saṃnidhiṃ kuru ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Kalasha Pooja';

-- 7. Ghanta Pooja
update public.pooja_steps set
  mantra_tamil = 'ஆக³மார்த²ம்ʼ து தே³வாநாம்ʼ க³மநார்த²ம்ʼ து ரக்ஷஸாம் । குரு க⁴ந்டாரவம்ʼ தத்ர தே³வதாவ்ஹாந லாஞ்ச²நம் ॥',
  mantra_translit = 'āgamārthaṃ tu devānāṃ gamanārthaṃ tu rakṣasām । kuru ghanṭāravaṃ tatra devatāvhāna lāñchanam ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Ghanta Pooja';

-- 8. Avahanam & Asanam
update public.pooja_steps set
  mantra_tamil = 'அஸ்மிந் ஹரித்³ரா பி³ம்பே³ ஶ்ரீ மஹாக³ணபதிம்ʼ ஆவாஹயாமி । ஆஸநார்தே² அக்ஷதாந் ஸமர்பயாமி ॥',
  mantra_translit = 'asmin haridrā bimbe śrī mahāgaṇapatiṃ āvāhayāmi । āsanārthe akṣatān samarpayāmi ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Avahanam & Asanam';

-- 9. Padyam & Arghyam
update public.pooja_steps set
  mantra_tamil = 'பாத³யோ꞉ பாத்³யம்ʼ ஸமர்பயாமி । ஹஸ்தயோ꞉ அர்க்⁴யம்ʼ ஸமர்பயாமி । முகே² ஆசமநீயம்ʼ ஸமர்பயாமி ॥',
  mantra_translit = 'pādayoḥ pādyaṃ samarpayāmi । hastayoḥ arghyaṃ samarpayāmi । mukhe ācamanīyaṃ samarpayāmi ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Padyam & Arghyam';

-- 10. Snanam & Vastram
update public.pooja_steps set
  mantra_tamil = 'ஸ்நாநம்ʼ ஸமர்பயாமி । வஸ்த்ரார்தே² அக்ஷதாந் ஸமர்பயாமி ॥',
  mantra_translit = 'snānaṃ samarpayāmi । vastrārthe akṣatān samarpayāmi ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Snanam & Vastram';

-- 11. Gandham, Kumkumam & Pushpam
update public.pooja_steps set
  mantra_tamil = 'தி³வ்ய ஶ்ரீ சந்த³நம்ʼ ஸமர்பயாமி । குங்குமம்ʼ ஸமர்பயாமி । புஷ்பை꞉ পূஜயாமி ॥',
  mantra_translit = 'divya śrī candanaṃ samarpayāmi । kuṅkumaṃ samarpayāmi । puṣpaiḥ পূjayāmi ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Gandham, Kumkumam & Pushpam';

-- 11. Anga Pooja
update public.pooja_steps set
  mantra_tamil = 'ௐ க³ணேஶ்வராய நம꞉ பாதௌ³ பூஜயாமி । ௐ விக்⁴நராஜாய நம꞉ ஜாநுநீ பூஜயாமி । ௐ ஆகு²வாஹநாய நம꞉ ஊரூ பூஜயாமி ...',
  mantra_translit = 'oṃ gaṇeśvarāya namaḥ pādau pūjayāmi । oṃ vighnarājāya namaḥ jānunī pūjayāmi । oṃ ākhuvāhanāya namaḥ ūrū pūjayāmi ...',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Anga Pooja';

-- 13. Dhoopam & Deepam
update public.pooja_steps set
  mantra_tamil = 'தூ⁴பமாக்⁴ராபயாமி । ப்ரத்யக்ஷ தீ³பம்ʼ த³ர்ஶயாமி । தூ⁴ப தீ³ப அநந்தரம்ʼ ஆசமநீயம்ʼ ஸமர்பயாமி ॥',
  mantra_translit = 'dhūpamāghrāpayāmi । pratyakṣa dīpaṃ darśayāmi । dhūpa dīpa anantaraṃ ācamanīyaṃ samarpayāmi ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Dhoopam & Deepam';

-- 14. Naivedyam
update public.pooja_steps set
  mantra_tamil = 'ௐ ப்ராணாய ஸ்வாஹா । ௐ அபாநாய ஸ்வாஹா । ௐ வ்யாநாய ஸ்வாஹா । ௐ உதா³நாய ஸ்வாஹா । ௐ ஸமாநாய ஸ்வாஹா । ஶ்ரீ மஹாக³ணபதயே நைவேத்³யம்ʼ ஸமர்பயாமி ॥',
  mantra_translit = 'oṃ prāṇāya svāhā । oṃ apānāya svāhā । oṃ vyānāya svāhā । oṃ udānāya svāhā । oṃ samānāya svāhā । śrī mahāgaṇapataye naivedyaṃ samarpayāmi ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Naivedyam';

-- 15. Karpura Neerajanam
update public.pooja_steps set
  mantra_tamil = 'கர்பூர நீராஜநம்ʼ ஸந்ததம்ʼ த³ர்ஶயாமி ।',
  mantra_translit = 'karpūra nīrājanaṃ santataṃ darśayāmi ।',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Karpura Neerajanam';

-- 16. Mantra Pushpam & Namaskaram
update public.pooja_steps set
  mantra_tamil = 'யாநி காநி ச பாபாநி ஜந்மாந்தர க்ருʼதாநி ச । தாநி தாநி விநஶ்யந்தி ப்ரத³க்ஷிண பதே³ பதே³ ॥ மந்த்ரபுஷ்பம்ʼ ஸமர்பயாமி ।',
  mantra_translit = 'yāni kāni ca pāpāni janmāntara kṛtāni ca । tāni tāni vinaśyanti pradakṣiṇa pade pade ॥ mantrapuṣpaṃ samarpayāmi ।',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Mantra Pushpam & Namaskaram';

-- 17. Kshama Prarthana & Conclusion
update public.pooja_steps set
  mantra_tamil = 'மந்த்ரஹீநம்ʼ க்ரியாஹீநம்ʼ ப⁴க்திஹீநம்ʼ க³ணாதி⁴ப । யத்பூஜிதம்ʼ மயா தே³வ பரிபூர்ணம்ʼ தத³ஸ்து தே ॥',
  mantra_translit = 'mantrahīnaṃ kriyāhīnaṃ bhaktihīnaṃ gaṇādhipa । yatpūjitaṃ mayā deva paripūrṇaṃ tadastu te ॥',
  scripts_generated = true
where pooja_id = 'ganesha_standard' and step_title_en = 'Kshama Prarthana & Conclusion';

-- 20 archana items.
update public.archana_items set
  invoked_name_ta = 'ௐ ஸுமுகா²ய நம꞉',
  invoked_name_translit = 'oṃ sumukhāya namaḥ'
where seq = 1 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ ஏகத³ந்தாய நம꞉',
  invoked_name_translit = 'oṃ ekadantāya namaḥ'
where seq = 2 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ கபிலாய நம꞉',
  invoked_name_translit = 'oṃ kapilāya namaḥ'
where seq = 3 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ க³ஜகர்ணகாய நம꞉',
  invoked_name_translit = 'oṃ gajakarṇakāya namaḥ'
where seq = 4 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ லம்போ³த³ராய நம꞉',
  invoked_name_translit = 'oṃ lambodarāya namaḥ'
where seq = 5 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ விகடாய நம꞉',
  invoked_name_translit = 'oṃ vikaṭāya namaḥ'
where seq = 6 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ விக்⁴நராஜாய நம꞉',
  invoked_name_translit = 'oṃ vighnarājāya namaḥ'
where seq = 7 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ க³ணாதி⁴பாய நம꞉',
  invoked_name_translit = 'oṃ gaṇādhipāya namaḥ'
where seq = 8 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ தூ⁴ம்ரகேதவே நம꞉',
  invoked_name_translit = 'oṃ dhūmraketave namaḥ'
where seq = 9 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ க³ணாத்⁴யக்ஷாய நம꞉',
  invoked_name_translit = 'oṃ gaṇādhyakṣāya namaḥ'
where seq = 10 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ பா⁴லசந்த்³ராய நம꞉',
  invoked_name_translit = 'oṃ bhālacandrāya namaḥ'
where seq = 11 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ க³ஜாநநாய நம꞉',
  invoked_name_translit = 'oṃ gajānanāya namaḥ'
where seq = 12 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ வக்ரதுண்டா³ய நம꞉',
  invoked_name_translit = 'oṃ vakratuṇḍāya namaḥ'
where seq = 13 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ ஶூர்பகர்ணாய நம꞉',
  invoked_name_translit = 'oṃ śūrpakarṇāya namaḥ'
where seq = 14 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ ஹேரம்பா³ய நம꞉',
  invoked_name_translit = 'oṃ herambāya namaḥ'
where seq = 15 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ ஸ்கந்த³பூர்வஜாய நம꞉',
  invoked_name_translit = 'oṃ skandapūrvajāya namaḥ'
where seq = 16 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ ஸித்³தி⁴ விநாயகாய நம꞉',
  invoked_name_translit = 'oṃ siddhi vināyakāya namaḥ'
where seq = 17 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ விக்⁴நகர்த்ரே நம꞉',
  invoked_name_translit = 'oṃ vighnakartre namaḥ'
where seq = 18 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ விக்⁴நஹர்த்ரே நம꞉',
  invoked_name_translit = 'oṃ vighnahartre namaḥ'
where seq = 19 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');
update public.archana_items set
  invoked_name_ta = 'ௐ ஶிவபுத்ராய நம꞉',
  invoked_name_translit = 'oṃ śivaputrāya namaḥ'
where seq = 20 and pooja_step_id = (
  select id from public.pooja_steps
  where pooja_id = 'ganesha_standard'
    and step_title_en = 'Pushpa Pooja (Archana)');

commit;
