-- =============================================================================
-- 0009_closing_steps_and_modes.sql
--
-- GENERATED by scripts/add-closing-steps.mjs.
--
-- Adds Ksheera Arghyam and Udvasanam, both of which Sathya Vadyar performs
-- and neither of which was in the database, and introduces pooja modes so a
-- multi-day observance can be driven:
--   main      day one, the full pooja
--   punar     a later day, abbreviated: the deity is already installed, so
--             Avahanam and Prana Pratishtha are not repeated
--   udvasana  the final day, which adds the release
-- Idempotent.
-- =============================================================================

begin;

alter table public.pooja_steps
  add column if not exists modes text[] not null default '{main}';

comment on column public.pooja_steps.modes is
  'Which pooja modes include this step: main, punar, udvasana.';

-- --- tag the existing steps ------------------------------------------------
update public.pooja_steps set modes = '{main,punar,udvasana}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Achamanam';
update public.pooja_steps set modes = '{main,punar}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Anga Vandanam';
update public.pooja_steps set modes = '{main,punar}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Vighneshwara Dhyanam';
update public.pooja_steps set modes = '{main,punar}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Pranayamam';
update public.pooja_steps set modes = '{main,punar,udvasana}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Sankalpam';
update public.pooja_steps set modes = '{main,punar}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Kalasha Pooja';
update public.pooja_steps set modes = '{main,punar,udvasana}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Ghanta Pooja';
update public.pooja_steps set modes = '{main}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Avahanam & Asanam';
update public.pooja_steps set modes = '{main,punar}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Padyam & Arghyam';
update public.pooja_steps set modes = '{main,punar}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Snanam & Vastram';
update public.pooja_steps set modes = '{main,punar}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Gandham, Kumkumam & Pushpam';
update public.pooja_steps set modes = '{main,punar}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Anga Pooja';
update public.pooja_steps set modes = '{main,punar}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Archana)';
update public.pooja_steps set modes = '{main,punar,udvasana}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Dhoopam & Deepam';
update public.pooja_steps set modes = '{main,punar,udvasana}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Naivedyam';
update public.pooja_steps set modes = '{main,punar,udvasana}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Karpura Neerajanam';
update public.pooja_steps set modes = '{main,punar,udvasana}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Mantra Pushpam & Namaskaram';
update public.pooja_steps set modes = '{main,punar,udvasana}'
where pooja_id = 'ganesha_standard' and step_title_en = 'Kshama Prarthana & Conclusion';

-- --- make room, then insert -------------------------------------------------
-- Ksheera Arghyam belongs after Mantra Pushpam and before the closing, so the
-- existing closing step moves from 18 to 19. Shift via negatives to dodge the
-- unique constraint on (pooja_id, step_number).
update public.pooja_steps set step_number = -19
where pooja_id = 'ganesha_standard' and step_number = 18;
update public.pooja_steps set step_number = 19
where pooja_id = 'ganesha_standard' and step_number = -19;

-- 18. Ksheera Arghyam
insert into public.pooja_steps
  (pooja_id, step_number, phase, modes, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   philosophy_en, gender_rule, scripts_generated, source_ref)
values ('ganesha_standard', 18, 'uttara', '{main,punar,udvasana}',
        'Ksheera Arghyam', 'க்ஷீர அர்க்யம்',
        'Mix a little water into raw milk. Holding the uddharani, pour the arghyam three times after each of the three verses, nine pourings in all. This is offered to Ganesha, not to the moon; the moon is deliberately not looked at today.',
        'பச்சைப் பாலில் சிறிது நீர் கலக்கவும். உத்தரிணியால், மூன்று ஸ்லோகங்களில் ஒவ்வொன்றுக்கும் பின் மூன்று முறை வீதம், மொத்தம் ஒன்பது முறை அர்க்யம் விடவும். இது விநாயகருக்கு சமர்ப்பிக்கப்படுகிறது; இன்று சந்திரனைப் பார்க்கக் கூடாது.',
        'गौर्यङ्गमल सम्भूत ज्येष्ठस्वामिन् गणेश्वर । गृहाणार्घ्यं मया दत्तं गजवक्त्र नमोऽस्तु ते ॥ अर्घ्यं गृहाण हेरम्ब सर्व सिद्धि प्रदायक । विनायक मया दत्तं पुष्पाक्षत समन्वितम् ॥ विनायक नमस्तेऽस्तु गन्ध पुष्पाक्षतैर्युतम् । गृहाणार्घ्यं मया दत्तं सर्वाभीष्ट प्रदो भव ॥ आनेन अर्घ्य प्रदानेन भगवान् सर्वात्मकः सिद्धि विनायकः प्रीयताम् ॥',
        'கௌர்யங்கமல ஸம்பூத ஜ்யேஷ்டஸ்வாமிந் கணேஶ்வர । க்ருஹாணார்க்யம் மயா தத்தம் கஜவக்த்ர நமோऽஸ்து தே ॥ அர்க்யம் க்ருஹாண ஹேரம்ப ஸர்வ ஸித்தி ப்ரதாயக । விநாயக மயா தத்தம் புஷ்பாக்ஷத ஸமந்விதம் ॥ விநாயக நமஸ்தேऽஸ்து கந்த புஷ்பாக்ஷதைர்யுதம் । க்ருஹாணார்க்யம் மயா தத்தம் ஸர்வாபீஷ்ட ப்ரதோ பவ ॥ ஆநேந அர்க்ய ப்ரதாநேந பகவாந் ஸர்வாத்மக꞉ ஸித்தி விநாயக꞉ ப்ரீயதாம் ॥',
        'gauryaṅgamala sambhūta jyeṣṭhasvāmin gaṇeśvara । gṛhāṇārghyaṃ mayā dattaṃ gajavaktra namo''stu te ॥ arghyaṃ gṛhāṇa heramba sarva siddhi pradāyaka । vināyaka mayā dattaṃ puṣpākṣata samanvitam ॥ vināyaka namaste''stu gandha puṣpākṣatairyutam । gṛhāṇārghyaṃ mayā dattaṃ sarvābhīṣṭa prado bhava ॥ ānena arghya pradānena bhagavān sarvātmakaḥ siddhi vināyakaḥ prīyatām ॥',
        'Arghyam is the water offered to an honoured guest on arrival and again on leaving. Giving it in milk at the close returns the hospitality the whole pooja has been: the guest is seen out as carefully as he was received.', 'all', true, 'Sathya Vadyar, Ganesha Chaturthi 2026; Tamil Smartha ksheerarghya pradanam')
on conflict (pooja_id, step_number) do update set
  step_title_en = excluded.step_title_en,
  step_title_ta = excluded.step_title_ta,
  instruction_en = excluded.instruction_en,
  instruction_ta = excluded.instruction_ta,
  mantra_sanskrit = excluded.mantra_sanskrit,
  mantra_tamil = excluded.mantra_tamil,
  mantra_translit = excluded.mantra_translit,
  philosophy_en = excluded.philosophy_en,
  modes = excluded.modes,
  phase = excluded.phase,
  source_ref = excluded.source_ref;

-- 20. Udvasanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, modes, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   philosophy_en, gender_rule, scripts_generated, source_ref)
values ('ganesha_standard', 20, 'uttara', '{udvasana}',
        'Udvasanam', 'உத்வாசனம்',
        'On the final day only. Move the idol slightly from its seat to release the presence invoked into it at Prana Pratishtha, then take leave. A clay image is immersed afterwards; a permanent metal idol or a photograph is not immersed, only moved.',
        'இறுதி நாளில் மட்டும். பிராண பிரதிஷ்டையில் எழுந்தருளச் செய்த சாந்நித்தியத்தை விடுவிக்க, விக்கிரகத்தை அதன் இடத்திலிருந்து சிறிது நகர்த்தி விடைபெறவும். களிமண் விக்கிரகம் பின்னர் கரைக்கப்படும்; நிரந்தர உலோக விக்கிரகமோ படமோ கரைக்கப்படுவதில்லை, நகர்த்தப்படுகிறது மட்டுமே.',
        'यज्ञेन यज्ञमयजन्त देवाः तानि धर्माणि प्रथमान्यासन् । श्री महागणपतये नमः यथास्थानं उद्वासयामि ॥',
        'யஜ்ஞேந யஜ்ஞமயஜந்த தேவா꞉ தாநி தர்மாணி ப்ரதமாந்யாஸந் । ஶ்ரீ மஹாகணபதயே நம꞉ யதாஸ்தாநம் உத்வாஸயாமி ॥',
        'yajñena yajñamayajanta devāḥ tāni dharmāṇi prathamānyāsan । śrī mahāgaṇapataye namaḥ yathāsthānaṃ udvāsayāmi ॥',
        'Prana Pratishtha made the clay a living presence, so something has to formally end that. Without Udvasanam the pooja is not closed. It is the step the diaspora most often does not know exists.', 'all', true, 'Tamil Smartha paddhati; Sathya Vadyar Punar Pooja chapter')
on conflict (pooja_id, step_number) do update set
  step_title_en = excluded.step_title_en,
  step_title_ta = excluded.step_title_ta,
  instruction_en = excluded.instruction_en,
  instruction_ta = excluded.instruction_ta,
  mantra_sanskrit = excluded.mantra_sanskrit,
  mantra_tamil = excluded.mantra_tamil,
  mantra_translit = excluded.mantra_translit,
  philosophy_en = excluded.philosophy_en,
  modes = excluded.modes,
  phase = excluded.phase,
  source_ref = excluded.source_ref;

commit;

-- Verify:
--   select step_number, step_title_en, modes from pooja_steps order by step_number;
--   select count(*) from pooja_steps where 'main' = any(modes);      -- 19
--   select count(*) from pooja_steps where 'punar' = any(modes);     -- 18
--   select count(*) from pooja_steps where 'udvasana' = any(modes);  -- 10
