-- =============================================================================
-- 0010_ganesha_content.sql
--
-- GENERATED by scripts/build-ganesha-content.mjs. Do not hand-edit.
--
-- Completes the Ganesha Chaturthi pooja against Sathya Vadyar's step-by-step
-- video, which docs/sources.md records as the primary reference for SEQUENCE.
-- Every mantra here comes from a published text; where published texts
-- disagree, the disagreement is recorded rather than silently resolved.
--
-- Adds    Prana Pratishtha, Patra Pooja (21), Durva Pooja (21),
--         Ganapathi Ashtottara Shatanamavali (108)
-- Fixes   Pushpa Pooja: vinayakaya restored at 8 per the Shodashanama verse,
--         four surplus names removed
-- Fixes   deities.ganesha forbade tulasi; the vadyar uses it
--
-- Steps go from 20 to 24 and are renumbered. Idempotent.
-- =============================================================================

begin;

-- --- tulasi ------------------------------------------------------------------
-- The original content carried the Brahma Vaivarta prohibition. Sathya Vadyar
-- lists thulasi among the leaves he uses, and it sits at position 8 of the
-- patra list below, so the prohibition does not describe this practice.
update public.deities set
  forbidden_offerings = '{}'::jsonb,
  permitted_offerings = '{"leaves":["macī","bṛhatī","bilva","dūrvā","dattūra","badarī","apāmārga","tulasī","cūta","karavīra","viṣṇukrānta","dāḍimī","devadāru","maruvaka","sindhuvāra","jātī","gaṇḍakī","śamī","aśvattha","arjuna","arka"],"note":"Tulasi is used. Sathya Vadyar lists it among the leaves for Ganesha Chaturthi."}'::jsonb,
  updated_at = now()
where id = 'ganesha';

-- --- the 108 names -----------------------------------------------------------
insert into public.namavalis (id, deity_id, recension, name_count, source_ref)
values ('ganesha_ashtottara_108', 'ganesha', 'South Indian, opening gajananaya and closing varasiddhivinayakaya', 108,
        'StotraNidhi Sri Ganesha Ashtottara Shatanamavali; Devanagari, Tamil and IAST pages cross-validated by scripts/parse-namavali.mjs')
on conflict (id) do update set
  recension = excluded.recension, source_ref = excluded.source_ref;

insert into public.namavali_items (namavali_id, seq, name_deva, name_ta, name_translit) values
  ('ganesha_ashtottara_108', 1, 'ॐ गजाननाय नमः', 'ஓம் கஜாநநாய நம꞉', 'ōṁ gajānanāya namaḥ'),
  ('ganesha_ashtottara_108', 2, 'ॐ गणाध्यक्षाय नमः', 'ஓம் கணாத்யக்ஷாய நம꞉', 'ōṁ gaṇādhyakṣāya namaḥ'),
  ('ganesha_ashtottara_108', 3, 'ॐ विघ्नराजाय नमः', 'ஓம் விக்நராஜாய நம꞉', 'ōṁ vighnarājāya namaḥ'),
  ('ganesha_ashtottara_108', 4, 'ॐ विनायकाय नमः', 'ஓம் விநாயகாய நம꞉', 'ōṁ vināyakāya namaḥ'),
  ('ganesha_ashtottara_108', 5, 'ॐ द्वैमातुराय नमः', 'ஓம் த்வைமாதுராய நம꞉', 'ōṁ dvaimāturāya namaḥ'),
  ('ganesha_ashtottara_108', 6, 'ॐ सुमुखाय नमः', 'ஓம் ஸுமுகாய நம꞉', 'ōṁ sumukhāya namaḥ'),
  ('ganesha_ashtottara_108', 7, 'ॐ प्रमुखाय नमः', 'ஓம் ப்ரமுகாய நம꞉', 'ōṁ pramukhāya namaḥ'),
  ('ganesha_ashtottara_108', 8, 'ॐ सन्मुखाय नमः', 'ஓம் ஸந்முகாய நம꞉', 'ōṁ sanmukhāya namaḥ'),
  ('ganesha_ashtottara_108', 9, 'ॐ कृतिने नमः', 'ஓம் க்ருதிநே நம꞉', 'ōṁ kr̥tinē namaḥ'),
  ('ganesha_ashtottara_108', 10, 'ॐ ज्ञानदीपाय नमः', 'ஓம் ஜ்ஞாநதீபாய நம꞉', 'ōṁ jñānadīpāya namaḥ'),
  ('ganesha_ashtottara_108', 11, 'ॐ सुखनिधये नमः', 'ஓம் ஸுகநிதயே நம꞉', 'ōṁ sukhanidhayē namaḥ'),
  ('ganesha_ashtottara_108', 12, 'ॐ सुराध्यक्षाय नमः', 'ஓம் ஸுராத்யக்ஷாய நம꞉', 'ōṁ surādhyakṣāya namaḥ'),
  ('ganesha_ashtottara_108', 13, 'ॐ सुरारिभिदे नमः', 'ஓம் ஸுராரிபிதே நம꞉', 'ōṁ surāribhidē namaḥ'),
  ('ganesha_ashtottara_108', 14, 'ॐ महागणपतये नमः', 'ஓம் மஹாகணபதயே நம꞉', 'ōṁ mahāgaṇapatayē namaḥ'),
  ('ganesha_ashtottara_108', 15, 'ॐ मान्याय नमः', 'ஓம் மாந்யாய நம꞉', 'ōṁ mānyāya namaḥ'),
  ('ganesha_ashtottara_108', 16, 'ॐ महन्मान्याय नमः', 'ஓம் மஹந்மாந்யாய நம꞉', 'ōṁ mahanmānyāya namaḥ'),
  ('ganesha_ashtottara_108', 17, 'ॐ मृडात्मजाय नमः', 'ஓம் ம்ருடாத்மஜாய நம꞉', 'ōṁ mr̥ḍātmajāya namaḥ'),
  ('ganesha_ashtottara_108', 18, 'ॐ पुराणाय नमः', 'ஓம் புராணாய நம꞉', 'ōṁ purāṇāya namaḥ'),
  ('ganesha_ashtottara_108', 19, 'ॐ पुरुषाय नमः', 'ஓம் புருஷாய நம꞉', 'ōṁ puruṣāya namaḥ'),
  ('ganesha_ashtottara_108', 20, 'ॐ पूष्णे नमः', 'ஓம் பூஷ்ணே நம꞉', 'ōṁ pūṣṇē namaḥ'),
  ('ganesha_ashtottara_108', 21, 'ॐ पुष्करिणे नमः', 'ஓம் புஷ்கரிணே நம꞉', 'ōṁ puṣkariṇē namaḥ'),
  ('ganesha_ashtottara_108', 22, 'ॐ पुण्यकृते नमः', 'ஓம் புண்யக்ருதே நம꞉', 'ōṁ puṇyakr̥tē namaḥ'),
  ('ganesha_ashtottara_108', 23, 'ॐ अग्रगण्याय नमः', 'ஓம் அக்ரகண்யாய நம꞉', 'ōṁ agragaṇyāya namaḥ'),
  ('ganesha_ashtottara_108', 24, 'ॐ अग्रपूज्याय नमः', 'ஓம் அக்ரபூஜ்யாய நம꞉', 'ōṁ agrapūjyāya namaḥ'),
  ('ganesha_ashtottara_108', 25, 'ॐ अग्रगामिने नमः', 'ஓம் அக்ரகாமிநே நம꞉', 'ōṁ agragāminē namaḥ'),
  ('ganesha_ashtottara_108', 26, 'ॐ मन्त्रकृते नमः', 'ஓம் மந்த்ரக்ருதே நம꞉', 'ōṁ mantrakr̥tē namaḥ'),
  ('ganesha_ashtottara_108', 27, 'ॐ चामीकरप्रभाय नमः', 'ஓம் சாமீகரப்ரபாய நம꞉', 'ōṁ cāmīkaraprabhāya namaḥ'),
  ('ganesha_ashtottara_108', 28, 'ॐ सर्वस्मै नमः', 'ஓம் ஸர்வஸ்மை நம꞉', 'ōṁ sarvasmai namaḥ'),
  ('ganesha_ashtottara_108', 29, 'ॐ सर्वोपास्याय नमः', 'ஓம் ஸர்வோபாஸ்யாய நம꞉', 'ōṁ sarvōpāsyāya namaḥ'),
  ('ganesha_ashtottara_108', 30, 'ॐ सर्वकर्त्रे नमः', 'ஓம் ஸர்வகர்த்ரே நம꞉', 'ōṁ sarvakartrē namaḥ'),
  ('ganesha_ashtottara_108', 31, 'ॐ सर्वनेत्रे नमः', 'ஓம் ஸர்வநேத்ரே நம꞉', 'ōṁ sarvanētrē namaḥ'),
  ('ganesha_ashtottara_108', 32, 'ॐ सर्वसिद्धिप्रदाय नमः', 'ஓம் ஸர்வஸித்திப்ரதாய நம꞉', 'ōṁ sarvasiddhipradāya namaḥ'),
  ('ganesha_ashtottara_108', 33, 'ॐ सर्वसिद्धाय नमः', 'ஓம் ஸர்வஸித்தாய நம꞉', 'ōṁ sarvasiddhāya namaḥ'),
  ('ganesha_ashtottara_108', 34, 'ॐ सर्ववन्द्याय नमः', 'ஓம் ஸர்வவந்த்யாய நம꞉', 'ōṁ sarvavandyāya namaḥ'),
  ('ganesha_ashtottara_108', 35, 'ॐ महाकालाय नमः', 'ஓம் மஹாகாலாய நம꞉', 'ōṁ mahākālāya namaḥ'),
  ('ganesha_ashtottara_108', 36, 'ॐ महाबलाय नमः', 'ஓம் மஹாபலாய நம꞉', 'ōṁ mahābalāya namaḥ'),
  ('ganesha_ashtottara_108', 37, 'ॐ हेरम्बाय नमः', 'ஓம் ஹேரம்பாய நம꞉', 'ōṁ hērambāya namaḥ'),
  ('ganesha_ashtottara_108', 38, 'ॐ लम्बजठराय नमः', 'ஓம் லம்பஜடராய நம꞉', 'ōṁ lambajaṭharāya namaḥ'),
  ('ganesha_ashtottara_108', 39, 'ॐ ह्रस्वग्रीवाय नमः', 'ஓம் ஹ்ரஸ்வக்ரீவாய நம꞉', 'ōṁ hrasvagrīvāya namaḥ'),
  ('ganesha_ashtottara_108', 40, 'ॐ महोदराय नमः', 'ஓம் மஹோதராய நம꞉', 'ōṁ mahōdarāya namaḥ'),
  ('ganesha_ashtottara_108', 41, 'ॐ मदोत्कटाय नमः', 'ஓம் மதோத்கடாய நம꞉', 'ōṁ madōtkaṭāya namaḥ'),
  ('ganesha_ashtottara_108', 42, 'ॐ महावीराय नमः', 'ஓம் மஹாவீராய நம꞉', 'ōṁ mahāvīrāya namaḥ'),
  ('ganesha_ashtottara_108', 43, 'ॐ मन्त्रिणे नमः', 'ஓம் மந்த்ரிணே நம꞉', 'ōṁ mantriṇē namaḥ'),
  ('ganesha_ashtottara_108', 44, 'ॐ मङ्गलदाय नमः', 'ஓம் மங்களதாய நம꞉', 'ōṁ maṅgaladāya namaḥ'),
  ('ganesha_ashtottara_108', 45, 'ॐ प्रथमाचार्याय नमः', 'ஓம் ப்ரதமாசார்யாய நம꞉', 'ōṁ prathamācāryāya namaḥ'),
  ('ganesha_ashtottara_108', 46, 'ॐ प्राज्ञाय नमः', 'ஓம் ப்ராஜ்ஞாய நம꞉', 'ōṁ prājñāya namaḥ'),
  ('ganesha_ashtottara_108', 47, 'ॐ प्रमोदाय नमः', 'ஓம் ப்ரமோதாய நம꞉', 'ōṁ pramōdāya namaḥ'),
  ('ganesha_ashtottara_108', 48, 'ॐ मोदकप्रियाय नमः', 'ஓம் மோதகப்ரியாய நம꞉', 'ōṁ mōdakapriyāya namaḥ'),
  ('ganesha_ashtottara_108', 49, 'ॐ धृतिमते नमः', 'ஓம் த்ருதிமதே நம꞉', 'ōṁ dhr̥timatē namaḥ'),
  ('ganesha_ashtottara_108', 50, 'ॐ मतिमते नमः', 'ஓம் மதிமதே நம꞉', 'ōṁ matimatē namaḥ'),
  ('ganesha_ashtottara_108', 51, 'ॐ कामिने नमः', 'ஓம் காமிநே நம꞉', 'ōṁ kāminē namaḥ'),
  ('ganesha_ashtottara_108', 52, 'ॐ कपित्थपनसप्रियाय नमः', 'ஓம் கபித்தபநஸப்ரியாய நம꞉', 'ōṁ kapitthapanasapriyāya namaḥ'),
  ('ganesha_ashtottara_108', 53, 'ॐ ब्रह्मचारिणे नमः', 'ஓம் ப்ரஹ்மசாரிணே நம꞉', 'ōṁ brahmacāriṇē namaḥ'),
  ('ganesha_ashtottara_108', 54, 'ॐ ब्रह्मरूपिणे नमः', 'ஓம் ப்ரஹ்மரூபிணே நம꞉', 'ōṁ brahmarūpiṇē namaḥ'),
  ('ganesha_ashtottara_108', 55, 'ॐ ब्रह्मविदे नमः', 'ஓம் ப்ரஹ்மவிதே நம꞉', 'ōṁ brahmavidē namaḥ'),
  ('ganesha_ashtottara_108', 56, 'ॐ ब्रह्मवन्दिताय नमः', 'ஓம் ப்ரஹ்மவந்திதாய நம꞉', 'ōṁ brahmavanditāya namaḥ'),
  ('ganesha_ashtottara_108', 57, 'ॐ जिष्णवे नमः', 'ஓம் ஜிஷ்ணவே நம꞉', 'ōṁ jiṣṇavē namaḥ'),
  ('ganesha_ashtottara_108', 58, 'ॐ विष्णुप्रियाय नमः', 'ஓம் விஷ்ணுப்ரியாய நம꞉', 'ōṁ viṣṇupriyāya namaḥ'),
  ('ganesha_ashtottara_108', 59, 'ॐ भक्तजीविताय नमः', 'ஓம் பக்தஜீவிதாய நம꞉', 'ōṁ bhaktajīvitāya namaḥ'),
  ('ganesha_ashtottara_108', 60, 'ॐ जितमन्मथाय नमः', 'ஓம் ஜிதமந்மதாய நம꞉', 'ōṁ jitamanmathāya namaḥ'),
  ('ganesha_ashtottara_108', 61, 'ॐ ऐश्वर्यदाय नमः', 'ஓம் ஐஶ்வர்யதாய நம꞉', 'ōṁ aiśvaryadāya namaḥ'),
  ('ganesha_ashtottara_108', 62, 'ॐ गुहज्यायसे नमः', 'ஓம் குஹஜ்யாயஸே நம꞉', 'ōṁ guhajyāyasē namaḥ'),
  ('ganesha_ashtottara_108', 63, 'ॐ सिद्धसेविताय नमः', 'ஓம் ஸித்தஸேவிதாய நம꞉', 'ōṁ siddhasēvitāya namaḥ'),
  ('ganesha_ashtottara_108', 64, 'ॐ विघ्नकर्त्रे नमः', 'ஓம் விக்நகர்த்ரே நம꞉', 'ōṁ vighnakartrē namaḥ'),
  ('ganesha_ashtottara_108', 65, 'ॐ विघ्नहर्त्रे नमः', 'ஓம் விக்நஹர்த்ரே நம꞉', 'ōṁ vighnahartrē namaḥ'),
  ('ganesha_ashtottara_108', 66, 'ॐ विश्वनेत्रे नमः', 'ஓம் விஶ்வநேத்ரே நம꞉', 'ōṁ viśvanētrē namaḥ'),
  ('ganesha_ashtottara_108', 67, 'ॐ विराजे नमः', 'ஓம் விராஜே நம꞉', 'ōṁ virājē namaḥ'),
  ('ganesha_ashtottara_108', 68, 'ॐ स्वराजे नमः', 'ஓம் ஸ்வராஜே நம꞉', 'ōṁ svarājē namaḥ'),
  ('ganesha_ashtottara_108', 69, 'ॐ श्रीपतये नमः', 'ஓம் ஶ்ரீபதயே நம꞉', 'ōṁ śrīpatayē namaḥ'),
  ('ganesha_ashtottara_108', 70, 'ॐ वाक्पतये नमः', 'ஓம் வாக்பதயே நம꞉', 'ōṁ vākpatayē namaḥ'),
  ('ganesha_ashtottara_108', 71, 'ॐ श्रीमते नमः', 'ஓம் ஶ்ரீமதே நம꞉', 'ōṁ śrīmatē namaḥ'),
  ('ganesha_ashtottara_108', 72, 'ॐ शृङ्गारिणे नमः', 'ஓம் ஶ்ருங்காரிணே நம꞉', 'ōṁ śr̥ṅgāriṇē namaḥ'),
  ('ganesha_ashtottara_108', 73, 'ॐ श्रितवत्सलाय नमः', 'ஓம் ஶ்ரிதவத்ஸலாய நம꞉', 'ōṁ śritavatsalāya namaḥ'),
  ('ganesha_ashtottara_108', 74, 'ॐ शिवप्रियाय नमः', 'ஓம் ஶிவப்ரியாய நம꞉', 'ōṁ śivapriyāya namaḥ'),
  ('ganesha_ashtottara_108', 75, 'ॐ शीघ्रकारिणे नमः', 'ஓம் ஶீக்ரகாரிணே நம꞉', 'ōṁ śīghrakāriṇē namaḥ'),
  ('ganesha_ashtottara_108', 76, 'ॐ शाश्वताय नमः', 'ஓம் ஶாஶ்வதாய நம꞉', 'ōṁ śāśvatāya namaḥ'),
  ('ganesha_ashtottara_108', 77, 'ॐ शिवनन्दनाय नमः', 'ஓம் ஶிவநந்தநாய நம꞉', 'ōṁ śivanandanāya namaḥ'),
  ('ganesha_ashtottara_108', 78, 'ॐ बलोद्धताय नमः', 'ஓம் பலோத்ததாய நம꞉', 'ōṁ balōddhatāya namaḥ'),
  ('ganesha_ashtottara_108', 79, 'ॐ भक्तनिधये नमः', 'ஓம் பக்தநிதயே நம꞉', 'ōṁ bhaktanidhayē namaḥ'),
  ('ganesha_ashtottara_108', 80, 'ॐ भावगम्याय नमः', 'ஓம் பாவகம்யாய நம꞉', 'ōṁ bhāvagamyāya namaḥ'),
  ('ganesha_ashtottara_108', 81, 'ॐ भवात्मजाय नमः', 'ஓம் பவாத்மஜாய நம꞉', 'ōṁ bhavātmajāya namaḥ'),
  ('ganesha_ashtottara_108', 82, 'ॐ महते नमः', 'ஓம் மஹதே நம꞉', 'ōṁ mahatē namaḥ'),
  ('ganesha_ashtottara_108', 83, 'ॐ मङ्गलदायिने नमः', 'ஓம் மங்களதாயிநே நம꞉', 'ōṁ maṅgaladāyinē namaḥ'),
  ('ganesha_ashtottara_108', 84, 'ॐ महेशाय नमः', 'ஓம் மஹேஶாய நம꞉', 'ōṁ mahēśāya namaḥ'),
  ('ganesha_ashtottara_108', 85, 'ॐ महिताय नमः', 'ஓம் மஹிதாய நம꞉', 'ōṁ mahitāya namaḥ'),
  ('ganesha_ashtottara_108', 86, 'ॐ सत्यधर्मिणे नमः', 'ஓம் ஸத்யதர்மிணே நம꞉', 'ōṁ satyadharmiṇē namaḥ'),
  ('ganesha_ashtottara_108', 87, 'ॐ सदाधाराय नमः', 'ஓம் ஸதாதாராய நம꞉', 'ōṁ sadādhārāya namaḥ'),
  ('ganesha_ashtottara_108', 88, 'ॐ सत्याय नमः', 'ஓம் ஸத்யாய நம꞉', 'ōṁ satyāya namaḥ'),
  ('ganesha_ashtottara_108', 89, 'ॐ सत्यपराक्रमाय नमः', 'ஓம் ஸத்யபராக்ரமாய நம꞉', 'ōṁ satyaparākramāya namaḥ'),
  ('ganesha_ashtottara_108', 90, 'ॐ शुभाङ्गाय नमः', 'ஓம் ஶுபாங்காய நம꞉', 'ōṁ śubhāṅgāya namaḥ'),
  ('ganesha_ashtottara_108', 91, 'ॐ शुभ्रदन्ताय नमः', 'ஓம் ஶுப்ரதந்தாய நம꞉', 'ōṁ śubhradantāya namaḥ'),
  ('ganesha_ashtottara_108', 92, 'ॐ शुभदाय नमः', 'ஓம் ஶுபதாய நம꞉', 'ōṁ śubhadāya namaḥ'),
  ('ganesha_ashtottara_108', 93, 'ॐ शुभविग्रहाय नमः', 'ஓம் ஶுபவிக்ரஹாய நம꞉', 'ōṁ śubhavigrahāya namaḥ'),
  ('ganesha_ashtottara_108', 94, 'ॐ पञ्चपातकनाशिने नमः', 'ஓம் பஞ்சபாதகநாஶிநே நம꞉', 'ōṁ pañcapātakanāśinē namaḥ'),
  ('ganesha_ashtottara_108', 95, 'ॐ पार्वतीप्रियनन्दनाय नमः', 'ஓம் பார்வதீப்ரியநந்தநாய நம꞉', 'ōṁ pārvatīpriyanandanāya namaḥ'),
  ('ganesha_ashtottara_108', 96, 'ॐ विश्वेशाय नमः', 'ஓம் விஶ்வேஶாய நம꞉', 'ōṁ viśvēśāya namaḥ'),
  ('ganesha_ashtottara_108', 97, 'ॐ विबुधाराध्यपदाय नमः', 'ஓம் விபுதாராத்யபதாய நம꞉', 'ōṁ vibudhārādhyapadāya namaḥ'),
  ('ganesha_ashtottara_108', 98, 'ॐ वीरवराग्रगाय नमः', 'ஓம் வீரவராக்ரகாய நம꞉', 'ōṁ vīravarāgragāya namaḥ'),
  ('ganesha_ashtottara_108', 99, 'ॐ कुमारगुरुवन्द्याय नमः', 'ஓம் குமாரகுருவந்த்யாய நம꞉', 'ōṁ kumāraguruvandyāya namaḥ'),
  ('ganesha_ashtottara_108', 100, 'ॐ कुञ्जरासुरभञ्जनाय नमः', 'ஓம் குஞ்ஜராஸுரபஞ்ஜநாய நம꞉', 'ōṁ kuñjarāsurabhañjanāya namaḥ'),
  ('ganesha_ashtottara_108', 101, 'ॐ वल्लभावल्लभाय नमः', 'ஓம் வல்லபாவல்லபாய நம꞉', 'ōṁ vallabhāvallabhāya namaḥ'),
  ('ganesha_ashtottara_108', 102, 'ॐ वराभयकराम्बुजाय नमः', 'ஓம் வராபயகராம்புஜாய நம꞉', 'ōṁ varābhayakarāmbujāya namaḥ'),
  ('ganesha_ashtottara_108', 103, 'ॐ सुधाकलशहस्ताय नमः', 'ஓம் ஸுதாகலஶஹஸ்தாய நம꞉', 'ōṁ sudhākalaśahastāya namaḥ'),
  ('ganesha_ashtottara_108', 104, 'ॐ सुधाकरकलाधराय नमः', 'ஓம் ஸுதாகரகலாதராய நம꞉', 'ōṁ sudhākarakalādharāya namaḥ'),
  ('ganesha_ashtottara_108', 105, 'ॐ पञ्चहस्ताय नमः', 'ஓம் பஞ்சஹஸ்தாய நம꞉', 'ōṁ pañcahastāya namaḥ'),
  ('ganesha_ashtottara_108', 106, 'ॐ प्रधानेशाय नमः', 'ஓம் ப்ரதாநேஶாய நம꞉', 'ōṁ pradhānēśāya namaḥ'),
  ('ganesha_ashtottara_108', 107, 'ॐ पुरातनाय नमः', 'ஓம் புராதநாய நம꞉', 'ōṁ purātanāya namaḥ'),
  ('ganesha_ashtottara_108', 108, 'ॐ वरसिद्धिविनायकाय नमः', 'ஓம் வரஸித்திவிநாயகாய நம꞉', 'ōṁ varasiddhivināyakāya namaḥ')
on conflict (namavali_id, seq) do update set
  name_deva = excluded.name_deva, name_ta = excluded.name_ta, name_translit = excluded.name_translit;

-- --- renumber ----------------------------------------------------------------
-- Four steps are inserted in the middle, so everything from the old step 9
-- onward moves. Negate first: (pooja_id, step_number) is unique, and a direct
-- renumber would collide mid-update.
update public.pooja_steps set step_title_en = 'Pushpa Pooja (Shodasha Nama)'
where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Archana)';

update public.pooja_steps set step_number = -step_number
where pooja_id = 'ganesha_standard' and step_number > 0;

update public.pooja_steps set step_number = 1
where pooja_id = 'ganesha_standard' and step_title_en = 'Achamanam';
update public.pooja_steps set step_number = 2
where pooja_id = 'ganesha_standard' and step_title_en = 'Anga Vandanam';
update public.pooja_steps set step_number = 3
where pooja_id = 'ganesha_standard' and step_title_en = 'Vighneshwara Dhyanam';
update public.pooja_steps set step_number = 4
where pooja_id = 'ganesha_standard' and step_title_en = 'Pranayamam';
update public.pooja_steps set step_number = 5
where pooja_id = 'ganesha_standard' and step_title_en = 'Sankalpam';
update public.pooja_steps set step_number = 6
where pooja_id = 'ganesha_standard' and step_title_en = 'Kalasha Pooja';
update public.pooja_steps set step_number = 7
where pooja_id = 'ganesha_standard' and step_title_en = 'Ghanta Pooja';
update public.pooja_steps set step_number = 8
where pooja_id = 'ganesha_standard' and step_title_en = 'Avahanam & Asanam';
update public.pooja_steps set step_number = 9
where pooja_id = 'ganesha_standard' and step_title_en = 'Prana Pratishtha';
update public.pooja_steps set step_number = 10
where pooja_id = 'ganesha_standard' and step_title_en = 'Padyam & Arghyam';
update public.pooja_steps set step_number = 11
where pooja_id = 'ganesha_standard' and step_title_en = 'Snanam & Vastram';
update public.pooja_steps set step_number = 12
where pooja_id = 'ganesha_standard' and step_title_en = 'Gandham, Kumkumam & Pushpam';
update public.pooja_steps set step_number = 13
where pooja_id = 'ganesha_standard' and step_title_en = 'Anga Pooja';
update public.pooja_steps set step_number = 14
where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)';
update public.pooja_steps set step_number = 15
where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)';
update public.pooja_steps set step_number = 16
where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)';
update public.pooja_steps set step_number = 17
where pooja_id = 'ganesha_standard' and step_title_en = 'Ganapathi Ashtottara Shatanamavali';
update public.pooja_steps set step_number = 18
where pooja_id = 'ganesha_standard' and step_title_en = 'Dhoopam & Deepam';
update public.pooja_steps set step_number = 19
where pooja_id = 'ganesha_standard' and step_title_en = 'Naivedyam';
update public.pooja_steps set step_number = 20
where pooja_id = 'ganesha_standard' and step_title_en = 'Karpura Neerajanam';
update public.pooja_steps set step_number = 21
where pooja_id = 'ganesha_standard' and step_title_en = 'Mantra Pushpam & Namaskaram';
update public.pooja_steps set step_number = 22
where pooja_id = 'ganesha_standard' and step_title_en = 'Ksheera Arghyam';
update public.pooja_steps set step_number = 23
where pooja_id = 'ganesha_standard' and step_title_en = 'Kshama Prarthana & Conclusion';
update public.pooja_steps set step_number = 24
where pooja_id = 'ganesha_standard' and step_title_en = 'Udvasanam';

-- --- the four new steps ------------------------------------------------------
-- 9. Prana Pratishtha
insert into public.pooja_steps
  (pooja_id, step_number, phase, modes, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   philosophy_en, gender_rule, scripts_generated, namavali_id, source_ref)
values ('ganesha_standard', 9, 'pradhana', '{main}',
        'Prana Pratishtha', 'ப்ராண ப்ரதிஷ்டை',
        'Touch the idol with the fingertips of the right hand and recite, asking the life breath to settle into it. After this the image is no longer clay: it is treated as a guest who is present. This is why the final day needs Udvasanam to formally release what is established here, and why a later day''s Punar Pooja does not repeat this step.',
        'வலது கையின் விரல் நுனிகளால் விக்கிரகத்தைத் தொட்டு, உயிர்ப்பு அதில் நிலைபெறும்படி வேண்டிப் பாராயணம் செய்யவும். இதன் பின் அந்த உருவம் களிமண் அல்ல; எழுந்தருளியிருக்கும் விருந்தினராகவே கருதப்படுகிறது. இதனாலேயே இறுதி நாளில் உத்வாசனம் தேவைப்படுகிறது; அடுத்த நாட்களின் புனர் பூஜையில் இந்தப் படி மீண்டும் செய்யப்படுவதில்லை.',
        'अस्य प्राणाः प्रतिष्ठन्तु अस्य प्राणाः क्षरन्तु च । अस्य देवत्वमर्चायै मामहेति च कश्चन ॥ श्री महागणपतये नमः प्राण प्रतिष्ठापयामि ॥',
        'அஸ்ய ப்ராணா꞉ ப்ரதிஷ்டந்து அஸ்ய ப்ராணா꞉ க்ஷரந்து ச । அஸ்ய தேவத்வமர்சாயை மாமஹேதி ச கஶ்சந ॥ ஶ்ரீ மஹாகணபதயே நம꞉ ப்ராண ப்ரதிஷ்டாபயாமி ॥',
        'asya prāṇāḥ pratiṣṭhantu asya prāṇāḥ kṣarantu ca । asya devatvamarcāyai māmaheti ca kaścana ॥ śrī mahāgaṇapataye namaḥ prāṇa pratiṣṭhāpayāmi ॥',
        'Everything before this point prepares a seat. This is the step that makes the rest of the pooja hospitality rather than decoration. A goddess takes the feminine form of the same verse, asyai in place of asya.', 'all', true, null, 'Standard prana pratishtha verse; Sathya Vadyar, Ganesha Chaturthi 2026, chapter at 34:36')
on conflict (pooja_id, step_number) do update set
  step_title_en = excluded.step_title_en,
  step_title_ta = excluded.step_title_ta,
  instruction_en = excluded.instruction_en,
  instruction_ta = excluded.instruction_ta,
  mantra_sanskrit = excluded.mantra_sanskrit,
  mantra_tamil = excluded.mantra_tamil,
  mantra_translit = excluded.mantra_translit,
  philosophy_en = excluded.philosophy_en,
  namavali_id = excluded.namavali_id,
  modes = excluded.modes,
  phase = excluded.phase,
  source_ref = excluded.source_ref;

-- 14. Patra Pooja (21 Leaves)
insert into public.pooja_steps
  (pooja_id, step_number, phase, modes, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   philosophy_en, gender_rule, scripts_generated, namavali_id, source_ref)
values ('ganesha_standard', 14, 'pradhana', '{main,punar}',
        'Patra Pooja (21 Leaves)', 'பத்ர பூஜை (21 இலைகள்)',
        'Offer the twenty-one leaves one at a time, in this order, saying the offering line for each. Few households have all twenty-one; offer what you have and substitute the rest with arugampul or tulasi, which is what is done in practice. The printed paddhatis pair a different Ganesha name with each leaf but disagree with one another on which name goes with which, so this follows the deity''s own mantra for every leaf instead of picking one pairing.',
        'இருபத்தொரு இலைகளையும் இந்த வரிசையில் ஒவ்வொன்றாக, அதற்குரிய வரியைச் சொல்லிச் சமர்ப்பிக்கவும். இருபத்தொன்றும் கிடைப்பது அரிது; கிடைப்பதைச் சமர்ப்பித்து, மற்றவற்றுக்கு அருகம்புல் அல்லது துளசியைப் பயன்படுத்தலாம் — நடைமுறையில் அதுவே செய்யப்படுகிறது. அச்சிடப்பட்ட பத்ததிகள் ஒவ்வொரு இலைக்கும் ஒரு விநாயகர் நாமத்தைக் கூறுகின்றன; ஆனால் எந்த நாமம் எந்த இலைக்கு என்பதில் அவை ஒன்றுக்கொன்று முரண்படுகின்றன. எனவே இங்கு ஒவ்வொரு இலைக்கும் மூல மந்திரமே சொல்லப்படுகிறது.',
        'ॐ श्री महागणपतये नमः',
        'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉',
        'oṃ śrī mahāgaṇapataye namaḥ',
        'The leaves are not decoration and not incense. Each is a plant that grows where people live, and gathering twenty-one of them is a morning''s walk. The rite is built so that the offering costs attention rather than money.', 'all', true, null, 'Leaf list: South Indian recension, Vinayaka Vratha Kalpam (telugupanchangamdaily), corroborated as the South variation by drikpanchang. Name pairing deliberately not seeded, paddhatis disagree. Sequence: Sathya Vadyar, chapter at 45:36')
on conflict (pooja_id, step_number) do update set
  step_title_en = excluded.step_title_en,
  step_title_ta = excluded.step_title_ta,
  instruction_en = excluded.instruction_en,
  instruction_ta = excluded.instruction_ta,
  mantra_sanskrit = excluded.mantra_sanskrit,
  mantra_tamil = excluded.mantra_tamil,
  mantra_translit = excluded.mantra_translit,
  philosophy_en = excluded.philosophy_en,
  namavali_id = excluded.namavali_id,
  modes = excluded.modes,
  phase = excluded.phase,
  source_ref = excluded.source_ref;

-- 16. Durva Pooja (21 Names)
insert into public.pooja_steps
  (pooja_id, step_number, phase, modes, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   philosophy_en, gender_rule, scripts_generated, namavali_id, source_ref)
values ('ganesha_standard', 16, 'pradhana', '{main,punar}',
        'Durva Pooja (21 Names)', 'தூர்வா பூஜை (21 நாமங்கள்)',
        'Take arugampul in pairs of blades. Offer one pair at each of the twenty-one names. Durva is the offering Ganesha is said to prefer above every other, and this is the only upachara in the whole pooja given twenty-one times.',
        'அருகம்புல்லை இரண்டிரண்டாக எடுக்கவும். இருபத்தொரு நாமங்களில் ஒவ்வொன்றுக்கும் ஒரு ஜோடி சமர்ப்பிக்கவும். எல்லா த்ரவ்யங்களிலும் விநாயகருக்கு மிகவும் உகந்தது அருகம்புல்; பூஜையில் இருபத்தொரு முறை செய்யப்படும் ஒரே உபசாரம் இதுவே.',
        'ॐ श्री महागणपतये नमः दूर्वायुग्मं समर्पयामि',
        'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉ தூர்வாயுக்மம் ஸமர்பயாமி',
        'oṃ śrī mahāgaṇapataye namaḥ dūrvāyugmaṃ samarpayāmi',
        'Durva is a weed that survives being walked on and cut and still spreads. Offering the most persistent thing in the garden to the remover of obstacles is not an accident of botany.', 'all', true, null, 'sanskritdocuments gaNeshapUjAvidhi.itx v.35 ekaviMshatidUrvA~NkurumarpaN, corroborated by StotraNidhi Sankatahara Chaturthi puja vidhanam; Sathya Vadyar, chapter at 52:03')
on conflict (pooja_id, step_number) do update set
  step_title_en = excluded.step_title_en,
  step_title_ta = excluded.step_title_ta,
  instruction_en = excluded.instruction_en,
  instruction_ta = excluded.instruction_ta,
  mantra_sanskrit = excluded.mantra_sanskrit,
  mantra_tamil = excluded.mantra_tamil,
  mantra_translit = excluded.mantra_translit,
  philosophy_en = excluded.philosophy_en,
  namavali_id = excluded.namavali_id,
  modes = excluded.modes,
  phase = excluded.phase,
  source_ref = excluded.source_ref;

-- 17. Ganapathi Ashtottara Shatanamavali
insert into public.pooja_steps
  (pooja_id, step_number, phase, modes, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   philosophy_en, gender_rule, scripts_generated, namavali_id, source_ref)
values ('ganesha_standard', 17, 'pradhana', '{main,punar}',
        'Ganapathi Ashtottara Shatanamavali', 'கணபதி அஷ்டோத்தர சதநாமாவளி',
        'Offer a flower, a pinch of akshatai or a blade of arugampul at each of the hundred and eight names. If time is short the sixteen-name Pushpa Pooja already done stands in its place, but on Chaturthi itself the full hundred and eight is the practice.',
        'நூற்றெட்டு நாமங்களில் ஒவ்வொன்றிலும் ஒரு புஷ்பமோ, சிறிது அக்ஷதையோ, அருகம்புல்லோ சமர்ப்பிக்கவும். நேரம் குறைவாக இருந்தால் ஏற்கெனவே செய்த பதினாறு நாம புஷ்ப பூஜை போதுமானது; ஆனால் சதுர்த்தி அன்று நூற்றெட்டும் சொல்வதே வழக்கம்.',
        null,
        null,
        null,
        'The list closes on Varasiddhi Vinayaka, which is the form worshipped on Chaturthi itself. The hundred and eight names are not a hundred and eight gods; they are one guest described until the description runs out.', 'all', true, 'ganesha_ashtottara_108', 'StotraNidhi Sri Ganesha Ashtottara Shatanamavali, Devanagari, Tamil and IAST pages cross-validated; Sathya Vadyar, chapter at 54:58')
on conflict (pooja_id, step_number) do update set
  step_title_en = excluded.step_title_en,
  step_title_ta = excluded.step_title_ta,
  instruction_en = excluded.instruction_en,
  instruction_ta = excluded.instruction_ta,
  mantra_sanskrit = excluded.mantra_sanskrit,
  mantra_tamil = excluded.mantra_tamil,
  mantra_translit = excluded.mantra_translit,
  philosophy_en = excluded.philosophy_en,
  namavali_id = excluded.namavali_id,
  modes = excluded.modes,
  phase = excluded.phase,
  source_ref = excluded.source_ref;

-- --- archana rows -----------------------------------------------------------
-- Patra Pooja (21 Leaves): 21 rows
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit,
   offering_deva, offering_en, offering_ta, botanical, is_substitutable, substitute_with)
values
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 1, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'मचीपत्रं समर्पयामि', 'Machi (davanam) leaf', 'மாசிப்பத்திரம்', 'Artemisia pallens', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 2, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'बृहतीपत्रं समर्पयामि', 'Brihati (Indian nightshade) leaf', 'கண்டங்கத்தரி', 'Solanum virginianum', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 3, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'बिल्वपत्रं समर्पयामि', 'Bilva leaf', 'வில்வம்', 'Aegle marmelos', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 4, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'दूर्वापत्रं समर्पयामि', 'Durva grass leaf', 'அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 5, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'दत्तूरपत्रं समर्पयामि', 'Dattura leaf', 'ஊமத்தை', 'Datura metel', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 6, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'बदरीपत्रं समर्पयामि', 'Badari (jujube) leaf', 'இலந்தை', 'Ziziphus mauritiana', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 7, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'अपामार्गपत्रं समर्पयामि', 'Apamarga leaf', 'நாயுருவி', 'Achyranthes aspera', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 8, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'तुलसीपत्रं समर्पयामि', 'Tulasi leaf', 'துளசி', 'Ocimum tenuiflorum', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 9, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'चूतपत्रं समर्पयामि', 'Chuta (mango) leaf', 'மாவிலை', 'Mangifera indica', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 10, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'करवीरपत्रं समर्पयामि', 'Karavira (oleander) leaf', 'அரளி', 'Nerium oleander', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 11, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'विष्णुक्रान्तपत्रं समर्पयामि', 'Vishnukranta leaf', 'விஷ்ணுகிராந்தி', 'Evolvulus alsinoides', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 12, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'दाडिमीपत्रं समर्पयामि', 'Dadimi (pomegranate) leaf', 'மாதுளை', 'Punica granatum', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 13, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'देवदारुपत्रं समर्पयामि', 'Devadaru leaf', 'தேவதாரு', 'Cedrus deodara', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 14, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'मरुवकपत्रं समर्पयामि', 'Maruvaka (marjoram) leaf', 'மருக்கொழுந்து', 'Origanum majorana', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 15, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'सिन्धुवारपत्रं समर्पयामि', 'Sindhuvara leaf', 'நொச்சி', 'Vitex negundo', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 16, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'जातीपत्रं समर्पयामि', 'Jati (jasmine) leaf', 'ஜாதிமல்லி', 'Jasminum grandiflorum', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 17, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'गण्डकीपत्रं समर्पयामि', 'Gandaki leaf', 'மந்தாரை', 'Bauhinia variegata', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 18, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'शमीपत्रं समर्पयामि', 'Shami leaf', 'வன்னி', 'Prosopis cineraria', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 19, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'अश्वत्थपत्रं समर्पयामि', 'Ashvattha (peepal) leaf', 'அரசு', 'Ficus religiosa', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 20, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'अर्जुनपत्रं समर्पयामि', 'Arjuna leaf', 'மருதம்', 'Terminalia arjuna', true, 'Arugampul (durva) or tulasi'),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), 21, 'ॐ श्री महागणपतये नमः', 'ஓம் ஶ்ரீ மஹாகணபதயே நம꞉', 'oṃ śrī mahāgaṇapataye namaḥ', 'अर्कपत्रं समर्पयामि', 'Arka (calotropis) leaf', 'எருக்கு', 'Calotropis gigantea', false, null)
on conflict (pooja_step_id, seq) do update set
  invoked_name_deva = excluded.invoked_name_deva,
  invoked_name_ta = excluded.invoked_name_ta,
  invoked_name_translit = excluded.invoked_name_translit,
  offering_deva = excluded.offering_deva,
  offering_en = excluded.offering_en,
  offering_ta = excluded.offering_ta,
  botanical = excluded.botanical,
  is_substitutable = excluded.is_substitutable,
  substitute_with = excluded.substitute_with;

delete from public.archana_items
where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and seq > 21;

-- Pushpa Pooja (Shodasha Nama): 16 rows
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit,
   offering_deva, offering_en, offering_ta, botanical, is_substitutable, substitute_with)
values
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 1, 'ॐ सुमुखाय नमः', 'ஓம் ஸுமுகாய நம꞉', 'oṃ sumukhāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 2, 'ॐ एकदन्ताय नमः', 'ஓம் ஏகதந்தாய நம꞉', 'oṃ ekadantāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 3, 'ॐ कपिलाय नमः', 'ஓம் கபிலாய நம꞉', 'oṃ kapilāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 4, 'ॐ गजकर्णकाय नमः', 'ஓம் கஜகர்ணகாய நம꞉', 'oṃ gajakarṇakāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 5, 'ॐ लम्बोदराय नमः', 'ஓம் லம்போதராய நம꞉', 'oṃ lambodarāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 6, 'ॐ विकटाय नमः', 'ஓம் விகடாய நம꞉', 'oṃ vikaṭāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 7, 'ॐ विघ्नराजाय नमः', 'ஓம் விக்நராஜாய நம꞉', 'oṃ vighnarājāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 8, 'ॐ विनायकाय नमः', 'ஓம் விநாயகாய நம꞉', 'oṃ vināyakāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 9, 'ॐ धूम्रकेतवे नमः', 'ஓம் தூம்ரகேதவே நம꞉', 'oṃ dhūmraketave namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 10, 'ॐ गणाध्यक्षाय नमः', 'ஓம் கணாத்யக்ஷாய நம꞉', 'oṃ gaṇādhyakṣāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 11, 'ॐ भालचन्द्राय नमः', 'ஓம் பாலசந்த்ராய நம꞉', 'oṃ bhālacandrāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 12, 'ॐ गजाननाय नमः', 'ஓம் கஜாநநாய நம꞉', 'oṃ gajānanāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 13, 'ॐ वक्रतुण्डाय नमः', 'ஓம் வக்ரதுண்டாய நம꞉', 'oṃ vakratuṇḍāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 14, 'ॐ शूर्पकर्णाय नमः', 'ஓம் ஶூர்பகர்ணாய நம꞉', 'oṃ śūrpakarṇāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 15, 'ॐ हेरम्बाय नमः', 'ஓம் ஹேரம்பாய நம꞉', 'oṃ herambāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)'), 16, 'ॐ स्कन्दपूर्वजाय नमः', 'ஓம் ஸ்கந்தபூர்வஜாய நம꞉', 'oṃ skandapūrvajāya namaḥ', 'पुष्पं समर्पयामि', 'A flower or a pinch of akshatai', 'ஒரு புஷ்பம் அல்லது சிறிது அக்ஷதை', null, false, null)
on conflict (pooja_step_id, seq) do update set
  invoked_name_deva = excluded.invoked_name_deva,
  invoked_name_ta = excluded.invoked_name_ta,
  invoked_name_translit = excluded.invoked_name_translit,
  offering_deva = excluded.offering_deva,
  offering_en = excluded.offering_en,
  offering_ta = excluded.offering_ta,
  botanical = excluded.botanical,
  is_substitutable = excluded.is_substitutable,
  substitute_with = excluded.substitute_with;

delete from public.archana_items
where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (Shodasha Nama)') and seq > 16;

-- Durva Pooja (21 Names): 21 rows
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit,
   offering_deva, offering_en, offering_ta, botanical, is_substitutable, substitute_with)
values
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 1, 'ॐ गणाधिपतये नमः', 'ஓம் கணாதிபதயே நம꞉', 'oṃ gaṇādhipataye namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades (StotraNidhi reads this name gaṇādhipāya)', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 2, 'ॐ उमापुत्राय नमः', 'ஓம் உமாபுத்ராய நம꞉', 'oṃ umāputrāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 3, 'ॐ अघनाशनाय नमः', 'ஓம் அகநாஶநாய நம꞉', 'oṃ aghanāśanāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 4, 'ॐ एकदन्ताय नमः', 'ஓம் ஏகதந்தாய நம꞉', 'oṃ ekadantāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 5, 'ॐ इभवक्त्राय नमः', 'ஓம் இபவக்த்ராய நம꞉', 'oṃ ibhavaktrāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 6, 'ॐ मूषकवाहनाय नमः', 'ஓம் மூஷகவாஹநாய நம꞉', 'oṃ mūṣakavāhanāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades (StotraNidhi reads this name mūṣikavāhanāya)', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 7, 'ॐ विनायकाय नमः', 'ஓம் விநாயகாய நம꞉', 'oṃ vināyakāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 8, 'ॐ ईशपुत्राय नमः', 'ஓம் ஈஶபுத்ராய நம꞉', 'oṃ īśaputrāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 9, 'ॐ सर्वसिद्धिप्रदाय नमः', 'ஓம் ஸர்வஸித்திப்ரதாய நம꞉', 'oṃ sarvasiddhipradāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 10, 'ॐ लम्बोदराय नमः', 'ஓம் லம்போதராய நம꞉', 'oṃ lambodarāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 11, 'ॐ वक्रतुण्डाय नमः', 'ஓம் வக்ரதுண்டாய நம꞉', 'oṃ vakratuṇḍāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 12, 'ॐ मोदकप्रियाय नमः', 'ஓம் மோதகப்ரியாய நம꞉', 'oṃ modakapriyāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 13, 'ॐ विघ्नविध्वंसकर्त्रे नमः', 'ஓம் விக்நவித்வம்ஸகர்த்ரே நம꞉', 'oṃ vighnavidhvaṃsakartre namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 14, 'ॐ विश्ववन्द्याय नमः', 'ஓம் விஶ்வவந்த்யாய நம꞉', 'oṃ viśvavandyāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 15, 'ॐ अमरेशाय नमः', 'ஓம் அமரேஶாய நம꞉', 'oṃ amareśāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 16, 'ॐ गजकर्णाय नमः', 'ஓம் கஜகர்ணாய நம꞉', 'oṃ gajakarṇāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades (StotraNidhi reads this name gajakarṇakāya)', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 17, 'ॐ नागयज्ञोपवीतिने नमः', 'ஓம் நாகயஜ்ஞோபவீதிநே நம꞉', 'oṃ nāgayajñopavītine namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 18, 'ॐ भालचन्द्राय नमः', 'ஓம் பாலசந்த்ராய நம꞉', 'oṃ bhālacandrāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades (StotraNidhi reads this name phālacandrāya)', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 19, 'ॐ परशुधारिणे नमः', 'ஓம் பரஶுதாரிணே நம꞉', 'oṃ paraśudhāriṇe namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 20, 'ॐ विघ्नाधिपाय नमः', 'ஓம் விக்நாதிபாய நம꞉', 'oṃ vighnādhipāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null),
  ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)'), 21, 'ॐ विद्याप्रदाय नमः', 'ஓம் வித்யாப்ரதாய நம꞉', 'oṃ vidyāpradāya namaḥ', 'दूर्वायुग्मं समर्पयामि', 'A pair of arugampul blades', 'ஒரு ஜோடி அருகம்புல்', 'Cynodon dactylon', false, null)
on conflict (pooja_step_id, seq) do update set
  invoked_name_deva = excluded.invoked_name_deva,
  invoked_name_ta = excluded.invoked_name_ta,
  invoked_name_translit = excluded.invoked_name_translit,
  offering_deva = excluded.offering_deva,
  offering_en = excluded.offering_en,
  offering_ta = excluded.offering_ta,
  botanical = excluded.botanical,
  is_substitutable = excluded.is_substitutable,
  substitute_with = excluded.substitute_with;

delete from public.archana_items
where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Durva Pooja (21 Names)') and seq > 21;

commit;

-- Verify:
--   select step_number, step_title_en, namavali_id, modes
--     from pooja_steps where pooja_id = 'ganesha_standard' order by step_number;  -- 24 rows
--   select count(*) from namavali_items where namavali_id = 'ganesha_ashtottara_108';  -- 108
--   select s.step_title_en, count(*) from archana_items a
--     join pooja_steps s on s.id = a.pooja_step_id group by 1;  -- 21, 16, 21
