-- =============================================================================
-- 0014_philosophy.sql
--
-- GENERATED by scripts/build-philosophy.mjs. Do not hand-edit.
--
-- philosophy_en for the eleven steps that had none: the plain upacharas of the
-- Ganesha pooja, which the original content skipped, plus the Varalakshmi
-- Ghanta Pooja, which was null only because 0011 copied it from the Ganesha row
-- while that row was still empty.
--
-- After this, no step in either pooja is missing instruction, mantra where one
-- applies, meaning or philosophy.
--
-- Like the meanings, this is the project's own English and carries no
-- source_ref. Existing philosophy entries are NOT touched.
--
-- Idempotent.
-- =============================================================================

begin;

update public.pooja_steps set philosophy_en = 'The sentence starts at the age of Brahma and narrows, kalpa by continent by country, until it arrives at this room on this morning. Nothing about the pooja changes because of it; what changes is that it has been placed. Note what is actually asked for: not gain, but that the wrong already gathered should fall away.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Sankalpam' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'One sound doing two opposite jobs: agamartham tu devanam, gamanartham tu rakshasam, for the coming of the gods and the going of what should not be here. It is also the only part of the pooja the rest of the house can hear from another room, which is how everyone knows it has begun.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Ghanta Pooja' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'One sound doing two opposite jobs: agamartham tu devanam, gamanartham tu rakshasam, for the coming of the gods and the going of what should not be here. It is also the only part of the pooja the rest of the house can hear from another room, which is how everyone knows it has begun.', updated_at = now()
where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Ghanta Pooja' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'The turmeric was shaped a minute ago and it is not being made into a god. It is being asked to hold one, and the asking is the rite. The seat comes in the same breath as the invitation, because inviting someone to stand is not an invitation.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Avahanam & Asanam' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'Feet, then hands, then mouth. That is the order you would actually use for someone who had walked to your door in the heat, and the pooja keeps it unchanged. Three spoonfuls of water is the whole of it.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Padyam & Arghyam' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'Akshatan samarpayami, "I offer rice in place of cloth". The rite names what it cannot supply and offers rice instead, and that is accepted. This is the substitution rule that makes the whole pooja possible in a flat with no silk and no river; it is stated here, at the least important step, and holds everywhere after.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Snanam & Vastram' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'The first three upacharas that meet no need. Water, seat and bath are what a guest requires; sandal, kumkumam and flowers are only for the pleasure of it. A guest given only what they need has not been welcomed.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Gandham, Kumkumam & Pushpam' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'Both are spent in the giving. Smoke cannot be gathered back and a flame cannot be re-offered, which sets them apart from the rice and the fruit, still there afterwards to be eaten. The line that follows is the tell: even after smoke, water is offered to rinse the mouth. The courtesy does not lapse because the offering was intangible.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Dhoopam & Deepam' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'The food is offered to the five breaths, not to a mouth: pranaya svaha, apanaya svaha, and so on. What is being fed is the life in the guest. The same five breaths are in the person holding the plate, which is why nothing is tasted until this step is done.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Naivedyam' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'The one upachara that is shown rather than given, and then taken back. It is also where the household arrives: the bell goes, and people who were not in the room come to stand in it. Up to here the pooja belonged to whoever was reciting.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Karpura Neerajanam' and philosophy_en is null;
update public.pooja_steps set philosophy_en = 'Pradakshina pade pade, "at every step of the going round". The verse does not say the wrong is forgiven for saying the verse; it is undone by the walking, step by step. The body is asked to do the work, which is why this is not performed sitting.', updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Mantra Pushpam & Namaskaram' and philosophy_en is null;

do $$
declare missing text;
begin
  select string_agg(pooja_id || ' / ' || step_title_en, ', ')
    into missing
    from public.pooja_steps
   where pooja_id in ('ganesha_standard', 'varalakshmi_vratham') and philosophy_en is null;
  if missing is not null then
    raise exception 'steps left without philosophy_en: %', missing;
  end if;
end $$;

commit;

-- Verify:
--   select count(*) from pooja_steps where philosophy_en is null;   -- 0
