-- =============================================================================
-- 0020_purvangam_and_upacharas.sql
--
-- GENERATED by scripts/build-purvangam-and-upacharas.mjs. Do not hand-edit.
--
-- The last of the steps carrying "Tamil draft, pending vaidika review".
--
-- Two spelling errors are corrected, both in production in BOTH poojas since
-- the first migration: देवताव्हान for देवताह्वान -- आह्वान is invocation and
-- "vhāna" is not a Sanskrit word -- and घन्टा for घण्टा.
--
-- Kalasha Pooja gains the five sections it was missing, including the
-- samprokshana: the water is charged so it can be sprinkled on the materials,
-- the deity and the performer, and none of that was in the step.
--
-- Ganesha stops being invoked "asmin haridrā bimbe", into a turmeric cone.
-- That is the Haridra Ganapati rite; on Chaturthi he is invoked into the idol.
--
-- Achamanam and Anga Vandanam keep their text. StotraNidhi is Telugu Smartha
-- and gives the keśavāya svāhā achamanam; the acyuta-ananta-govinda form here
-- is the Tamil one, and the keshava names belong at the Anga Vandanam that
-- follows. Only their source_ref changes, to say which recension and why.
--
-- The Sankalpam is deliberately untouched: it carries the dynamic panchangam
-- slot, and the published version is a form with blanks.
--
-- Idempotent.
-- =============================================================================

begin;

-- --- ganesha_standard / Achamanam
update public.pooja_steps set
  source_ref = 'Tamil Smartha (Iyer) achamanam, acyuta-ananta-govinda. DELIBERATELY NOT the form in StotraNidhi’s Smartha Paddhati purvangam, which is the Telugu recension (keśavāya svāhā, nārāyaṇāya svāhā, mādhavāya svāhā and twenty-one further names); in Tamil practice those names are said at the Anga Vandanam that follows, touching the limbs, not at the achamanam. Text is unchanged from the original content and still wants vaidika confirmation of the wording, but the recension is the right one for this audience.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Achamanam';

-- --- varalakshmi_vratham / Achamanam
update public.pooja_steps set
  source_ref = 'Tamil Smartha (Iyer) achamanam, acyuta-ananta-govinda. DELIBERATELY NOT the form in StotraNidhi’s Smartha Paddhati purvangam, which is the Telugu recension (keśavāya svāhā, nārāyaṇāya svāhā, mādhavāya svāhā and twenty-one further names); in Tamil practice those names are said at the Anga Vandanam that follows, touching the limbs, not at the achamanam. Text is unchanged from the original content and still wants vaidika confirmation of the wording, but the recension is the right one for this audience.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Achamanam';

-- --- ganesha_standard / Anga Vandanam
update public.pooja_steps set
  source_ref = 'The twelve names said touching the limbs, Tamil Smartha practice. StotraNidhi’s Smartha Paddhati prints twenty-four in its achamanam (through śrīkṛṣṇāya namaḥ); the twelve here are what an Iyer says at this step, and the instruction names the limb for each. Text unchanged from the original content.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Anga Vandanam';

-- --- varalakshmi_vratham / Anga Vandanam
update public.pooja_steps set
  source_ref = 'The twelve names said touching the limbs, Tamil Smartha practice. StotraNidhi’s Smartha Paddhati prints twenty-four in its achamanam (through śrīkṛṣṇāya namaḥ); the twelve here are what an Iyer says at this step, and the instruction names the limb for each. Text unchanged from the original content.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Vandanam';

-- --- ganesha_standard / Vighneshwara Dhyanam
update public.pooja_steps set
  instruction_en = 'Tap your temples gently with the knuckles of both hands while reciting. The first verse is the general invocation said before any undertaking; the second is to Ganesha himself.',
  instruction_ta = 'இரு கைகளின் நெரிக்கும் விரல் மூட்டுகளால் நெற்றிப் பொட்டுகளில் மெதுவாகத் தட்டியபடி பாராயணம் செய்யவும். முதல் ஸ்லோகம் எந்தக் காரியத்தின் தொடக்கத்திலும் சொல்லப்படும் பொது வணக்கம்; இரண்டாவது விநாயகருக்கே உரியது.',
  mantra_sanskrit = 'शुक्लाम्बरधरं विष्णुं शशिवर्णं चतुर्भुजम् ।
प्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशान्तये ॥
अगजानन पद्मार्कं गजाननमहर्निशम् ।
अनेकदं तं भक्तानां एकदन्तमुपास्महे ॥',
  mantra_tamil = 'ஶுக்லாம்பரதரம் விஷ்ணும் ஶஶிவர்ணம் சதுர்புஜம் ।
ப்ரஸந்நவதநம் த்யாயேத் ஸர்வவிக்நோபஶாந்தயே ॥
அகஜாநந பத்மார்கம் கஜாநநமஹர்நிஶம் ।
அநேகதம் தம் பக்தாநாம் ஏகதந்தமுபாஸ்மஹே ॥',
  mantra_translit = 'śuklāmbaradharaṃ viṣṇuṃ śaśivarṇaṃ caturbhujam ।
prasannavadanaṃ dhyāyet sarvavighnopaśāntaye ॥
agajānana padmārkaṃ gajānanamaharniśam ।
anekadaṃ taṃ bhaktānāṃ ekadantamupāsmahe ॥',
  source_ref = 'StotraNidhi, Puja Vidhanam (Poorvangam – Smartha Paddhati), stotranidhi.com/en/puja-vidhanam-poorvangam-in-english/, round-trip verified IAST->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Svara marks are stripped; the app does not render them yet.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Vighneshwara Dhyanam';

-- --- varalakshmi_vratham / Vighneshwara Dhyanam
update public.pooja_steps set
  instruction_en = 'Tap your temples gently with the knuckles of both hands while reciting. The first verse is the general invocation said before any undertaking; the second is to Ganesha himself.',
  instruction_ta = 'இரு கைகளின் நெரிக்கும் விரல் மூட்டுகளால் நெற்றிப் பொட்டுகளில் மெதுவாகத் தட்டியபடி பாராயணம் செய்யவும். முதல் ஸ்லோகம் எந்தக் காரியத்தின் தொடக்கத்திலும் சொல்லப்படும் பொது வணக்கம்; இரண்டாவது விநாயகருக்கே உரியது.',
  mantra_sanskrit = 'शुक्लाम्बरधरं विष्णुं शशिवर्णं चतुर्भुजम् ।
प्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशान्तये ॥
अगजानन पद्मार्कं गजाननमहर्निशम् ।
अनेकदं तं भक्तानां एकदन्तमुपास्महे ॥',
  mantra_tamil = 'ஶுக்லாம்பரதரம் விஷ்ணும் ஶஶிவர்ணம் சதுர்புஜம் ।
ப்ரஸந்நவதநம் த்யாயேத் ஸர்வவிக்நோபஶாந்தயே ॥
அகஜாநந பத்மார்கம் கஜாநநமஹர்நிஶம் ।
அநேகதம் தம் பக்தாநாம் ஏகதந்தமுபாஸ்மஹே ॥',
  mantra_translit = 'śuklāmbaradharaṃ viṣṇuṃ śaśivarṇaṃ caturbhujam ।
prasannavadanaṃ dhyāyet sarvavighnopaśāntaye ॥
agajānana padmārkaṃ gajānanamaharniśam ।
anekadaṃ taṃ bhaktānāṃ ekadantamupāsmahe ॥',
  source_ref = 'StotraNidhi, Puja Vidhanam (Poorvangam – Smartha Paddhati), stotranidhi.com/en/puja-vidhanam-poorvangam-in-english/, round-trip verified IAST->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Svara marks are stripped; the app does not render them yet.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Vighneshwara Dhyanam';

-- --- ganesha_standard / Pranayamam
update public.pooja_steps set
  mantra_sanskrit = 'ॐ भूः ॐ भुवः ॐ सुवः ॐ महः ॐ जनः ॐ तपः ॐ सत्यम् ।
ॐ तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि ।
धियो यो नः प्रचोदयात् ।
ओमापो ज्योती रसोऽमृतं ब्रह्म भूर्भुवस्सुवरोम् ॥',
  mantra_tamil = 'ஓம் பூ꞉ ஓம் புவ꞉ ஓம் ஸுவ꞉ ஓம் மஹ꞉ ஓம் ஜந꞉ ஓம் தப꞉ ஓம் ஸத்யம் ।
ஓம் தத்ஸவிதுர்வரேண்யம் பர்கோ தேவஸ்ய தீமஹி ।
தியோ யோ ந꞉ ப்ரசோதயாத் ।
ஓமாபோ ஜ்யோதீ ரஸோம்ருதம் ப்ரஹ்ம பூர்புவஸ்ஸுவரோம் ॥',
  mantra_translit = 'oṃ bhūḥ oṃ bhuvaḥ oṃ suvaḥ oṃ mahaḥ oṃ janaḥ oṃ tapaḥ oṃ satyam ।
oṃ tatsaviturvareṇyaṃ bhargo devasya dhīmahi ।
dhiyo yo naḥ pracodayāt ।
omāpo jyotī raso''mṛtaṃ brahma bhūrbhuvassuvarom ॥',
  source_ref = 'StotraNidhi, Puja Vidhanam (Poorvangam – Smartha Paddhati), stotranidhi.com/en/puja-vidhanam-poorvangam-in-english/, round-trip verified IAST->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Svara marks are stripped; the app does not render them yet.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Pranayamam';

-- --- varalakshmi_vratham / Pranayamam
update public.pooja_steps set
  mantra_sanskrit = 'ॐ भूः ॐ भुवः ॐ सुवः ॐ महः ॐ जनः ॐ तपः ॐ सत्यम् ।
ॐ तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि ।
धियो यो नः प्रचोदयात् ।
ओमापो ज्योती रसोऽमृतं ब्रह्म भूर्भुवस्सुवरोम् ॥',
  mantra_tamil = 'ஓம் பூ꞉ ஓம் புவ꞉ ஓம் ஸுவ꞉ ஓம் மஹ꞉ ஓம் ஜந꞉ ஓம் தப꞉ ஓம் ஸத்யம் ।
ஓம் தத்ஸவிதுர்வரேண்யம் பர்கோ தேவஸ்ய தீமஹி ।
தியோ யோ ந꞉ ப்ரசோதயாத் ।
ஓமாபோ ஜ்யோதீ ரஸோம்ருதம் ப்ரஹ்ம பூர்புவஸ்ஸுவரோம் ॥',
  mantra_translit = 'oṃ bhūḥ oṃ bhuvaḥ oṃ suvaḥ oṃ mahaḥ oṃ janaḥ oṃ tapaḥ oṃ satyam ।
oṃ tatsaviturvareṇyaṃ bhargo devasya dhīmahi ।
dhiyo yo naḥ pracodayāt ।
omāpo jyotī raso''mṛtaṃ brahma bhūrbhuvassuvarom ॥',
  source_ref = 'StotraNidhi, Puja Vidhanam (Poorvangam – Smartha Paddhati), stotranidhi.com/en/puja-vidhanam-poorvangam-in-english/, round-trip verified IAST->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Svara marks are stripped; the app does not render them yet.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Pranayamam';

-- --- ganesha_standard / Kalasha Pooja
update public.pooja_steps set
  instruction_en = 'Put sandal, kumkumam and akshatai on the vessel, fill it with water, and rest your right hand over its mouth while reciting. The verses seat Vishnu at the mouth, Rudra at the neck and Brahma at the base, then call the seven rivers into the water. At the end sprinkle that water on the pooja materials, on the deity and on yourself — that sprinkling is what the whole step is for.',
  instruction_ta = 'கலசத்தில் சந்தனம், குங்குமம், அக்ஷதை இட்டு, ஜலம் நிரப்பி, வலது கையை அதன் வாயின் மேல் வைத்தபடி பாராயணம் செய்யவும். ஸ்லோகங்கள் வாயில் விஷ்ணுவையும், கழுத்தில் ருத்திரனையும், அடியில் பிரம்மனையும் நிலைபெறச் செய்து, பின் ஏழு நதிகளையும் அந்த ஜலத்தில் ஆவாஹனம் செய்கின்றன. இறுதியில் அந்த ஜலத்தை பூஜைப் பொருட்கள் மீதும், சுவாமியின் மீதும், உங்கள் மீதும் தெளிக்கவும் — இந்தப் ப்ரோக்ஷணமே இந்தப் படியின் நோக்கம்.',
  mantra_sanskrit = 'कलशे गन्ध पुष्पाक्षतैरभ्यर्च्य ।
कलशे उदकं पूरयित्वा ।
कलशस्योपरि हस्तं निधाय ।
कलशस्य मुखे विष्णुः कण्ठे रुद्रः समाश्रितः ।
मूले त्वस्य स्थितो ब्रह्मा मध्ये मातृगणाः स्मृता ॥
कुक्षौ तु सागराः सर्वे सप्तद्वीपा वसुन्धरा ।
ऋग्वेदोऽथ यजुर्वेदो सामवेदो ह्यथर्वणः ॥
अङ्गैश्च सहिताः सर्वे कलशाम्बु समाश्रिताः ।
ॐ आकलशेषु धावति पवित्रे परिषिच्यते ।
उक्थैर्यज्ञेषु वर्धते ।
आपो वा इदं सर्वं विश्वा भूतान्यापः
प्राणा वा आपः पशव आपोऽन्नमापोऽमृतमापः
सम्राडापो विराडापः स्वराडापश्छन्दांस्यापो
ज्योतींष्यापो यजूंष्यापः सत्यमापः
सर्वा देवता आपो भूर्भुवः सुवराप ओम् ॥
गङ्गे च यमुने चैव गोदावरी सरस्वती ।
नर्मदे सिन्धु कावेरी जलेऽस्मिन् सन्निधिं कुरु ॥
कावेरी तुङ्गभद्रा च कृष्णवेणी च गौतमी ।
भागीरथीति विख्याताः पञ्चगङ्गाः प्रकीर्तिताः ॥
आयान्तु श्री महागणपति पूजार्थं मम दुरितक्षयकारकाः ।
ॐ ॐ ॐ कलशोदकेन पूजा द्रव्याणि सम्प्रोक्ष्य,
देवं सम्प्रोक्ष्य, आत्मानं च सम्प्रोक्ष्य ॥',
  mantra_tamil = 'கலஶே கந்த புஷ்பாக்ஷதைரப்யர்ச்ய ।
கலஶே உதகம் பூரயித்வா ।
கலஶஸ்யோபரி ஹஸ்தம் நிதாய ।
கலஶஸ்ய முகே விஷ்ணு꞉ கண்டே ருத்ர꞉ ஸமாஶ்ரித꞉ ।
மூலே த்வஸ்ய ஸ்திதோ ப்ரஹ்மா மத்யே மாத்ருகணா꞉ ஸ்ம்ருதா ॥
குக்ஷௌ து ஸாகரா꞉ ஸர்வே ஸப்தத்வீபா வஸுந்தரா ।
ருக்வேதோத யஜுர்வேதோ ஸாமவேதோ ஹ்யதர்வண꞉ ॥
அங்கைஶ்ச ஸஹிதா꞉ ஸர்வே கலஶாம்பு ஸமாஶ்ரிதா꞉ ।
ஓம் ஆகலஶேஷு தாவதி பவித்ரே பரிஷிச்யதே ।
உக்தைர்யஜ்ஞேஷு வர்ததே ।
ஆபோ வா இதம் ஸர்வம் விஶ்வா பூதாந்யாப꞉
ப்ராணா வா ஆப꞉ பஶவ ஆபோந்நமாபோம்ருதமாப꞉
ஸம்ராடாபோ விராடாப꞉ ஸ்வராடாபஶ்சந்தாம்ஸ்யாபோ
ஜ்யோதீம்ஷ்யாபோ யஜூம்ஷ்யாப꞉ ஸத்யமாப꞉
ஸர்வா தேவதா ஆபோ பூர்புவ꞉ ஸுவராப ஓம் ॥
கங்கே ச யமுநே சைவ கோதாவரீ ஸரஸ்வதீ ।
நர்மதே ஸிந்து காவேரீ ஜலேஸ்மிந் ஸந்நிதிம் குரு ॥
காவேரீ துங்கபத்ரா ச க்ருஷ்ணவேணீ ச கௌதமீ ।
பாகீரதீதி விக்யாதா꞉ பஞ்சகங்கா꞉ ப்ரகீர்திதா꞉ ॥
ஆயாந்து ஶ்ரீ மஹாகணபதி பூஜார்தம் மம துரிதக்ஷயகாரகா꞉ ।
ஓம் ஓம் ஓம் கலஶோதகேந பூஜா த்ரவ்யாணி ஸம்ப்ரோக்ஷ்ய,
தேவம் ஸம்ப்ரோக்ஷ்ய, ஆத்மாநம் ச ஸம்ப்ரோக்ஷ்ய ॥',
  mantra_translit = 'kalaśe gandha puṣpākṣatairabhyarcya ।
kalaśe udakaṃ pūrayitvā ।
kalaśasyopari hastaṃ nidhāya ।
kalaśasya mukhe viṣṇuḥ kaṇṭhe rudraḥ samāśritaḥ ।
mūle tvasya sthito brahmā madhye mātṛgaṇāḥ smṛtā ॥
kukṣau tu sāgarāḥ sarve saptadvīpā vasundharā ।
ṛgvedo''tha yajurvedo sāmavedo hyatharvaṇaḥ ॥
aṅgaiśca sahitāḥ sarve kalaśāmbu samāśritāḥ ।
oṃ ākalaśeṣu dhāvati pavitre pariṣicyate ।
ukthairyajñeṣu vardhate ।
āpo vā idaṃ sarvaṃ viśvā bhūtānyāpaḥ
prāṇā vā āpaḥ paśava āpo''nnamāpo''mṛtamāpaḥ
samrāḍāpo virāḍāpaḥ svarāḍāpaśchandāṃsyāpo
jyotīṃṣyāpo yajūṃṣyāpaḥ satyamāpaḥ
sarvā devatā āpo bhūrbhuvaḥ suvarāpa om ॥
gaṅge ca yamune caiva godāvarī sarasvatī ।
narmade sindhu kāverī jale''smin sannidhiṃ kuru ॥
kāverī tuṅgabhadrā ca kṛṣṇaveṇī ca gautamī ।
bhāgīrathīti vikhyātāḥ pañcagaṅgāḥ prakīrtitāḥ ॥
āyāntu śrī mahāgaṇapati pūjārthaṃ mama duritakṣayakārakāḥ ।
oṃ oṃ oṃ kalaśodakena pūjā dravyāṇi samprokṣya,
devaṃ samprokṣya, ātmānaṃ ca samprokṣya ॥',
  source_ref = 'StotraNidhi, Puja Vidhanam (Poorvangam – Smartha Paddhati), stotranidhi.com/en/puja-vidhanam-poorvangam-in-english/, round-trip verified IAST->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Svara marks are stripped; the app does not render them yet.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Kalasha Pooja';

-- --- varalakshmi_vratham / Kalasha Pooja
update public.pooja_steps set
  instruction_en = 'Put sandal, kumkumam and akshatai on the vessel, fill it with water, and rest your right hand over its mouth while reciting. The verses seat Vishnu at the mouth, Rudra at the neck and Brahma at the base, then call the seven rivers into the water. At the end sprinkle that water on the pooja materials, on the deity and on yourself — that sprinkling is what the whole step is for.',
  instruction_ta = 'கலசத்தில் சந்தனம், குங்குமம், அக்ஷதை இட்டு, ஜலம் நிரப்பி, வலது கையை அதன் வாயின் மேல் வைத்தபடி பாராயணம் செய்யவும். ஸ்லோகங்கள் வாயில் விஷ்ணுவையும், கழுத்தில் ருத்திரனையும், அடியில் பிரம்மனையும் நிலைபெறச் செய்து, பின் ஏழு நதிகளையும் அந்த ஜலத்தில் ஆவாஹனம் செய்கின்றன. இறுதியில் அந்த ஜலத்தை பூஜைப் பொருட்கள் மீதும், சுவாமியின் மீதும், உங்கள் மீதும் தெளிக்கவும் — இந்தப் ப்ரோக்ஷணமே இந்தப் படியின் நோக்கம்.',
  mantra_sanskrit = 'कलशे गन्ध पुष्पाक्षतैरभ्यर्च्य ।
कलशे उदकं पूरयित्वा ।
कलशस्योपरि हस्तं निधाय ।
कलशस्य मुखे विष्णुः कण्ठे रुद्रः समाश्रितः ।
मूले त्वस्य स्थितो ब्रह्मा मध्ये मातृगणाः स्मृता ॥
कुक्षौ तु सागराः सर्वे सप्तद्वीपा वसुन्धरा ।
ऋग्वेदोऽथ यजुर्वेदो सामवेदो ह्यथर्वणः ॥
अङ्गैश्च सहिताः सर्वे कलशाम्बु समाश्रिताः ।
ॐ आकलशेषु धावति पवित्रे परिषिच्यते ।
उक्थैर्यज्ञेषु वर्धते ।
आपो वा इदं सर्वं विश्वा भूतान्यापः
प्राणा वा आपः पशव आपोऽन्नमापोऽमृतमापः
सम्राडापो विराडापः स्वराडापश्छन्दांस्यापो
ज्योतींष्यापो यजूंष्यापः सत्यमापः
सर्वा देवता आपो भूर्भुवः सुवराप ओम् ॥
गङ्गे च यमुने चैव गोदावरी सरस्वती ।
नर्मदे सिन्धु कावेरी जलेऽस्मिन् सन्निधिं कुरु ॥
कावेरी तुङ्गभद्रा च कृष्णवेणी च गौतमी ।
भागीरथीति विख्याताः पञ्चगङ्गाः प्रकीर्तिताः ॥
आयान्तु श्री वरलक्ष्मी पूजार्थं मम दुरितक्षयकारकाः ।
ॐ ॐ ॐ कलशोदकेन पूजा द्रव्याणि सम्प्रोक्ष्य,
देवं सम्प्रोक्ष्य, आत्मानं च सम्प्रोक्ष्य ॥',
  mantra_tamil = 'கலஶே கந்த புஷ்பாக்ஷதைரப்யர்ச்ய ।
கலஶே உதகம் பூரயித்வா ।
கலஶஸ்யோபரி ஹஸ்தம் நிதாய ।
கலஶஸ்ய முகே விஷ்ணு꞉ கண்டே ருத்ர꞉ ஸமாஶ்ரித꞉ ।
மூலே த்வஸ்ய ஸ்திதோ ப்ரஹ்மா மத்யே மாத்ருகணா꞉ ஸ்ம்ருதா ॥
குக்ஷௌ து ஸாகரா꞉ ஸர்வே ஸப்தத்வீபா வஸுந்தரா ।
ருக்வேதோத யஜுர்வேதோ ஸாமவேதோ ஹ்யதர்வண꞉ ॥
அங்கைஶ்ச ஸஹிதா꞉ ஸர்வே கலஶாம்பு ஸமாஶ்ரிதா꞉ ।
ஓம் ஆகலஶேஷு தாவதி பவித்ரே பரிஷிச்யதே ।
உக்தைர்யஜ்ஞேஷு வர்ததே ।
ஆபோ வா இதம் ஸர்வம் விஶ்வா பூதாந்யாப꞉
ப்ராணா வா ஆப꞉ பஶவ ஆபோந்நமாபோம்ருதமாப꞉
ஸம்ராடாபோ விராடாப꞉ ஸ்வராடாபஶ்சந்தாம்ஸ்யாபோ
ஜ்யோதீம்ஷ்யாபோ யஜூம்ஷ்யாப꞉ ஸத்யமாப꞉
ஸர்வா தேவதா ஆபோ பூர்புவ꞉ ஸுவராப ஓம் ॥
கங்கே ச யமுநே சைவ கோதாவரீ ஸரஸ்வதீ ।
நர்மதே ஸிந்து காவேரீ ஜலேஸ்மிந் ஸந்நிதிம் குரு ॥
காவேரீ துங்கபத்ரா ச க்ருஷ்ணவேணீ ச கௌதமீ ।
பாகீரதீதி விக்யாதா꞉ பஞ்சகங்கா꞉ ப்ரகீர்திதா꞉ ॥
ஆயாந்து ஶ்ரீ வரலக்ஷ்மீ பூஜார்தம் மம துரிதக்ஷயகாரகா꞉ ।
ஓம் ஓம் ஓம் கலஶோதகேந பூஜா த்ரவ்யாணி ஸம்ப்ரோக்ஷ்ய,
தேவம் ஸம்ப்ரோக்ஷ்ய, ஆத்மாநம் ச ஸம்ப்ரோக்ஷ்ய ॥',
  mantra_translit = 'kalaśe gandha puṣpākṣatairabhyarcya ।
kalaśe udakaṃ pūrayitvā ।
kalaśasyopari hastaṃ nidhāya ।
kalaśasya mukhe viṣṇuḥ kaṇṭhe rudraḥ samāśritaḥ ।
mūle tvasya sthito brahmā madhye mātṛgaṇāḥ smṛtā ॥
kukṣau tu sāgarāḥ sarve saptadvīpā vasundharā ।
ṛgvedo''tha yajurvedo sāmavedo hyatharvaṇaḥ ॥
aṅgaiśca sahitāḥ sarve kalaśāmbu samāśritāḥ ।
oṃ ākalaśeṣu dhāvati pavitre pariṣicyate ।
ukthairyajñeṣu vardhate ।
āpo vā idaṃ sarvaṃ viśvā bhūtānyāpaḥ
prāṇā vā āpaḥ paśava āpo''nnamāpo''mṛtamāpaḥ
samrāḍāpo virāḍāpaḥ svarāḍāpaśchandāṃsyāpo
jyotīṃṣyāpo yajūṃṣyāpaḥ satyamāpaḥ
sarvā devatā āpo bhūrbhuvaḥ suvarāpa om ॥
gaṅge ca yamune caiva godāvarī sarasvatī ।
narmade sindhu kāverī jale''smin sannidhiṃ kuru ॥
kāverī tuṅgabhadrā ca kṛṣṇaveṇī ca gautamī ।
bhāgīrathīti vikhyātāḥ pañcagaṅgāḥ prakīrtitāḥ ॥
āyāntu śrī varalakṣmī pūjārthaṃ mama duritakṣayakārakāḥ ।
oṃ oṃ oṃ kalaśodakena pūjā dravyāṇi samprokṣya,
devaṃ samprokṣya, ātmānaṃ ca samprokṣya ॥',
  source_ref = 'StotraNidhi, Puja Vidhanam (Poorvangam – Smartha Paddhati), stotranidhi.com/en/puja-vidhanam-poorvangam-in-english/, round-trip verified IAST->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Svara marks are stripped; the app does not render them yet.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Kalasha Pooja';

-- --- ganesha_standard / Ghanta Pooja
update public.pooja_steps set
  instruction_en = 'Worship the bell with akshatai, then ring it with the left hand. The verse says plainly what the sound is for: to call the devas and to send away what should not be here.',
  instruction_ta = 'மணியை அக்ஷதையால் பூஜித்து, பின் இடது கையால் அடிக்கவும். அந்த ஒலி எதற்கு என்பதை ஸ்லோகமே சொல்கிறது: தேவர்களை அழைக்கவும், இருக்கக் கூடாதவற்றை விலக்கவும்.',
  mantra_sanskrit = 'ॐ जयध्वनि मन्त्रमातः स्वाहा ।
घण्टदेवताभ्यो नमः ।
सकलोपचार पूजार्थे अक्षतान् समर्पयामि ।
आगमार्थं तु देवानां गमनार्थं तु राक्षसाम् ।
घण्टारवं करोम्यादौ देवताह्वान लाञ्छनम् ॥
इति घण्टानादं कृत्वा ॥',
  mantra_tamil = 'ஓம் ஜயத்வநி மந்த்ரமாத꞉ ஸ்வாஹா ।
கண்டதேவதாப்யோ நம꞉ ।
ஸகலோபசார பூஜார்தே அக்ஷதாந் ஸமர்பயாமி ।
ஆகமார்தம் து தேவாநாம் கமநார்தம் து ராக்ஷஸாம் ।
கண்டாரவம் கரோம்யாதௌ தேவதாஹ்வாந லாஞ்சநம் ॥
இதி கண்டாநாதம் க்ருத்வா ॥',
  mantra_translit = 'oṃ jayadhvani mantramātaḥ svāhā ।
ghaṇṭadevatābhyo namaḥ ।
sakalopacāra pūjārthe akṣatān samarpayāmi ।
āgamārthaṃ tu devānāṃ gamanārthaṃ tu rākṣasām ।
ghaṇṭāravaṃ karomyādau devatāhvāna lāñchanam ॥
iti ghaṇṭānādaṃ kṛtvā ॥',
  source_ref = 'StotraNidhi, Puja Vidhanam (Poorvangam – Smartha Paddhati), stotranidhi.com/en/puja-vidhanam-poorvangam-in-english/, round-trip verified IAST->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Svara marks are stripped; the app does not render them yet. Corrects two spellings that were in production in both poojas: देवताव्हान for देवताह्वान (āhvāna, invocation — vhāna is not a word), and घन्टा for घण्टा. The paddhati also reads ghaṇṭāravaṃ karomyādau where the earlier text had kuru ghaṇṭāravaṃ tatra; both readings circulate and the published one is used.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Ghanta Pooja';

-- --- varalakshmi_vratham / Ghanta Pooja
update public.pooja_steps set
  instruction_en = 'Worship the bell with akshatai, then ring it with the left hand. The verse says plainly what the sound is for: to call the devas and to send away what should not be here.',
  instruction_ta = 'மணியை அக்ஷதையால் பூஜித்து, பின் இடது கையால் அடிக்கவும். அந்த ஒலி எதற்கு என்பதை ஸ்லோகமே சொல்கிறது: தேவர்களை அழைக்கவும், இருக்கக் கூடாதவற்றை விலக்கவும்.',
  mantra_sanskrit = 'ॐ जयध्वनि मन्त्रमातः स्वाहा ।
घण्टदेवताभ्यो नमः ।
सकलोपचार पूजार्थे अक्षतान् समर्पयामि ।
आगमार्थं तु देवानां गमनार्थं तु राक्षसाम् ।
घण्टारवं करोम्यादौ देवताह्वान लाञ्छनम् ॥
इति घण्टानादं कृत्वा ॥',
  mantra_tamil = 'ஓம் ஜயத்வநி மந்த்ரமாத꞉ ஸ்வாஹா ।
கண்டதேவதாப்யோ நம꞉ ।
ஸகலோபசார பூஜார்தே அக்ஷதாந் ஸமர்பயாமி ।
ஆகமார்தம் து தேவாநாம் கமநார்தம் து ராக்ஷஸாம் ।
கண்டாரவம் கரோம்யாதௌ தேவதாஹ்வாந லாஞ்சநம் ॥
இதி கண்டாநாதம் க்ருத்வா ॥',
  mantra_translit = 'oṃ jayadhvani mantramātaḥ svāhā ।
ghaṇṭadevatābhyo namaḥ ।
sakalopacāra pūjārthe akṣatān samarpayāmi ।
āgamārthaṃ tu devānāṃ gamanārthaṃ tu rākṣasām ।
ghaṇṭāravaṃ karomyādau devatāhvāna lāñchanam ॥
iti ghaṇṭānādaṃ kṛtvā ॥',
  source_ref = 'StotraNidhi, Puja Vidhanam (Poorvangam – Smartha Paddhati), stotranidhi.com/en/puja-vidhanam-poorvangam-in-english/, round-trip verified IAST->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Svara marks are stripped; the app does not render them yet. Corrects two spellings that were in production in both poojas: देवताव्हान for देवताह्वान (āhvāna, invocation — vhāna is not a word), and घन्टा for घण्टा. The paddhati also reads ghaṇṭāravaṃ karomyādau where the earlier text had kuru ghaṇṭāravaṃ tatra; both readings circulate and the published one is used.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Ghanta Pooja';

-- --- ganesha_standard / Avahanam & Asanam
update public.pooja_steps set
  instruction_en = 'Meditate on the form first, then invite him with akshatai and flowers, then offer the seat. He is invoked into the idol you have installed, not into a turmeric cone — the turmeric Pillaiyar is a separate pooja.',
  instruction_ta = 'முதலில் திருவுருவத்தை த்யானிக்கவும்; பின் அக்ஷதையும் புஷ்பமும் கொண்டு ஆவாஹனம் செய்து, ஆசனம் சமர்ப்பிக்கவும். நீங்கள் பிரதிஷ்டை செய்த விக்கிரகத்திலேயே ஆவாஹனம் — மஞ்சள் பிள்ளையாரில் அல்ல; அது தனிப் பூஜை.',
  mantra_sanskrit = 'ध्यायेद्गजाननं देवं तप्तकांचनसन्निभम् ।
चतुर्भुजं महाकायं सर्वाभरणभूषितम् ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः ध्यायामि ।
अत्रागच्छ जगद्वंद्य सुरराजार्चितेश्वर ।
अनाथनाथ सर्वज्ञ गौरीगर्भसमुद्भव ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः आवाहयामि ।
मौक्तिकैः पुष्परागैश्च नानारत्नैर्विराजितम् ।
रत्नसिंहासनं चारु प्रीत्यर्थं प्रतिगृह्यताम् ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः आसनं समर्पयामि ।',
  mantra_tamil = 'த்யாயேத்கஜாநநம் தேவம் தப்தகாம்சநஸந்நிபம் ।
சதுர்புஜம் மஹாகாயம் ஸர்வாபரணபூஷிதம் ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ த்யாயாமி ।
அத்ராகச்ச ஜகத்வம்த்ய ஸுரராஜார்சிதேஶ்வர ।
அநாதநாத ஸர்வஜ்ஞ கௌரீகர்பஸமுத்பவ ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ ஆவாஹயாமி ।
மௌக்திகை꞉ புஷ்பராகைஶ்ச நாநாரத்நைர்விராஜிதம் ।
ரத்நஸிம்ஹாஸநம் சாரு ப்ரீத்யர்தம் ப்ரதிக்ருஹ்யதாம் ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ ஆஸநம் ஸமர்பயாமி ।',
  mantra_translit = 'dhyāyedgajānanaṃ devaṃ taptakāṃcanasannibham ।
caturbhujaṃ mahākāyaṃ sarvābharaṇabhūṣitam ॥
oṃ śrī siddhivināyaka svāmine namaḥ dhyāyāmi ।
atrāgaccha jagadvaṃdya surarājārciteśvara ।
anāthanātha sarvajña gaurīgarbhasamudbhava ॥
oṃ śrī siddhivināyaka svāmine namaḥ āvāhayāmi ।
mauktikaiḥ puṣparāgaiśca nānāratnairvirājitam ।
ratnasiṃhāsanaṃ cāru prītyarthaṃ pratigṛhyatām ॥
oṃ śrī siddhivināyaka svāmine namaḥ āsanaṃ samarpayāmi ।',
  source_ref = 'StotraNidhi Sri Siddhi Vinayaka Vrata Kalpam (Telugu), round-trip verified Telugu->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Replaces a bare samarpayami tag that carried no verse. Also replaces "asmin haridrā bimbe", which invoked Ganesha into a turmeric cone: that is the Haridra Ganapati rite, and on Ganesha Chaturthi the deity is invoked into the idol.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Avahanam & Asanam';

-- --- ganesha_standard / Padyam & Arghyam
update public.pooja_steps set
  instruction_en = 'Four offerings of water, each into a separate empty bowl, never back into the panchapatra: arghyam for the hands, padyam for the feet, achamaniyam for sipping, and the madhuparkam of curd, milk, honey and ghee for a guest of honour.',
  instruction_ta = 'நான்கு ஜல சமர்ப்பணங்கள் — ஒவ்வொன்றையும் தனி வெறும் பாத்திரத்தில் விடவும், பஞ்சபாத்திரத்திற்குள் மீண்டும் விடக் கூடாது: கைகளுக்கு அர்க்யம், திருவடிகளுக்கு பாத்யம், ஆசமனத்திற்கு ஆசமனீயம், சிறந்த விருந்தினருக்குரிய தயிர், பால், தேன், நெய் கலந்த மதுபர்க்கம்.',
  mantra_sanskrit = 'गौरीपुत्र नमस्तेऽस्तु शंकरप्रियनंदन ।
गृहाणार्घ्यं मया दत्तं गंधपुष्पाक्षतैर्युतम् ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः अर्घ्यं समर्पयामि ।
गजवक्त्र नमस्तेऽस्तु सर्वाभीष्टप्रदायक ।
भक्त्या पाद्यं मया दत्तं गृहाण द्विरदानन ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः पाद्यं समर्पयामि ।
अनाथनाथ सर्वज्ञ गीर्वाणवरपूजित ।
गृहाणाचमनं देव तुभ्यं दत्तं मया प्रभो ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः आचमनीयं समर्पयामि ।
दधिक्षीरसमायुक्तं मध्वाज्येन समन्वितम् ।
मधुपर्कं गृहाणेदं गजवक्त्र नमोऽस्तु ते ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः मधुपर्कं समर्पयामि ।',
  mantra_tamil = 'கௌரீபுத்ர நமஸ்தேஸ்து ஶம்கரப்ரியநம்தந ।
க்ருஹாணார்க்யம் மயா தத்தம் கம்தபுஷ்பாக்ஷதைர்யுதம் ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ அர்க்யம் ஸமர்பயாமி ।
கஜவக்த்ர நமஸ்தேஸ்து ஸர்வாபீஷ்டப்ரதாயக ।
பக்த்யா பாத்யம் மயா தத்தம் க்ருஹாண த்விரதாநந ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ பாத்யம் ஸமர்பயாமி ।
அநாதநாத ஸர்வஜ்ஞ கீர்வாணவரபூஜித ।
க்ருஹாணாசமநம் தேவ துப்யம் தத்தம் மயா ப்ரபோ ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ ஆசமநீயம் ஸமர்பயாமி ।
ததிக்ஷீரஸமாயுக்தம் மத்வாஜ்யேந ஸமந்விதம் ।
மதுபர்கம் க்ருஹாணேதம் கஜவக்த்ர நமோஸ்து தே ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ மதுபர்கம் ஸமர்பயாமி ।',
  mantra_translit = 'gaurīputra namaste''stu śaṃkarapriyanaṃdana ।
gṛhāṇārghyaṃ mayā dattaṃ gaṃdhapuṣpākṣatairyutam ॥
oṃ śrī siddhivināyaka svāmine namaḥ arghyaṃ samarpayāmi ।
gajavaktra namaste''stu sarvābhīṣṭapradāyaka ।
bhaktyā pādyaṃ mayā dattaṃ gṛhāṇa dviradānana ॥
oṃ śrī siddhivināyaka svāmine namaḥ pādyaṃ samarpayāmi ।
anāthanātha sarvajña gīrvāṇavarapūjita ।
gṛhāṇācamanaṃ deva tubhyaṃ dattaṃ mayā prabho ॥
oṃ śrī siddhivināyaka svāmine namaḥ ācamanīyaṃ samarpayāmi ।
dadhikṣīrasamāyuktaṃ madhvājyena samanvitam ।
madhuparkaṃ gṛhāṇedaṃ gajavaktra namo''stu te ॥
oṃ śrī siddhivināyaka svāmine namaḥ madhuparkaṃ samarpayāmi ।',
  source_ref = 'StotraNidhi Sri Siddhi Vinayaka Vrata Kalpam (Telugu), round-trip verified Telugu->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Replaces a bare samarpayami tag that carried no verse.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Padyam & Arghyam';

-- --- ganesha_standard / Snanam & Vastram
update public.pooja_steps set
  instruction_en = 'Bathe the idol in panchamritam, then in clean water, and offer achamaniyam after. Then the vastram, and the single poonal that is on the samagri list for this pooja. Akshatai or a flower stands in for cloth if you have none.',
  instruction_ta = 'விக்கிரகத்திற்கு பஞ்சாமிர்தத்தால் அபிஷேகம் செய்து, பின் சுத்த ஜலத்தால் ஸ்நானம் செய்வித்து, பிறகு ஆசமனீயம் சமர்ப்பிக்கவும். பின் வஸ்திரமும், இந்தப் பூஜைக்கான சாமக்ரி பட்டியலில் உள்ள ஒற்றைப் பூணூலும். துணி இல்லையெனில் அக்ஷதையோ புஷ்பமோ அதற்குப் பதிலாகும்.',
  mantra_sanskrit = 'स्नानं पंचामृतैर्देव गृहाण गणनायक ।
अनाथनाथ सर्वज्ञ गीर्वाणगणपूजित ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः पंचामृत स्नानं समर्पयामि ।
गंगादिसर्वतीर्थेभ्य आहृतैरमलैर्जलैः ।
स्नानं कुरुष्य भगवन्नुमापुत्र नमोऽस्तु ते ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः शुद्धोदक स्नानं समर्पयामि ।
स्नानानंतरं आचमनीयं समर्पयामि ।
रक्तवस्त्रद्वयं चारु देवयोग्यं च मंगळम् ।
शुभप्रद गृहाण त्वं लंबोदर हरात्मज ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः वस्त्रयुग्मं समर्पयामि ।
राजतं ब्रह्मसूत्रं च कांचनं चोत्तरीयकम् ।
गृहाण देव सर्वज्ञ भक्तानामिष्टदायक ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः यज्ञोपवीतं समर्पयामि ।',
  mantra_tamil = 'ஸ்நாநம் பம்சாம்ருதைர்தேவ க்ருஹாண கணநாயக ।
அநாதநாத ஸர்வஜ்ஞ கீர்வாணகணபூஜித ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ பம்சாம்ருத ஸ்நாநம் ஸமர்பயாமி ।
கம்காதிஸர்வதீர்தேப்ய ஆஹ்ருதைரமலைர்ஜலை꞉ ।
ஸ்நாநம் குருஷ்ய பகவந்நுமாபுத்ர நமோஸ்து தே ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ ஶுத்தோதக ஸ்நாநம் ஸமர்பயாமி ।
ஸ்நாநாநம்தரம் ஆசமநீயம் ஸமர்பயாமி ।
ரக்தவஸ்த்ரத்வயம் சாரு தேவயோக்யம் ச மம்களம் ।
ஶுபப்ரத க்ருஹாண த்வம் லம்போதர ஹராத்மஜ ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ வஸ்த்ரயுக்மம் ஸமர்பயாமி ।
ராஜதம் ப்ரஹ்மஸூத்ரம் ச காம்சநம் சோத்தரீயகம் ।
க்ருஹாண தேவ ஸர்வஜ்ஞ பக்தாநாமிஷ்டதாயக ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ யஜ்ஞோபவீதம் ஸமர்பயாமி ।',
  mantra_translit = 'snānaṃ paṃcāmṛtairdeva gṛhāṇa gaṇanāyaka ।
anāthanātha sarvajña gīrvāṇagaṇapūjita ॥
oṃ śrī siddhivināyaka svāmine namaḥ paṃcāmṛta snānaṃ samarpayāmi ।
gaṃgādisarvatīrthebhya āhṛtairamalairjalaiḥ ।
snānaṃ kuruṣya bhagavannumāputra namo''stu te ॥
oṃ śrī siddhivināyaka svāmine namaḥ śuddhodaka snānaṃ samarpayāmi ।
snānānaṃtaraṃ ācamanīyaṃ samarpayāmi ।
raktavastradvayaṃ cāru devayogyaṃ ca maṃgal̤am ।
śubhaprada gṛhāṇa tvaṃ laṃbodara harātmaja ॥
oṃ śrī siddhivināyaka svāmine namaḥ vastrayugmaṃ samarpayāmi ।
rājataṃ brahmasūtraṃ ca kāṃcanaṃ cottarīyakam ।
gṛhāṇa deva sarvajña bhaktānāmiṣṭadāyaka ॥
oṃ śrī siddhivināyaka svāmine namaḥ yajñopavītaṃ samarpayāmi ।',
  source_ref = 'StotraNidhi Sri Siddhi Vinayaka Vrata Kalpam (Telugu), round-trip verified Telugu->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Replaces a bare samarpayami tag that carried no verse.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Snanam & Vastram';

-- --- ganesha_standard / Gandham, Kumkumam & Pushpam
update public.pooja_steps set
  instruction_en = 'Sandal paste first, then kumkumam and akshatai, then the flowers. The pushpam verse asks for the twenty-one leaves by name, which is what the Patra Pooja a few steps later offers one at a time.',
  instruction_ta = 'முதலில் சந்தனம், பின் குங்குமமும் அக்ஷதையும், பிறகு புஷ்பங்கள். புஷ்ப ஸ்லோகம் இருபத்தொரு பத்திரங்களையும் பெயர் சொல்லிக் கேட்கிறது — அவற்றையே சில படிகளுக்குப் பின் வரும் பத்ர பூஜையில் ஒவ்வொன்றாகச் சமர்ப்பிக்கிறோம்.',
  mantra_sanskrit = 'चंदनागरु कर्पूर कस्तूरी कुंकुमान्वितम् ।
विलेपनं सुरश्रेष्ठ प्रीत्यर्थं प्रतिगृह्यताम् ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः श्रीगंधान् धारयामि ।
अक्षतान् धवळान् दिव्यान् शालीयांस्तंडुलान् शुभान् ।
गृहाण परमानंद शंभुपुत्र नमोऽस्तु ते ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः अलंकरणार्थं अक्षतान् समर्पयामि ।
सुगंधानि च पुष्पाणि जातीकुंदमुखानि च ।
एकविंशतिपत्राणि संगृहाण नमोऽस्तु ते ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः पुष्पैः पूजयामि ।',
  mantra_tamil = 'சம்தநாகரு கர்பூர கஸ்தூரீ கும்குமாந்விதம் ।
விலேபநம் ஸுரஶ்ரேஷ்ட ப்ரீத்யர்தம் ப்ரதிக்ருஹ்யதாம் ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ ஶ்ரீகம்தாந் தாரயாமி ।
அக்ஷதாந் தவளாந் திவ்யாந் ஶாலீயாம்ஸ்தம்டுலாந் ஶுபாந் ।
க்ருஹாண பரமாநம்த ஶம்புபுத்ர நமோஸ்து தே ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ அலம்கரணார்தம் அக்ஷதாந் ஸமர்பயாமி ।
ஸுகம்தாநி ச புஷ்பாணி ஜாதீகும்தமுகாநி ச ।
ஏகவிம்ஶதிபத்ராணி ஸம்க்ருஹாண நமோஸ்து தே ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ புஷ்பை꞉ பூஜயாமி ।',
  mantra_translit = 'caṃdanāgaru karpūra kastūrī kuṃkumānvitam ।
vilepanaṃ suraśreṣṭha prītyarthaṃ pratigṛhyatām ॥
oṃ śrī siddhivināyaka svāmine namaḥ śrīgaṃdhān dhārayāmi ।
akṣatān dhaval̤ān divyān śālīyāṃstaṃḍulān śubhān ।
gṛhāṇa paramānaṃda śaṃbhuputra namo''stu te ॥
oṃ śrī siddhivināyaka svāmine namaḥ alaṃkaraṇārthaṃ akṣatān samarpayāmi ।
sugaṃdhāni ca puṣpāṇi jātīkuṃdamukhāni ca ।
ekaviṃśatipatrāṇi saṃgṛhāṇa namo''stu te ॥
oṃ śrī siddhivināyaka svāmine namaḥ puṣpaiḥ pūjayāmi ।',
  source_ref = 'StotraNidhi Sri Siddhi Vinayaka Vrata Kalpam (Telugu), round-trip verified Telugu->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Replaces a bare samarpayami tag that carried no verse.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Gandham, Kumkumam & Pushpam';

-- --- ganesha_standard / Kshama Prarthana & Conclusion
update public.pooja_steps set
  instruction_en = 'Ask forgiveness for whatever was short in the mantras, in the procedure or in the attention, and dedicate the whole pooja. Release akshatai and water at the end.',
  instruction_ta = 'மந்திரத்திலோ, கிரியையிலோ, பக்தியிலோ குறைந்தது எதுவானாலும் மன்னிக்கும்படி வேண்டி, பூஜை முழுவதையும் சமர்ப்பிக்கவும். இறுதியில் அக்ஷதையும் ஜலமும் விடவும்.',
  mantra_sanskrit = 'यस्य स्मृत्या च नामोक्त्या तपः पूजा क्रियादिषु ।
न्यूनं संपूर्णतां याति सद्यो वंदे गजाननम् ॥
मंत्रहीनं क्रियाहीनं भक्तिहीनं विनायक ।
यत्पूजितं मया देव परिपूर्णं तदस्तु ते ॥
अनया ध्यानावहनादि षोडशोपचार पूजया भगवान् सर्वात्मकः श्री सिद्धि विनायकः स्वामि सुप्रीतो सुप्रसन्नो वरदो भवंतु ।',
  mantra_tamil = 'யஸ்ய ஸ்ம்ருத்யா ச நாமோக்த்யா தப꞉ பூஜா க்ரியாதிஷு ।
ந்யூநம் ஸம்பூர்ணதாம் யாதி ஸத்யோ வம்தே கஜாநநம் ॥
மம்த்ரஹீநம் க்ரியாஹீநம் பக்திஹீநம் விநாயக ।
யத்பூஜிதம் மயா தேவ பரிபூர்ணம் ததஸ்து தே ॥
அநயா த்யாநாவஹநாதி ஷோடஶோபசார பூஜயா பகவாந் ஸர்வாத்மக꞉ ஶ்ரீ ஸித்தி விநாயக꞉ ஸ்வாமி ஸுப்ரீதோ ஸுப்ரஸந்நோ வரதோ பவம்து ।',
  mantra_translit = 'yasya smṛtyā ca nāmoktyā tapaḥ pūjā kriyādiṣu ।
nyūnaṃ saṃpūrṇatāṃ yāti sadyo vaṃde gajānanam ॥
maṃtrahīnaṃ kriyāhīnaṃ bhaktihīnaṃ vināyaka ।
yatpūjitaṃ mayā deva paripūrṇaṃ tadastu te ॥
anayā dhyānāvahanādi ṣoḍaśopacāra pūjayā bhagavān sarvātmakaḥ śrī siddhi vināyakaḥ svāmi suprīto suprasanno varado bhavaṃtu ।',
  source_ref = 'StotraNidhi Sri Siddhi Vinayaka Vrata Kalpam (Telugu), round-trip verified Telugu->Devanagari by scripts/build-purvangam-and-upacharas.mjs. Replaces a bare samarpayami tag that carried no verse.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Kshama Prarthana & Conclusion';

-- --- assert -------------------------------------------------------------------
do $$
declare n int;
begin
  -- The misspellings must be gone everywhere, not just where this migration looked.
  select count(*) into n from public.pooja_steps
   where mantra_sanskrit like '%व्हान%' or mantra_sanskrit like '%घन्ट%'
      or mantra_translit like '%vhāna%' or mantra_translit like '%ghanṭ%';
  if n > 0 then raise exception '% steps still carry the ghanta misspellings', n; end if;
  select count(*) into n from public.pooja_steps
   where step_title_en = 'Ghanta Pooja' and mantra_sanskrit like '%देवताह्वान%';
  if n <> 2 then raise exception 'expected both ghanta steps corrected, found %', n; end if;
  -- Kalasha without the samprokshana is the step with its point removed.
  select count(*) into n from public.pooja_steps
   where step_title_en = 'Kalasha Pooja'
     and mantra_sanskrit like '%कलशस्य मुखे%' and mantra_sanskrit like '%सम्प्रोक्ष्य%';
  if n <> 2 then raise exception 'expected both kalasha steps filled out, found %', n; end if;
  -- No turmeric cone in the Chaturthi avahanam.
  select count(*) into n from public.pooja_steps
   where pooja_id = 'ganesha_standard' and step_title_en = 'Avahanam & Asanam' and mantra_sanskrit like '%हरिद्रा%';
  if n > 0 then raise exception 'Ganesha is still invoked into a turmeric image'; end if;
  -- Only the Sankalpam may still be an unreviewed draft.
  select count(*) into n from public.pooja_steps
   where source_ref like '%Tamil draft, pending vaidika review%'
     and step_title_en <> 'Sankalpam';
  if n > 0 then raise exception '% steps other than Sankalpam are still drafts', n; end if;
end $$;

commit;

-- Verify:
--   select pooja_id, step_title_en from pooja_steps where source_ref like '%pending vaidika review%';
