-- =============================================================================
-- 0021_prana_pratishtha_and_udvasanam.sql
--
-- GENERATED by scripts/build-prana-pratishtha.mjs. Do not hand-edit.
--
-- Prana Pratishtha held one verse and a samarpayami tag, under a source_ref
-- that named no text -- "Standard prana pratishtha verse". It appears in none
-- of this project's cached sources: it was typed from memory in 0010.
--
-- Udvasanam was worse as a truncation: it held the FIRST HALF of yajñena
-- yajñamayajanta and stopped mid-verse, and had none of the closing
-- śobhanārthe kṣemāya punarāgamanāya ca, which is the last thing said in the
-- whole pooja.
--
-- Both genders are published text now. The masculine comes from the Haridra
-- Ganapati puja and the feminine from the Lalitha shodashopachara vidhanam;
-- they share the Vedic core, asunīte punarasmāsu cakṣuḥ and amṛtaṃ vai
-- prāṇāḥ, and differ where Sanskrit gender makes them differ.
--
-- Idempotent.
-- =============================================================================

begin;

-- --- ganesha_standard / Prana Pratishtha
update public.pooja_steps set
  mantra_sanskrit = 'ॐ असुनीते पुनरस्मासु चक्षुः
पुनः प्राणमिह नो धेहि भोगम् ।
ज्योक्पश्येम सूर्यमुच्चरन्त
मनुमते मृडया नः स्वस्ति ॥
अमृतं वै प्राणा अमृतमापः
प्राणानेव यथास्थानमुपह्वयते ॥
श्री महागणपतये नमः ।
स्थिरो भव वरदो भव ।
सुमुखो भव सुप्रसन्नो भव ।
स्थिरासनं कुरु ।',
  mantra_tamil = 'ஓம் அஸுநீதே புநரஸ்மாஸு சக்ஷு꞉
புந꞉ ப்ராணமிஹ நோ தேஹி போகம் ।
ஜ்யோக்பஶ்யேம ஸூர்யமுச்சரந்த
மநுமதே ம்ருடயா ந꞉ ஸ்வஸ்தி ॥
அம்ருதம் வை ப்ராணா அம்ருதமாப꞉
ப்ராணாநேவ யதாஸ்தாநமுபஹ்வயதே ॥
ஶ்ரீ மஹாகணபதயே நம꞉ ।
ஸ்திரோ பவ வரதோ பவ ।
ஸுமுகோ பவ ஸுப்ரஸந்நோ பவ ।
ஸ்திராஸநம் குரு ।',
  mantra_translit = 'oṃ asunīte punarasmāsu cakṣuḥ
punaḥ prāṇamiha no dhehi bhogam ।
jyokpaśyema sūryamuccaranta
manumate mṛḍayā naḥ svasti ॥
amṛtaṃ vai prāṇā amṛtamāpaḥ
prāṇāneva yathāsthānamupahvayate ॥
śrī mahāgaṇapataye namaḥ ।
sthiro bhava varado bhava ।
sumukho bhava suprasanno bhava ।
sthirāsanaṃ kuru ।',
  meaning_en = 'Asunite, giver of life: give us back our sight, give us back our breath and our enjoyment here. May we long see the sun rising; be gracious to us, Anumati, and grant us well-being. The breaths are the deathless, the waters are the deathless: the breaths are called back, each to its own place. To Sri Mahaganapati, salutations. Be steady; be the giver of boons; be gracious of face; be well pleased; take a firm seat.',
  philosophy_en = 'Everything before this prepares a seat. This is the step that makes the rest of the pooja hospitality rather than arrangement. The verse is Rigveda 10.59.6, and it is not addressed to the idol at all — it asks that breath, sight and gladness be given back, and only then does the invocation turn to the deity and ask him to sit. A goddess takes the feminine form, which the Varalakshmi step carries.',
  source_ref = 'StotraNidhi Sri Haridra Ganapati Puja (Telugu, with svara), prāṇapratiṣṭha section, round-trip verified Telugu->Devanagari by scripts/build-prana-pratishtha.mjs. Replaces the single verse written in migration 0010, whose source_ref named a video chapter and a tradition but no text, and which appears in none of this project’s cached sources. (Deliberately paraphrased: quoting the old source_ref verbatim here would make this one match the gate that hunts for survivors of it, which is exactly what happened in 0019.) Svara marks are stripped.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Prana Pratishtha';

-- --- varalakshmi_vratham / Prana Pratishtha
update public.pooja_steps set
  mantra_sanskrit = 'ॐ असुनीते पुनरस्मासु चक्षुः
पुनः प्राणमिह नो धेहि भोगम् ।
ज्योक्पश्येम सूर्यमुच्चरन्त
मनुमते मृडया नः स्वस्ति ।
अमृतं वै प्राणा अमृतमापः
प्राणानेव यथास्थानमुपह्वयते ॥
श्री वरलक्ष्मी देवतायै नमः ।
आवाहिता भव स्थापिता भव ।
सुप्रसन्नो भव वरदा भव ।
स्थिरासनं कुरु प्रसीद प्रसीद ।',
  mantra_tamil = 'ஓம் அஸுநீதே புநரஸ்மாஸு சக்ஷு꞉
புந꞉ ப்ராணமிஹ நோ தேஹி போகம் ।
ஜ்யோக்பஶ்யேம ஸூர்யமுச்சரந்த
மநுமதே ம்ருடயா ந꞉ ஸ்வஸ்தி ।
அம்ருதம் வை ப்ராணா அம்ருதமாப꞉
ப்ராணாநேவ யதாஸ்தாநமுபஹ்வயதே ॥
ஶ்ரீ வரலக்ஷ்மீ தேவதாயை நம꞉ ।
ஆவாஹிதா பவ ஸ்தாபிதா பவ ।
ஸுப்ரஸந்நோ பவ வரதா பவ ।
ஸ்திராஸநம் குரு ப்ரஸீத ப்ரஸீத ।',
  mantra_translit = 'oṃ asunīte punarasmāsu cakṣuḥ
punaḥ prāṇamiha no dhehi bhogam ।
jyokpaśyema sūryamuccaranta
manumate mṛḍayā naḥ svasti ।
amṛtaṃ vai prāṇā amṛtamāpaḥ
prāṇāneva yathāsthānamupahvayate ॥
śrī varalakṣmī devatāyai namaḥ ।
āvāhitā bhava sthāpitā bhava ।
suprasanno bhava varadā bhava ।
sthirāsanaṃ kuru prasīda prasīda ।',
  meaning_en = 'Asunite, giver of life: give us back our sight, give us back our breath and our enjoyment here. May we long see the sun rising; be gracious to us, Anumati, and grant us well-being. The breaths are the deathless, the waters are the deathless: the breaths are called back, each to its own place. To Sri Varalakshmi, salutations. Be invoked; be established; be well pleased; be the giver of boons; take a firm seat; be gracious, be gracious.',
  philosophy_en = 'The same Vedic verse as at Ganesha Chaturthi, and the same turn: it asks that breath and sight be given back before it asks anything of the goddess. The feminine forms are not cosmetic — āvāhitā, sthāpitā, varadā are how the published Lalitha vidhanam writes them, and it is why the kalasham is dismantled the next day with a step of its own rather than simply being put away.',
  source_ref = 'StotraNidhi Sri Lalitha Shodasopachara Puja Vidhanam (IAST), prāṇapratiṣṭha section, round-trip verified IAST->Devanagari by scripts/build-prana-pratishtha.mjs. The feminine recension: āvāhitā bhava, sthāpitā bhava, varadā bhava where the masculine has sthiro bhava, varado bhava. The Varalakshmi Vrata Kalpam carries no prana pratishtha of its own, and the namaskara naming the goddess is supplied. Svara marks are stripped.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Prana Pratishtha';

-- --- ganesha_standard / Udvasanam
update public.pooja_steps set
  mantra_sanskrit = 'ॐ यज्ञेन यज्ञमयजन्त देवाः ।
तानि धर्माणि प्रथमान्यासन् ।
ते ह नाकं महिमानस्सचन्ते ।
यत्र पूर्वे साध्यास्सन्ति देवाः ॥
ॐ श्री महागणपतये नमः यथास्थानं उद्वासयामि ॥
शोभनार्थे क्षेमाय पुनरागमनाय च ।
ॐ शांतिः शांतिः शांतिः ।',
  mantra_tamil = 'ஓம் யஜ்ஞேந யஜ்ஞமயஜந்த தேவா꞉ ।
தாநி தர்மாணி ப்ரதமாந்யாஸந் ।
தே ஹ நாகம் மஹிமாநஸ்ஸசந்தே ।
யத்ர பூர்வே ஸாத்யாஸ்ஸந்தி தேவா꞉ ॥
ஓம் ஶ்ரீ மஹாகணபதயே நம꞉ யதாஸ்தாநம் உத்வாஸயாமி ॥
ஶோபநார்தே க்ஷேமாய புநராகமநாய ச ।
ஓம் ஶாம்தி꞉ ஶாம்தி꞉ ஶாம்தி꞉ ।',
  mantra_translit = 'oṃ yajñena yajñamayajanta devāḥ ।
tāni dharmāṇi prathamānyāsan ।
te ha nākaṃ mahimānassacante ।
yatra pūrve sādhyāssanti devāḥ ॥
oṃ śrī mahāgaṇapataye namaḥ yathāsthānaṃ udvāsayāmi ॥
śobhanārthe kṣemāya punarāgamanāya ca ।
oṃ śāṃtiḥ śāṃtiḥ śāṃtiḥ ।',
  meaning_en = 'By sacrifice the gods sacrificed to sacrifice; these were the first observances. They reached the height where the ancient Sadhyas, the gods, abide. To Sri Mahaganapati, salutations: I take leave of you to your own place — for what is good, for well-being, and for your coming again. Peace, peace, peace.',
  philosophy_en = 'Prana Pratishtha made the clay a living presence, so something has to formally end that, and the half-verse this step used to carry ended nothing. Punarāgamanāya ca, "and for your coming again", is the line that makes the leave-taking an invitation rather than a dismissal. It is the step the diaspora most often does not know exists.',
  source_ref = 'StotraNidhi Sri Haridra Ganapati Puja (Telugu, with svara), udvāsanam section, round-trip verified Telugu->Devanagari by scripts/build-prana-pratishtha.mjs. The earlier text held only the first half of yajñena yajñamayajanta and stopped mid-verse, and had none of the closing śobhanārthe kṣemāya punarāgamanāya ca. Svara marks are stripped.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'ganesha_standard' and step_title_en = 'Udvasanam';

-- --- varalakshmi_vratham / Udvasanam
update public.pooja_steps set
  mantra_sanskrit = 'ॐ यज्ञेन यज्ञमयजन्त देवाः ।
तानि धर्माणि प्रथमान्यासन् ।
ते ह नाकं महिमानस्सचन्ते ।
यत्र पूर्वे साध्यास्सन्ति देवाः ॥
ॐ श्री वरलक्ष्मी देवतायै नमः यथास्थानं उद्वासयामि ॥
शोभनार्थे क्षेमाय पुनरागमनाय च ।
ॐ शांतिः शांतिः शांतिः ।',
  mantra_tamil = 'ஓம் யஜ்ஞேந யஜ்ஞமயஜந்த தேவா꞉ ।
தாநி தர்மாணி ப்ரதமாந்யாஸந் ।
தே ஹ நாகம் மஹிமாநஸ்ஸசந்தே ।
யத்ர பூர்வே ஸாத்யாஸ்ஸந்தி தேவா꞉ ॥
ஓம் ஶ்ரீ வரலக்ஷ்மீ தேவதாயை நம꞉ யதாஸ்தாநம் உத்வாஸயாமி ॥
ஶோபநார்தே க்ஷேமாய புநராகமநாய ச ।
ஓம் ஶாம்தி꞉ ஶாம்தி꞉ ஶாம்தி꞉ ।',
  mantra_translit = 'oṃ yajñena yajñamayajanta devāḥ ।
tāni dharmāṇi prathamānyāsan ।
te ha nākaṃ mahimānassacante ।
yatra pūrve sādhyāssanti devāḥ ॥
oṃ śrī varalakṣmī devatāyai namaḥ yathāsthānaṃ udvāsayāmi ॥
śobhanārthe kṣemāya punarāgamanāya ca ।
oṃ śāṃtiḥ śāṃtiḥ śāṃtiḥ ।',
  meaning_en = 'By sacrifice the gods sacrificed to sacrifice; these were the first observances. They reached the height where the ancient Sadhyas, the gods, abide. To Sri Varalakshmi, salutations: I take leave of you to your own place — for what is good, for well-being, and for your coming again. Peace, peace, peace.',
  philosophy_en = 'Prana Pratishtha made the kalasham a presence, so something has to end that; without it the vessels are put away with a guest still in them. Punarāgamanāya ca, "and for your coming again", is why the thread comes off next year rather than never, and why the vratham is annual.',
  source_ref = 'StotraNidhi Sri Haridra Ganapati Puja (Telugu, with svara), udvāsanam section, round-trip verified Telugu->Devanagari, with the namaskara changed to name the goddess. yathāsthānaṃ udvāsayāmi is the performer’s verb and does not inflect for the deity’s gender, so only the namaskara differs. The earlier text held only the first half of the verse.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Udvasanam';

-- --- assert -------------------------------------------------------------------
do $$
declare n int;
begin
  select count(*) into n from public.pooja_steps
   where step_title_en in ('Prana Pratishtha', 'Udvasanam')
     and (mantra_sanskrit is null
          or (length(mantra_sanskrit) - length(replace(mantra_sanskrit, chr(10), ''))) < 4);
  if n > 0 then raise exception '% of these steps are still short', n; end if;
  -- The verse that traced to no text must be gone from both poojas.
  select count(*) into n from public.pooja_steps
   where mantra_sanskrit like '%प्राणाः प्रतिष्ठन्तु%';
  if n > 0 then raise exception '% steps still carry the unsourced pratishthantu verse', n; end if;
  -- Gender must be right in each: masculine for Ganesha, feminine for the goddess.
  select count(*) into n from public.pooja_steps
   where pooja_id = 'ganesha_standard' and step_title_en = 'Prana Pratishtha' and mantra_sanskrit like '%स्थिरो भव%';
  if n <> 1 then raise exception 'the Ganesha prana pratishtha is not in the masculine'; end if;
  select count(*) into n from public.pooja_steps
   where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Prana Pratishtha'
     and mantra_sanskrit like '%वरदा भव%' and mantra_sanskrit not like '%वरदो भव%';
  if n <> 1 then raise exception 'the Varalakshmi prana pratishtha is not in the feminine'; end if;
  -- The udvasanam verse must be whole, and must end the pooja properly.
  select count(*) into n from public.pooja_steps
   where step_title_en = 'Udvasanam'
     and mantra_sanskrit like '%ते ह नाकं%' and mantra_sanskrit like '%पुनरागमनाय%'
     and mantra_sanskrit like '%शांतिः शांतिः शांतिः%';
  if n <> 2 then raise exception 'expected both udvasanams whole, found %', n; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;

-- Verify:
--   select pooja_id, length(mantra_sanskrit) from pooja_steps where step_title_en = 'Prana Pratishtha';
