-- =============================================================================
-- 0026_prana_pratishtha_nyasa.sql
--
-- GENERATED by scripts/build-prana-pratishtha-nyasa.mjs. Do not hand-edit.
--
-- Prana Pratishtha has been wrong twice. First it was invented -- "I shall now
-- perform prana pratishtha", with no mantra behind it. 0021 replaced that with
-- the genuine Vedic core, which was right as far as it went, and it went about
-- a fifth of the way: the rite the book prints runs six pages and what 0021
-- restored sits in the middle of it.
--
-- Added: the viniyoga (rishi, chhandas, devata, bija, shakti, kilaka); the kara
-- nyasa; the anga nyasa and the digbandha; the dhyanam of Prana Shakti; the
-- bija string and hamsah so-ham; "asyam murtau pranastishthatu", the sentence
-- that actually asks the breath and every sense to come and stay; six more
-- bhava lines; and the request to remain until the pooja ends.
--
-- AND a defect the book exposed. Pages 24-25 print the bhava lines in parallel
-- masculine and feminine columns. Varalakshmi mixed them: feminine aavaahitaa,
-- sthaapitaa and varadaa, with MASCULINE suprasanno among them. One word is
-- corrected here and nothing else, because Varalakshmi is on hold until its own
-- section of the book is photographed.
--
-- Idempotent.
-- =============================================================================

begin;

-- --- ganesha_standard / Prana Pratishtha -------------------------------------
update public.pooja_steps set
  mantra_sanskrit = 'ॐ अस्य श्री प्राणप्रतिष्ठा महामन्त्रस्य ।
ब्रह्म विष्णु महेश्वराः ऋषयः ।
ऋग्यजुस्सामाथर्वाणि छन्दांसि ।
सकल जगत्सृष्टिस्थिति संहारकारिणी प्राणशक्तिः परादेवता ।
आं बीजम् । ह्रीं शक्तिः । क्रों कीलकम् ।
प्राण प्रतिष्ठार्थे जपे विनियोगः ॥
आं अंगुष्ठाभ्यां नमः ।
ह्रीं तर्जनीभ्यां नमः ।
क्रों मध्यमाभ्यां नमः ।
आं अनामिकाभ्यां नमः ।
ह्रीं कनिष्ठिकाभ्यां नमः ।
क्रों करतलकरपृष्ठाभ्यां नमः ॥
आं हृदयाय नमः ।
ह्रीं शिरसे स्वाहा ।
क्रों शिखायै वषट् ।
आं कवचाय हुं ।
ह्रीं नेत्रत्रयाय वौषट् ।
क्रों अस्त्राय फट् ।
भूर्भुवस्सुवरोमिति दिग्बन्धः ॥
रक्तांबोधिस्थ पोतोल्लसदरुण सरोजाधिरूढा कराब्जैः ।
पाशं कोदण्डमिक्षूद्भवमलिगुणमप्यंकुशं पञ्चबाणान् ॥
बिभ्राणासृक्कपालं त्रिनयनलसिताऽऽपीन वक्षोरुहाढ्या ।
देवी बालार्कवर्णा भवतु सुखकरी प्राणशक्तिः परा नः ॥
ॐ आं ह्रीं क्रों । क्रों ह्रीं आं ।
अं यं रं लं वं शं षं सं हं ।
हंसः सोऽहं, सोऽहं हंसः ॥
अस्यां मूर्तौ प्राणस्तिष्ठतु जीवस्तिष्ठतु ।
अस्यां मूर्तौ सर्वेन्द्रियाणि
वाङ् मनस् त्वक् चक्षुः श्रोत्र जिह्वा घ्राण पाणि पाद पायूपस्थानि,
प्राणापान व्यानोदान समानाः इहागत्य
स्वस्ति सुखं चिरं तिष्ठन्तु स्वाहा ॥
सान्निध्यं कुरु स्वाहा ।
ॐ असुनीते पुनरस्मासु चक्षुः
पुनः प्राणमिह नो धेहि भोगम् ।
ज्योक्पश्येम सूर्यमुच्चरन्त
मनुमते मृडया नः स्वस्ति ॥
प्राणान् प्रतिष्ठापयामि ।
अमृतं वै प्राणा अमृतमापः
प्राणानेव यथास्थानमुपह्वयते ॥
ॐ श्री सिद्धिविनायक स्वामिने नमः ।
आवाहितो भव । स्थापितो भव ।
सन्निहितो भव । सन्निरुद्धो भव ।
अवकुण्ठितो भव । सुप्रीतो भव ।
सुप्रसन्नो भव । सुमुखो भव । वरदो भव ॥
स्थिरो भव । स्थिरासनं कुरु ।
स्वामिन् सर्वजगन्नाथ
यावत्पूजावसानकाले तावत् त्वं प्रीतिभावेन
बिंबेऽस्मिन् सन्निधिं कुरु ॥',
  mantra_tamil = 'ஓம் அஸ்ய ஶ்ரீ ப்ராணப்ரதிஷ்டா மஹாமந்த்ரஸ்ய ।
ப்ரஹ்ம விஷ்ணு மஹேஶ்வரா꞉ ருஷய꞉ ।
ருக்யஜுஸ்ஸாமாதர்வாணி சந்தாம்ஸி ।
ஸகல ஜகத்ஸ்ருஷ்டிஸ்திதி ஸம்ஹாரகாரிணீ ப்ராணஶக்தி꞉ பராதேவதா ।
ஆம் பீஜம் । ஹ்ரீம் ஶக்தி꞉ । க்ரோம் கீலகம் ।
ப்ராண ப்ரதிஷ்டார்தே ஜபே விநியோக꞉ ॥
ஆம் அம்குஷ்டாப்யாம் நம꞉ ।
ஹ்ரீம் தர்ஜநீப்யாம் நம꞉ ।
க்ரோம் மத்யமாப்யாம் நம꞉ ।
ஆம் அநாமிகாப்யாம் நம꞉ ।
ஹ்ரீம் கநிஷ்டிகாப்யாம் நம꞉ ।
க்ரோம் கரதலகரப்ருஷ்டாப்யாம் நம꞉ ॥
ஆம் ஹ்ருதயாய நம꞉ ।
ஹ்ரீம் ஶிரஸே ஸ்வாஹா ।
க்ரோம் ஶிகாயை வஷட் ।
ஆம் கவசாய ஹும் ।
ஹ்ரீம் நேத்ரத்ரயாய வௌஷட் ।
க்ரோம் அஸ்த்ராய பட் ।
பூர்புவஸ்ஸுவரோமிதி திக்பந்த꞉ ॥
ரக்தாம்போதிஸ்த போதோல்லஸதருண ஸரோஜாதிரூடா கராப்ஜை꞉ ।
பாஶம் கோதண்டமிக்ஷூத்பவமலிகுணமப்யம்குஶம் பஞ்சபாணாந் ॥
பிப்ராணாஸ்ருக்கபாலம் த்ரிநயநலஸிதாபீந வக்ஷோருஹாட்யா ।
தேவீ பாலார்கவர்ணா பவது ஸுககரீ ப்ராணஶக்தி꞉ பரா ந꞉ ॥
ஓம் ஆம் ஹ்ரீம் க்ரோம் । க்ரோம் ஹ்ரீம் ஆம் ।
அம் யம் ரம் லம் வம் ஶம் ஷம் ஸம் ஹம் ।
ஹம்ஸ꞉ ஸோஹம், ஸோஹம் ஹம்ஸ꞉ ॥
அஸ்யாம் மூர்தௌ ப்ராணஸ்திஷ்டது ஜீவஸ்திஷ்டது ।
அஸ்யாம் மூர்தௌ ஸர்வேந்த்ரியாணி
வாங் மநஸ் த்வக் சக்ஷு꞉ ஶ்ரோத்ர ஜிஹ்வா க்ராண பாணி பாத பாயூபஸ்தாநி,
ப்ராணாபாந வ்யாநோதாந ஸமாநா꞉ இஹாகத்ய
ஸ்வஸ்தி ஸுகம் சிரம் திஷ்டந்து ஸ்வாஹா ॥
ஸாந்நித்யம் குரு ஸ்வாஹா ।
ஓம் அஸுநீதே புநரஸ்மாஸு சக்ஷு꞉
புந꞉ ப்ராணமிஹ நோ தேஹி போகம் ।
ஜ்யோக்பஶ்யேம ஸூர்யமுச்சரந்த
மநுமதே ம்ருடயா ந꞉ ஸ்வஸ்தி ॥
ப்ராணாந் ப்ரதிஷ்டாபயாமி ।
அம்ருதம் வை ப்ராணா அம்ருதமாப꞉
ப்ராணாநேவ யதாஸ்தாநமுபஹ்வயதே ॥
ஓம் ஶ்ரீ ஸித்திவிநாயக ஸ்வாமிநே நம꞉ ।
ஆவாஹிதோ பவ । ஸ்தாபிதோ பவ ।
ஸந்நிஹிதோ பவ । ஸந்நிருத்தோ பவ ।
அவகுண்டிதோ பவ । ஸுப்ரீதோ பவ ।
ஸுப்ரஸந்நோ பவ । ஸுமுகோ பவ । வரதோ பவ ॥
ஸ்திரோ பவ । ஸ்திராஸநம் குரு ।
ஸ்வாமிந் ஸர்வஜகந்நாத
யாவத்பூஜாவஸாநகாலே தாவத் த்வம் ப்ரீதிபாவேந
பிம்பேஸ்மிந் ஸந்நிதிம் குரு ॥',
  mantra_translit = 'oṃ asya śrī prāṇapratiṣṭhā mahāmantrasya ।
brahma viṣṇu maheśvarāḥ ṛṣayaḥ ।
ṛgyajussāmātharvāṇi chandāṃsi ।
sakala jagatsṛṣṭisthiti saṃhārakāriṇī prāṇaśaktiḥ parādevatā ।
āṃ bījam । hrīṃ śaktiḥ । kroṃ kīlakam ।
prāṇa pratiṣṭhārthe jape viniyogaḥ ॥
āṃ aṃguṣṭhābhyāṃ namaḥ ।
hrīṃ tarjanībhyāṃ namaḥ ।
kroṃ madhyamābhyāṃ namaḥ ।
āṃ anāmikābhyāṃ namaḥ ।
hrīṃ kaniṣṭhikābhyāṃ namaḥ ।
kroṃ karatalakarapṛṣṭhābhyāṃ namaḥ ॥
āṃ hṛdayāya namaḥ ।
hrīṃ śirase svāhā ।
kroṃ śikhāyai vaṣaṭ ।
āṃ kavacāya huṃ ।
hrīṃ netratrayāya vauṣaṭ ।
kroṃ astrāya phaṭ ।
bhūrbhuvassuvaromiti digbandhaḥ ॥
raktāṃbodhistha potollasadaruṇa sarojādhirūḍhā karābjaiḥ ।
pāśaṃ kodaṇḍamikṣūdbhavamaliguṇamapyaṃkuśaṃ pañcabāṇān ॥
bibhrāṇāsṛkkapālaṃ trinayanalasitā''''pīna vakṣoruhāḍhyā ।
devī bālārkavarṇā bhavatu sukhakarī prāṇaśaktiḥ parā naḥ ॥
oṃ āṃ hrīṃ kroṃ । kroṃ hrīṃ āṃ ।
aṃ yaṃ raṃ laṃ vaṃ śaṃ ṣaṃ saṃ haṃ ।
haṃsaḥ so''haṃ, so''haṃ haṃsaḥ ॥
asyāṃ mūrtau prāṇastiṣṭhatu jīvastiṣṭhatu ।
asyāṃ mūrtau sarvendriyāṇi
vāṅ manas tvak cakṣuḥ śrotra jihvā ghrāṇa pāṇi pāda pāyūpasthāni,
prāṇāpāna vyānodāna samānāḥ ihāgatya
svasti sukhaṃ ciraṃ tiṣṭhantu svāhā ॥
sānnidhyaṃ kuru svāhā ।
oṃ asunīte punarasmāsu cakṣuḥ
punaḥ prāṇamiha no dhehi bhogam ।
jyokpaśyema sūryamuccaranta
manumate mṛḍayā naḥ svasti ॥
prāṇān pratiṣṭhāpayāmi ।
amṛtaṃ vai prāṇā amṛtamāpaḥ
prāṇāneva yathāsthānamupahvayate ॥
oṃ śrī siddhivināyaka svāmine namaḥ ।
āvāhito bhava । sthāpito bhava ।
sannihito bhava । sanniruddho bhava ।
avakuṇṭhito bhava । suprīto bhava ।
suprasanno bhava । sumukho bhava । varado bhava ॥
sthiro bhava । sthirāsanaṃ kuru ।
svāmin sarvajagannātha
yāvatpūjāvasānakāle tāvat tvaṃ prītibhāvena
biṃbe''smin sannidhiṃ kuru ॥',
  instruction_en = 'Place the right palm on the head, the nostrils and the chest for the three lines of the viniyoga, then on the right chest, the left chest and the middle of the chest for the bija, shakti and kilaka. For the kara nyasa roll the thumb from the base of each finger to its tip in turn, then rub the palms together. For the anga nyasa touch chest, forehead, tuft, shoulders crossed, the three eyes, and strike the left palm with the right index and middle fingers. Seal the directions by rolling the right hand clockwise around the head. Then meditate on Prana Shakti and chant. BEFORE the asunite verse, chant "Om" fifteen times, for the fifteen sacraments of the deity from jatakarma onwards. Finish with the nine "bhava" lines, asking the deity to remain until the pooja ends.',
  instruction_ta = 'விநியோகத்தின் மூன்று வரிகளுக்கு வலது உள்ளங்கையைத் தலையிலும், நாசியிலும், மார்பிலும் வைக்கவும்; பீஜம், சக்தி, கீலகம் ஆகியவற்றுக்கு வலது மார்பு, இடது மார்பு, மார்பின் நடு ஆகியவற்றில் வைக்கவும். கர ந்யாஸத்தில், ஒவ்வொரு விரலின் அடியிலிருந்து நுனி வரை கட்டைவிரலை உருட்டவும்; பிறகு இரு உள்ளங்கைகளையும் தேய்க்கவும். அங்க ந்யாஸத்தில் மார்பு, நெற்றி, குடுமி, கை குறுக்காகத் தோள்கள், மூன்று கண்கள் ஆகியவற்றைத் தொட்டு, வலது ஆள்காட்டி நடுவிரல்களால் இடது உள்ளங்கையில் தட்டவும். வலது கையைத் தலையைச் சுற்றி வலமாகச் சுழற்றி திக்பந்தம் செய்யவும். பிறகு ப்ராணசக்தியை த்யானித்துச் சொல்லவும். "அஸுநீதே" மந்திரத்திற்கு முன், ஜாதகர்மம் முதலான பதினைந்து சம்ஸ்காரங்களுக்காக "ஓம்" பதினைந்து முறை சொல்லவும். இறுதியாக ஒன்பது "பவ" வரிகளைச் சொல்லி, பூஜை முடியும் வரை எழுந்தருளியிருக்கும்படி வேண்டவும்.',
  meaning_en = 'The mantra of prana pratishtha: its rishis are Brahma, Vishnu and Maheshwara; its metres are the Rig, Yajus, Saman and Atharvan; its deity is the supreme Prana Shakti who makes, sustains and withdraws the whole world. Aam is the seed, hreem the power, krom the pin; it is used in recitation for the establishing of life. May the goddess of the colour of the young sun, seated on the lotus, bearing noose and bow and goad and five arrows, become the giver of happiness to us. In this image let the breath abide and the life abide; in this image let all the senses — speech, mind, skin, eye, ear, tongue, nose, hands, feet, and the organs below — and the five breaths come and remain, well and happy, for a long time. Giver of breath, place sight in us again, and breath again, and enjoyment here; long may we see the sun rise. Be invoked, be established, be present, be held here, be veiled, be well pleased, be gracious, be fair of face, be the giver of boons. Lord of all the world, until the pooja ends remain with love in this image.',
  source_ref = 'Sampradaya Vratha Pooja Vidhi (Giri), purvanga pooja pp.19-25, step 18, praaNapratiSHTHaa, in full: viniyoga, kara nyaasa, anga nyaasa, digbandha, the dhyaanam of Praana Shakti, the bija string, "asyaam moortau praaNastiSHTHatu", and the nine bhava lines from the masculine column on p.24-25. "bimbe''smin" is chosen from the book''s three alternatives (bimbe''smin / kalashe''smin / pratimaayaam) because this deity is invoked into a clay image. "amRtaM vai praaNaa", and "sthiro bhava / sthiraasanam kuru", are retained from the previous StotraNidhi-sourced text although the book does not print them here. One phrase is replaced rather than kept: the deity address "shree mahaagaNapataye namaha" becomes "OM shree siddhivinaayaka svaamine namaha", which is the address every other step in this pooja uses. Transcribed from a photograph of the printed page, so unlike the round-tripped sources in this project it carries no reversibility proof. Tamil instruction prose is this project’s own drafting.',
  verified_by = null,
  verified_at = null,
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Prana Pratishtha';

-- --- varalakshmi_vratham: the gender agreement only --------------------------
-- A masculine bhava line standing in a feminine set. Scoped to a replace of
-- that one phrase so nothing else in the step moves.
update public.pooja_steps set mantra_sanskrit = replace(mantra_sanskrit, 'सुप्रसन्नो भव', 'सुप्रसन्ना भव'),
  updated_at = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Prana Pratishtha';
update public.pooja_steps set mantra_tamil = replace(mantra_tamil, 'ஸுப்ரஸந்நோ பவ', 'ஸுப்ரஸந்நா பவ'),
  updated_at = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Prana Pratishtha';
update public.pooja_steps set mantra_translit = replace(mantra_translit, 'suprasanno bhava', 'suprasannā bhava'),
  updated_at = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Prana Pratishtha';

-- --- assert -------------------------------------------------------------------
do $$
declare n int;
begin
  -- The rite is no longer a fragment.
  select count(*) into n from public.pooja_steps
   where pooja_id = 'ganesha_standard' and step_title_en = 'Prana Pratishtha'
     and mantra_sanskrit like '%प्राण प्रतिष्ठार्थे जपे विनियोगः%'
     and mantra_sanskrit like '%करतलकरपृष्ठाभ्यां%'
     and mantra_sanskrit like '%दिग्बन्धः%'
     and mantra_sanskrit like '%अस्यां मूर्तौ प्राणस्तिष्ठतु%'
     and mantra_sanskrit like '%यावत्पूजावसानकाले%';
  if n <> 1 then raise exception 'the prana pratishtha is still missing a section'; end if;
  -- All nine bhava lines, as PHRASES. Counting the substring "bhava" finds
  -- eleven, because the dhyanam says "bhavatu sukhakaree".
  select count(*) into n from public.pooja_steps
   where pooja_id = 'ganesha_standard' and step_title_en = 'Prana Pratishtha'
     and mantra_sanskrit like '%' || 'आवाहितो भव' || '%'
     and mantra_sanskrit like '%' || 'स्थापितो भव' || '%'
     and mantra_sanskrit like '%' || 'सन्निहितो भव' || '%'
     and mantra_sanskrit like '%' || 'सन्निरुद्धो भव' || '%'
     and mantra_sanskrit like '%' || 'अवकुण्ठितो भव' || '%'
     and mantra_sanskrit like '%' || 'सुप्रीतो भव' || '%'
     and mantra_sanskrit like '%' || 'सुप्रसन्नो भव' || '%'
     and mantra_sanskrit like '%' || 'सुमुखो भव' || '%'
     and mantra_sanskrit like '%' || 'वरदो भव' || '%'
  ;
  if n <> 1 then raise exception 'a masculine bhava line is missing from the Ganesha step'; end if;
  select count(*) into n from public.pooja_steps
   where pooja_id = 'ganesha_standard' and step_title_en = 'Prana Pratishtha'
     and (mantra_sanskrit like '%आवाहिता भव%' or mantra_sanskrit like '%सुप्रसन्ना भव%'
          or mantra_sanskrit like '%वरदा भव%' or mantra_sanskrit like '%सुमुखी भव%');
  if n > 0 then raise exception 'a feminine bhava line is in the Ganesha step'; end if;
  -- and no masculine one left in the feminine set.
  select count(*) into n from public.pooja_steps
   where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Prana Pratishtha'
     and (mantra_sanskrit like '%सुप्रसन्नो भव%' or mantra_tamil like '%ஸுப்ரஸந்நோ ப⁴வ%');
  if n > 0 then raise exception 'a masculine bhava line is still in the Varalakshmi step'; end if;
  select count(*) into n from public.pooja_steps
   where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Prana Pratishtha'
     and mantra_sanskrit like '%सुप्रसन्ना भव%';
  if n <> 1 then raise exception 'the Varalakshmi bhava line was not corrected'; end if;
  -- The nyasa syllables survived into every script.
  select count(*) into n from public.pooja_steps
   where pooja_id = 'ganesha_standard' and step_title_en = 'Prana Pratishtha'
     and mantra_tamil like '%' || 'க்ரோம்' || '%'
     and mantra_translit like '%' || 'kroṃ' || '%';
  if n <> 1 then raise exception 'the bija syllables did not survive transliteration'; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;

-- Verify:
--   select length(mantra_sanskrit) from pooja_steps
--    where pooja_id = 'ganesha_standard' and step_title_en = 'Prana Pratishtha';
