-- =============================================================================
-- 0027_new_step_philosophy.sql
--
-- GENERATED by scripts/build-new-step-philosophy.mjs. Do not hand-edit.
--
-- proofread.mjs blocked on the thirteen steps 0025 added: every other step in
-- both poojas carries a philosophy_en and these did not. The viewer guards the
-- block so nothing rendered broken -- the steps simply had no answer to "why am
-- I doing this", which on a screen that gives one everywhere else reads as an
-- omission rather than a silence.
--
-- This is the project’s own prose. The book gives the mantra, the mudra and the
-- substance and assumes a teacher for the rest.
--
-- Idempotent.
-- =============================================================================

begin;

update public.pooja_steps set philosophy_en = 'The pooja resolves twice, and this is the first. It is worth noticing that the two resolves are not the same sentence: this one asks only that the rite about to begin reach its end without obstruction, and the one later asks for everything the household actually wants. Splitting them is a kind of honesty about sequence. You do not ask for prosperity while the road is still blocked; you clear the road, and then you ask.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Vighneshwara Sankalpam'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'Before the rite narrows to one deity it widens, once, to all of them — everything from the world of Brahma to the mountain at the edge of the worlds. It takes about four seconds and it is easy to treat as throat-clearing. It is not. A household pooja is a small, particular thing done in one room for one family, and this line places it inside something that is neither small nor particular before it begins.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Sakala Devata Vandanam'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'The lamp is lit first and then worshipped in its own right, which is the tell. It is not illumination for the deity to be seen by; the verse calls the flame Brahman and Janardana outright. Light is the first guest, not the lighting.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Deepa Pooja'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'You consecrate the seat while sitting outside it, and only then take your place. Every other upachara in the pooja is offered to someone else. This one is offered to the ground under yourself, and it is asked of the earth rather than of a god — bear me, and make this seat pure. The performer is prepared like an object in the rite, because that is what he is about to become.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Asana Pooja'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'A complete pooja inside a pooja: invocation, sixteen upacharas, an archana, food and a light, done in miniature before the real one starts. The deity is a cone of turmeric and water, made in a minute and dissolved at the end, and the rite around it is not abridged for that. The point is that obstacles are not removed by asking in passing. You stop, you do the whole thing, and then you begin.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Vighneshwara Pooja'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'Sixteen names and not one of them is a title. Fair-faced, single-tusked, tawny, elephant-eared, pot-bellied, formidable, curve-trunked, winnow-eared — every one describes a body. The archana does not tell the deity who he outranks; it tells him you have looked at him.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Vighneshwara Shodasha Nama Archana'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'The preliminary Ganesha is fed and shown a light, exactly as the main deity will be an hour later, and the fruit or piece of jaggery that goes to him is not a smaller category of offering. A guest invited for a short errand is still a guest.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Vighneshwara Naivedyam & Neerajanam'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'He is sent back. This is the step most easily skipped and it is the one that makes the rest coherent: something was invoked into a cone of turmeric, and if the pooja simply moved on it would still be there. The turmeric is nudged north, the flowers offered to it are taken back onto your own head, and the invitation is formally closed. Nothing in a pooja is left standing.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Vighneshwara Udvasanam'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'The conch is worshipped, not blown. Its water is what sanctifies everything else set out for the pooja, so it is treated as a vessel that holds the sacred waters of the three worlds rather than as an instrument. The book allows the step to be skipped if there is no conch in the house, which is worth reading twice: a household vidhi that expects to be performed by real households says plainly which parts require an object you may not own.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Shankha Pooja'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'The one step in which the worshipper is the worshipped. You hold, for a few seconds, that the self inside you is the same as the one you are about to invoke into clay, and then you put akshatai on your own head. The verse is blunt about it: the body is the temple, the living self is the deity, and what you discard is not flowers but ignorance. Every other step points outward. This one turns around.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Atma Pooja'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'The seat is built before the guest arrives, and built from the bottom of the cosmos upward — the power that holds everything, primordial nature, the first tortoise, the first boar, the earth, and only then the jewelled pavilion, the golden pillar, the white parasol, the wish-giving tree. Fourteen names to furnish a spot the size of a plate. The scale is the message.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Peetha Pooja'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'The last human link before the divine one. It comes immediately before the deity is meditated on and invoked, and the placement is the argument: whatever is about to happen reaches you through someone who taught it to you, and through whoever taught them. The verse does not say the guru is like Brahma, Vishnu and Maheshwara. It says the guru is them.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Guru Dhyanam'
   and position('Written for this project from what the s' in source_ref) = 0;
update public.pooja_steps set philosophy_en = 'The pooja ends by giving something away, and the words are careful about whose it was: Ganesha receives and Ganesha gives — I present this to you, and it is not mine. The gift goes to the priest if there is one and to an elder of the house if there is not, which means a household with no priest still performs the step. Nothing is kept back at the end, including the credit.',
  source_ref = source_ref || ' Written for this project from what the step does, not taken from a source. The book gives the mantra, the mudra and the substance and assumes a teacher for the rest, so it explains almost nothing; this is the least reviewed prose in the app after the Tamil instructions and should be read as sceptically.',
  updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Upayana Danam'
   and position('Written for this project from what the s' in source_ref) = 0;

-- --- assert -------------------------------------------------------------------
do $$
declare n int;
begin
  select count(*) into n from public.pooja_steps
   where pooja_id = 'ganesha_standard'
     and (philosophy_en is null or btrim(philosophy_en) = '');
  if n > 0 then raise exception '% Ganesha steps still have no philosophy_en', n; end if;
  -- No two steps IN THE SAME POOJA may share it: a copy-paste there is
  -- invisible on screen. Across poojas sharing is correct and deliberate --
  -- the purvangam belongs to the act, not the deity, so Achamanam, Anga
  -- Vandanam, Vighneshwara Dhyanam, Pranayamam, Ghanta Pooja and Kalasha Pooja
  -- each carry one explanation used by both. The first version of this check
  -- was unscoped and failed on exactly those six.
  select count(*) into n from (
    select pooja_id, philosophy_en from public.pooja_steps
     where philosophy_en is not null group by 1, 2 having count(*) > 1) x;
  if n > 0 then raise exception '% philosophy texts are shared within one pooja', n; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
