-- =============================================================================
-- 0028_patra_pushpa_pairings.sql
--
-- GENERATED by scripts/build-patra-pushpa-pairings.mjs. Do not hand-edit.
--
-- Closes the oldest open question in docs/sources.md: the 21 leaves are paired
-- with 21 names, 14 of the pairs alliterate, and the other 7 looked mismatched.
--
-- The alliteration IS the design -- but only ONE of the seven is an error here.
-- The other six are paired the same way in the book, deliberately. The seventh:
--   bhRngaraajatkaTaaya namaha -> ashvattha patram     (this app)
--   bhRngaraajatkaTaaya namaha -> bhRngaraaja patram   (the book)
-- A name meaning "he whose matted hair is the bhringaraja" was getting a peepal
-- leaf.
--
-- Four more differences alliteration would never have caught, plus the order:
-- the app had Ekadanta/daaDimee at 12 where the book has it at 21. And two in
-- the flowers, of which shamyaaka -> shyaamaka is the clearest transcription
-- error found in this project: the same four syllables in a different order.
--
-- Idempotent.
-- =============================================================================

begin;

-- --- 1. the offerings that change --------------------------------------------
-- patra: धत्तूरपत्रं समर्पयामि -> दुर्धूरपत्रं समर्पयामि
update public.archana_items set
  offering_deva = 'दुर्धूरपत्रं समर्पयामि',
  offering_ta = 'துர்தூரபத்ரம் ஸமர்பயாமி',
  offering_en = 'Durdhura leaf',
  botanical = 'Datura metel'
 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)')
   and position('धूमकेतवे' in invoked_name_deva) > 0;

-- patra: सिंधुवार पत्रं समर्पयामि -> सिंधूरपत्रं समर्पयामि
update public.archana_items set
  offering_deva = 'सिंधूरपत्रं समर्पयामि',
  offering_ta = 'ஸிம்தூரபத்ரம் ஸமர்பயாமி',
  offering_en = 'Sindhura leaf',
  botanical = 'Vitex negundo'
 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)')
   and position('सिंधूराय' in invoked_name_deva) > 0;

-- patra: गंडवी पत्रं समर्पयामि -> गंडलीपत्रं समर्पयामि
update public.archana_items set
  offering_deva = 'गंडलीपत्रं समर्पयामि',
  offering_ta = 'கம்டலீபத்ரம் ஸமர்பயாமி',
  offering_en = 'Gandali leaf',
  botanical = null
 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)')
   and position('गंडगळन्मदाय' in invoked_name_deva) > 0;

-- patra: अश्वत्थ पत्रं समर्पयामि -> भृंगराजपत्रं समर्पयामि
update public.archana_items set
  offering_deva = 'भृंगराजपत्रं समर्पयामि',
  offering_ta = 'ப்ரும்கராஜபத்ரம் ஸமர்பயாமி',
  offering_en = 'Bhringaraja leaf',
  botanical = 'Eclipta prostrata'
 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)')
   and position('भृंगराजत्कटाय' in invoked_name_deva) > 0;

-- pushpa: धत्तूर पुष्पं समर्पयामि -> दुर्धूर पुष्पं समर्पयामि
update public.archana_items set
  offering_deva = 'दुर्धूर पुष्पं समर्पयामि',
  offering_ta = 'துர்தூர புஷ்பம் ஸமர்பயாமி',
  offering_en = 'Durdhura flower',
  botanical = 'Datura metel'
 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (21 Flowers)')
   and position('विद्या गणपतये' in invoked_name_deva) > 0;

-- pushpa: शम्याक पुष्पं समर्पयामि -> श्यामक पुष्पं समर्पयामि
update public.archana_items set
  offering_deva = 'श्यामक पुष्पं समर्पयामि',
  offering_ta = 'ஶ்யாமக புஷ்பம் ஸமர்பயாமி',
  offering_en = 'Shyamaka flower',
  botanical = 'Echinochloa frumentacea'
 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (21 Flowers)')
   and position('विष्णु गणपतये' in invoked_name_deva) > 0;

-- --- 2. the one name that changes --------------------------------------------
update public.archana_items set
  invoked_name_deva = 'ॐ शंकरीप्रियाय नमः',
  invoked_name_ta = 'ஓம் ஶம்கரீப்ரியாய நம꞉',
  invoked_name_translit = 'oṃ śaṃkarīpriyāya namaḥ'
 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and invoked_name_deva = 'ॐ शंकरप्रियाय नमः';

-- --- 3. the order ------------------------------------------------------------
-- Park first: seq is unique per step, so an in-place shuffle always has an
-- intermediate state with two rows on one number. Same reason 0025 parked the
-- step numbers above 1000.
update public.archana_items set seq = seq + 1000 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and seq < 1000;
update public.archana_items set seq = 1 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('उमापुत्राय' in invoked_name_deva) > 0;
update public.archana_items set seq = 2 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('हेरंबाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 3 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('लंबोदराय' in invoked_name_deva) > 0;
update public.archana_items set seq = 4 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('द्विरदाननाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 5 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('धूमकेतवे' in invoked_name_deva) > 0;
update public.archana_items set seq = 6 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('बृहते' in invoked_name_deva) > 0;
update public.archana_items set seq = 7 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('अपवर्गदाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 8 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('द्वैमातुराय' in invoked_name_deva) > 0;
update public.archana_items set seq = 9 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('चिरंतनाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 10 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('कपिलाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 11 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('विष्णुस्तुताय' in invoked_name_deva) > 0;
update public.archana_items set seq = 12 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('अमलाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 13 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('महते' in invoked_name_deva) > 0;
update public.archana_items set seq = 14 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('सिंधूराय' in invoked_name_deva) > 0;
update public.archana_items set seq = 15 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('गजाननाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 16 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('गंडगळन्मदाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 17 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('शंकर' in invoked_name_deva) > 0;
update public.archana_items set seq = 18 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('भृंगराजत्कटाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 19 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('अर्जुनदंताय' in invoked_name_deva) > 0;
update public.archana_items set seq = 20 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('अर्कप्रभाय' in invoked_name_deva) > 0;
update public.archana_items set seq = 21 where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('एकदंताय' in invoked_name_deva) > 0;

-- --- 4. the deity’s own list of permitted leaves ---------------------------
-- It agreed with neither the book nor the archana rows: devadaaru where the
-- archana has aamalakee, gaNDakee where the archana has gaNDavee and the book
-- has gaNDalee. Three lists that should be one.
update public.deities set
  permitted_offerings = jsonb_set(permitted_offerings::jsonb, '{leaves}', '["macī","bṛhatī","bilva","dūrvā","durdhūra","badarī","apāmārga","tulasī","cūta","karavīra","viṣṇukrānta","āmalakī","maruvaka","sindhūra","jātī","gaṇḍalī","śamī","bhṛṅgarāja","arjuna","arka","dāḍimī"]'::jsonb),
  updated_at = now()
 where id = 'ganesha';

-- --- 5. record what changed and why ------------------------------------------
update public.pooja_steps set
  source_ref = 'Sampradaya Vratha Pooja Vidhi (Giri), p.63-64, ekavimshati patrapoojaa. Order and pairing follow the book, which puts ekadanta/daaDimee last where this app had it twelfth. Four offerings corrected: durdhoora for dhattoora (two names for Datura metel), sindhoora for sindhuvaara, gaNDalee for gaNDavee, and bhRngaraaja for ashvattha -- the last being the only one of the seven non-alliterating pairs that was actually wrong, the other six being paired the same way in the book. gaNDalee is left without a botanical identification rather than inheriting the one recorded for gaNDavee, which is a different word. Transcribed from a photograph of the printed page; no round-trip proof, diffed against the previous pairing before it was written.',
  verified_by = null, verified_at = null, updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)';

update public.pooja_steps set
  source_ref = 'Sampradaya Vratha Pooja Vidhi (Giri), p.65, ekavimshati puSHpapoojaa. Order confirmed identical. Two offerings corrected: durdhoora for dhattoora, and shyaamaka for shamyaaka -- the same four syllables in a different order. Transcribed from a photograph of the printed page; no round-trip proof, diffed against the previous pairing before it was written.',
  verified_by = null, verified_at = null, updated_at = now()
 where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (21 Flowers)';

-- --- assert -------------------------------------------------------------------
do $$
declare n int;
begin
  -- Nothing parked, 1..21, no gap, no repeat.
  select count(*) into n from public.archana_items where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and seq >= 1000;
  if n > 0 then raise exception '% leaf offerings were left parked', n; end if;
  select (max(seq) - min(seq) + 1) - count(*) into n from public.archana_items
   where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)');
  if n <> 0 then raise exception 'the leaf sequence is not dense'; end if;
  select count(*) into n from public.archana_items where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)');
  if n <> 21 then raise exception 'expected 21 leaves, found %', n; end if;
  -- The one real mismatch is gone, in all three scripts.
  select count(*) into n from public.archana_items
   where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and offering_deva like '%अश्वत्थ%';
  if n > 0 then raise exception 'the ashvattha leaf is still paired with bhringarajatkata'; end if;
  select count(*) into n from public.archana_items
   where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)')
     and position('भृंगराजत्कटाय' in invoked_name_deva) > 0
     and offering_deva like '%भृंगराज%';
  if n <> 1 then raise exception 'bhringarajatkata is not paired with the bhringaraja leaf'; end if;
  -- Ekadanta is last, as the book has it.
  select seq into n from public.archana_items
   where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') and position('एकदंताय' in invoked_name_deva) > 0;
  if n <> 21 then raise exception 'ekadanta/dadimi is at seq %, expected 21', n; end if;
  -- The flower transcription error is gone.
  select count(*) into n from public.archana_items
   where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (21 Flowers)') and offering_deva like '%शम्याक%';
  if n > 0 then raise exception 'shamyaaka is still in the flower list'; end if;
  select count(*) into n from public.archana_items
   where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (21 Flowers)') and offering_deva like '%श्यामक%';
  if n <> 1 then raise exception 'shyaamaka is not in the flower list'; end if;
  -- Neither list still calls the plant dhattoora.
  select count(*) into n from public.archana_items
   where pooja_step_id in ((select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)'), (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Pushpa Pooja (21 Flowers)')) and offering_deva like '%धत्तूर%';
  if n > 0 then raise exception '% offerings still say dhattoora', n; end if;
  -- The deity list and the archana rows now agree, 21 to 21.
  select jsonb_array_length(permitted_offerings::jsonb -> 'leaves') into n
    from public.deities where id = 'ganesha';
  if n <> 21 then raise exception 'the deity leaf list has % entries', n; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;

-- Verify:
--   select seq, invoked_name_translit, offering_en from archana_items
--    where pooja_step_id = (select id from public.pooja_steps where pooja_id = 'ganesha_standard' and step_title_en = 'Patra Pooja (21 Leaves)') order by seq;
