-- =============================================================================
-- 0035_visarga_not_a_colon.sql
--
-- GENERATED by scripts/build-visarga-repair.mjs. Do not hand-edit.
--
-- namaHa was transcribed as नम: with an ASCII colon instead of the visarga ः.
-- Sanscript cannot see an ASCII colon as a letter, so it passed through into
-- BOTH generated scripts and 0032 wrote Tamil lines ending in a colon that
-- belongs to neither script -- ஓம் வரலக்ஷ்ம்யை நம: where it should read நம꞉.
--
-- The transcripts are corrected at source; this re-derives the affected text
-- from them. It regenerates all three script columns rather than patching the
-- colon, because the Tamil and the roman have to come FROM the corrected
-- Devanagari, not from a string edit of the broken output.
--
-- Idempotent: setting a value to what it should be.
-- =============================================================================

begin;

-- --- the fifteen replaced steps, plus the one new one -----------------------
update public.pooja_steps set
       mantra_sanskrit = 'अनेक रत्नखचितं क्षीरसागरसंभवे।
स्वर्णसिंहासनं देवि स्वीकुरुष्व हरिप्रिये।।
श्रीवरलक्ष्म्यै नमःआसनं समर्पयामि ।',
       mantra_tamil    = 'அநேக ரத்நகசிதம் க்ஷீரஸாகரஸம்பவே।
ஸ்வர்ணஸிம்ஹாஸநம் தேவி ஸ்வீகுருஷ்வ ஹரிப்ரியே।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉ஆஸநம் ஸமர்பயாமி ।',
       mantra_translit = 'aneka ratnakhacitaṃ kṣīrasāgarasaṃbhave।
svarṇasiṃhāsanaṃ devi svīkuruṣva haripriye।।
śrīvaralakṣmyai namaḥāsanaṃ samarpayāmi ।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Peeta Pooja';

update public.pooja_steps set
       mantra_sanskrit = 'लक्ष्मीं क्षीर-समुद्रराज-तनयां श्रीरङ्गधामेश्वरीं
दासीभूत-समस्त-देववनितां लोकैकदीपाङ्कुराम् ।
श्रीमन्मन्द-कटाक्ष-लब्ध-विभव-ब्रह्मेन्द्र-गङ्गाधरां
त्वां त्रैलोक्यकुटुंबिनीं सरसिजां वन्दे मुकुन्दप्रियाम्॥
या सा पद्मासनस्था विपुलकटितटी पद्मपत्रायताक्षी
गम्भीरावर्तनाभिः स्तनभरनमिता शुभ्र वस्त्रोत्तरीया ।
लक्ष्मीर्दिव्यैर्गजेन्द्रैः मणिगणखचितैःस्नापिता हेमकुम्भैः
नित्यं सा पद्महस्ता मम वसतु गृहे सर्वमाङ्गल्य युक्ता॥
पद्मासनां पद्मकरां पद्ममालाविभूषिताम्।
क्षीरसागर सम्भूतां क्षीरवर्ण समप्रभाम् ।।
क्षीरवर्णसमं वस्त्रं दधानां हरिवल्लभाम्।
भावये भक्तियोगेन कलशेऽस्मिन् मनोहरे
अस्मिन् कलशे श्रीवरलक्ष्मीं ध्यायामि।।',
       mantra_tamil    = 'லக்ஷ்மீம் க்ஷீர-ஸமுத்ரராஜ-தநயாம் ஶ்ரீரங்கதாமேஶ்வரீம்
தாஸீபூத-ஸமஸ்த-தேவவநிதாம் லோகைகதீபாங்குராம் ।
ஶ்ரீமந்மந்த-கடாக்ஷ-லப்த-விபவ-ப்ரஹ்மேந்த்ர-கங்காதராம்
த்வாம் த்ரைலோக்யகுடும்பிநீம் ஸரஸிஜாம் வந்தே முகுந்தப்ரியாம்॥
யா ஸா பத்மாஸநஸ்தா விபுலகடிதடீ பத்மபத்ராயதாக்ஷீ
கம்பீராவர்தநாபி꞉ ஸ்தநபரநமிதா ஶுப்ர வஸ்த்ரோத்தரீயா ।
லக்ஷ்மீர்திவ்யைர்கஜேந்த்ரை꞉ மணிகணகசிதை꞉ஸ்நாபிதா ஹேமகும்பை꞉
நித்யம் ஸா பத்மஹஸ்தா மம வஸது க்ருஹே ஸர்வமாங்கல்ய யுக்தா॥
பத்மாஸநாம் பத்மகராம் பத்மமாலாவிபூஷிதாம்।
க்ஷீரஸாகர ஸம்பூதாம் க்ஷீரவர்ண ஸமப்ரபாம் ।।
க்ஷீரவர்ணஸமம் வஸ்த்ரம் ததாநாம் ஹரிவல்லபாம்।
பாவயே பக்தியோகேந கலஶேஸ்மிந் மநோஹரே
அஸ்மிந் கலஶே ஶ்ரீவரலக்ஷ்மீம் த்யாயாமி।।',
       mantra_translit = 'lakṣmīṃ kṣīra-samudrarāja-tanayāṃ śrīraṅgadhāmeśvarīṃ
dāsībhūta-samasta-devavanitāṃ lokaikadīpāṅkurām ।
śrīmanmanda-kaṭākṣa-labdha-vibhava-brahmendra-gaṅgādharāṃ
tvāṃ trailokyakuṭuṃbinīṃ sarasijāṃ vande mukundapriyām॥
yā sā padmāsanasthā vipulakaṭitaṭī padmapatrāyatākṣī
gambhīrāvartanābhiḥ stanabharanamitā śubhra vastrottarīyā ।
lakṣmīrdivyairgajendraiḥ maṇigaṇakhacitaiḥsnāpitā hemakumbhaiḥ
nityaṃ sā padmahastā mama vasatu gṛhe sarvamāṅgalya yuktā॥
padmāsanāṃ padmakarāṃ padmamālāvibhūṣitām।
kṣīrasāgara sambhūtāṃ kṣīravarṇa samaprabhām ।।
kṣīravarṇasamaṃ vastraṃ dadhānāṃ harivallabhām।
bhāvaye bhaktiyogena kalaśe''smin manohare
asmin kalaśe śrīvaralakṣmīṃ dhyāyāmi।।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Dhyanam';

update public.pooja_steps set
       mantra_sanskrit = 'सर्वमङ्गलमाङ्गल्ये विष्णुवक्षस्थलालये।
आवाहयामि देवि त्वां अभीष्ट फलदा भव ।।
अस्मिन् कलशे श्रीवरलक्ष्मीं आवाहयामि।',
       mantra_tamil    = 'ஸர்வமங்கலமாங்கல்யே விஷ்ணுவக்ஷஸ்தலாலயே।
ஆவாஹயாமி தேவி த்வாம் அபீஷ்ட பலதா பவ ।।
அஸ்மிந் கலஶே ஶ்ரீவரலக்ஷ்மீம் ஆவாஹயாமி।',
       mantra_translit = 'sarvamaṅgalamāṅgalye viṣṇuvakṣasthalālaye।
āvāhayāmi devi tvāṃ abhīṣṭa phaladā bhava ।।
asmin kalaśe śrīvaralakṣmīṃ āvāhayāmi।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Avahanam';

update public.pooja_steps set
       mantra_sanskrit = 'गङ्गादि सरिदानीतं गन्धपुष्प समन्वितम्।
पाद्यं ददामि ते देवि प्रसीद परमेश्वरि।।
श्रीवरलक्ष्म्यै नमःपाद्यं समर्पयामि।।
गङ्गानदी समानीतं सुवर्णकलशस्थितम्।
गृहाणार्घ्यं मया दत्तं पुत्र पौत्र फलप्रदे।।
श्रीवरलक्ष्म्यै नमः अर्घ्यं समर्पयामि।।
प्रसन्नं शीतलं तोयं प्रसन्नमुखपङ्कजे।
गृहाणाचमनार्थाय गरुडध्वज वल्लभे।।
श्रीवरलक्ष्म्यै नमः आचमनीयं समर्पयामि।।
महालक्ष्मि महादेवि मध्वाज्य दधि संयुतम्।
मधुपर्कं गृहाणेदं मधुसूदनवल्लभे।।
श्रीवरलक्ष्म्यै नमः मधुपर्कं समर्पयामि।।',
       mantra_tamil    = 'கங்காதி ஸரிதாநீதம் கந்தபுஷ்ப ஸமந்விதம்।
பாத்யம் ததாமி தே தேவி ப்ரஸீத பரமேஶ்வரி।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉பாத்யம் ஸமர்பயாமி।।
கங்காநதீ ஸமாநீதம் ஸுவர்ணகலஶஸ்திதம்।
க்ருஹாணார்க்யம் மயா தத்தம் புத்ர பௌத்ர பலப்ரதே।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉ அர்க்யம் ஸமர்பயாமி।।
ப்ரஸந்நம் ஶீதலம் தோயம் ப்ரஸந்நமுகபங்கஜே।
க்ருஹாணாசமநார்தாய கருடத்வஜ வல்லபே।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉ ஆசமநீயம் ஸமர்பயாமி।।
மஹாலக்ஷ்மி மஹாதேவி மத்வாஜ்ய ததி ஸம்யுதம்।
மதுபர்கம் க்ருஹாணேதம் மதுஸூதநவல்லபே।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉ மதுபர்கம் ஸமர்பயாமி।।',
       mantra_translit = 'gaṅgādi saridānītaṃ gandhapuṣpa samanvitam।
pādyaṃ dadāmi te devi prasīda parameśvari।।
śrīvaralakṣmyai namaḥpādyaṃ samarpayāmi।।
gaṅgānadī samānītaṃ suvarṇakalaśasthitam।
gṛhāṇārghyaṃ mayā dattaṃ putra pautra phalaprade।।
śrīvaralakṣmyai namaḥ arghyaṃ samarpayāmi।।
prasannaṃ śītalaṃ toyaṃ prasannamukhapaṅkaje।
gṛhāṇācamanārthāya garuḍadhvaja vallabhe।।
śrīvaralakṣmyai namaḥ ācamanīyaṃ samarpayāmi।।
mahālakṣmi mahādevi madhvājya dadhi saṃyutam।
madhuparkaṃ gṛhāṇedaṃ madhusūdanavallabhe।।
śrīvaralakṣmyai namaḥ madhuparkaṃ samarpayāmi।।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Padyam, Arghyam & Achamaniyam';

update public.pooja_steps set
       mantra_sanskrit = 'पयोदधि धृतैर्युक्तं शर्करा मधुसंयुतम्।
पञ्चामृतं गृहाणेदं वरलक्ष्मि नमोऽस्तु ते।।
श्रीवरलक्ष्म्यै नमः पञ्चामृतं समर्पयामि।।
हेमकुम्भस्थितं स्वच्छं गङ्गादि सरिदाहृतम्।
स्नानार्थं सलिलं देवि गृह्यतां सागरात्मजे।।
श्रीवरलक्ष्म्यै नमः स्नानं समर्पयामि।।
स्नानानंतरं आचमनीयं समर्पयामि।।',
       mantra_tamil    = 'பயோததி த்ருதைர்யுக்தம் ஶர்கரா மதுஸம்யுதம்।
பஞ்சாம்ருதம் க்ருஹாணேதம் வரலக்ஷ்மி நமோஸ்து தே।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉ பஞ்சாம்ருதம் ஸமர்பயாமி।।
ஹேமகும்பஸ்திதம் ஸ்வச்சம் கங்காதி ஸரிதாஹ்ருதம்।
ஸ்நாநார்தம் ஸலிலம் தேவி க்ருஹ்யதாம் ஸாகராத்மஜே।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉ ஸ்நாநம் ஸமர்பயாமி।।
ஸ்நாநாநம்தரம் ஆசமநீயம் ஸமர்பயாமி।।',
       mantra_translit = 'payodadhi dhṛtairyuktaṃ śarkarā madhusaṃyutam।
pañcāmṛtaṃ gṛhāṇedaṃ varalakṣmi namo''stu te।।
śrīvaralakṣmyai namaḥ pañcāmṛtaṃ samarpayāmi।।
hemakumbhasthitaṃ svacchaṃ gaṅgādi saridāhṛtam।
snānārthaṃ salilaṃ devi gṛhyatāṃ sāgarātmaje।।
śrīvaralakṣmyai namaḥ snānaṃ samarpayāmi।।
snānānaṃtaraṃ ācamanīyaṃ samarpayāmi।।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Panchamrita & Shuddhodaka Snanam';

update public.pooja_steps set
       mantra_sanskrit = 'दिव्यांबरयुगं सूक्ष्मं कञ्चुकं च मनोहरम्।
वरलक्ष्मि महादेवि गृहाणेदं मयार्पितम्।।
श्री वरलक्ष्म्यै नमः वस्त्रं समर्पयामि।।
माङ्गल्यमणि सम्युक्तं मुक्ताविद्रुम संयुतम् ।
दत्तं मङ्गलसूत्रं च गृहाण हरिवल्लभे।।
श्रीवरलक्ष्म्यै नमः, कण्ठसूत्रं समर्पयामि।।
रत्नताटङ्क केयूर हारकङ्कणभूषिते।
भूषणानि महार्हाणि गृहाण करुणानिधे।।
श्रीवरलक्ष्म्यै नमः, आभरणानि समर्पयामि।।',
       mantra_tamil    = 'திவ்யாம்பரயுகம் ஸூக்ஷ்மம் கஞ்சுகம் ச மநோஹரம்।
வரலக்ஷ்மி மஹாதேவி க்ருஹாணேதம் மயார்பிதம்।।
ஶ்ரீ வரலக்ஷ்ம்யை நம꞉ வஸ்த்ரம் ஸமர்பயாமி।।
மாங்கல்யமணி ஸம்யுக்தம் முக்தாவித்ரும ஸம்யுதம் ।
தத்தம் மங்கலஸூத்ரம் ச க்ருஹாண ஹரிவல்லபே।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉, கண்டஸூத்ரம் ஸமர்பயாமி।।
ரத்நதாடங்க கேயூர ஹாரகங்கணபூஷிதே।
பூஷணாநி மஹார்ஹாணி க்ருஹாண கருணாநிதே।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉, ஆபரணாநி ஸமர்பயாமி।।',
       mantra_translit = 'divyāṃbarayugaṃ sūkṣmaṃ kañcukaṃ ca manoharam।
varalakṣmi mahādevi gṛhāṇedaṃ mayārpitam।।
śrī varalakṣmyai namaḥ vastraṃ samarpayāmi।।
māṅgalyamaṇi samyuktaṃ muktāvidruma saṃyutam ।
dattaṃ maṅgalasūtraṃ ca gṛhāṇa harivallabhe।।
śrīvaralakṣmyai namaḥ, kaṇṭhasūtraṃ samarpayāmi।।
ratnatāṭaṅka keyūra hārakaṅkaṇabhūṣite।
bhūṣaṇāni mahārhāṇi gṛhāṇa karuṇānidhe।।
śrīvaralakṣmyai namaḥ, ābharaṇāni samarpayāmi।।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Vastram, Abharanam & Mangalyam';

update public.pooja_steps set
       mantra_sanskrit = 'कर्पूर चन्दनोपेतं कस्तूरी कुङ्कुमान्वितम्।
सर्वगन्धं गृहाणाद्य सर्वमङ्गलदायिनि।।
श्रीवरलक्ष्म्यै नमः, गन्धान् धारयामि।
गन्धोपरि हरिद्राचूर्णं समर्पयामि।।
शालिजातान् चन्द्रवर्णान् स्निग्ध मौक्तिक सन्निभान्।
अक्षतान् देवि गृह्णीष्व पङ्कजाक्षस्य वल्लभे।।
श्रीवरलक्ष्म्यै नमः, अक्षतान् समर्पयामि।।
मन्दारपारिजाताब्जैः केतक्युत्पलपाटलैः।
मल्लिका जाति वकुलैःपुष्पैस्त्वां पूजयाम्यहम्।।
श्रीवरलक्ष्म्यै नमः पुष्पमालां समर्पयामि। पुष्पैः पूजयामि।',
       mantra_tamil    = 'கர்பூர சந்தநோபேதம் கஸ்தூரீ குங்குமாந்விதம்।
ஸர்வகந்தம் க்ருஹாணாத்ய ஸர்வமங்கலதாயிநி।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉, கந்தாந் தாரயாமி।
கந்தோபரி ஹரித்ராசூர்ணம் ஸமர்பயாமி।।
ஶாலிஜாதாந் சந்த்ரவர்ணாந் ஸ்நிக்த மௌக்திக ஸந்நிபாந்।
அக்ஷதாந் தேவி க்ருஹ்ணீஷ்வ பங்கஜாக்ஷஸ்ய வல்லபே।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉, அக்ஷதாந் ஸமர்பயாமி।।
மந்தாரபாரிஜாதாப்ஜை꞉ கேதக்யுத்பலபாடலை꞉।
மல்லிகா ஜாதி வகுலை꞉புஷ்பைஸ்த்வாம் பூஜயாம்யஹம்।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉ புஷ்பமாலாம் ஸமர்பயாமி। புஷ்பை꞉ பூஜயாமி।',
       mantra_translit = 'karpūra candanopetaṃ kastūrī kuṅkumānvitam।
sarvagandhaṃ gṛhāṇādya sarvamaṅgaladāyini।।
śrīvaralakṣmyai namaḥ, gandhān dhārayāmi।
gandhopari haridrācūrṇaṃ samarpayāmi।।
śālijātān candravarṇān snigdha mauktika sannibhān।
akṣatān devi gṛhṇīṣva paṅkajākṣasya vallabhe।।
śrīvaralakṣmyai namaḥ, akṣatān samarpayāmi।।
mandārapārijātābjaiḥ ketakyutpalapāṭalaiḥ।
mallikā jāti vakulaiḥpuṣpaistvāṃ pūjayāmyaham।।
śrīvaralakṣmyai namaḥ puṣpamālāṃ samarpayāmi। puṣpaiḥ pūjayāmi।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Gandham, Akshatai & Pushpam';

update public.pooja_steps set
       mantra_sanskrit = 'धूपं ददामि ते रम्यं गुग्गुल्वगरुसंयुतम्।
गृहाण त्वं महालक्ष्मि भक्तानामिष्टदायिनि।।
श्रीवरलक्ष्म्यै नमः धूपमाघ्रापयामि।।
साज्यं त्रिवर्तिसंयुक्तं सर्वाभीष्ट प्रदायिनि।
दीपं गृहाण कमले देहि मे सर्वमीप्सितम्।।
श्रीवरलक्ष्म्यै नमः दीपं दर्शयामि।।
धूप, दीपानन्तरं आचमनीयं समर्पयामि',
       mantra_tamil    = 'தூபம் ததாமி தே ரம்யம் குக்குல்வகருஸம்யுதம்।
க்ருஹாண த்வம் மஹாலக்ஷ்மி பக்தாநாமிஷ்டதாயிநி।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉ தூபமாக்ராபயாமி।।
ஸாஜ்யம் த்ரிவர்திஸம்யுக்தம் ஸர்வாபீஷ்ட ப்ரதாயிநி।
தீபம் க்ருஹாண கமலே தேஹி மே ஸர்வமீப்ஸிதம்।।
ஶ்ரீவரலக்ஷ்ம்யை நம꞉ தீபம் தர்ஶயாமி।।
தூப, தீபாநந்தரம் ஆசமநீயம் ஸமர்பயாமி',
       mantra_translit = 'dhūpaṃ dadāmi te ramyaṃ guggulvagarusaṃyutam।
gṛhāṇa tvaṃ mahālakṣmi bhaktānāmiṣṭadāyini।।
śrīvaralakṣmyai namaḥ dhūpamāghrāpayāmi।।
sājyaṃ trivartisaṃyuktaṃ sarvābhīṣṭa pradāyini।
dīpaṃ gṛhāṇa kamale dehi me sarvamīpsitam।।
śrīvaralakṣmyai namaḥ dīpaṃ darśayāmi।।
dhūpa, dīpānantaraṃ ācamanīyaṃ samarpayāmi',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Dhoopam & Deepam';

update public.pooja_steps set
       mantra_sanskrit = 'नीराजनं नीरजस्कं कर्पूरेण कृतं मया।
लक्ष्मि नीराजयामि त्वां नित्यलोकप्रकाशिका।।
श्री वरलक्ष्म्यै नमः कर्पूर नीराजनं दर्शयामि ।।
नीराजनानन्तरं आचमनीयं समर्पयामि।',
       mantra_tamil    = 'நீராஜநம் நீரஜஸ்கம் கர்பூரேண க்ருதம் மயா।
லக்ஷ்மி நீராஜயாமி த்வாம் நித்யலோகப்ரகாஶிகா।।
ஶ்ரீ வரலக்ஷ்ம்யை நம꞉ கர்பூர நீராஜநம் தர்ஶயாமி ।।
நீராஜநாநந்தரம் ஆசமநீயம் ஸமர்பயாமி।',
       mantra_translit = 'nīrājanaṃ nīrajaskaṃ karpūreṇa kṛtaṃ mayā।
lakṣmi nīrājayāmi tvāṃ nityalokaprakāśikā।।
śrī varalakṣmyai namaḥ karpūra nīrājanaṃ darśayāmi ।।
nīrājanānantaraṃ ācamanīyaṃ samarpayāmi।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Karpura Neerajanam';

update public.pooja_steps set
       mantra_sanskrit = 'जाती चंपक, पुन्नाग, मल्लिका, वकुलादिभिः
पुष्पाञ्जलिं प्रदास्यामि गृहाण हरिवल्लभे।
श्री वरलक्ष्म्यै नमः मन्त्रपुष्पं समर्पयामि, स्वर्णपुष्पं समर्पयामि।।',
       mantra_tamil    = 'ஜாதீ சம்பக, புந்நாக, மல்லிகா, வகுலாதிபி꞉
புஷ்பாஞ்ஜலிம் ப்ரதாஸ்யாமி க்ருஹாண ஹரிவல்லபே।
ஶ்ரீ வரலக்ஷ்ம்யை நம꞉ மந்த்ரபுஷ்பம் ஸமர்பயாமி, ஸ்வர்ணபுஷ்பம் ஸமர்பயாமி।।',
       mantra_translit = 'jātī caṃpaka, punnāga, mallikā, vakulādibhiḥ
puṣpāñjaliṃ pradāsyāmi gṛhāṇa harivallabhe।
śrī varalakṣmyai namaḥ mantrapuṣpaṃ samarpayāmi, svarṇapuṣpaṃ samarpayāmi।।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Pushpanjali & Mantra Pushpam';

update public.pooja_steps set
       mantra_sanskrit = 'सर्वमङ्गल लाभाय सर्व पापनिवृत्तये।
प्रदक्षिणं करोम्यद्य प्रसीद परमेश्वरि।।
नमोऽस्तु नालीक निभाननायै नमोऽस्तु नारायण वल्लभायै।
नमोऽस्तु रत्नाकर संभवायै नमोऽस्तु लक्ष्म्यै जगतां जनन्यै।।
श्री वरलक्ष्म्यै नमः प्रदक्षिण नमस्कारान् समर्पयामि ।',
       mantra_tamil    = 'ஸர்வமங்கல லாபாய ஸர்வ பாபநிவ்ருத்தயே।
ப்ரதக்ஷிணம் கரோம்யத்ய ப்ரஸீத பரமேஶ்வரி।।
நமோஸ்து நாலீக நிபாநநாயை நமோஸ்து நாராயண வல்லபாயை।
நமோஸ்து ரத்நாகர ஸம்பவாயை நமோஸ்து லக்ஷ்ம்யை ஜகதாம் ஜநந்யை।।
ஶ்ரீ வரலக்ஷ்ம்யை நம꞉ ப்ரதக்ஷிண நமஸ்காராந் ஸமர்பயாமி ।',
       mantra_translit = 'sarvamaṅgala lābhāya sarva pāpanivṛttaye।
pradakṣiṇaṃ karomyadya prasīda parameśvari।।
namo''stu nālīka nibhānanāyai namo''stu nārāyaṇa vallabhāyai।
namo''stu ratnākara saṃbhavāyai namo''stu lakṣmyai jagatāṃ jananyai।।
śrī varalakṣmyai namaḥ pradakṣiṇa namaskārān samarpayāmi ।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Pradakshina';

update public.pooja_steps set
       mantra_sanskrit = 'आयुरारोग्यमैश्वर्यं पुत्रपौत्रान् पशून् धनम्।
शत्रुक्षयं महालक्ष्मि प्रयच्छ करुणानिधे।।
छत्र–चामर–नृत्त–गीत–वाद्य इत्यादि समस्तोपचार–शक्त्युपचार–
देवोपचारान् समर्पयामि।',
       mantra_tamil    = 'ஆயுராரோக்யமைஶ்வர்யம் புத்ரபௌத்ராந் பஶூந் தநம்।
ஶத்ருக்ஷயம் மஹாலக்ஷ்மி ப்ரயச்ச கருணாநிதே।।
சத்ர–சாமர–ந்ருத்த–கீத–வாத்ய இத்யாதி ஸமஸ்தோபசார–ஶக்த்யுபசார–
தேவோபசாராந் ஸமர்பயாமி।',
       mantra_translit = 'āyurārogyamaiśvaryaṃ putrapautrān paśūn dhanam।
śatrukṣayaṃ mahālakṣmi prayaccha karuṇānidhe।।
chatra–cāmara–nṛtta–gīta–vādya ityādi samastopacāra–śaktyupacāra–
devopacārān samarpayāmi।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Namaskaram & Varalakshmi Prarthana';

update public.pooja_steps set
       mantra_sanskrit = 'सर्वमङ्गलमाङ्गल्ये सर्वपाप प्रणाशिनि।
दोरकं प्रतिगृह्णामि सुप्रीता भव सर्वदा।।
नवतन्तु समायुक्तं नवग्रन्थि समन्वितम्।
बध्नीयां दक्षिणे हस्ते दोरकं हरिवल्लभे।।',
       mantra_tamil    = 'ஸர்வமங்கலமாங்கல்யே ஸர்வபாப ப்ரணாஶிநி।
தோரகம் ப்ரதிக்ருஹ்ணாமி ஸுப்ரீதா பவ ஸர்வதா।।
நவதந்து ஸமாயுக்தம் நவக்ரந்தி ஸமந்விதம்।
பத்நீயாம் தக்ஷிணே ஹஸ்தே தோரகம் ஹரிவல்லபே।।',
       mantra_translit = 'sarvamaṅgalamāṅgalye sarvapāpa praṇāśini।
dorakaṃ pratigṛhṇāmi suprītā bhava sarvadā।।
navatantu samāyuktaṃ navagranthi samanvitam।
badhnīyāṃ dakṣiṇe haste dorakaṃ harivallabhe।।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Sharadu Dharanam';

update public.pooja_steps set
       mantra_sanskrit = 'वरलक्ष्मी स्वरूपस्य ब्राह्मणस्य इदमासनम् ।
इमे गन्धाः सकलाराधनैः स्वर्चितम् ।।
हिरण्यगर्भ गर्भस्थं हेमबीजं विभावसोः।
अनन्त पुण्यफलदं अथः शान्तिं प्रयच्छ मे।।
इन्दिरा प्रतिगृह्णाति इन्दिरा वै ददाति च।
इन्दिरा तारकाद्वाभ्यां इन्दिरायै नमो नमः।।
इदं उपायनं सदक्षिणाकं, सताम्बूलं, वरलक्ष्मी पूजाफल सादुगुण्यं,
दीर्घ सौमाङ्गल्यावािं, सत् पुत्र पौत्राभिवृद्धिं वरलक्ष्मी प्रीतिं च
कामयमाना तुभ्यं अहं संप्रददे न मम।।',
       mantra_tamil    = 'வரலக்ஷ்மீ ஸ்வரூபஸ்ய ப்ராஹ்மணஸ்ய இதமாஸநம் ।
இமே கந்தா꞉ ஸகலாராதநை꞉ ஸ்வர்சிதம் ।।
ஹிரண்யகர்ப கர்பஸ்தம் ஹேமபீஜம் விபாவஸோ꞉।
அநந்த புண்யபலதம் அத꞉ ஶாந்திம் ப்ரயச்ச மே।।
இந்திரா ப்ரதிக்ருஹ்ணாதி இந்திரா வை ததாதி ச।
இந்திரா தாரகாத்வாப்யாம் இந்திராயை நமோ நம꞉।।
இதம் உபாயநம் ஸதக்ஷிணாகம், ஸதாம்பூலம், வரலக்ஷ்மீ பூஜாபல ஸாதுகுண்யம்,
தீர்க ஸௌமாங்கல்யாவாிம், ஸத் புத்ர பௌத்ராபிவ்ருத்திம் வரலக்ஷ்மீ ப்ரீதிம் ச
காமயமாநா துப்யம் அஹம் ஸம்ப்ரததே ந மம।।',
       mantra_translit = 'varalakṣmī svarūpasya brāhmaṇasya idamāsanam ।
ime gandhāḥ sakalārādhanaiḥ svarcitam ।।
hiraṇyagarbha garbhasthaṃ hemabījaṃ vibhāvasoḥ।
ananta puṇyaphaladaṃ athaḥ śāntiṃ prayaccha me।।
indirā pratigṛhṇāti indirā vai dadāti ca।
indirā tārakādvābhyāṃ indirāyai namo namaḥ।।
idaṃ upāyanaṃ sadakṣiṇākaṃ, satāmbūlaṃ, varalakṣmī pūjāphala sāduguṇyaṃ,
dīrgha saumāṅgalyāvāiṃ, sat putra pautrābhivṛddhiṃ varalakṣmī prītiṃ ca
kāmayamānā tubhyaṃ ahaṃ saṃpradade na mama।।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Vayana Dhanam';

update public.pooja_steps set
       mantra_sanskrit = 'अस्मात् कुंभात् श्रीवरलक्ष्मीं यथास्थानं
प्रतिष्ठापयामि। शोभनार्थे क्षेमाय पुनरागमनाय च।।',
       mantra_tamil    = 'அஸ்மாத் கும்பாத் ஶ்ரீவரலக்ஷ்மீம் யதாஸ்தாநம்
ப்ரதிஷ்டாபயாமி। ஶோபநார்தே க்ஷேமாய புநராகமநாய ச।।',
       mantra_translit = 'asmāt kuṃbhāt śrīvaralakṣmīṃ yathāsthānaṃ
pratiṣṭhāpayāmi। śobhanārthe kṣemāya punarāgamanāya ca।।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Udvasanam';

update public.pooja_steps set
       mantra_sanskrit = 'बालभानु प्रतीकाशं पूर्णचन्द्रनिभाननं।
सूत्रेऽस्मिन् सुस्थिता भूत्वा प्रयच्छ बहुलान् वरान्।।',
       mantra_tamil    = 'பாலபாநு ப்ரதீகாஶம் பூர்ணசந்த்ரநிபாநநம்।
ஸூத்ரேஸ்மிந் ஸுஸ்திதா பூத்வா ப்ரயச்ச பஹுலாந் வராந்।।',
       mantra_translit = 'bālabhānu pratīkāśaṃ pūrṇacandranibhānanaṃ।
sūtre''smin susthitā bhūtvā prayaccha bahulān varān।।',
       updated_at      = now()
 where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Dora Sthapanam';

-- --- the twenty-four anga pooja rows ----------------------------------------
update public.archana_items set
       invoked_name_deva     = 'ॐ वरलक्ष्म्यै नमः',
       invoked_name_ta       = 'ஓம் வரலக்ஷ்ம்யை நம꞉',
       invoked_name_translit = 'oṃ varalakṣmyai namaḥ',
       offering_deva         = 'पादौ पूजयामि',
       offering_ta           = 'பாதௌ பூஜயாமி'
 where seq = 1 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ महालक्ष्म्यै नमः',
       invoked_name_ta       = 'ஓம் மஹாலக்ஷ்ம்யை நம꞉',
       invoked_name_translit = 'oṃ mahālakṣmyai namaḥ',
       offering_deva         = 'गुल्फौ पूजयामि',
       offering_ta           = 'குல்பௌ பூஜயாமி'
 where seq = 2 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ इन्दिरायै नमः',
       invoked_name_ta       = 'ஓம் இந்திராயை நம꞉',
       invoked_name_translit = 'oṃ indirāyai namaḥ',
       offering_deva         = 'जङ्घे पूजयामि',
       offering_ta           = 'ஜங்கே பூஜயாமி'
 where seq = 3 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ चण्डिकायै नमः',
       invoked_name_ta       = 'ஓம் சண்டிகாயை நம꞉',
       invoked_name_translit = 'oṃ caṇḍikāyai namaḥ',
       offering_deva         = 'जानुनी पूजयामि',
       offering_ta           = 'ஜாநுநீ பூஜயாமி'
 where seq = 4 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ क्षीराब्धि तनयायै नमः',
       invoked_name_ta       = 'ஓம் க்ஷீராப்தி தநயாயை நம꞉',
       invoked_name_translit = 'oṃ kṣīrābdhi tanayāyai namaḥ',
       offering_deva         = 'ऊरू पूजयामि',
       offering_ta           = 'ஊரூ பூஜயாமி'
 where seq = 5 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ पीतांबर धारिण्यै नमः',
       invoked_name_ta       = 'ஓம் பீதாம்பர தாரிண்யை நம꞉',
       invoked_name_translit = 'oṃ pītāṃbara dhāriṇyai namaḥ',
       offering_deva         = 'कटिं पूजयामि',
       offering_ta           = 'கடிம் பூஜயாமி'
 where seq = 6 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ सागरसंभवायै नमः',
       invoked_name_ta       = 'ஓம் ஸாகரஸம்பவாயை நம꞉',
       invoked_name_translit = 'oṃ sāgarasaṃbhavāyai namaḥ',
       offering_deva         = 'गुह्यम् पूजयामि',
       offering_ta           = 'குஹ்யம் பூஜயாமி'
 where seq = 7 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ नारायण प्रियायै नमः',
       invoked_name_ta       = 'ஓம் நாராயண ப்ரியாயை நம꞉',
       invoked_name_translit = 'oṃ nārāyaṇa priyāyai namaḥ',
       offering_deva         = 'नाभिं पूजयामि',
       offering_ta           = 'நாபிம் பூஜயாமி'
 where seq = 8 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ जगत्कुक्ष्यै नमः',
       invoked_name_ta       = 'ஓம் ஜகத்குக்ஷ்யை நம꞉',
       invoked_name_translit = 'oṃ jagatkukṣyai namaḥ',
       offering_deva         = 'कुक्षिं पूजयामि',
       offering_ta           = 'குக்ஷிம் பூஜயாமி'
 where seq = 9 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ विश्वजनन्यै नमः',
       invoked_name_ta       = 'ஓம் விஶ்வஜநந்யை நம꞉',
       invoked_name_translit = 'oṃ viśvajananyai namaḥ',
       offering_deva         = 'वक्षः पूजयामि',
       offering_ta           = 'வக்ஷ꞉ பூஜயாமி'
 where seq = 10 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ सुस्तन्यै नमः',
       invoked_name_ta       = 'ஓம் ஸுஸ்தந்யை நம꞉',
       invoked_name_translit = 'oṃ sustanyai namaḥ',
       offering_deva         = 'स्तनौ पूजयामि',
       offering_ta           = 'ஸ்தநௌ பூஜயாமி'
 where seq = 11 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ कम्बुकण्ठ्यै नमः',
       invoked_name_ta       = 'ஓம் கம்புகண்ட்யை நம꞉',
       invoked_name_translit = 'oṃ kambukaṇṭhyai namaḥ',
       offering_deva         = 'कण्ठम् पूजयामि',
       offering_ta           = 'கண்டம் பூஜயாமி'
 where seq = 12 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ सुन्दर्यै नमः',
       invoked_name_ta       = 'ஓம் ஸுந்தர்யை நம꞉',
       invoked_name_translit = 'oṃ sundaryai namaḥ',
       offering_deva         = 'स्कन्धौ पूजयामि',
       offering_ta           = 'ஸ்கந்தௌ பூஜயாமி'
 where seq = 13 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ पद्महस्तायै नमः',
       invoked_name_ta       = 'ஓம் பத்மஹஸ்தாயை நம꞉',
       invoked_name_translit = 'oṃ padmahastāyai namaḥ',
       offering_deva         = 'हस्तान् पूजयामि',
       offering_ta           = 'ஹஸ்தாந் பூஜயாமி'
 where seq = 14 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ बहुप्रदायै नमः',
       invoked_name_ta       = 'ஓம் பஹுப்ரதாயை நம꞉',
       invoked_name_translit = 'oṃ bahupradāyai namaḥ',
       offering_deva         = 'बाहून् पूजयामि',
       offering_ta           = 'பாஹூந் பூஜயாமி'
 where seq = 15 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ चन्द्रवदनायै नमः',
       invoked_name_ta       = 'ஓம் சந்த்ரவதநாயை நம꞉',
       invoked_name_translit = 'oṃ candravadanāyai namaḥ',
       offering_deva         = 'वक्त्रं पूजयामि',
       offering_ta           = 'வக்த்ரம் பூஜயாமி'
 where seq = 16 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ चञ्चलायै नमः',
       invoked_name_ta       = 'ஓம் சஞ்சலாயை நம꞉',
       invoked_name_translit = 'oṃ cañcalāyai namaḥ',
       offering_deva         = 'चिबुकं पूजयामि',
       offering_ta           = 'சிபுகம் பூஜயாமி'
 where seq = 17 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ बिम्बोष्ठ्यै नमः',
       invoked_name_ta       = 'ஓம் பிம்போஷ்ட்யை நம꞉',
       invoked_name_translit = 'oṃ bimboṣṭhyai namaḥ',
       offering_deva         = 'ओष्ठं पूजयामि',
       offering_ta           = 'ஓஷ்டம் பூஜயாமி'
 where seq = 18 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ अनघायै नमः',
       invoked_name_ta       = 'ஓம் அநகாயை நம꞉',
       invoked_name_translit = 'oṃ anaghāyai namaḥ',
       offering_deva         = 'अधरं पूजयामि',
       offering_ta           = 'அதரம் பூஜயாமி'
 where seq = 19 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ सुकपोलायै नमः',
       invoked_name_ta       = 'ஓம் ஸுகபோலாயை நம꞉',
       invoked_name_translit = 'oṃ sukapolāyai namaḥ',
       offering_deva         = 'कपोलौ पूजयामि',
       offering_ta           = 'கபோலௌ பூஜயாமி'
 where seq = 20 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ फलप्रदायै नमः',
       invoked_name_ta       = 'ஓம் பலப்ரதாயை நம꞉',
       invoked_name_translit = 'oṃ phalapradāyai namaḥ',
       offering_deva         = 'फालम् पूजयामि',
       offering_ta           = 'பாலம் பூஜயாமி'
 where seq = 21 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ नीलालकायै नमः',
       invoked_name_ta       = 'ஓம் நீலாலகாயை நம꞉',
       invoked_name_translit = 'oṃ nīlālakāyai namaḥ',
       offering_deva         = 'अलकान् पूजयामि',
       offering_ta           = 'அலகாந் பூஜயாமி'
 where seq = 22 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ शिवायै नमः',
       invoked_name_ta       = 'ஓம் ஶிவாயை நம꞉',
       invoked_name_translit = 'oṃ śivāyai namaḥ',
       offering_deva         = 'शिरः पूजयामि',
       offering_ta           = 'ஶிர꞉ பூஜயாமி'
 where seq = 23 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');
update public.archana_items set
       invoked_name_deva     = 'ॐ सर्वमङ्गलायै नमः',
       invoked_name_ta       = 'ஓம் ஸர்வமங்கலாயை நம꞉',
       invoked_name_translit = 'oṃ sarvamaṅgalāyai namaḥ',
       offering_deva         = 'सर्वाण्यङ्गानि पूजयामि',
       offering_ta           = 'ஸர்வாண்யங்காநி பூஜயாமி'
 where seq = 24 and pooja_step_id = (select id from public.pooja_steps
        where pooja_id = 'varalakshmi_vratham' and step_title_en = 'Anga Pooja');

-- --- assert ------------------------------------------------------------------
do $$
declare n int;
begin
  -- Not one ASCII colon may remain in any script column, in any pooja.
  select count(*) into n from public.pooja_steps
   where mantra_sanskrit like '%:%' or mantra_tamil like '%:%'
      or mantra_translit like '%:%';
  if n > 0 then raise exception '% steps still carry an ASCII colon', n; end if;

  select count(*) into n from public.archana_items
   where invoked_name_deva like '%:%' or invoked_name_ta like '%:%'
      or invoked_name_translit like '%:%' or offering_deva like '%:%'
      or offering_ta like '%:%';
  if n > 0 then raise exception '% archana rows still carry an ASCII colon', n; end if;

  select count(*) into n from public.namavali_items
   where name_deva like '%:%' or name_ta like '%:%' or name_translit like '%:%';
  if n > 0 then raise exception '% namavali items carry an ASCII colon', n; end if;

  -- And the visarga is present in each script where it belongs.
  select count(*) into n from public.archana_items a
    join public.pooja_steps s on s.id = a.pooja_step_id
   where s.pooja_id = 'varalakshmi_vratham' and s.step_title_en = 'Anga Pooja'
     and a.invoked_name_ta like '%' || chr(42889) || '%';
  if n <> 24 then raise exception 'only % of 24 anga rows have the Tamil visarga', n; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
