-- =============================================================================
-- 0038_rls_read_only.sql
--
-- GENERATED by scripts/build-rls-lockdown.mjs. Do not hand-edit.
--
-- WHAT PROMPTED THIS, AND A CORRECTION. The alarm was a PATCH sent with the
-- anon key, WHERE matching no rows, which answered 204 on every table and was
-- read as "anon can write". That proves nothing: PostgREST answers 204 to an
-- update matching zero rows whether RLS refused it or there was nothing to
-- update. INSERT is the probe that discriminates, and afterwards it was
-- refused everywhere. So it is NOT established that RLS was off beforehand.
--
-- The reason to keep this migration is independent of that:
--
--   poojas and pooja_steps -- the two tables the app reads -- are protected
--   nowhere in supabase/migrations. Their RLS came from a dashboard click and
--   survives in the repo only as a stub in the test harness. A database built
--   from migrations alone would come up with them wide open and nothing in
--   version control would say so.
--
-- The risk is integrity, not disclosure: nothing here is private, but the rows
-- are liturgy people recite and there is no undo but replaying migrations.
--
-- Every content table gets RLS and exactly one policy: select using (true).
-- No insert, update or delete policy exists for anon, so those are refused.
--
-- `enable`, NOT `force`. Forced RLS applies to the table owner too, and
-- migrations are run as the owner in the SQL editor -- forcing it would make
-- the next migration fail. user_sessions keeps its own per-user policies.
--
-- Idempotent, and safe on a database missing any of these tables.
-- =============================================================================

begin;

do $$
declare t text;
begin
  foreach t in array array[
    'poojas',
    'pooja_steps',
    'deities',
    'upachara_templates',
    'namavalis',
    'namavali_items',
    'archana_items',
    'samagri_items',
    'naivedyam_items',
    'media_assets',
    'pooja_date_overrides'
  ] loop
    -- to_regclass returns null rather than raising, so a database that does
    -- not have one of these tables is skipped instead of failing.
    if to_regclass('public.' || t) is null then
      raise notice 'skipping %, which does not exist here', t;
      continue;
    end if;

    execute format('alter table public.%I enable row level security', t);

    if not exists (
      select 1 from pg_policies
       where schemaname = 'public' and tablename = t
         and policyname = 'public read ' || t
    ) then
      execute format(
        'create policy %I on public.%I for select using (true)',
        'public read ' || t, t);
    end if;

    -- Anything that lets anon write is removed. A permissive FOR ALL policy
    -- reads as harmless next to a select policy and is not.
    declare p record;
    begin
      for p in
        select policyname, cmd from pg_policies
         where schemaname = 'public' and tablename = t
           and cmd <> 'SELECT'
      loop
        raise notice 'dropping % policy % on %', p.cmd, p.policyname, t;
        execute format('drop policy %I on public.%I', p.policyname, t);
      end loop;
    end;
  end loop;
end $$;

-- --- assert ------------------------------------------------------------------
do $$
declare t text; n int;
begin
  foreach t in array array[
    'poojas',
    'pooja_steps',
    'deities',
    'upachara_templates',
    'namavalis',
    'namavali_items',
    'archana_items',
    'samagri_items',
    'naivedyam_items',
    'media_assets',
    'pooja_date_overrides'
  ] loop
    if to_regclass('public.' || t) is null then continue; end if;

    select count(*) into n from pg_class c
      join pg_namespace ns on ns.oid = c.relnamespace
     where ns.nspname = 'public' and c.relname = t and c.relrowsecurity;
    if n <> 1 then raise exception 'row level security is not enabled on %', t; end if;

    select count(*) into n from pg_policies
     where schemaname = 'public' and tablename = t and cmd = 'SELECT';
    if n < 1 then raise exception '% has no select policy, so nothing can read it', t; end if;

    select count(*) into n from pg_policies
     where schemaname = 'public' and tablename = t and cmd <> 'SELECT';
    if n > 0 then raise exception '% still has % non-select policies', t, n; end if;
  end loop;

  -- user_sessions must KEEP its write policies; this migration must not have
  -- stripped them.
  if to_regclass('public.user_sessions') is not null then
    select count(*) into n from pg_policies
     where schemaname = 'public' and tablename = 'user_sessions' and cmd <> 'SELECT';
    if n < 1 then raise exception 'user_sessions lost its own write policies'; end if;
  end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
