-- =============================================================================
-- 0040_nitya_archana_prose.sql
--
-- GENERATED by scripts/build-nitya-archana-prose.mjs. Do not hand-edit.
--
-- 0037 generated the meaning and philosophy of all five archanas from one
-- template, varying only the count word and the flower. Every one carried the
-- same paragraph, and Shiva and Devi carried the same meaning too, because both
-- lists have eight names. proofread flagged the duplication and was right:
-- five deities were being explained with one sentence that fitted none of them.
--
-- A template is fine for a hundred rows of a namavali. It is not fine for the
-- one paragraph that tells a reader what they are looking at.
-- =============================================================================

begin;

update public.pooja_steps set
       meaning_en    = 'Sixteen names, from Sumukha the fair-faced to Skandapurvaja the elder brother of Skanda, each closed with namaha, and then the offering of fragrant leaves and flowers of many kinds.',
       philosophy_en = 'These are the same sixteen names the book gives in the Purvanga section and again in the Siddhivinayaka pooja. Three separate places, the same list in the same order -- which is how you can tell a short archana is fixed rather than chosen.',
       updated_at    = now()
 where pooja_id = 'nitya_panchayatana' and step_title_en = 'Archana — Vinayaka';

update public.pooja_steps set
       meaning_en    = 'Twelve names -- Mitra, Ravi, Surya, Bhanu, Khaga, Pushan, Hiranyagarbha, Marichi, Aditya, Savitr, Arka, Bhaskara -- offered to Surya with Chhaya and Sanjna.',
       philosophy_en = 'Twelve names for twelve months, one Aditya for each. The sun is the only one of the five whose archana is counted by the year, and the only one invoked in a stone you can see through.',
       updated_at    = now()
 where pooja_id = 'nitya_panchayatana' and step_title_en = 'Archana — Surya';

update public.pooja_steps set
       meaning_en    = 'Twenty-four names, from Keshava to Shri Krishna, offered to Mahavishnu with Bhumi and Nila.',
       philosophy_en = 'The first twelve are exactly the twelve of the Anga Vandanam, in the same order. There they are said bare while touching the limbs of your own body; here they take the dative and namaha and are said to an image. The same names, used twice in one rite for two different things. The book also prints a twenty-fifth, hayagreevaaya, in brackets and does not count it -- the same convention it uses for two of the Lakshmi hundred and eight.',
       updated_at    = now()
 where pooja_id = 'nitya_panchayatana' and step_title_en = 'Archana — Vishnu';

update public.pooja_steps set
       meaning_en    = 'Eight names -- Bhava, Sharva, Ishana, Pashupati, Rudra, Ugra, Bhima and Mahat -- each addressed as devaaya, to the god.',
       philosophy_en = 'The eight forms of Rudra, and the shortest archana of the five. The deity at the centre of the arrangement is given fewer names than any of the four around him.',
       updated_at    = now()
 where pooja_id = 'nitya_panchayatana' and step_title_en = 'Archana — Shiva';

update public.pooja_steps set
       meaning_en    = 'Eight names, each one the genitive of a form of Shiva followed by patnyai: to the wife of Bhava the god, to the wife of Sharva the god, and so on through the same eight.',
       philosophy_en = 'Devi is given no eight names of her own here. She is worshipped as the consort of each of Shiva’s eight forms, using his list in the genitive -- so the two archanas either side of the centre are the same eight words said twice, once in the dative and once in the possessive. Whether that reads as subordination or as inseparability is exactly the question the arrangement is posing, and the book does not answer it.',
       updated_at    = now()
 where pooja_id = 'nitya_panchayatana' and step_title_en = 'Archana — Devi';

-- --- assert ------------------------------------------------------------------
do $$
declare n int;
begin
  -- All five carry prose, and no two of them carry the same prose.
  select count(*) into n from public.pooja_steps
   where pooja_id = 'nitya_panchayatana' and step_title_en like 'Archana%'
     and coalesce(trim(meaning_en), '') <> '' and coalesce(trim(philosophy_en), '') <> '';
  if n <> 5 then raise exception 'only % of 5 archanas have prose', n; end if;

  select count(distinct meaning_en) into n from public.pooja_steps
   where pooja_id = 'nitya_panchayatana' and step_title_en like 'Archana%';
  if n <> 5 then raise exception 'the archanas share a meaning: % distinct of 5', n; end if;

  select count(distinct philosophy_en) into n from public.pooja_steps
   where pooja_id = 'nitya_panchayatana' and step_title_en like 'Archana%';
  if n <> 5 then raise exception 'the archanas share a philosophy: % distinct of 5', n; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
