-- =============================================================================
-- 0041_karta_recommendation.sql
--
-- GENERATED by scripts/build-karta-recommendation.mjs. Do not hand-edit.
--
-- A pooja may now recommend a karta. Varalakshmi recommends a woman.
--
-- WHY NOT THE eligibility COLUMN THAT ALREADY EXISTS. It is constrained to
-- all / male_only / female_only / initiated_male_only, and female_only is a
-- PROHIBITION the book does not make. Its Varalakshmi chapter expects women --
-- kept "more so by the women who are looked upon as the embodiment of Lakshmi",
-- the origin story told entirely through Surachandrika, Shyama Bala and
-- Charumati, Lakshmi herself disguised as a "Suvasini (married woman)" -- but
-- it never writes that a man may not keep the vratham. When this book means to
-- exclude someone it says so and offers a substitute; that is how it handles
-- gaNaanaam tvaa in the Purvanga section.
--
--   eligibility        who MAY.      Left at all on every pooja.
--   karta_recommended  who is EXPECTED. Varalakshmi: female.
--
-- Ganesha and the Nitya Panchayatana stay null. The daily rite is commonly the
-- male householder's in practice, but the book says nothing of the kind, and
-- household custom does not get promoted to printed instruction here.
--
-- In the app the recommendation only pre-selects a button. The other two stay
-- live and choosing one is not an error state.
-- =============================================================================

begin;

alter table public.poojas
  add column if not exists karta_recommended text;

do $$ begin
  alter table public.poojas
    add constraint poojas_karta_recommended_ck
    check (karta_recommended in ('male', 'female', 'couple'));
exception when duplicate_object or duplicate_table then null; end $$;

comment on column public.poojas.karta_recommended is
  'Who the tradition EXPECTS to perform this rite, or null for no recommendation. A recommendation, not a rule: see eligibility for who MAY. The app uses it only to pre-select the karta toggle.';

update public.poojas set
       karta_recommended = 'female',
       updated_at = now()
 where id = 'varalakshmi_vratham';

update public.poojas set
       karta_recommended = null,
       updated_at = now()
 where id = 'ganesha_standard';

update public.poojas set
       karta_recommended = null,
       updated_at = now()
 where id = 'nitya_panchayatana';

-- --- assert ------------------------------------------------------------------
do $$
declare n int; v text;
begin
  if to_regclass('public.poojas') is null then
    raise exception 'public.poojas is missing';
  end if;

  -- The column exists and is nullable. A not-null default would have forced
  -- every future pooja to claim a recommendation it may not have.
  select count(*) into n from information_schema.columns
   where table_schema = 'public' and table_name = 'poojas'
     and column_name = 'karta_recommended' and is_nullable = 'YES';
  if n <> 1 then raise exception 'karta_recommended is missing or not nullable'; end if;

  select karta_recommended into v from public.poojas where id = 'varalakshmi_vratham';
  if not found then raise notice 'varalakshmi_vratham is not in this database, skipping';
  elsif v is distinct from 'female' then
    raise exception 'varalakshmi_vratham recommends %, expected female', coalesce(v, 'nobody');
  end if;

  select karta_recommended into v from public.poojas where id = 'ganesha_standard';
  if not found then raise notice 'ganesha_standard is not in this database, skipping';
  elsif v is not null then
    raise exception 'ganesha_standard recommends %, but it should recommend nobody', v;
  end if;

  select karta_recommended into v from public.poojas where id = 'nitya_panchayatana';
  if not found then raise notice 'nitya_panchayatana is not in this database, skipping';
  elsif v is not null then
    raise exception 'nitya_panchayatana recommends %, but it should recommend nobody', v;
  end if;

  -- The constraint rejects anything else. Checked by TRYING it, because a
  -- constraint that exists and does not bite is the failure mode here, and
  -- reading it out of pg_constraint would only prove it was written down.
  -- The write is real and is rolled back by the subtransaction the exception
  -- block opens, so nothing survives it.
  select count(*) into n from public.poojas;
  if n > 0 then
    begin
      update public.poojas set karta_recommended = 'priest'
       where id = (select id from public.poojas order by id limit 1);
      raise exception 'the check constraint let an invalid karta through';
    exception when check_violation then null;
    end;
  end if;

  -- eligibility is deliberately untouched: this migration adds an expectation,
  -- not a permission rule.
  select count(*) into n from public.poojas where eligibility <> 'all';
  if n > 0 then raise exception '% pooja(s) carry a non-all eligibility; this migration should not have set one', n; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
