-- =============================================================================
-- 0047_pooja_modes_table.sql
--
-- GENERATED by scripts/build-pooja-modes-table.mjs. Do not hand-edit.
--
-- A pooja's modes become data. pooja_steps.modes has been a free text[] since
-- 0009, but the three values it held -- main, punar, udvasana -- were hardcoded
-- in PoojaViewer along with their labels, their Tamil and their hints. Fine
-- while every pooja with modes was a multi-day observance.
--
-- Sandhyavandanam is not. Its modes are three SITTINGS: praatah, maadhyaahnika,
-- saayam. Same machinery, different words, and the picker cannot know them
-- because they live in a .tsx file.
--
-- A TABLE RATHER THAN A SECOND HARDCODED MAP, because these are content: they
-- are bilingual, they need the same Tamil review as every other string, and the
-- next rite will bring its own. A map in the component puts Tamil somewhere no
-- proofread gate can see it, which is how step_title_ta came to be empty on
-- eighteen rows before 0006.
--
-- seq is stored because the order is neither alphabetical nor insertion order:
-- main before punar before udvasana, morning before noon before evening. A
-- picker that sorted for itself would put maadhyaahnika first.
-- =============================================================================

begin;

create table if not exists public.pooja_modes (
  pooja_id   text not null references public.poojas(id) on delete cascade,
  mode       text not null,
  seq        integer not null,
  label_en   text not null,
  label_ta   text not null,
  hint_en    text not null,
  hint_ta    text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (pooja_id, mode)
);

comment on table public.pooja_modes is
  'The modes a pooja offers, with their labels. A mode string here must match the values used in pooja_steps.modes. seq orders the picker.';

-- Read-only through the API like every other content table. Same reasoning as
-- 0038: the app only reads, and migrations run as the owner, so enable rather
-- than force.
alter table public.pooja_modes enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public'
                  and tablename = 'pooja_modes' and policyname = 'public read pooja_modes') then
    create policy "public read pooja_modes" on public.pooja_modes for select using (true);
  end if;
end $$;

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('ganesha_standard', 'main', 1, 'Main Pooja', 'பிரதான பூஜை', 'First day. Full vidhi, the idol is installed.', 'முதல் நாள். முழு விதி, விக்கிரகம் பிரதிஷ்டை செய்யப்படுகிறது.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('ganesha_standard', 'punar', 2, 'Punar Pooja', 'புனர் பூஜை', 'A later day. Shorter: the deity is already installed.', 'அடுத்த நாட்கள். சுருக்கமானது: மூர்த்தி ஏற்கனவே பிரதிஷ்டை செய்யப்பட்டுள்ளது.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('ganesha_standard', 'udvasana', 3, 'Udvasanam only', 'உத்வாசனம்', 'Final day. Closing and release, before immersion.', 'இறுதி நாள். நிறைவும் உத்வாசனமும், விசர்ஜனத்திற்கு முன்.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('varalakshmi_vratham', 'main', 1, 'Main Pooja', 'பிரதான பூஜை', 'First day. Full vidhi, the kalasham is dressed and installed.', 'முதல் நாள். முழு விதி, கலசம் அலங்கரித்து பிரதிஷ்டை செய்யப்படுகிறது.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('varalakshmi_vratham', 'punar', 2, 'Punar Pooja', 'புனர் பூஜை', 'The next day. Shorter: the goddess is already installed.', 'மறுநாள். சுருக்கமானது: தாயார் ஏற்கனவே பிரதிஷ்டை செய்யப்பட்டுள்ளார்.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('varalakshmi_vratham', 'udvasana', 3, 'Udvasanam only', 'உத்வாசனம்', 'Closing and release, before the kalasham is dismantled.', 'நிறைவும் உத்வாசனமும், கலசம் கலைக்கப்படுவதற்கு முன்.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('nitya_panchayatana', 'main', 1, 'Daily', 'தினசரி', 'Performed every morning. There is no second day.', 'தினமும் காலையில் செய்யப்படுவது. இரண்டாம் நாள் கிடையாது.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('sandhyavandanam', 'pratah', 1, 'Prātaḥ — morning', 'ப்ராதஃ — காலை', 'At dawn. Gayatri japa 108 times, facing east.', 'விடியற்காலை. காயத்ரி ஜபம் 108 முறை, கிழக்கு நோக்கி.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('sandhyavandanam', 'madhyahnika', 2, 'Mādhyāhnika — noon', 'மாத்யாஹ்நிகம் — உச்சி', 'At midday. Gayatri japa 32 times, facing east.', 'நண்பகல். காயத்ரி ஜபம் 32 முறை, கிழக்கு நோக்கி.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

insert into public.pooja_modes (pooja_id, mode, seq, label_en, label_ta, hint_en, hint_ta)
values ('sandhyavandanam', 'sayam', 3, 'Sāyam — evening', 'ஸாயம் — மாலை', 'At dusk. Gayatri japa 64 times, facing west before sunset and east after.', 'அந்தி வேளை. காயத்ரி ஜபம் 64 முறை; சூரியன் மறைவதற்கு முன் மேற்கு, பின் கிழக்கு.')
on conflict (pooja_id, mode) do update set
       seq = excluded.seq, label_en = excluded.label_en, label_ta = excluded.label_ta,
       hint_en = excluded.hint_en, hint_ta = excluded.hint_ta, updated_at = now();

-- --- assert ------------------------------------------------------------------
do $$
declare n int;
begin
  select count(*) into n from public.pooja_modes where pooja_id = 'ganesha_standard';
  if n <> 3 then raise exception 'ganesha_standard has % modes, expected 3', n; end if;
  select count(*) into n from public.pooja_modes where pooja_id = 'varalakshmi_vratham';
  if n <> 3 then raise exception 'varalakshmi_vratham has % modes, expected 3', n; end if;
  select count(*) into n from public.pooja_modes where pooja_id = 'nitya_panchayatana';
  if n <> 1 then raise exception 'nitya_panchayatana has % modes, expected 1', n; end if;
  select count(*) into n from public.pooja_modes where pooja_id = 'sandhyavandanam';
  if n <> 3 then raise exception 'sandhyavandanam has % modes, expected 3', n; end if;

  -- Every mode a STEP claims must be declared here, or the picker will filter
  -- on a value it cannot name and the step will be unreachable. This is the
  -- assertion that makes the table worth having.
  select count(*) into n from (
    select distinct s.pooja_id, unnest(s.modes) as mode from public.pooja_steps s
  ) claimed
  where not exists (
    select 1 from public.pooja_modes m
     where m.pooja_id = claimed.pooja_id and m.mode = claimed.mode
  );
  if n > 0 then raise exception '% step mode(s) are not declared in pooja_modes', n; end if;

  -- ...and nothing is declared that no step uses, which would put a dead button
  -- on the preparation screen.
  select count(*) into n from public.pooja_modes m
   where exists (select 1 from public.pooja_steps s where s.pooja_id = m.pooja_id)
     and not exists (
       select 1 from public.pooja_steps s
        where s.pooja_id = m.pooja_id and m.mode = any(s.modes)
     );
  if n > 0 then raise exception '% declared mode(s) have no steps', n; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
