-- =============================================================================
-- 0048_sandhyavandanam_part_one.sql
--
-- GENERATED by scripts/build-sandhyavandanam-part-one.mjs. Do not hand-edit.
--
-- Sandhyavandanam, book pages 16 to 27: from the achamanam to the seal the book
-- puts on its own first half. Eighteen steps.
--
-- Source: Yajurveda Trikaala Sandhyaavandanam, Giri Trading Agency, English
-- translation by A. R. Parthasarathi. Mantras transcribed from photographs of
-- the printed page; the English here is written for this app, because the
-- book's glosses and rubrics are the editor's prose.
--
-- THREE SITTINGS, THREE KINDS OF DIFFERENCE, and the data follows the rite
-- rather than one convenient pattern:
--
--   different mantra, same action -> three rows, one mode each. The Sankalpa,
--   and the Prashanam, which is three entirely separate mantras.
--
--   same mantra, different count -> one row, the count in instruction_en.
--   Arghyam is offered three times morning and evening, twice at noon.
--
--   same everything -> one row carrying all three modes.
--
-- THREE MISPRINTS ARE CORRECTED, each with its evidence:
--
--   यो वशिशवतमो रसः  ->  यो वः शिवतमो रसः
--   Book pages 21 and 24 both set यो वशिशवतमो रसः -- the visarga after वः
--   lost and शि doubled. Three readings agree against the page: this book's
--   OWN roman four lines below ("yo vah-shivatamo rasaha"), the Bhavan
--   edition's roman ("yo vah sivatamorasah"), and the received text of the
--   Rigvedic apo hi shtha. The same wrong setting appears twice with the
--   right roman twice, which means reused type rather than a compositor
--   slipping.
--
--   ओं भूर्भुवस्तुवः।  ->  ओं भूर्भुवः सुवः।
--   Book page 25 sets तुवः where the roman beside it reads "suvaha" and
--   every other occurrence in the book reads सुवः. A स set as त.
--
--   त्रिविक्रमं तर्पयामिा  ->  त्रिविक्रमं तर्पयामि
--   Book page 27 carries a stray aa-matra on one of twenty-one otherwise
--   identical lines. Every other line is तर्पयामि and the roman reads
--   "trivikramam tarpayaami".
--
-- The generator asserts each correction applied exactly as often as expected,
-- so a fix that silently matched nothing fails the build instead of shipping
-- the misprint.
--
-- The pooja stays PLANNED. It is published by 0049, when the japa half lands
-- and the rite is whole.
-- =============================================================================

begin;

-- Idempotent: re-running replaces the same steps rather than renumbering.
delete from public.archana_items where pooja_step_id in (select id from public.pooja_steps where pooja_id = 'sandhyavandanam');
delete from public.pooja_steps where pooja_id = 'sandhyavandanam';

-- 1. Achamanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 1, 'purvangam', 'Achamanam', 'ஆசமனம்',
   'Sit facing east or north. Fold the forefinger of the right hand against the thumb and curl the other three so the palm holds a spoonful of water. Sip once at each of the three names. Achamanam and Anga Vandanam are done three times over at the start.',
   'अच्युताय नमः
अनन्ताय नमः
गोविन्दाय नमः',
   'அச்யுதாய நம꞉
அநந்தாய நம꞉
கோவிந்தாய நம꞉',
   'acyutāya namaḥ
anantāya namaḥ
govindāya namaḥ',
   'Three names of Vishnu, each closed with namaha, one sip of water to each. The book calls the set the nama-trayee vidya and says it cures all disease.',
   'Nothing has been asked for and no deity invited. Water is taken into the body while three names are said over it, and that is the whole step. Every rite in this app opens the same way, which is the point: the mouth about to recite is rinsed first, and the rinsing is itself done with names.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 2. Anga Vandanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 2, 'purvangam', 'Anga Vandanam', 'அங்க வந்தனம்',
   'Six pairs of names, each touched to a part of the body with the finger named against it: thumb to the cheeks, ring finger to the eyes, forefinger to the nostrils, little finger to the ears, middle finger to the shoulders, and all the fingers to the navel and the crown.',
   'केशव – नारायण
माधव – गोविन्द
विष्णो – मधुसूदन
त्रिविक्रम – वामन
श्रीधर – हृषीकेश
पद्मनाभ – दामोदर',
   'கேஶவ – நாராயண
மாதவ – கோவிந்த
விஷ்ணோ – மதுஸூதந
த்ரிவிக்ரம – வாமந
ஶ்ரீதர – ஹ்ருஷீகேஶ
பத்மநாப – தாமோதர',
   'keśava – nārāyaṇa
mādhava – govinda
viṣṇo – madhusūdana
trivikrama – vāmana
śrīdhara – hṛṣīkeśa
padmanābha – dāmodara',
   'The twelve names of Vishnu, placed on the body two at a time — Keshava and Narayana, Madhava and Govinda, Vishnu and Madhusudana, Trivikrama and Vamana, Sridhara and Hrishikesha, Padmanabha and Damodara.',
   'The book gives a reason for every finger, and it is not decorative: thumb and mouth are held to be the seat of fire, ring finger and eyes of the sun, forefinger and nose of wind, little finger and ears of Indra, middle finger and shoulders of Prajapati. The inside of the hand is God, which is why the last pair goes to the heart and the head. The body is not being blessed part by part; it is being identified part by part with what already lives there.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 3. Vighneshwara Dhyanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 3, 'purvangam', 'Vighneshwara Dhyanam', 'விக்னேஶ்வர த்யானம்',
   'Tap both temples gently with the knuckles five times while reciting.',
   'शुक्लाम्बरधरं विष्णुं शशिवर्णं चतुर्भुजम्।
प्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशान्तये॥',
   'ஶுக்லாம்பரதரம் விஷ்ணும் ஶஶிவர்ணம் சதுர்புஜம்।
ப்ரஸந்நவதநம் த்யாயேத் ஸர்வவிக்நோபஶாந்தயே॥',
   'śuklāmbaradharaṃ viṣṇuṃ śaśivarṇaṃ caturbhujam।
prasannavadanaṃ dhyāyet sarvavighnopaśāntaye॥',
   'He who wears white, who pervades all, moon-coloured and four-armed, with a face at ease — meditate on him, for the quieting of every obstacle.',
   'The same verse opens the japa half of this rite as well, and it opens most poojas in this app. It asks for obstacles to be quieted rather than removed, which is a smaller and more exact request: the rite is about to be performed either way.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 4. Pranayamam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 4, 'purvangam', 'Pranayamam', 'ப்ராணாயாமம்',
   'Fold the index and middle fingers. Close the right nostril with the thumb and the left with the ring and little fingers. The mantra has three parts and the breath is assigned to each: breathe IN through the left nostril reciting silently from om bhuh to ogm satyam; HOLD through om tat savitur to prachodayat; breathe OUT through the right nostril through om aapo jyoti to bhurbhuvassuvarom. That is one pranayama.',
   'ओं भूः ओं भुवः ओꣳ सुवः ओं महः ओं जनः ओं तपः ओꣳ सत्यम्
ओं तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि। धियो यो नः प्रचोदयात्।
ओमापो ज्योतीरसोऽमृतं ब्रह्म भूर्भुवः सुवरोम्॥',
   'ஓம் பூ꞉ ஓம் புவ꞉ ஓகும் ஸுவ꞉ ஓம் மஹ꞉ ஓம் ஜந꞉ ஓம் தப꞉ ஓகும் ஸத்யம்
ஓம் தத்ஸவிதுர்வரேண்யம் பர்கோ தேவஸ்ய தீமஹி। தியோ யோ ந꞉ ப்ரசோதயாத்।
ஓமாபோ ஜ்யோதீரஸோம்ருதம் ப்ரஹ்ம பூர்புவ꞉ ஸுவரோம்॥',
   'oṃ bhūḥ oṃ bhuvaḥ ogm suvaḥ oṃ mahaḥ oṃ janaḥ oṃ tapaḥ ogm satyam
oṃ tatsaviturvareṇyaṃ bhargo devasya dhīmahi। dhiyo yo naḥ pracodayāt।
omāpo jyotīraso''mṛtaṃ brahma bhūrbhuvaḥ suvarom॥',
   'Seven worlds named as Om, then the Gayatri, then the declaration that the waters, the light, the essence, the immortal and Brahman are all bhuh bhuvah suvah — Om.',
   'The step is defined by the breath and not by repetition. Told only the words, a reader would recite a mantra; told the division, they perform a pranayama, because the three parts are in with the breath, held, and out. The book adds that this is properly learnt from a teacher, which is the first of three places it admits a page cannot teach a body.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 5. Sankalpam — morning
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 5, 'purvangam', 'Sankalpam — morning', 'ஸங்கல்பம் — காலை',
   'Clasp the right palm over the left and rest both on the right thigh while reciting.',
   'ममोपात्त समस्त दुरितक्षयद्वारा श्रीपरमेश्वरप्रीत्यर्थं
प्रातः सन्ध्यामुपासिष्ये',
   'மமோபாத்த ஸமஸ்த துரிதக்ஷயத்வாரா ஶ்ரீபரமேஶ்வரப்ரீத்யர்தம்
ப்ராத꞉ ஸந்த்யாமுபாஸிஷ்யே',
   'mamopātta samasta duritakṣayadvārā śrīparameśvaraprītyarthaṃ
prātaḥ sandhyāmupāsiṣye',
   'That all the wrong accumulated in me may be destroyed, and so that the Supreme may be pleased: I begin to worship the Sandhya of the morning.',
   'This sankalpa names no person, no gotra, no year, month, tithi or star — and the Bhavan edition prints it the same way, so two independent editions agree. A rite performed on a particular day must say which day; a nitya karma need not, because the occasion is that it is morning. Only the last word changes between the three sittings, and not quite symmetrically: morning and evening take upasishye, "I begin to worship", governing the goddess Sandhya, while noon takes karishye, "I shall do", governing the rite itself.',
   array['pratah']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 6. Sankalpam — noon
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 6, 'purvangam', 'Sankalpam — noon', 'ஸங்கல்பம் — உச்சி',
   'Clasp the right palm over the left and rest both on the right thigh while reciting.',
   'ममोपात्त समस्त दुरितक्षयद्वारा श्रीपरमेश्वरप्रीत्यर्थं
माध्याह्निकम् करिष्ये',
   'மமோபாத்த ஸமஸ்த துரிதக்ஷயத்வாரா ஶ்ரீபரமேஶ்வரப்ரீத்யர்தம்
மாத்யாஹ்நிகம் கரிஷ்யே',
   'mamopātta samasta duritakṣayadvārā śrīparameśvaraprītyarthaṃ
mādhyāhnikam kariṣye',
   'That all the wrong accumulated in me may be destroyed, and so that the Supreme may be pleased: I shall perform the midday rite.',
   'This sankalpa names no person, no gotra, no year, month, tithi or star — and the Bhavan edition prints it the same way, so two independent editions agree. A rite performed on a particular day must say which day; a nitya karma need not, because the occasion is that it is morning. Only the last word changes between the three sittings, and not quite symmetrically: morning and evening take upasishye, "I begin to worship", governing the goddess Sandhya, while noon takes karishye, "I shall do", governing the rite itself.',
   array['madhyahnika']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 7. Sankalpam — evening
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 7, 'purvangam', 'Sankalpam — evening', 'ஸங்கல்பம் — மாலை',
   'Clasp the right palm over the left and rest both on the right thigh while reciting.',
   'ममोपात्त समस्त दुरितक्षयद्वारा श्रीपरमेश्वरप्रीत्यर्थं
सायं सन्ध्यामुपासिष्ये',
   'மமோபாத்த ஸமஸ்த துரிதக்ஷயத்வாரா ஶ்ரீபரமேஶ்வரப்ரீத்யர்தம்
ஸாயம் ஸந்த்யாமுபாஸிஷ்யே',
   'mamopātta samasta duritakṣayadvārā śrīparameśvaraprītyarthaṃ
sāyaṃ sandhyāmupāsiṣye',
   'That all the wrong accumulated in me may be destroyed, and so that the Supreme may be pleased: I begin to worship the Sandhya of the evening.',
   'This sankalpa names no person, no gotra, no year, month, tithi or star — and the Bhavan edition prints it the same way, so two independent editions agree. A rite performed on a particular day must say which day; a nitya karma need not, because the occasion is that it is morning. Only the last word changes between the three sittings, and not quite symmetrically: morning and evening take upasishye, "I begin to worship", governing the goddess Sandhya, while noon takes karishye, "I shall do", governing the rite itself.',
   array['sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 8. Jala Prarthana
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 8, 'purvangam', 'Jala Prarthana', 'ஜல ப்ரார்த்தனை',
   'Take water in the uddharani and keep the right ring finger in it. At the end of the mantra write om on the surface of the water and apply it to the forehead.',
   'आपो वा इदꣳ सर्वं विश्वा भूतान्यापः
प्राणा वा आपः पशव आपः
अन्नमापः अमृतमापः सम्राडापः
विराडापः स्वराडापः छन्दाꣳस्यापः
ज्योतीꣳष्यापः यजूꣳष्यापः सत्यमापः
सर्वा देवता आपः भूर्भुवस्सुवराप
ओम् श्री केशवाय नमः',
   'ஆபோ வா இதகும் ஸர்வம் விஶ்வா பூதாந்யாப꞉
ப்ராணா வா ஆப꞉ பஶவ ஆப꞉
அந்நமாப꞉ அம்ருதமாப꞉ ஸம்ராடாப꞉
விராடாப꞉ ஸ்வராடாப꞉ சந்தாகும்ஸ்யாப꞉
ஜ்யோதீகும்ஷ்யாப꞉ யஜூகும்ஷ்யாப꞉ ஸத்யமாப꞉
ஸர்வா தேவதா ஆப꞉ பூர்புவஸ்ஸுவராப
ஓம் ஶ்ரீ கேஶவாய நம꞉',
   'āpo vā idagm sarvaṃ viśvā bhūtānyāpaḥ
prāṇā vā āpaḥ paśava āpaḥ
annamāpaḥ amṛtamāpaḥ samrāḍāpaḥ
virāḍāpaḥ svarāḍāpaḥ chandāgmsyāpaḥ
jyotīgmṣyāpaḥ yajūgmṣyāpaḥ satyamāpaḥ
sarvā devatā āpaḥ bhūrbhuvassuvarāpa
om śrī keśavāya namaḥ',
   'The waters are all this; the worlds are waters, the pranas are waters, cattle are waters, food, the deathless, the metres, the lights, the yajus, truth and all the deities are waters.',
   'Every line predicates something OF water rather than asking anything of it. Nothing is requested; water is identified with each thing in turn until it is identified with everything. Only then is it used, and everything it touches afterwards in this rite has been declared to be everything already. The rubric alone makes this look like washing.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 9. Marjanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 9, 'purvangam', 'Marjanam', 'மார்ஜனம்',
   'Sprinkle water over the head with the ring finger at each of the first seven lines. Touch the right and left thighs at the eighth. Sprinkle again at the ninth. Then take water in the right palm and pass it clockwise around the head.',
   'ओं आपो हि ष्ठा मयोभुवः। ता न ऊर्जे दधातन।
महे रणाय चक्षसे। यो वः शिवतमो रसः। तस्य भाजयतेह नः।
उशतीरिव मातरः। तस्मा अरङ्गमाम वः।
यस्य क्षयाय जिन्वथ।
आपो जनयथा च नः। ओं भूर्भुवःसुवः।',
   'ஓம் ஆபோ ஹி ஷ்டா மயோபுவ꞉। தா ந ஊர்ஜே ததாதந।
மஹே ரணாய சக்ஷஸே। யோ வ꞉ ஶிவதமோ ரஸ꞉। தஸ்ய பாஜயதேஹ ந꞉।
உஶதீரிவ மாதர꞉। தஸ்மா அரங்கமாம வ꞉।
யஸ்ய க்ஷயாய ஜிந்வத।
ஆபோ ஜநயதா ச ந꞉। ஓம் பூர்புவ꞉ஸுவ꞉।',
   'oṃ āpo hi ṣṭhā mayobhuvaḥ। tā na ūrje dadhātana।
mahe raṇāya cakṣase। yo vaḥ śivatamo rasaḥ। tasya bhājayateha naḥ।
uśatīriva mātaraḥ। tasmā araṅgamāma vaḥ।
yasya kṣayāya jinvatha।
āpo janayathā ca naḥ। oṃ bhūrbhuvaḥsuvaḥ।',
   'Waters, you are happiness itself; give us vigour, and the sight of a great gladness. Let us share here in that most kindly essence of yours, like mothers who long for us. We come to you for that whose dwelling you quicken. Waters, beget us anew.',
   'The ten lines are choreography, not layout: the book assigns the first seven to the head, the eighth to the thighs, the ninth to sprinkling again, and the tenth is the closing vyahriti rather than another line of the marjanam. Run together as one mantra the step still recites correctly and stops meaning anything.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 10. Apaam Prashanam — morning
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 10, 'purvangam', 'Apaam Prashanam — morning', 'அபாம் ப்ராஶனம் — காலை',
   'Take one uddharani of water in the palm, recite, and drink the water at the end.',
   'सूर्यश्च मा मन्युश्च मन्युपतयश्च मन्युकृतेभ्यः।
पापेभ्यो रक्षन्ताम्। यद्रात्रिया पापमाकार्षम्॥
मनसा वाचा हस्ताभ्याम्। पद्भ्यामुदरेण शिश्ञा।
रात्रिस्तदवलुम्पतु। यत् किञ्च दुरितं मयि।
इदमहं माममृतयोनौ। सूर्ये ज्योतिषि जुहोमि स्वाहा॥',
   'ஸூர்யஶ்ச மா மந்யுஶ்ச மந்யுபதயஶ்ச மந்யுக்ருதேப்ய꞉।
பாபேப்யோ ரக்ஷந்தாம்। யத்ராத்ரியா பாபமாகார்ஷம்॥
மநஸா வாசா ஹஸ்தாப்யாம்। பத்ப்யாமுதரேண ஶிஶ்ஞா।
ராத்ரிஸ்ததவலும்பது। யத் கிஞ்ச துரிதம் மயி।
இதமஹம் மாமம்ருதயோநௌ। ஸூர்யே ஜ்யோதிஷி ஜுஹோமி ஸ்வாஹா॥',
   'sūryaśca mā manyuśca manyupatayaśca manyukṛtebhyaḥ।
pāpebhyo rakṣantām। yadrātriyā pāpamākārṣam॥
manasā vācā hastābhyām। padbhyāmudareṇa śiśñā।
rātristadavalumpatu। yat kiñca duritaṃ mayi।
idamahaṃ māmamṛtayonau। sūrye jyotiṣi juhomi svāhā॥',
   'May the Sun, and Anger, and the lords of Anger, guard me from the wrong done out of anger; may the night wipe away whatever wrong I did in the night by mind, speech, hands, feet, belly or sex. I offer myself into the sun, into the light, into the deathless. Svaha.',
   'Not one mantra with a word swapped — three different texts, and reading them together shows why. The morning asks the Sun to absolve what was done BY NIGHT; the evening asks Agni to absolve what was done BY DAY; and each offers itself into a different light, the sun in the morning and the truth in the evening. Each sitting cleans the stretch of time behind it. Noon has neither a night nor a day behind it, only a morning of living, so its mantra is about food eaten and gifts taken instead.',
   array['pratah']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 11. Apaam Prashanam — noon
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 11, 'purvangam', 'Apaam Prashanam — noon', 'அபாம் ப்ராஶனம் — உச்சி',
   'Take one uddharani of water in the palm, recite, and drink the water at the end.',
   'आपः पुनन्तु पृथिवीं पृथिवी पूता पुनातु माम्।
पुनन्तु ब्रह्मणस्पतिर्ब्रह्म पूता पुनातु माम्॥
यदुच्छिष्टमभोज्यं यद्वा दुश्चरितं मम।
सर्वं पुनन्तु मामापोऽसतां च प्रतिग्रहꣳः स्वाहा॥',
   'ஆப꞉ புநந்து ப்ருதிவீம் ப்ருதிவீ பூதா புநாது மாம்।
புநந்து ப்ரஹ்மணஸ்பதிர்ப்ரஹ்ம பூதா புநாது மாம்॥
யதுச்சிஷ்டமபோஜ்யம் யத்வா துஶ்சரிதம் மம।
ஸர்வம் புநந்து மாமாபோஸதாம் ச ப்ரதிக்ரஹகும்꞉ ஸ்வாஹா॥',
   'āpaḥ punantu pṛthivīṃ pṛthivī pūtā punātu mām।
punantu brahmaṇaspatirbrahma pūtā punātu mām॥
yaducchiṣṭamabhojyaṃ yadvā duścaritaṃ mama।
sarvaṃ punantu māmāpo''satāṃ ca pratigrahagmḥ svāhā॥',
   'May the waters purify the earth, and the purified earth purify me; may Brahmanaspati purify, and the purified Veda purify me. Whatever was left over and not to be eaten, whatever I did wrongly, whatever I took from the undeserving — may the waters purify all of it. Svaha.',
   'Not one mantra with a word swapped — three different texts, and reading them together shows why. The morning asks the Sun to absolve what was done BY NIGHT; the evening asks Agni to absolve what was done BY DAY; and each offers itself into a different light, the sun in the morning and the truth in the evening. Each sitting cleans the stretch of time behind it. Noon has neither a night nor a day behind it, only a morning of living, so its mantra is about food eaten and gifts taken instead.',
   array['madhyahnika']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 12. Apaam Prashanam — evening
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 12, 'purvangam', 'Apaam Prashanam — evening', 'அபாம் ப்ராஶனம் — மாலை',
   'Take one uddharani of water in the palm, recite, and drink the water at the end.',
   'अग्निश्च मा मन्युश्च मन्युपतयश्च मन्युकृतेभ्यः पापेभ्यो रक्षन्ताम्।
यदह्ना पापमकार्षम्। मनसा वाचा हस्ताभ्याम्।
पद्भ्यामुदरेण शिश्ञा। अहस्तदवलुम्पतु यत् किञ्च दुरितं मयि।
इदमहं माममृतयोनौ। सत्ये ज्योतिषि जुहोमि स्वाहा॥',
   'அக்நிஶ்ச மா மந்யுஶ்ச மந்யுபதயஶ்ச மந்யுக்ருதேப்ய꞉ பாபேப்யோ ரக்ஷந்தாம்।
யதஹ்நா பாபமகார்ஷம்। மநஸா வாசா ஹஸ்தாப்யாம்।
பத்ப்யாமுதரேண ஶிஶ்ஞா। அஹஸ்ததவலும்பது யத் கிஞ்ச துரிதம் மயி।
இதமஹம் மாமம்ருதயோநௌ। ஸத்யே ஜ்யோதிஷி ஜுஹோமி ஸ்வாஹா॥',
   'agniśca mā manyuśca manyupatayaśca manyukṛtebhyaḥ pāpebhyo rakṣantām।
yadahnā pāpamakārṣam। manasā vācā hastābhyām।
padbhyāmudareṇa śiśñā। ahastadavalumpatu yat kiñca duritaṃ mayi।
idamahaṃ māmamṛtayonau। satye jyotiṣi juhomi svāhā॥',
   'May Agni, and Anger, and the lords of Anger, guard me from the wrong done out of anger; may the day wipe away whatever wrong I did in the day by mind, speech, hands, feet, belly or sex. I offer myself into the truth, into the light, into the deathless. Svaha.',
   'Not one mantra with a word swapped — three different texts, and reading them together shows why. The morning asks the Sun to absolve what was done BY NIGHT; the evening asks Agni to absolve what was done BY DAY; and each offers itself into a different light, the sun in the morning and the truth in the evening. Each sitting cleans the stretch of time behind it. Noon has neither a night nor a day behind it, only a morning of living, so its mantra is about food eaten and gifts taken instead.',
   array['sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 13. Punar Marjanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 13, 'purvangam', 'Punar Marjanam', 'புனர் மார்ஜனம்',
   'The same sprinkling as the Marjanam, with four further lines added in front of it and included in the same order.',
   'दधिक्राव्णो अकारिषं।
जिष्णोरश्वस्य वाजिनः।
सुरभि नो मुखा करत्।
प्रण आयूꣳषि तारिषत्॥
आपो हि ष्ठा मयोभुवः।
ता न ऊर्जे दधातन।
महे रणाय चक्षसे।
यो वः शिवतमो रसः।
तस्य भाजयतेह नः।
उशतीरिव मातरः।
तस्मा अरङ्गमाम वः।
यस्य क्षयाय जिन्वथ।
आपो जनयथा च नः।
ओं भूर्भुवःसुवः।',
   'ததிக்ராவ்ணோ அகாரிஷம்।
ஜிஷ்ணோரஶ்வஸ்ய வாஜிந꞉।
ஸுரபி நோ முகா கரத்।
ப்ரண ஆயூகும்ஷி தாரிஷத்॥
ஆபோ ஹி ஷ்டா மயோபுவ꞉।
தா ந ஊர்ஜே ததாதந।
மஹே ரணாய சக்ஷஸே।
யோ வ꞉ ஶிவதமோ ரஸ꞉।
தஸ்ய பாஜயதேஹ ந꞉।
உஶதீரிவ மாதர꞉।
தஸ்மா அரங்கமாம வ꞉।
யஸ்ய க்ஷயாய ஜிந்வத।
ஆபோ ஜநயதா ச ந꞉।
ஓம் பூர்புவ꞉ஸுவ꞉।',
   'dadhikrāvṇo akāriṣaṃ।
jiṣṇoraśvasya vājinaḥ।
surabhi no mukhā karat।
praṇa āyūgmṣi tāriṣat॥
āpo hi ṣṭhā mayobhuvaḥ।
tā na ūrje dadhātana।
mahe raṇāya cakṣase।
yo vaḥ śivatamo rasaḥ।
tasya bhājayateha naḥ।
uśatīriva mātaraḥ।
tasmā araṅgamāma vaḥ।
yasya kṣayāya jinvatha।
āpo janayathā ca naḥ।
oṃ bhūrbhuvaḥsuvaḥ।',
   'I have praised Dadhikravan, the swift victorious horse. May he make our mouths fragrant and lengthen our lives. Then the nine lines of the Marjanam again.',
   'Not a second washing. The book says plainly that only four mantras are new and the other ten are the same, and its own gloss reads the horse as Hayagriva, the swiftest and the ground of all learning. The request is physical and specific — make our mouths fragrant, lengthen our lives — said over the organ that is about to do the reciting.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 14. Arghya Pradanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 14, 'purvangam', 'Arghya Pradanam', 'அர்க்ய ப்ரதானம்',
   'Take water in both cupped hands and let it fall from the fingertips at the end of the mantra. THREE times in the morning and in the evening; TWICE at noon. Then do one pranayama.',
   'ओं भूर्भुवः सुवः।
तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि।
धियो यो नः प्रचोदयात्।',
   'ஓம் பூர்புவ꞉ ஸுவ꞉।
தத்ஸவிதுர்வரேண்யம் பர்கோ தேவஸ்ய தீமஹி।
தியோ யோ ந꞉ ப்ரசோதயாத்।',
   'oṃ bhūrbhuvaḥ suvaḥ।
tatsaviturvareṇyaṃ bhargo devasya dhīmahi।
dhiyo yo naḥ pracodayāt।',
   'The three worlds are Om. We meditate on the brilliance of that god who impels our thoughts.',
   'The first point in the rite where the sittings differ in the ACTION rather than the words. Everything before this changed its mantra and kept its gesture; here the Gayatri is the same at all three and the count is not. Two at noon and three at either end of the day — the offering is made to the sun at its junctures, and the middle of the day has only one juncture to mark.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 15. Prayashchitta Arghyam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 15, 'purvangam', 'Prayashchitta Arghyam', 'ப்ராயஶ்சித்த அர்க்யம்',
   'Hold the hands as for the Sankalpam and recite. Then offer arghyam once more, and pass water around the head reciting the closing line.',
   'कालातीत प्रायश्चित्तार्थम् अर्घ्यप्रदानम् करिष्ये।
ओं भूर्भुवः सुवः।',
   'காலாதீத ப்ராயஶ்சித்தார்தம் அர்க்யப்ரதாநம் கரிஷ்யே।
ஓம் பூர்புவ꞉ ஸுவ꞉।',
   'kālātīta prāyaścittārtham arghyapradānam kariṣye।
oṃ bhūrbhuvaḥ suvaḥ।',
   'For the expiation of the hour having passed, I shall make the offering of arghyam. The three worlds are Om.',
   'This is an apology for being late. Kalatita means the time has gone — the sitting was not kept at its own hour — and the remedy is one extra arghyam offered with a resolution that says so out loud. A rite performed punctually does not need it, and a book that prints it in the ordinary sequence is being realistic about how mornings go.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 16. Aikyanusandhanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 16, 'purvangam', 'Aikyanusandhanam', 'ஐக்யானுஸந்தானம்',
   'Pray silently to Aditya while reciting.',
   'असावादित्यो ब्रह्म-ब्रह्मैवाहमस्मि',
   'அஸாவாதித்யோ ப்ரஹ்ம-ப்ரஹ்மைவாஹமஸ்மி',
   'asāvādityo brahma-brahmaivāhamasmi',
   'That sun is Brahman. I am Brahman.',
   'Eight words, and the book marks them as the life line of the whole sandhyavandanam. Everything before this prepares the reciter; everything after it worships. Here the two are identified, and that is what keeps the rest of the rite from being sun-worship: the arghyam is poured towards the sun, the upasthanam addressed to it, the Gayatri is Savitr''s — and the reciter has just said the sun is Brahman, and so is he.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- 17. Navagraha Deva Tarpanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 17, 'purvangam', 'Navagraha Deva Tarpanam', 'நவக்ரஹ தேவ தர்ப்பணம்',
   'Take water in the hand and let it fall from the fingertips once after each name. Do Achamanam and Anga Vandanam once at the end.',
   null,
   null,
   null,
   'Water offered to the nine planets — Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu and Ketu — and then to the twelve names of Narayana, who is Time.',
   'Twenty-one offerings, and the second twelve are the calendar: the book says the Keshava names are Narayana in the form of time, one presiding over each month from Margashirsha to Kartika. So the step waters the planets that govern the sky and then the months that govern the year. These same twelve names have already been touched to the body in the Anga Vandanam; there they were bare and placed on limbs, here they take the accusative and a verb. One list, twice, doing two different things.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 1, 'आदित्यं तर्पयामि', 'ஆதித்யம் தர்பயாமி', 'ādityaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 2, 'सोमं तर्पयामि', 'ஸோமம் தர்பயாமி', 'somaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 3, 'अङ्गारकं तर्पयामि', 'அங்காரகம் தர்பயாமி', 'aṅgārakaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 4, 'बुधं तर्पयामि', 'புதம் தர்பயாமி', 'budhaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 5, 'बृहस्पतिं तर्पयामि', 'ப்ருஹஸ்பதிம் தர்பயாமி', 'bṛhaspatiṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 6, 'शुक्रं तर्पयामि', 'ஶுக்ரம் தர்பயாமி', 'śukraṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 7, 'शनैश्चरं तर्पयामि', 'ஶநைஶ்சரம் தர்பயாமி', 'śanaiścaraṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 8, 'राहुं तर्पयामि', 'ராஹும் தர்பயாமி', 'rāhuṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 9, 'केतुं तर्पयामि', 'கேதும் தர்பயாமி', 'ketuṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 10, 'केशवं तर्पयामि', 'கேஶவம் தர்பயாமி', 'keśavaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 11, 'नारायणं तर्पयामि', 'நாராயணம் தர்பயாமி', 'nārāyaṇaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 12, 'माधवं तर्पयामि', 'மாதவம் தர்பயாமி', 'mādhavaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 13, 'गोविन्दं तर्पयामि', 'கோவிந்தம் தர்பயாமி', 'govindaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 14, 'विष्णुं तर्पयामि', 'விஷ்ணும் தர்பயாமி', 'viṣṇuṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 15, 'मधुसूदनं तर्पयामि', 'மதுஸூதநம் தர்பயாமி', 'madhusūdanaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 16, 'त्रिविक्रमं तर्पयामि', 'த்ரிவிக்ரமம் தர்பயாமி', 'trivikramaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 17, 'वामनं तर्पयामि', 'வாமநம் தர்பயாமி', 'vāmanaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 18, 'श्रीधरं तर्पयामि', 'ஶ்ரீதரம் தர்பயாமி', 'śrīdharaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 19, 'हृषीकेशं तर्पयामि', 'ஹ்ருஷீகேஶம் தர்பயாமி', 'hṛṣīkeśaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 20, 'पद्मनाभं तर्पयामि', 'பத்மநாபம் தர்பயாமி', 'padmanābhaṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit)
select id, 21, 'दामोदरं तर्पयामि', 'தாமோதரம் தர்பயாமி', 'dāmodaraṃ tarpayāmi'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 17;

-- 18. Conclusion of the First Part
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 18, 'purvangam', 'Conclusion of the First Part', 'முதல் பகுதி நிறைவு',
   'Take water in the hand and pour it onto the plate as an offering while reciting.',
   'मया कृतं इदं सर्वं कर्म ओं तत् सत् ब्रह्मार्पणमस्तु',
   'மயா க்ருதம் இதம் ஸர்வம் கர்ம ஓம் தத் ஸத் ப்ரஹ்மார்பணமஸ்து',
   'mayā kṛtaṃ idaṃ sarvaṃ karma oṃ tat sat brahmārpaṇamastu',
   'Whatever I have done, all of it — om tat sat — let it be an offering to Brahman.',
   'The book seals its own half here and says so: the first part of the sandhyavandanam ends, and then iti praatah sandhyaavandanam. What follows is the japa, which has its own sankalpa and its own name. The seal hands the work back rather than claiming it, and the japa half will end with the same words.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.16-27, photographed page');

-- --- assert ------------------------------------------------------------------
do $$
declare n int;
begin
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam';
  if n <> 18 then raise exception 'expected 18 steps, found %', n; end if;

  -- Step numbers dense from 1, which the app relies on for the jump list.
  select count(*) into n from (
    select step_number, row_number() over (order by step_number) as rn
      from public.pooja_steps where pooja_id = 'sandhyavandanam'
  ) t where t.step_number <> t.rn;
  if n > 0 then raise exception '% step(s) are not numbered 1..n', n; end if;

  -- Every sitting is walkable end to end.
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and 'pratah' = any(modes);
  if n <> 14 then raise exception 'pratah has % steps, expected 14', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and 'madhyahnika' = any(modes);
  if n <> 14 then raise exception 'madhyahnika has % steps, expected 14', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and 'sayam' = any(modes);
  if n <> 14 then raise exception 'sayam has % steps, expected 14', n; end if;

  -- The misprints are gone and the corrections are present. Asserted on the
  -- stored rows, not on the generator's own variables.
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and mantra_sanskrit like '%यो वशिशवतमो रसः%';
  if n > 0 then raise exception '% step(s) still carry the misprint यो वशिशवतमो रसः', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and mantra_sanskrit like '%ओं भूर्भुवस्तुवः।%';
  if n > 0 then raise exception '% step(s) still carry the misprint ओं भूर्भुवस्तुवः।', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and mantra_sanskrit like '%त्रिविक्रमं तर्पयामिा%';
  if n > 0 then raise exception '% step(s) still carry the misprint त्रिविक्रमं तर्पयामिा', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and mantra_sanskrit like '%यो वः शिवतमो रसः%';
  if n <> 2 then raise exception 'expected 2 steps with the corrected apo hi shtha line, found %', n; end if;

  -- The tarpanam is twenty-one offerings, and none of them is a bare number
  -- the way the nitya tarpanam shipped in 0037.
  select count(*) into n from public.archana_items a
    join public.pooja_steps s on s.id = a.pooja_step_id
   where s.pooja_id = 'sandhyavandanam' and s.step_title_en = 'Navagraha Deva Tarpanam';
  if n <> 21 then raise exception 'tarpanam has % offerings, expected 21', n; end if;
  select count(*) into n from public.archana_items a
    join public.pooja_steps s on s.id = a.pooja_step_id
   where s.pooja_id = 'sandhyavandanam' and a.invoked_name_deva !~ '[ऀ-ॿ]';
  if n > 0 then raise exception '% offering(s) carry no Devanagari', n; end if;

  -- No Devanagari leaked into the Tamil, which is the check that caught the
  -- gm nasal. Devanagari Extended included, which the original range missed.
  --
  -- THE DANDAS ARE STRIPPED FIRST. U+0964 and U+0965 sit inside the Devanagari
  -- block, but _tamil.mjs protects them deliberately: they are shared
  -- punctuation rather than letters, and every Tamil mantra in this app
  -- already carries them. The first draft of this assertion did not strip
  -- them and failed nine of eighteen steps over punctuation that belongs
  -- there. proofread has excluded them since the visarga gate was added.
  select count(*) into n from public.pooja_steps
   where pooja_id = 'sandhyavandanam'
     and translate(coalesce(mantra_tamil, ''), '।॥', '') ~ '[ऀ-ॿ꣠-ꣿ]';
  if n > 0 then raise exception '% Tamil mantra(s) carry Devanagari', n; end if;

  -- Still planned. 0049 publishes it.
  select count(*) into n from public.poojas where id = 'sandhyavandanam' and status = 'planned';
  if n <> 1 then raise exception 'sandhyavandanam should still be planned until 0049'; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
