-- =============================================================================
-- 0049_sandhyavandanam_part_two.sql
--
-- GENERATED by scripts/build-sandhyavandanam-part-two.mjs. Do not hand-edit.
--
-- The japa half, book pages 28 to 48: 27 steps from the Namaskara mantras
-- to the sprinkling of the place of japa, ending at the book's own colophon,
-- iti trikaala sandhyaagaayatreejapavidhih. The rite is published here.
--
-- IT ALSO REPAIRS SOMETHING 0048 SHIPPED WITHOUT. All eighteen of part one's
-- steps went in with instruction_ta empty. Every other pooja in this app has
-- Tamil on every step, and proofread said so the moment 0048 was run. The
-- lesson was already recorded in 0033 -- diff a new step's column set against
-- an existing step of the SAME pooja, not against the schema -- and was there
-- to be read. Backfilled here rather than in a file of its own, so the rite is
-- whole in one place. The generator now refuses to emit a step without Tamil,
-- which is the only change that stops it recurring.
--
-- TWO MORE MISPRINTS CORRECTED:
--
--   सायं मन्ध्या गायत्री  ->  सायं सन्ध्या गायत्री
--   Book page 31 sets मन्ध्या in the evening row of the japa sankalpa -- a स
--   as म. The morning row spells सन्ध्या correctly, the roman beside the
--   evening row reads "saayam sandhyaa-gaayatree", and page 37 sets the same
--   word correctly.
--
--   भूरादिससव्याहृतीनाम्  ->  भूरादिसप्तव्याहृतीनाम्
--   Book page 32 has सस where it needs सप्त. The roman beside it reads
--   "bhooraadi saptavyaahrteenaam" and the English gloss on the same page
--   says "The seven vyahrutis beginning with Bhu".
--
-- ABHIVADANAM IS PRINTED AS THE BOOK PRINTS IT, blanks and all. It is not a
-- form the app fills in: the book sets the Apastamba sutra and the Yajus
-- recension in type and leaves dotted rules for the pravaras, the gotra and
-- the name, because whoever is reciting knows their own.
-- =============================================================================

begin;

-- Part one's missing Tamil instructions. Keyed on the title, which is stable.
update public.pooja_steps set instruction_ta = 'கிழக்கு அல்லது வடக்கு நோக்கி அமரவும். வலது கையின் ஆட்காட்டி விரலை கட்டைவிரலுடன் சேர்த்து, மற்ற மூன்று விரல்களையும் மடக்கி உள்ளங்கையில் ஒரு உத்தரிணி நீர் நிற்குமாறு வைக்கவும். மூன்று நாமங்களிலும் ஒவ்வொரு முறை நீரை உள்கொள்ளவும். ஆசமனமும் அங்கவந்தனமும் தொடக்கத்தில் மும்முறை செய்யப்படும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Achamanam';
update public.pooja_steps set instruction_ta = 'ஆறு ஜோடி நாமங்கள்; ஒவ்வொன்றுக்கும் குறிக்கப்பட்ட விரலால் உடலின் அந்தந்த இடத்தைத் தொடவும் — கட்டைவிரலால் கன்னங்கள், மோதிர விரலால் கண்கள், ஆட்காட்டி விரலால் நாசிகள், சுண்டு விரலால் காதுகள், நடுவிரலால் தோள்கள், அனைத்து விரல்களாலும் நாபியும் தலையும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Anga Vandanam';
update public.pooja_steps set instruction_ta = 'நெற்றியின் இரு பக்கங்களையும் முஷ்டிகளால் மெல்ல ஐந்து முறை தட்டியபடி சொல்லவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Vighneshwara Dhyanam';
update public.pooja_steps set instruction_ta = 'ஆட்காட்டி, நடுவிரல்களை மடக்கவும். வலது நாசியைக் கட்டைவிரலாலும், இடது நாசியை மோதிர, சுண்டு விரல்களாலும் அடைக்கவும். மந்திரம் மூன்று பகுதிகள்: இடது நாசி வழியாக மூச்சை இழுத்தபடி "ஓம் பூஃ" முதல் "ஓகும் ஸத்யம்" வரை; மூச்சை நிறுத்தி "ஓம் தத் ஸவிதுஃ" முதல் "ப்ரசோதயாத்" வரை; வலது நாசி வழியாக வெளியிட்டபடி "ஓம் ஆபோ ஜ்யோதி" முதல் "பூர்புவஸ்ஸுவரோம்" வரை. இதுவே ஒரு ப்ராணாயாமம்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Pranayamam';
update public.pooja_steps set instruction_ta = 'வலது உள்ளங்கையை இடது உள்ளங்கையின் மேல் வைத்து, இரண்டையும் வலது தொடையில் வைத்தபடி சொல்லவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Sankalpam — morning';
update public.pooja_steps set instruction_ta = 'வலது உள்ளங்கையை இடது உள்ளங்கையின் மேல் வைத்து, இரண்டையும் வலது தொடையில் வைத்தபடி சொல்லவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Sankalpam — noon';
update public.pooja_steps set instruction_ta = 'வலது உள்ளங்கையை இடது உள்ளங்கையின் மேல் வைத்து, இரண்டையும் வலது தொடையில் வைத்தபடி சொல்லவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Sankalpam — evening';
update public.pooja_steps set instruction_ta = 'உத்தரிணியில் நீர் எடுத்து, வலது மோதிர விரலை அதில் வைத்திருக்கவும். மந்திரம் முடியும்போது நீரின் மேல் ஓம் எழுதி, அதை நெற்றியில் இடவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Jala Prarthana';
update public.pooja_steps set instruction_ta = 'முதல் ஏழு வரிகளிலும் மோதிர விரலால் தலையில் நீர் தெளிக்கவும். எட்டாவது வரியில் வலது, இடது தொடைகளைத் தொடவும். ஒன்பதாவது வரியில் மீண்டும் தெளிக்கவும். பின் வலது உள்ளங்கையில் நீர் எடுத்து தலையைச் சுற்றி வலமாகச் சுழற்றவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Marjanam';
update public.pooja_steps set instruction_ta = 'உள்ளங்கையில் ஒரு உத்தரிணி நீர் எடுத்து, மந்திரம் முடிந்ததும் அந்த நீரைப் பருகவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Apaam Prashanam — morning';
update public.pooja_steps set instruction_ta = 'உள்ளங்கையில் ஒரு உத்தரிணி நீர் எடுத்து, மந்திரம் முடிந்ததும் அந்த நீரைப் பருகவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Apaam Prashanam — noon';
update public.pooja_steps set instruction_ta = 'உள்ளங்கையில் ஒரு உத்தரிணி நீர் எடுத்து, மந்திரம் முடிந்ததும் அந்த நீரைப் பருகவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Apaam Prashanam — evening';
update public.pooja_steps set instruction_ta = 'மார்ஜனத்தில் செய்த அதே தெளித்தல்; முன்னால் நான்கு வரிகள் சேர்க்கப்படுகின்றன, அவையும் அதே வரிசையில் அடங்கும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Punar Marjanam';
update public.pooja_steps set instruction_ta = 'இரு உள்ளங்கைகளிலும் நீர் ஏந்தி, மந்திரம் முடியும்போது விரல் நுனிகள் வழியே கீழே விடவும். காலையிலும் மாலையிலும் மூன்று முறை; உச்சிப்போதில் இரண்டு முறை. பின் ஒரு ப்ராணாயாமம்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Arghya Pradanam';
update public.pooja_steps set instruction_ta = 'ஸங்கல்பத்தில் செய்தது போல கைகளை வைத்துச் சொல்லவும். பின் மீண்டும் ஒரு முறை அர்க்யம் கொடுத்து, இறுதி வரியைச் சொல்லியபடி தலையைச் சுற்றி நீர் சுழற்றவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Prayashchitta Arghyam';
update public.pooja_steps set instruction_ta = 'ஆதித்யனை மௌனமாக த்யானித்தபடி சொல்லவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Aikyanusandhanam';
update public.pooja_steps set instruction_ta = 'கையில் நீர் எடுத்து, ஒவ்வொரு நாமத்திற்குப் பின்னும் விரல் நுனிகள் வழியே ஒரு முறை விடவும். இறுதியில் ஆசமனமும் அங்கவந்தனமும் ஒரு முறை செய்யவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Navagraha Deva Tarpanam';
update public.pooja_steps set instruction_ta = 'கையில் நீர் எடுத்து, சொல்லியபடி தாம்பாளத்தில் அர்ப்பணமாக விடவும்.', updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Conclusion of the First Part';

-- Part two. Idempotent: these step numbers are replaced, part one is untouched.
delete from public.archana_items where pooja_step_id in (
  select id from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number > 18);
delete from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number > 18;

-- 19. Namaskara Mantras
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 19, 'pradhana', 'Namaskara Mantras', 'நமஸ்கார மந்திரங்கள்',
   'Stand facing east with folded hands and prostrate at the end of each of the two verses. The book asks for the ten postures of Surya Namaskara here, breathing in at the start of each and out at the end: stand erect, elbows at chest height; raise the folded hands over the head with the elbows straight; bend forward and place both palms flat on the floor with the knees straight; stretch both legs back onto the toes with the knees raised; straighten above the waist and lift the head, arms straight on the palms; lie flat, folding the elbows; stretch both hands forward on the floor, clasped. Then return through postures three, two and one to complete one namaskara. The book says to learn these from a teacher.',
   'கிழக்கு நோக்கி நின்று, கைகூப்பி, இரு ஸ்லோகங்களின் இறுதியிலும் நமஸ்காரம் செய்யவும். நூல் இங்கு சூர்ய நமஸ்காரத்தின் பத்து நிலைகளைக் கூறுகிறது; ஒவ்வொரு நிலையின் தொடக்கத்தில் மூச்சை இழுத்து, முடிவில் வெளியிடவும். இவற்றை யோகாசிரியரிடம் கற்பது நல்லது என்று நூலே கூறுகிறது.',
   'नमो ब्रह्मण्यदेवाय गोब्राह्मणहिताय च।
जगद्धिताय कृष्णाय गोविन्दाय नमो नमः॥
आ ब्रह्मलोकादा शेषात् आलोकालोकपर्वतात्।
ये वसन्ति द्विजा देवाः तेभ्यो नित्यं नमो नमः॥',
   'நமோ ப்ரஹ்மண்யதேவாய கோப்ராஹ்மணஹிதாய ச।
ஜகத்திதாய க்ருஷ்ணாய கோவிந்தாய நமோ நம꞉॥
ஆ ப்ரஹ்மலோகாதா ஶேஷாத் ஆலோகாலோகபர்வதாத்।
யே வஸந்தி த்விஜா தேவா꞉ தேப்யோ நித்யம் நமோ நம꞉॥',
   'namo brahmaṇyadevāya gobrāhmaṇahitāya ca।
jagaddhitāya kṛṣṇāya govindāya namo namaḥ॥
ā brahmalokādā śeṣāt ālokālokaparvatāt।
ye vasanti dvijā devāḥ tebhyo nityaṃ namo namaḥ॥',
   'Salutation to the god who is the good of the brahmins and the cattle, to Krishna, to Govinda, again and again. From the world of Brahma to the last of things, as far as the Lokaloka mountain — to the twice-born and the gods who dwell there, salutation always.',
   'Part one was done sitting, with water. Part two begins by standing up. The book does not merely say prostrate: it gives the ten postures with the breath assigned to each, and then admits they are properly learnt from a teacher. The two verses widen as they go — the first salutes one deity by name, the second everything that exists.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 20. Prarthana
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 20, 'pradhana', 'Prarthana', 'ப்ரார்த்தனை',
   'Two verses asking the spirits of the place for room before the japa begins.',
   'ஜபம் தொடங்கும் முன், அவ்விடத்தின் பூதங்களிடம் இடம் கேட்கும் இரு ஸ்லோகங்கள்.',
   'अपसर्पन्तु ते भूता ये भूता भुवि संस्थिताः।
ये भूता विघ्नकर्तारः ते गच्छन्तु शिवाज्ञया॥
उग्रभूतपिशाचाद्याः ये च वै भूमिधारकाः।
एतेषामविरोधेन ब्रह्मकर्म समारभे॥',
   'அபஸர்பந்து தே பூதா யே பூதா புவி ஸம்ஸ்திதா꞉।
யே பூதா விக்நகர்தார꞉ தே கச்சந்து ஶிவாஜ்ஞயா॥
உக்ரபூதபிஶாசாத்யா꞉ யே ச வை பூமிதாரகா꞉।
ஏதேஷாமவிரோதேந ப்ரஹ்மகர்ம ஸமாரபே॥',
   'apasarpantu te bhūtā ye bhūtā bhuvi saṃsthitāḥ।
ye bhūtā vighnakartāraḥ te gacchantu śivājñayā॥
ugrabhūtapiśācādyāḥ ye ca vai bhūmidhārakāḥ।
eteṣāmavirodhena brahmakarma samārabhe॥',
   'May those beings settled on the earth who make obstruction depart, by Shiva''s order. And the fierce spirits and pishachas who hold the earth up — without their opposition, may I begin the brahma karma.',
   'The second verse is the interesting half. The first tells obstructing spirits to leave. The second names the fierce ones who SUSTAIN the earth and asks only to proceed without their opposition. They are not driven off; they hold the ground up, and the reciter is asking to work on ground that is theirs.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 21. Asana Mantra
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 21, 'pradhana', 'Asana Mantra', 'ஆஸன மந்திரம்',
   'Sit down for the japa. Touch the head, the nostrils and the chest as the rishi, the metre and the deity are named, then pray with folded hands. With the ring finger touch the floor and then the point between the eyebrows while reciting the verse.',
   'ஜபத்திற்காக அமரவும். ரிஷி, சந்தஸ், தேவதை சொல்லும்போது முறையே தலை, நாசி, மார்பைத் தொடவும்; பின் கைகூப்பி வேண்டவும். மோதிர விரலால் முதலில் தரையையும் பின் புருவ மத்தியையும் தொட்டபடி ஸ்லோகத்தைச் சொல்லவும்.',
   'आसन महामन्त्रस्य–
पृथिव्या मेरुपृष्ठ ऋषिः
अतलं छन्दः
कूर्मो देवता,
आसने विनियोगः
पृथ्वि त्वया धृता लोकाः देवि त्वं विष्णुना धृता।
त्वं च धारय मां देवि पवित्रं कुरु चासनम्॥',
   'ஆஸந மஹாமந்த்ரஸ்ய–
ப்ருதிவ்யா மேருப்ருஷ்ட ருஷி꞉
அதலம் சந்த꞉
கூர்மோ தேவதா,
ஆஸநே விநியோக꞉
ப்ருத்வி த்வயா த்ருதா லோகா꞉ தேவி த்வம் விஷ்ணுநா த்ருதா।
த்வம் ச தாரய மாம் தேவி பவித்ரம் குரு சாஸநம்॥',
   'āsana mahāmantrasya–
pṛthivyā merupṛṣṭha ṛṣiḥ
atalaṃ chandaḥ
kūrmo devatā,
āsane viniyogaḥ
pṛthvi tvayā dhṛtā lokāḥ devi tvaṃ viṣṇunā dhṛtā।
tvaṃ ca dhāraya māṃ devi pavitraṃ kuru cāsanam॥',
   'Earth, by you the worlds are borne, and you are borne by Vishnu. Bear me too, goddess, and make this seat pure.',
   'The same verse the app already carries as Asana Pooja elsewhere, with a fuller frame around it here: the mantra is given a rishi, a metre and a deity of its own, each touched to a different part of the body as it is named. You consecrate the seat while still outside it, and only then take your place.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 22. Vighneshwara Dhyanam (japa)
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 22, 'pradhana', 'Vighneshwara Dhyanam (japa)', 'விக்னேஶ்வர த்யானம் (ஜபம்)',
   'Tap both temples gently with the knuckles five times while reciting.',
   'நெற்றியின் இரு பக்கங்களையும் முஷ்டிகளால் மெல்ல ஐந்து முறை தட்டியபடி சொல்லவும்.',
   'शुक्लाम्बरधरं विष्णुं शशिवर्णं चतुर्भुजम्।
प्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशान्तये॥',
   'ஶுக்லாம்பரதரம் விஷ்ணும் ஶஶிவர்ணம் சதுர்புஜம்।
ப்ரஸந்நவதநம் த்யாயேத் ஸர்வவிக்நோபஶாந்தயே॥',
   'śuklāmbaradharaṃ viṣṇuṃ śaśivarṇaṃ caturbhujam।
prasannavadanaṃ dhyāyet sarvavighnopaśāntaye॥',
   'He who wears white, who pervades all, moon-coloured and four-armed, with a face at ease — meditate on him, for the quieting of every obstacle.',
   'The same verse that opened part one, said again. Both halves of the rite begin by tapping the temples for Ganesha, which is why the app carries it twice rather than once: it is two moments, not one repeated for emphasis.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 23. Pranayamam (japa)
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 23, 'pradhana', 'Pranayamam (japa)', 'ப்ராணாயாமம் (ஜபம்)',
   'The same breathing as before — in through the left through the seven worlds, held through the Gayatri, out through the right through om aapo jyoti.',
   'முன்பு போலவே மூச்சுப்பயிற்சி — இடது நாசி வழியே ஏழு லோகங்கள், மூச்சை நிறுத்தி காயத்ரி, வலது நாசி வழியே ஓம் ஆபோ ஜ்யோதி.',
   'ओं भूः ओं भुवः ओꣳ सुवः ओं महः ओं जनः ओं तपः ओꣳ सत्यम्
ओं तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि। धियो यो नः प्रचोदयात्।
ओमापो ज्योतीरसोऽमृतं ब्रह्म भूर्भुवः सुवरोम्॥',
   'ஓம் பூ꞉ ஓம் புவ꞉ ஓகும் ஸுவ꞉ ஓம் மஹ꞉ ஓம் ஜந꞉ ஓம் தப꞉ ஓகும் ஸத்யம்
ஓம் தத்ஸவிதுர்வரேண்யம் பர்கோ தேவஸ்ய தீமஹி। தியோ யோ ந꞉ ப்ரசோதயாத்।
ஓமாபோ ஜ்யோதீரஸோம்ருதம் ப்ரஹ்ம பூர்புவ꞉ ஸுவரோம்॥',
   'oṃ bhūḥ oṃ bhuvaḥ ogm suvaḥ oṃ mahaḥ oṃ janaḥ oṃ tapaḥ ogm satyam
oṃ tatsaviturvareṇyaṃ bhargo devasya dhīmahi। dhiyo yo naḥ pracodayāt।
omāpo jyotīraso''mṛtaṃ brahma bhūrbhuvaḥ suvarom॥',
   'The seven worlds are Om; we meditate on the brilliance of the Creator; the waters, the light, the essence and the deathless are Brahman, bhuh bhuvah suvah, Om.',
   'The book gives the mantra again and refers back to page 18 for the action rather than reprinting it. It cross-references itself the same way the Giri Nitya Pooja book does for its purvangam, and for the same reason: one description, corrected in one place.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 24. Japa Sankalpam — morning
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 24, 'pradhana', 'Japa Sankalpam — morning', 'ஜப ஸங்கல்பம் — காலை',
   'Hold the hands as for the first Sankalpam and recite.',
   'முதல் ஸங்கல்பத்தில் செய்தது போல கைகளை வைத்துச் சொல்லவும்.',
   'ममोपात्त समस्त दुरितक्षयद्वारा श्रीपरमेश्वरप्रीत्यर्थं
प्रातस्सन्ध्यागायत्रीमहामन्त्रजपं करिष्ये।',
   'மமோபாத்த ஸமஸ்த துரிதக்ஷயத்வாரா ஶ்ரீபரமேஶ்வரப்ரீத்யர்தம்
ப்ராதஸ்ஸந்த்யாகாயத்ரீமஹாமந்த்ரஜபம் கரிஷ்யே।',
   'mamopātta samasta duritakṣayadvārā śrīparameśvaraprītyarthaṃ
prātassandhyāgāyatrīmahāmantrajapaṃ kariṣye।',
   'That all the wrong accumulated in me may be destroyed, and so that the Supreme may be pleased: I shall perform the japa of the great Gayatri mantra of the morning.',
   'The rite''s second resolution, and it differs from the first in its object: there the goddess Sandhya was worshipped, here the japa is performed. All three sittings take karishye this time, where the first sankalpa gave upasishye to the morning and evening and karishye only to noon — because japa is a thing done at every hour.',
   array['pratah']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 25. Japa Sankalpam — noon
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 25, 'pradhana', 'Japa Sankalpam — noon', 'ஜப ஸங்கல்பம் — உச்சி',
   'Hold the hands as for the first Sankalpam and recite.',
   'முதல் ஸங்கல்பத்தில் செய்தது போல கைகளை வைத்துச் சொல்லவும்.',
   'ममोपात्त समस्त दुरितक्षयद्वारा श्रीपरमेश्वरप्रीत्यर्थं
माध्याह्निकगायत्रीमहामन्त्रजपं करिष्ये',
   'மமோபாத்த ஸமஸ்த துரிதக்ஷயத்வாரா ஶ்ரீபரமேஶ்வரப்ரீத்யர்தம்
மாத்யாஹ்நிககாயத்ரீமஹாமந்த்ரஜபம் கரிஷ்யே',
   'mamopātta samasta duritakṣayadvārā śrīparameśvaraprītyarthaṃ
mādhyāhnikagāyatrīmahāmantrajapaṃ kariṣye',
   'That all the wrong accumulated in me may be destroyed, and so that the Supreme may be pleased: I shall perform the japa of the great Gayatri mantra of the noon.',
   'The rite''s second resolution, and it differs from the first in its object: there the goddess Sandhya was worshipped, here the japa is performed. All three sittings take karishye this time, where the first sankalpa gave upasishye to the morning and evening and karishye only to noon — because japa is a thing done at every hour.',
   array['madhyahnika']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 26. Japa Sankalpam — evening
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 26, 'pradhana', 'Japa Sankalpam — evening', 'ஜப ஸங்கல்பம் — மாலை',
   'Hold the hands as for the first Sankalpam and recite.',
   'முதல் ஸங்கல்பத்தில் செய்தது போல கைகளை வைத்துச் சொல்லவும்.',
   'ममोपात्त समस्त दुरितक्षयद्वारा श्रीपरमेश्वरप्रीत्यर्थं
सायं सन्ध्या गायत्री महा मन्त्र जपं करिष्ये',
   'மமோபாத்த ஸமஸ்த துரிதக்ஷயத்வாரா ஶ்ரீபரமேஶ்வரப்ரீத்யர்தம்
ஸாயம் ஸந்த்யா காயத்ரீ மஹா மந்த்ர ஜபம் கரிஷ்யே',
   'mamopātta samasta duritakṣayadvārā śrīparameśvaraprītyarthaṃ
sāyaṃ sandhyā gāyatrī mahā mantra japaṃ kariṣye',
   'That all the wrong accumulated in me may be destroyed, and so that the Supreme may be pleased: I shall perform the japa of the great Gayatri mantra of the evening.',
   'The rite''s second resolution, and it differs from the first in its object: there the goddess Sandhya was worshipped, here the japa is performed. All three sittings take karishye this time, where the first sankalpa gave upasishye to the morning and evening and karishye only to noon — because japa is a thing done at every hour.',
   array['sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 27. Pranava Japa
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 27, 'pradhana', 'Pranava Japa', 'ப்ரணவ ஜபம்',
   'Touch the head, the nostrils and the chest at each of the two sets, as the rishi, the metre and the deity are named. Then do ten pranayamas.',
   'இரு தொகுதிகளிலும் ரிஷி, சந்தஸ், தேவதை சொல்லும்போது முறையே தலை, நாசி, மார்பைத் தொடவும். பின் பத்து ப்ராணாயாமம் செய்யவும்.',
   'प्रणवस्य ऋषिः ब्रह्मा।
देवी गायत्री छन्दः।
परमात्मा देवता
भूरादिसप्तव्याहृतीनाम् अत्रि भृगु कुत्स वसिष्ठ गौतम काश्यप आङ्गिरस ऋषयः।
गायत्री उष्णिग् अनुष्टुप् बृहती पङ्क्ति त्रिष्टुप् जगत्यः छन्दांसि।
अग्नि वायु अर्क वागीश वरुण इन्द्र विश्वेदेवा देवताः।',
   'ப்ரணவஸ்ய ருஷி꞉ ப்ரஹ்மா।
தேவீ காயத்ரீ சந்த꞉।
பரமாத்மா தேவதா
பூராதிஸப்தவ்யாஹ்ருதீநாம் அத்ரி ப்ருகு குத்ஸ வஸிஷ்ட கௌதம காஶ்யப ஆங்கிரஸ ருஷய꞉।
காயத்ரீ உஷ்ணிக் அநுஷ்டுப் ப்ருஹதீ பங்க்தி த்ரிஷ்டுப் ஜகத்ய꞉ சந்தாம்ஸி।
அக்நி வாயு அர்க வாகீஶ வருண இந்த்ர விஶ்வேதேவா தேவதா꞉।',
   'praṇavasya ṛṣiḥ brahmā।
devī gāyatrī chandaḥ।
paramātmā devatā
bhūrādisaptavyāhṛtīnām atri bhṛgu kutsa vasiṣṭha gautama kāśyapa āṅgirasa ṛṣayaḥ।
gāyatrī uṣṇig anuṣṭup bṛhatī paṅkti triṣṭup jagatyaḥ chandāṃsi।
agni vāyu arka vāgīśa varuṇa indra viśvedevā devatāḥ।',
   'For the Pranava: Brahma is the rishi, Devi Gayatri the metre, Paramatman the deity. For the seven vyahritis beginning with bhuh: the rishis are Atri, Bhrigu, Kutsa, Vasishtha, Gautama, Kashyapa and Angirasa; the metres Gayatri, Ushnik, Anushtup, Brihati, Pankti, Trishtup and Jagati; the deities Agni, Vayu, Arka, Vagisha, Varuna, Indra and the Vishvedevas.',
   'Four lists of seven, given in parallel and left for the reader to line up: each world has its own seer, its own metre and its own god, and the pranayama walks up through all seven. Ten repetitions here where the earlier pranayama asked for one — the second place in the rite where a number rather than a text distinguishes one performance from another.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 28. Gayatri Avahanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 28, 'pradhana', 'Gayatri Avahanam', 'காயத்ரி ஆவாஹனம்',
   'Touch head, nostrils and chest again for the rishi, metre and deity. Then hold both palms together in front of the face as though looking into them, and turn them inwards at the end of each of the three invocations — Gayatri, Savitri, Sarasvati.',
   'ரிஷி, சந்தஸ், தேவதைக்காக மீண்டும் தலை, நாசி, மார்பைத் தொடவும். பின் இரு உள்ளங்கைகளையும் முகத்திற்கு முன் சேர்த்து, அவற்றுள் பார்ப்பது போல வைத்து, காயத்ரி, ஸாவித்ரி, ஸரஸ்வதி என்ற மூன்று ஆவாஹனங்களின் இறுதியிலும் உள்நோக்கித் திருப்பவும்.',
   'आयात्विति अनुवाकस्य वामदेव ऋषिः।
अनुष्टुप् छन्दः।
गायत्री देवता।
आयातु वरदा देवी अक्षरं ब्रह्मसम्मितम्।
गायत्रीं छन्दसां मातेदं ब्रह्म जुषस्व नः॥
ओजोऽसि सहोऽसि बलमसि भ्राजोऽसि देवानां धाम नामासि
विश्वमसि विश्वायुः सर्वमसि सर्वायुः अभिभूरों
गायत्रीमावाहयामि। सावित्रीमावाहयामि। सरस्वतीमावाहयामि।',
   'ஆயாத்விதி அநுவாகஸ்ய வாமதேவ ருஷி꞉।
அநுஷ்டுப் சந்த꞉।
காயத்ரீ தேவதா।
ஆயாது வரதா தேவீ அக்ஷரம் ப்ரஹ்மஸம்மிதம்।
காயத்ரீம் சந்தஸாம் மாதேதம் ப்ரஹ்ம ஜுஷஸ்வ ந꞉॥
ஓஜோஸி ஸஹோஸி பலமஸி ப்ராஜோஸி தேவாநாம் தாம நாமாஸி
விஶ்வமஸி விஶ்வாயு꞉ ஸர்வமஸி ஸர்வாயு꞉ அபிபூரோம்
காயத்ரீமாவாஹயாமி। ஸாவித்ரீமாவாஹயாமி। ஸரஸ்வதீமாவாஹயாமி।',
   'āyātviti anuvākasya vāmadeva ṛṣiḥ।
anuṣṭup chandaḥ।
gāyatrī devatā।
āyātu varadā devī akṣaraṃ brahmasammitam।
gāyatrīṃ chandasāṃ mātedaṃ brahma juṣasva naḥ॥
ojo''si saho''si balamasi bhrājo''si devānāṃ dhāma nāmāsi
viśvamasi viśvāyuḥ sarvamasi sarvāyuḥ abhibhūroṃ
gāyatrīmāvāhayāmi। sāvitrīmāvāhayāmi। sarasvatīmāvāhayāmi।',
   'Come, boon-giving goddess, syllable equal to Brahman. Gayatri, mother of the metres, be pleased with this Brahman of ours. You are vigour, you are strength, you are might, you are splendour, you are the dwelling and the name of the gods. You are all, you are all life. I invoke Gayatri. I invoke Savitri. I invoke Sarasvati.',
   'One goddess called in three aspects, and the invocation is finished by a movement of the hands rather than by an offering. Elsewhere in this app a deity is invoked into an image or a kalasham; here she is invoked into the reciter''s own cupped palms.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 29. Gayatri Nyasa
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 29, 'pradhana', 'Gayatri Nyasa', 'காயத்ரி ந்யாஸம்',
   'Touch the head, the nostrils and the chest as each is named.',
   'ஒவ்வொன்றையும் சொல்லும்போது முறையே தலை, நாசி, மார்பைத் தொடவும்.',
   'सावित्र्या-ऋषिः विश्वामित्रः
निचृत् गायत्री छन्दः
सविता देवता।',
   'ஸாவித்ர்யா-ருஷி꞉ விஶ்வாமித்ர꞉
நிச்ருத் காயத்ரீ சந்த꞉
ஸவிதா தேவதா।',
   'sāvitryā-ṛṣiḥ viśvāmitraḥ
nicṛt gāyatrī chandaḥ
savitā devatā।',
   'For the Savitri: Vishvamitra is the rishi, Nichrit-Gayatri the metre, Savitr the deity.',
   'The fourth nyasa in five pages, identical in shape to the asana, the pranava and the avahanam and different in content each time. This one names the credentials of the mantra about to be repeated a hundred and eight times.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 30. Dhyanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 30, 'pradhana', 'Dhyanam', 'த்யானம்',
   'Contemplate a single form of the goddess, whichever is most cherished, while reciting.',
   'மிகவும் விருப்பமான ஒரு வடிவத்தை மனத்தில் நிறுத்தி த்யானித்தபடி சொல்லவும்.',
   'मुक्ताविद्रुमहेमनीलधवलच्छायैर्मुखैस्त्रीक्षणैः
युक्तामिन्दुकलानिबद्धरत्नमकुटां तत्वार्थवर्णात्मिकाम्।
गायत्रीं वरदाभयाङ्कुशकशाः शुभ्रं कपालं गदां
शङ्खं चक्रमथारविन्दयुगळं हस्तैर्वहन्तीं भजे॥
अक्षस्रक्कुण्डिका हस्तां शुद्धस्फटिक निर्मलां
सर्व विद्यामयीं वन्दे गायत्री वेदमातरम्
यो देवः सविताऽस्माकं धियो धर्मादिगोचराः।
प्रेरयेत् तस्य यद्भर्गः तद्वरेण्यमुपास्महे॥',
   'முக்தாவித்ருமஹேமநீலதவலச்சாயைர்முகைஸ்த்ரீக்ஷணை꞉
யுக்தாமிந்துகலாநிபத்தரத்நமகுடாம் தத்வார்தவர்ணாத்மிகாம்।
காயத்ரீம் வரதாபயாங்குஶகஶா꞉ ஶுப்ரம் கபாலம் கதாம்
ஶங்கம் சக்ரமதாரவிந்தயுகளம் ஹஸ்தைர்வஹந்தீம் பஜே॥
அக்ஷஸ்ரக்குண்டிகா ஹஸ்தாம் ஶுத்தஸ்படிக நிர்மலாம்
ஸர்வ வித்யாமயீம் வந்தே காயத்ரீ வேதமாதரம்
யோ தேவ꞉ ஸவிதாஸ்மாகம் தியோ தர்மாதிகோசரா꞉।
ப்ரேரயேத் தஸ்ய யத்பர்க꞉ தத்வரேண்யமுபாஸ்மஹே॥',
   'muktāvidrumahemanīladhavalacchāyairmukhaistrīkṣaṇaiḥ
yuktāmindukalānibaddharatnamakuṭāṃ tatvārthavarṇātmikām।
gāyatrīṃ varadābhayāṅkuśakaśāḥ śubhraṃ kapālaṃ gadāṃ
śaṅkhaṃ cakramathāravindayugal̤aṃ hastairvahantīṃ bhaje॥
akṣasrakkuṇḍikā hastāṃ śuddhasphaṭika nirmalāṃ
sarva vidyāmayīṃ vande gāyatrī vedamātaram
yo devaḥ savitā''smākaṃ dhiyo dharmādigocarāḥ।
prerayet tasya yadbhargaḥ tadvareṇyamupāsmahe॥',
   'Gayatri of five faces coloured like pearl, coral, gold, sapphire and white, each three-eyed, crowned with a jewelled crown bound with the crescent; bearing in her hands the boon and the fear-not, the goad and the whip, the bright skull and the mace, the conch, the discus and a pair of lotuses. And: her whose hands hold the rosary and the water pot, clear as pure crystal, made of all knowledge — Gayatri, mother of the Vedas. That god Savitr who impels our thoughts towards dharma: his brilliance is what we worship.',
   'Three movements: her form in ornament, her form in simplicity, and her function. The book prints the ornate and the plain images one after the other without comment, because the japa may be done contemplating either. The third verse restates the Gayatri''s own sense and hands the reciter straight into the mantra.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 31. Gayatri Japa
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 31, 'pradhana', 'Gayatri Japa', 'காயத்ரி ஜபம்',
   'Count on the joints of the fingers: hold both palms together sideways before the face and begin with the right thumb on the middle line of the ring finger, moving down, across and up in a clockwise circuit of ten, then anticlockwise back for the next ten. MORNING 108 times facing east. NOON 32 times facing east. EVENING 64 times, facing west before sunset and east after it. Then do one pranayama.',
   'விரல் கணுக்களில் எண்ணவும்: இரு உள்ளங்கைகளையும் முகத்திற்கு முன் பக்கவாட்டில் சேர்த்து, வலது கட்டைவிரலை மோதிர விரலின் நடுக்கோட்டில் வைத்துத் தொடங்கி, வலமாகச் சுற்றி பத்து; பின் இடமாகத் திரும்பி அடுத்த பத்து. காலை 108 முறை, கிழக்கு நோக்கி. உச்சி 32 முறை, கிழக்கு நோக்கி. மாலை 64 முறை; சூரியன் மறைவதற்கு முன் மேற்கு, மறைந்த பின் கிழக்கு. பின் ஒரு ப்ராணாயாமம்.',
   'ओम्-भूर्भुवस्सुवः
तत्सवितुर्वरेण्यम्। भर्गो देवस्य धीमहि।
धियो यो नः प्रचोदयात्।',
   'ஓம்-பூர்புவஸ்ஸுவ꞉
தத்ஸவிதுர்வரேண்யம்। பர்கோ தேவஸ்ய தீமஹி।
தியோ யோ ந꞉ ப்ரசோதயாத்।',
   'om-bhūrbhuvassuvaḥ
tatsaviturvareṇyam। bhargo devasya dhīmahi।
dhiyo yo naḥ pracodayāt।',
   'The three worlds are Om. We meditate on the brilliance of that god who impels our thoughts.',
   'The most mode-dependent step in the rite, and none of it is the mantra. The Gayatri is identical at all three sittings; the count changes and so does the direction faced. The evening rule is conditional on the actual sun rather than the clock — west before it sets, east afterwards — so the app prints both halves and leaves the sky to settle it.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 32. Gayatri Upasthanam — morning
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 32, 'pradhana', 'Gayatri Upasthanam — morning', 'காயத்ரி உபஸ்தானம் — காலை',
   'Lock both hands one into the other, right over left, clasp the palms, rotate them from inside and release. Then touch the floor with the ring finger and the point between the eyebrows while reciting the verse.',
   'இரு கைகளையும் ஒன்றோடொன்று கோத்து, வலது கை இடது மேல் இருக்கும்படி உள்ளங்கைகளைச் சேர்த்து, உள்ளிருந்து சுழற்றி விடுவிக்கவும். பின் மோதிர விரலால் தரையையும் புருவ மத்தியையும் தொட்டபடி ஸ்லோகத்தைச் சொல்லவும்.',
   'प्रातस्सन्ध्यागायत्री उपस्थानं करिष्ये
उत्तमे शिखरे देवि भूम्यां पर्वतमूर्धनि।
ब्राह्मणेभ्यो ह्यनुज्ञानं गच्छ देवि यथासुखम्॥',
   'ப்ராதஸ்ஸந்த்யாகாயத்ரீ உபஸ்தாநம் கரிஷ்யே
உத்தமே ஶிகரே தேவி பூம்யாம் பர்வதமூர்தநி।
ப்ராஹ்மணேப்யோ ஹ்யநுஜ்ஞாநம் கச்ச தேவி யதாஸுகம்॥',
   'prātassandhyāgāyatrī upasthānaṃ kariṣye
uttame śikhare devi bhūmyāṃ parvatamūrdhani।
brāhmaṇebhyo hyanujñānaṃ gaccha devi yathāsukham॥',
   'I shall perform the upasthanam of the Gayatri of the morning. On the highest summit, goddess, on the earth, on the head of the mountain — with the leave of the brahmins, go, goddess, happily.',
   'The udvasanam of the Gayatri, and it mirrors the avahanam exactly: invoked with the palms turned inwards, dismissed with them locked, turned from inside and opened. She is not dissolved and not taken into the heart — she is returned to a place. The app now holds three different ways of ending an invocation, and this is the third.',
   array['pratah']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 33. Gayatri Upasthanam — noon
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 33, 'pradhana', 'Gayatri Upasthanam — noon', 'காயத்ரி உபஸ்தானம் — உச்சி',
   'Lock both hands one into the other, right over left, clasp the palms, rotate them from inside and release. Then touch the floor with the ring finger and the point between the eyebrows while reciting the verse.',
   'இரு கைகளையும் ஒன்றோடொன்று கோத்து, வலது கை இடது மேல் இருக்கும்படி உள்ளங்கைகளைச் சேர்த்து, உள்ளிருந்து சுழற்றி விடுவிக்கவும். பின் மோதிர விரலால் தரையையும் புருவ மத்தியையும் தொட்டபடி ஸ்லோகத்தைச் சொல்லவும்.',
   'माध्याह्निकगायत्री उपस्थानं करिष्ये
उत्तमे शिखरे देवि भूम्यां पर्वतमूर्धनि।
ब्राह्मणेभ्यो ह्यनुज्ञानं गच्छ देवि यथासुखम्॥',
   'மாத்யாஹ்நிககாயத்ரீ உபஸ்தாநம் கரிஷ்யே
உத்தமே ஶிகரே தேவி பூம்யாம் பர்வதமூர்தநி।
ப்ராஹ்மணேப்யோ ஹ்யநுஜ்ஞாநம் கச்ச தேவி யதாஸுகம்॥',
   'mādhyāhnikagāyatrī upasthānaṃ kariṣye
uttame śikhare devi bhūmyāṃ parvatamūrdhani।
brāhmaṇebhyo hyanujñānaṃ gaccha devi yathāsukham॥',
   'I shall perform the upasthanam of the Gayatri of the noon. On the highest summit, goddess, on the earth, on the head of the mountain — with the leave of the brahmins, go, goddess, happily.',
   'The udvasanam of the Gayatri, and it mirrors the avahanam exactly: invoked with the palms turned inwards, dismissed with them locked, turned from inside and opened. She is not dissolved and not taken into the heart — she is returned to a place. The app now holds three different ways of ending an invocation, and this is the third.',
   array['madhyahnika']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 34. Gayatri Upasthanam — evening
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 34, 'pradhana', 'Gayatri Upasthanam — evening', 'காயத்ரி உபஸ்தானம் — மாலை',
   'Lock both hands one into the other, right over left, clasp the palms, rotate them from inside and release. Then touch the floor with the ring finger and the point between the eyebrows while reciting the verse.',
   'இரு கைகளையும் ஒன்றோடொன்று கோத்து, வலது கை இடது மேல் இருக்கும்படி உள்ளங்கைகளைச் சேர்த்து, உள்ளிருந்து சுழற்றி விடுவிக்கவும். பின் மோதிர விரலால் தரையையும் புருவ மத்தியையும் தொட்டபடி ஸ்லோகத்தைச் சொல்லவும்.',
   'सायं सन्ध्यागायत्री उपस्थानं करिष्ये
उत्तमे शिखरे देवि भूम्यां पर्वतमूर्धनि।
ब्राह्मणेभ्यो ह्यनुज्ञानं गच्छ देवि यथासुखम्॥',
   'ஸாயம் ஸந்த்யாகாயத்ரீ உபஸ்தாநம் கரிஷ்யே
உத்தமே ஶிகரே தேவி பூம்யாம் பர்வதமூர்தநி।
ப்ராஹ்மணேப்யோ ஹ்யநுஜ்ஞாநம் கச்ச தேவி யதாஸுகம்॥',
   'sāyaṃ sandhyāgāyatrī upasthānaṃ kariṣye
uttame śikhare devi bhūmyāṃ parvatamūrdhani।
brāhmaṇebhyo hyanujñānaṃ gaccha devi yathāsukham॥',
   'I shall perform the upasthanam of the Gayatri of the evening. On the highest summit, goddess, on the earth, on the head of the mountain — with the leave of the brahmins, go, goddess, happily.',
   'The udvasanam of the Gayatri, and it mirrors the avahanam exactly: invoked with the palms turned inwards, dismissed with them locked, turned from inside and opened. She is not dissolved and not taken into the heart — she is returned to a place. The app now holds three different ways of ending an invocation, and this is the third.',
   array['sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 35. Surya Prarthana — morning
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 35, 'pradhana', 'Surya Prarthana — morning', 'ஸூர்ய ப்ரார்த்தனை — காலை',
   'Pray with folded hands.',
   'கைகூப்பி வேண்டவும்.',
   'ओम् मित्रस्य चर्षणीधृतः श्रवो देवस्य सानसिम्। सत्यं चित्रश्रवस्तमम्॥
मित्रो जनान् यातयति प्रजानन् मित्रो दाधार पृथिवीमुत द्याम्।
मित्रः कृष्टीरनिमिषाऽभिचष्टे सत्याय हव्यं घृतवद्विधेम॥
प्र स मित्र मर्तो अस्तु प्रयस्वान् यस्त आदित्य शिक्षति व्रतेन।
न हन्यते न जीयते त्वोतो नैनमꣳहो अश्नोत्यन्तितो न दूरात्॥',
   'ஓம் மித்ரஸ்ய சர்ஷணீத்ருத꞉ ஶ்ரவோ தேவஸ்ய ஸாநஸிம்। ஸத்யம் சித்ரஶ்ரவஸ்தமம்॥
மித்ரோ ஜநாந் யாதயதி ப்ரஜாநந் மித்ரோ தாதார ப்ருதிவீமுத த்யாம்।
மித்ர꞉ க்ருஷ்டீரநிமிஷாபிசஷ்டே ஸத்யாய ஹவ்யம் க்ருதவத்விதேம॥
ப்ர ஸ மித்ர மர்தோ அஸ்து ப்ரயஸ்வாந் யஸ்த ஆதித்ய ஶிக்ஷதி வ்ரதேந।
ந ஹந்யதே ந ஜீயதே த்வோதோ நைநமகும்ஹோ அஶ்நோத்யந்திதோ ந தூராத்॥',
   'om mitrasya carṣaṇīdhṛtaḥ śravo devasya sānasim। satyaṃ citraśravastamam॥
mitro janān yātayati prajānan mitro dādhāra pṛthivīmuta dyām।
mitraḥ kṛṣṭīranimiṣā''bhicaṣṭe satyāya havyaṃ ghṛtavadvidhema॥
pra sa mitra marto astu prayasvān yasta āditya śikṣati vratena।
na hanyate na jīyate tvoto nainamagmho aśnotyantito na dūrāt॥',
   'The glory of Mitra, sustainer of people, is worth winning and most brilliantly true. Mitra marshals people, knowing them; Mitra holds earth and sky; Mitra watches the settlements without blinking. Let us offer to the true one an oblation rich in ghee. That mortal is foremost who, Aditya, serves you by your law: he is neither slain nor overcome, and no evil reaches him from near or far.',
   'The morning sun is addressed as Mitra, the friend, and the epithet does the work: three clauses each beginning with the name. It ends in the only outright guarantee in the rite — one whom you protect is neither slain nor overcome.',
   array['pratah']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 36. Surya Prarthana — noon
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 36, 'pradhana', 'Surya Prarthana — noon', 'ஸூர்ய ப்ரார்த்தனை — உச்சி',
   'The mantra has two parts. At the end of the first, at jyok cha sooryam drushe, look at the sun through the gap made by locking both hands together above the eyes. The book says to learn this from a teacher. Then return and continue.',
   'மந்திரம் இரு பகுதிகள். முதல் பகுதி "ஜ்யோக் ச ஸூர்யம் த்ருஶே" என்பதில் முடியும்; அப்போது இரு கைகளையும் கண்களுக்கு மேல் கோத்து, அதன் இடைவெளி வழியே சூரியனைப் பார்க்கவும். இதை ஆசிரியரிடம் கற்க வேண்டும் என நூல் கூறுகிறது. பின் தொடரவும்.',
   'आ सत्येन रजसा वर्तमानो निवेशयन्नमृतं मर्त्यं च।
हिरण्ययेन सविता रथेना देवो याति भुवना विपश्यन्॥
उद्वयं तमसस्परि पश्यन्तो ज्योतिरुत्तरम्।
देवं देवत्रा सूर्यमगन्म ज्योतिरुत्तमम्॥
उदुत्यं जातवेदसं देवं वहन्ति केतवः। दृशे विश्वाय सूर्यम्॥
चित्रं देवानामुदगादनीकं चक्षुर्मित्रस्य वरुणस्याग्नेः।
आप्रा द्यावापृथिवी अन्तरिक्षꣳ सूर्य आत्मा जगतस्तस्थुषश्च।
तच्चक्षुर्देवहितं पुरस्ताच्छुक्रमुच्चरत्।
पश्येम शरदश्शतं जीवेम शरदश्शतं
नन्दाम शरदश्शतं मोदाम शरदश्शतं
भवाम शरदश्शतꣳ शृण्वाम शरदश्शतं
प्रब्रवाम शरदश्शतमजीतास्स्याम शरदश्शतं "ज्योक् च सूर्यं दृशे"।
य उदगान्महतोऽर्णवाद्विभ्राजमानस्सरिरस्य मध्यात् स मा वृषभो लोहिताक्षः
सूर्यो विपश्चिन्मनसा पुनातु',
   'ஆ ஸத்யேந ரஜஸா வர்தமாநோ நிவேஶயந்நம்ருதம் மர்த்யம் ச।
ஹிரண்யயேந ஸவிதா ரதேநா தேவோ யாதி புவநா விபஶ்யந்॥
உத்வயம் தமஸஸ்பரி பஶ்யந்தோ ஜ்யோதிருத்தரம்।
தேவம் தேவத்ரா ஸூர்யமகந்ம ஜ்யோதிருத்தமம்॥
உதுத்யம் ஜாதவேதஸம் தேவம் வஹந்தி கேதவ꞉। த்ருஶே விஶ்வாய ஸூர்யம்॥
சித்ரம் தேவாநாமுதகாதநீகம் சக்ஷுர்மித்ரஸ்ய வருணஸ்யாக்நே꞉।
ஆப்ரா த்யாவாப்ருதிவீ அந்தரிக்ஷகும் ஸூர்ய ஆத்மா ஜகதஸ்தஸ்துஷஶ்ச।
தச்சக்ஷுர்தேவஹிதம் புரஸ்தாச்சுக்ரமுச்சரத்।
பஶ்யேம ஶரதஶ்ஶதம் ஜீவேம ஶரதஶ்ஶதம்
நந்தாம ஶரதஶ்ஶதம் மோதாம ஶரதஶ்ஶதம்
பவாம ஶரதஶ்ஶதகும் ஶ்ருண்வாம ஶரதஶ்ஶதம்
ப்ரப்ரவாம ஶரதஶ்ஶதமஜீதாஸ்ஸ்யாம ஶரதஶ்ஶதம் "ஜ்யோக் ச ஸூர்யம் த்ருஶே"।
ய உதகாந்மஹதோர்ணவாத்விப்ராஜமாநஸ்ஸரிரஸ்ய மத்யாத் ஸ மா வ்ருஷபோ லோஹிதாக்ஷ꞉
ஸூர்யோ விபஶ்சிந்மநஸா புநாது',
   'ā satyena rajasā vartamāno niveśayannamṛtaṃ martyaṃ ca।
hiraṇyayena savitā rathenā devo yāti bhuvanā vipaśyan॥
udvayaṃ tamasaspari paśyanto jyotiruttaram।
devaṃ devatrā sūryamaganma jyotiruttamam॥
udutyaṃ jātavedasaṃ devaṃ vahanti ketavaḥ। dṛśe viśvāya sūryam॥
citraṃ devānāmudagādanīkaṃ cakṣurmitrasya varuṇasyāgneḥ।
āprā dyāvāpṛthivī antarikṣagm sūrya ātmā jagatastasthuṣaśca।
taccakṣurdevahitaṃ purastācchukramuccarat।
paśyema śaradaśśataṃ jīvema śaradaśśataṃ
nandāma śaradaśśataṃ modāma śaradaśśataṃ
bhavāma śaradaśśatagm śṛṇvāma śaradaśśataṃ
prabravāma śaradaśśatamajītāssyāma śaradaśśataṃ "jyok ca sūryaṃ dṛśe"।
ya udagānmahato''rṇavādvibhrājamānassarirasya madhyāt sa mā vṛṣabho lohitākṣaḥ
sūryo vipaścinmanasā punātu',
   'Moving with truth through the atmosphere, settling the immortal and the mortal, Savitr comes in his golden chariot, beholding the worlds. Seeing the higher light beyond the darkness, we have reached the sun, god among gods, the highest light. May we see a hundred autumns, live a hundred, rejoice a hundred, delight a hundred, be a hundred, hear a hundred, speak a hundred, be unconquered a hundred — and long may we see the sun.',
   'The longest mantra in the rite and the only one with an action inside it rather than before or after. Eight verbs on one frame ask not for release but for another century of looking at the sun: to see, live, rejoice, delight, be, hear, speak and remain unconquered, each for a hundred autumns.',
   array['madhyahnika']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 37. Varuna Prarthana — evening
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 37, 'pradhana', 'Varuna Prarthana — evening', 'வருண ப்ரார்த்தனை — மாலை',
   'Pray with folded hands.',
   'கைகூப்பி வேண்டவும்.',
   'इमं मे वरुण श्रुधी हवमद्या च मृडय। त्वामवस्युराचके॥
तत्वा यामि ब्रह्मणा वन्दमानस्तदाशास्ते यजमानो हविर्भिः।
अहेडमानो वरुणेह बोध्युरुशꣳस मा न आयुः प्रमोषीः॥
यच्चिद्धि ते विशो यथा प्रदेव वरुण व्रतम्। मिनीमसि द्यविद्यवि॥
यत् किञ्चेदं वरुण दैव्ये जनेऽभिद्रोहं मनुष्याश्चरामसि।
अचित्ती यत्तव धर्मा युयोपिम मा नस्तस्मादेनसो देव रीरिषः॥
कितवासो यद्रिरिपुर्न दीवि यद्वा घा सत्यमुत यन्न विद्म।
सर्वा ता विष्य शिथिरेव देवाथा ते स्याम वरुण प्रियासः॥',
   'இமம் மே வருண ஶ்ருதீ ஹவமத்யா ச ம்ருடய। த்வாமவஸ்யுராசகே॥
தத்வா யாமி ப்ரஹ்மணா வந்தமாநஸ்ததாஶாஸ்தே யஜமாநோ ஹவிர்பி꞉।
அஹேடமாநோ வருணேஹ போத்யுருஶகும்ஸ மா ந ஆயு꞉ ப்ரமோஷீ꞉॥
யச்சித்தி தே விஶோ யதா ப்ரதேவ வருண வ்ரதம்। மிநீமஸி த்யவித்யவி॥
யத் கிஞ்சேதம் வருண தைவ்யே ஜநேபித்ரோஹம் மநுஷ்யாஶ்சராமஸி।
அசித்தீ யத்தவ தர்மா யுயோபிம மா நஸ்தஸ்மாதேநஸோ தேவ ரீரிஷ꞉॥
கிதவாஸோ யத்ரிரிபுர்ந தீவி யத்வா கா ஸத்யமுத யந்ந வித்ம।
ஸர்வா தா விஷ்ய ஶிதிரேவ தேவாதா தே ஸ்யாம வருண ப்ரியாஸ꞉॥',
   'imaṃ me varuṇa śrudhī havamadyā ca mṛḍaya। tvāmavasyurācake॥
tatvā yāmi brahmaṇā vandamānastadāśāste yajamāno havirbhiḥ।
aheḍamāno varuṇeha bodhyuruśagmsa mā na āyuḥ pramoṣīḥ॥
yacciddhi te viśo yathā pradeva varuṇa vratam। minīmasi dyavidyavi॥
yat kiñcedaṃ varuṇa daivye jane''bhidrohaṃ manuṣyāścarāmasi।
acittī yattava dharmā yuyopima mā nastasmādenaso deva rīriṣaḥ॥
kitavāso yadriripurna dīvi yadvā ghā satyamuta yanna vidma।
sarvā tā viṣya śithireva devāthā te syāma varuṇa priyāsaḥ॥',
   'Hear this call of mine, Varuna, and be gracious today; longing for help I come to you. I entreat you with prayer; the sacrificer asks the same with his oblations. Be here, Varuna, without anger, widely famed; do not take away our life. Whatever offence we men commit against the divine folk, whatever of your law we have disturbed unknowing — do not destroy us for that wrong, god. Whatever we have cheated at, like gamblers, or truly know or do not know: loosen all of it like loosened bonds, and may we be dear to you.',
   'The three sittings now have three deities — Mitra at dawn, Surya at noon, Varuna at dusk — and the tone changes with them. The morning promised protection; this one confesses. Three admissions and then the request: do not destroy us for it. The rite ends its day by owning what it got wrong, having begun by asking to be kept from it.',
   array['sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 38. Samashti Abhivadanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 38, 'pradhana', 'Samashti Abhivadanam', 'ஸமஷ்ட்ய அபிவாதனம்',
   'Turn clockwise, pausing to face each quarter as it is named: Sandhya east, Savitri south, Gayatri west, Sarasvati north, and all the deities facing east again. Then pray with folded hands.',
   'வலமாகத் திரும்பி, ஒவ்வொரு திசையையும் நோக்கி நிற்கவும்: ஸந்த்யா கிழக்கு, ஸாவித்ரி தெற்கு, காயத்ரி மேற்கு, ஸரஸ்வதி வடக்கு, பின் அனைத்து தேவதைகளுக்கும் மீண்டும் கிழக்கு நோக்கி. பின் கைகூப்பி வேண்டவும்.',
   'कामोऽकार्षीन्मन्युरकार्षीत् नमो नमः।',
   'காமோகார்ஷீந்மந்யுரகார்ஷீத் நமோ நம꞉।',
   'kāmo''kārṣīnmanyurakārṣīt namo namaḥ।',
   'Salutation to Sandhya, to Savitri, to Gayatri, to Sarasvati, and to all the deities. Desire did it; anger did it. Salutation, salutation.',
   'A circuit rather than a list: five salutations, each said facing a different quarter, ending where it began. The closing line is the third and shortest of the rite''s confessions — after the Prashanam''s list of organs and the Varuna prayer''s list of offences, two verbs and a bow.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 1, 'सन्ध्यायै नमः', 'ஸந்த்யாயை நம꞉', 'sandhyāyai namaḥ', 'East'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 38;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 2, 'सावित्र्यै नमः', 'ஸாவித்ர்யை நம꞉', 'sāvitryai namaḥ', 'South'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 38;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 3, 'गायत्र्यै नमः', 'காயத்ர்யை நம꞉', 'gāyatryai namaḥ', 'West'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 38;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 4, 'सरस्वत्यै नमः', 'ஸரஸ்வத்யை நம꞉', 'sarasvatyai namaḥ', 'North'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 38;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 5, 'सर्वाभ्यो देवताभ्यो नमः।', 'ஸர்வாப்யோ தேவதாப்யோ நம꞉।', 'sarvābhyo devatābhyo namaḥ।', 'East'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 38;

-- 39. Abhivadanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 39, 'pradhana', 'Abhivadanam', 'அபிவாதனம்',
   'Cover both ears with the hands and touch the floor at the end. Say your own pravara rishis, gotra and name in the blanks — the book leaves them blank because the reciter knows them. Three rishis take tryarsheya, five take panchaarsheya.',
   'இரு காதுகளையும் கைகளால் மூடி, இறுதியில் தரையைத் தொடவும். இடைவெளிகளில் உங்கள் ப்ரவர ரிஷிகள், கோத்ரம், பெயர் ஆகியவற்றைச் சொல்லவும் — சொல்பவருக்குத் தெரியும் என்பதால் நூலும் அவற்றை வெறுமையாகவே விட்டிருக்கிறது. மூன்று ரிஷிகளானால் த்ர்யார்ஷேய, ஐந்தானால் பஞ்சார்ஷேய.',
   'अभिवादये ............ ............ ............ ............ ............
त्र्यार्षेय / पञ्चार्षेय प्रवरान्वित ............ गोत्रः आपस्तम्ब सूत्रः
यजुः शाखाऽध्यायी श्री ............ शर्मा नामाहं अस्मि भोः',
   'அபிவாதயே ............ ............ ............ ............ ............
த்ர்யார்ஷேய / பஞ்சார்ஷேய ப்ரவராந்வித ............ கோத்ர꞉ ஆபஸ்தம்ப ஸூத்ர꞉
யஜு꞉ ஶாகாத்யாயீ ஶ்ரீ ............ ஶர்மா நாமாஹம் அஸ்மி போ꞉',
   'abhivādaye ............ ............ ............ ............ ............
tryārṣeya / pañcārṣeya pravarānvita ............ gotraḥ āpastamba sūtraḥ
yajuḥ śākhā''dhyāyī śrī ............ śarmā nāmāhaṃ asmi bhoḥ',
   'I salute — of the pravara of three (or five) rishis, of such a gotra, of the Apastamba sutra, a student of the Yajus recension: I am so-and-so sharma by name, sir.',
   'Printed with its blanks, as the book prints it. The book fills in two of the five slots in type — Apastamba sutra and the Yajus recension, because it is a Yajurveda Apastamba manual — and leaves the rest dotted. The ears are covered because the reciter is about to say his own name and lineage aloud.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 40. Dig Devata Vandanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 40, 'pradhana', 'Dig Devata Vandanam', 'திக் தேவதா வந்தனம்',
   'Salute each quarter as it is named. The last three — above, below and the mid-space — are said facing east without turning.',
   'ஒவ்வொரு திசையையும் சொல்லும்போது வணங்கவும். இறுதி மூன்று — மேல், கீழ், அந்தரிக்ஷம் — திரும்பாமல் கிழக்கு நோக்கியே சொல்லப்படும்.',
   null,
   null,
   null,
   'Salutation to the eastern quarter, the southern, the western, the northern; to what is above, what is below, and the space between; to Earth, to Brahma, to Vishnu, to Death.',
   'The Samashti Abhivadanam turned through four quarters; this salutes the quarters as deities in their own right and then adds the vertical — up, down, and the space between — without turning. Eleven salutations, four horizontal, three vertical and four by name.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 1, 'प्राच्यै दिशे नमः', 'ப்ராச்யை திஶே நம꞉', 'prācyai diśe namaḥ', 'East'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 2, 'दक्षिणायै दिशे नमः', 'தக்ஷிணாயை திஶே நம꞉', 'dakṣiṇāyai diśe namaḥ', 'South'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 3, 'प्रतीच्यै दिशे नमः', 'ப்ரதீச்யை திஶே நம꞉', 'pratīcyai diśe namaḥ', 'West'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 4, 'उदीच्यै दिशे नमः', 'உதீச்யை திஶே நம꞉', 'udīcyai diśe namaḥ', 'North'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 5, 'ऊर्ध्वाय नमः', 'ஊர்த்வாய நம꞉', 'ūrdhvāya namaḥ', 'Above (sky), facing east'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 6, 'अधराय नमः', 'அதராய நம꞉', 'adharāya namaḥ', 'Below (earth), facing east'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 7, 'अन्तरिक्षाय नमः', 'அந்தரிக்ஷாய நம꞉', 'antarikṣāya namaḥ', 'Above (sky), facing east'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 8, 'भूम्यै नमः', 'பூம்யை நம꞉', 'bhūmyai namaḥ', 'Below (earth)'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 9, 'ब्रह्मणे नमः', 'ப்ரஹ்மணே நம꞉', 'brahmaṇe namaḥ', 'Above (sky)'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 10, 'विष्णवे नमः', 'விஷ்ணவே நம꞉', 'viṣṇave namaḥ', 'Below (earth)'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;
insert into public.archana_items
  (pooja_step_id, seq, invoked_name_deva, invoked_name_ta, invoked_name_translit, offering_en)
select id, 11, 'मृत्यवे नमः', 'ம்ருத்யவே நம꞉', 'mṛtyave namaḥ', 'South'
  from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = 40;

-- 41. Yama Vandanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 41, 'pradhana', 'Yama Vandanam', 'யம வந்தனம்',
   'Face south while reciting.',
   'தெற்கு நோக்கிச் சொல்லவும்.',
   'यमाय नमः
यमाय धर्मराजाय मृत्यवे चान्तकाय च।
वैवस्वताय कालाय सर्वभूतक्षयाय च॥
औदुम्बराय दध्नाय नीलाय परमेष्ठिने।
वृकोदराय चित्राय चित्रगुप्ताय वै नमः॥
''चित्र गुप्ताय वै नम ओं नमः'' इति',
   'யமாய நம꞉
யமாய தர்மராஜாய ம்ருத்யவே சாந்தகாய ச।
வைவஸ்வதாய காலாய ஸர்வபூதக்ஷயாய ச॥
ஔதும்பராய தத்நாய நீலாய பரமேஷ்டிநே।
வ்ருகோதராய சித்ராய சித்ரகுப்தாய வை நம꞉॥
சித்ர குப்தாய வை நம ஓம் நம꞉ இதி',
   'yamāya namaḥ
yamāya dharmarājāya mṛtyave cāntakāya ca।
vaivasvatāya kālāya sarvabhūtakṣayāya ca॥
audumbarāya dadhnāya nīlāya parameṣṭhine।
vṛkodarāya citrāya citraguptāya vai namaḥ॥
''citra guptāya vai nama oṃ namaḥ'' iti',
   'Salutation to Yama, to the king of dharma, to Death and to the Ender; to the son of Vivasvat, to Time, to the destroyer of all beings; to the one of the udumbara, to Dadhna, to the dark one, to the highest; to the wide-bellied, to Chitra, and to Chitragupta.',
   'Twelve datives, and the rite that began by asking Mitra for protection ends by naming death in every aspect it has. The last name is Chitragupta, said again on its own — the one who writes down what each person did. After three confessions, the rite bows to the clerk who keeps the account.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 42. Harihara Vandanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 42, 'pradhana', 'Harihara Vandanam', 'ஹரிஹர வந்தனம்',
   'Face north while reciting.',
   'வடக்கு நோக்கிச் சொல்லவும்.',
   'ऋतꣳसत्यं परं ब्रह्म पुरुषं कृष्णपिङ्गलम्।
ऊर्ध्वरेतं विरूपाक्षं विश्वरूपाय वै नमो नमः॥
''विश्वरूपाय वै नम ओं नम इति''',
   'ருதகும்ஸத்யம் பரம் ப்ரஹ்ம புருஷம் க்ருஷ்ணபிங்கலம்।
ஊர்த்வரேதம் விரூபாக்ஷம் விஶ்வரூபாய வை நமோ நம꞉॥
விஶ்வரூபாய வை நம ஓம் நம இதி',
   'ṛtagmsatyaṃ paraṃ brahma puruṣaṃ kṛṣṇapiṅgalam।
ūrdhvaretaṃ virūpākṣaṃ viśvarūpāya vai namo namaḥ॥
''viśvarūpāya vai nama oṃ nama iti''',
   'Order and truth, the supreme Brahman, the person dark and tawny, whose seed is drawn upward, of strange eyes — salutation, salutation to him whose form is the universe.',
   'One figure, not two. Dark and tawny is the whole point: the grey body of Vishnu blended with the red of Shiva in a single form. It makes the same case in one word that the panchayatana arrangement makes with five deities and a diagram.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 43. Suryanarayana Vandanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 43, 'pradhana', 'Suryanarayana Vandanam', 'ஸூர்யநாராயண வந்தனம்',
   'Face east while reciting.',
   'கிழக்கு நோக்கிச் சொல்லவும்.',
   'नमः सवित्रे जगदेकचक्षुषे जगत्प्रसूतिस्थितिनाशहेतवे।
त्रयीमयाय त्रिगुणात्मधारिणे विरिञ्चिनारायणशङ्करात्मने॥ १
ध्येयः सदा सवितृमण्डलमध्यवर्ती नारायणः सरसिजासनसंनिविष्टः।
केयूरवान् मकरकुण्डलवान् किरीटी हारी हिरण्मयवपुर्धृतशङ्खचक्रः॥ २
शङ्खचक्रगदापाणे द्वारकानिलयाच्युत।
गोविन्द पुण्डरीकाक्ष रक्ष मां शरणागतम्॥ ३
आकाशात् पतितं तोयं यथा गच्छति सागरम्।
सर्वदेवनमस्कारः केशवं प्रति गच्छति॥ ४
श्रीकेशवं प्रति गच्छत्यों नम इति',
   'நம꞉ ஸவித்ரே ஜகதேகசக்ஷுஷே ஜகத்ப்ரஸூதிஸ்திதிநாஶஹேதவே।
த்ரயீமயாய த்ரிகுணாத்மதாரிணே விரிஞ்சிநாராயணஶங்கராத்மநே॥ ௧
த்யேய꞉ ஸதா ஸவித்ருமண்டலமத்யவர்தீ நாராயண꞉ ஸரஸிஜாஸநஸம்நிவிஷ்ட꞉।
கேயூரவாந் மகரகுண்டலவாந் கிரீடீ ஹாரீ ஹிரண்மயவபுர்த்ருதஶங்கசக்ர꞉॥ ௨
ஶங்கசக்ரகதாபாணே த்வாரகாநிலயாச்யுத।
கோவிந்த புண்டரீகாக்ஷ ரக்ஷ மாம் ஶரணாகதம்॥ ௩
ஆகாஶாத் பதிதம் தோயம் யதா கச்சதி ஸாகரம்।
ஸர்வதேவநமஸ்கார꞉ கேஶவம் ப்ரதி கச்சதி॥ ௪
ஶ்ரீகேஶவம் ப்ரதி கச்சத்யோம் நம இதி',
   'namaḥ savitre jagadekacakṣuṣe jagatprasūtisthitināśahetave।
trayīmayāya triguṇātmadhāriṇe viriñcinārāyaṇaśaṅkarātmane॥ 1
dhyeyaḥ sadā savitṛmaṇḍalamadhyavartī nārāyaṇaḥ sarasijāsanasaṃniviṣṭaḥ।
keyūravān makarakuṇḍalavān kirīṭī hārī hiraṇmayavapurdhṛtaśaṅkhacakraḥ॥ 2
śaṅkhacakragadāpāṇe dvārakānilayācyuta।
govinda puṇḍarīkākṣa rakṣa māṃ śaraṇāgatam॥ 3
ākāśāt patitaṃ toyaṃ yathā gacchati sāgaram।
sarvadevanamaskāraḥ keśavaṃ prati gacchati॥ 4
śrīkeśavaṃ prati gacchatyoṃ nama iti',
   'Salutation to Savitr, the one eye of the world, cause of its birth, its standing and its end; made of the three Vedas, bearing the three qualities, whose self is Brahma, Vishnu and Shankara. Narayana seated always in the middle of the solar orbit, on the lotus, with armlets and makara earrings, crowned and garlanded, golden-bodied, holding conch and discus, is ever worthy of meditation. Holder of conch, discus and mace, dweller in Dvaraka, Achyuta, Govinda, lotus-eyed — protect me, who have come for refuge. As water fallen from the sky makes its way to the sea, salutation to any god makes its way to Keshava.',
   'The closing verse is the rite''s own justification. After Mitra, Varuna, nine planets, twelve months, four quarters, three verticals and the lord of death, it says all of it arrives at one place. It also answers the question a reader is most likely to have by now — why so many names — and it answers it with water finding the sea.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 44. Samarpanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 44, 'pradhana', 'Samarpanam', 'ஸமர்ப்பணம்',
   'Cover both ears with the hands again, say the Abhivadanam once more, and touch the floor and prostrate at the end.',
   'மீண்டும் இரு காதுகளையும் கைகளால் மூடி, அபிவாதனத்தை ஒரு முறை சொல்லி, இறுதியில் தரையைத் தொட்டு நமஸ்கரிக்கவும்.',
   'अभिवादये..... अस्मि भोः
कायेन वाचा मनसेन्द्रियैर्वा बुध्याऽऽत्मना वा प्रकृतेः स्वभावात्।
करोमि यद्यत् सकलं परस्मै नारायणायेति समर्पयामि॥
मन्त्रहीनं क्रियाहीनं भक्तिहीनं जनार्दन।
यत् कृतं तु मया देव परिपूर्णं तदस्तु ते॥
प्रायश्चित्तान्यशेषाणि तपःकर्मात्मकानि वै।
यानि तेषामशेषाणां श्री कृष्णानुस्मरणं परम्॥
श्री कृष्ण कृष्ण कृष्ण',
   'அபிவாதயே..... அஸ்மி போ꞉
காயேந வாசா மநஸேந்த்ரியைர்வா புத்யாத்மநா வா ப்ரக்ருதே꞉ ஸ்வபாவாத்।
கரோமி யத்யத் ஸகலம் பரஸ்மை நாராயணாயேதி ஸமர்பயாமி॥
மந்த்ரஹீநம் க்ரியாஹீநம் பக்திஹீநம் ஜநார்தந।
யத் க்ருதம் து மயா தேவ பரிபூர்ணம் ததஸ்து தே॥
ப்ராயஶ்சித்தாந்யஶேஷாணி தப꞉கர்மாத்மகாநி வை।
யாநி தேஷாமஶேஷாணாம் ஶ்ரீ க்ருஷ்ணாநுஸ்மரணம் பரம்॥
ஶ்ரீ க்ருஷ்ண க்ருஷ்ண க்ருஷ்ண',
   'abhivādaye..... asmi bhoḥ
kāyena vācā manasendriyairvā budhyā''''tmanā vā prakṛteḥ svabhāvāt।
karomi yadyat sakalaṃ parasmai nārāyaṇāyeti samarpayāmi॥
mantrahīnaṃ kriyāhīnaṃ bhaktihīnaṃ janārdana।
yat kṛtaṃ tu mayā deva paripūrṇaṃ tadastu te॥
prāyaścittānyaśeṣāṇi tapaḥkarmātmakāni vai।
yāni teṣāmaśeṣāṇāṃ śrī kṛṣṇānusmaraṇaṃ param॥
śrī kṛṣṇa kṛṣṇa kṛṣṇa',
   'Whatever I do by body, speech, mind, senses, intellect, self or by the force of nature, all of it I offer to the supreme Narayana. Short of mantra, short of rite, short of devotion, Janardana — whatever I have done, let it stand complete for you. Of all expiations whatsoever, made of austerity and action, the remembrance of Krishna is the highest.',
   'The app already holds two of these three verses: kaayena vaachaa, and the mantra-heenam that closes the Ganesha pooja. Completion is asked for as something the deity grants, not something the karta achieved. The third verse is new and it outranks everything before it: of all the expiations in a rite full of them, remembering a name is the highest.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- 45. Japasthanam Prokshanam
insert into public.pooja_steps
  (pooja_id, step_number, phase, step_title_en, step_title_ta,
   instruction_en, instruction_ta, mantra_sanskrit, mantra_tamil, mantra_translit,
   meaning_en, philosophy_en, modes, gender_rule, scripts_generated, source_ref)
values
  ('sandhyavandanam', 45, 'pradhana', 'Japasthanam Prokshanam', 'ஜபஸ்தான ப்ரோக்ஷணம்',
   'Do Achamanam and Anga Vandanam once. Then take water in the hand, pour it down at the end of the mantra, and make a tilak with it. Finally pour water onto the plate as an offering while saying the closing line.',
   'ஆசமனமும் அங்கவந்தனமும் ஒரு முறை செய்யவும். பின் கையில் நீர் எடுத்து, மந்திரம் முடியும்போது கீழே விட்டு, அந்த நீரால் திலகம் இடவும். இறுதியாக, இறுதி வரியைச் சொல்லியபடி தாம்பாளத்தில் நீரை அர்ப்பணமாக விடவும்.',
   'अद्या नो देव सवितः। प्रजावत्सावीः सौभगम्। परा दुष्वप्नियꣳसुव।
विश्वानि देव सवितः। दुरितानि परासुव। यद् भद्रं तन्म आसुव॥
''ओं तत् सत् ब्रह्मार्पणमस्तु''',
   'அத்யா நோ தேவ ஸவித꞉। ப்ரஜாவத்ஸாவீ꞉ ஸௌபகம்। பரா துஷ்வப்நியகும்ஸுவ।
விஶ்வாநி தேவ ஸவித꞉। துரிதாநி பராஸுவ। யத் பத்ரம் தந்ம ஆஸுவ॥
ஓம் தத் ஸத் ப்ரஹ்மார்பணமஸ்து',
   'adyā no deva savitaḥ। prajāvatsāvīḥ saubhagam। parā duṣvapniyagmsuva।
viśvāni deva savitaḥ। duritāni parāsuva। yad bhadraṃ tanma āsuva॥
''oṃ tat sat brahmārpaṇamastu''',
   'Today, god Savitr, send us prosperity with children. Drive away the bad dream. God Savitr, drive away all our wrongs, and send us what is good. Om tat sat — let it be an offering to Brahman.',
   'The rite ends by sealing the PLACE rather than the person: water is poured where the reciter has been sitting. And the last request is for sleep — drive away the bad dream. After the planets, the months, the directions, death and the keeper of the record, the closing mantra asks for children, for nightmares to stop, and for whatever is good. It is the plainest sentence in the rite.',
   array['pratah', 'madhyahnika', 'sayam']::text[], 'all', true, 'Yajurveda Trikaala Sandhyaavandanam (Giri), pp.28-48, photographed page');

-- The rite is whole. Publish it.
update public.poojas set status = 'published', updated_at = now() where id = 'sandhyavandanam';

-- --- assert ------------------------------------------------------------------
do $$
declare n int;
begin
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam';
  if n <> 45 then raise exception 'expected 45 steps, found %', n; end if;

  select count(*) into n from (
    select step_number, row_number() over (order by step_number) as rn
      from public.pooja_steps where pooja_id = 'sandhyavandanam'
  ) t where t.step_number <> t.rn;
  if n > 0 then raise exception '% step(s) are not numbered 1..n', n; end if;

  -- EVERY step has Tamil now, part one included. This is the assertion 0048
  -- should have carried.
  select count(*) into n from public.pooja_steps
   where pooja_id = 'sandhyavandanam' and coalesce(trim(instruction_ta), '') = '';
  if n > 0 then raise exception '% step(s) still have no Tamil instruction', n; end if;
  select count(*) into n from public.pooja_steps
   where pooja_id = 'sandhyavandanam' and instruction_ta !~ '[஀-௿]';
  if n > 0 then raise exception '% Tamil instruction(s) carry no Tamil', n; end if;

  -- Every sitting walks the whole rite.
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and 'pratah' = any(modes);
  if n <> 35 then raise exception 'pratah has % steps, expected 35', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and 'madhyahnika' = any(modes);
  if n <> 35 then raise exception 'madhyahnika has % steps, expected 35', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and 'sayam' = any(modes);
  if n <> 35 then raise exception 'sayam has % steps, expected 35', n; end if;

  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and mantra_sanskrit like '%सायं मन्ध्या गायत्री%';
  if n > 0 then raise exception '% step(s) still carry the misprint सायं मन्ध्या गायत्री', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and mantra_sanskrit like '%सायं सन्ध्या गायत्री%';
  if n < 1 then raise exception 'the correction सायं सन्ध्या गायत्री is not present'; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and mantra_sanskrit like '%भूरादिससव्याहृतीनाम्%';
  if n > 0 then raise exception '% step(s) still carry the misprint भूरादिससव्याहृतीनाम्', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and mantra_sanskrit like '%भूरादिसप्तव्याहृतीनाम्%';
  if n < 1 then raise exception 'the correction भूरादिसप्तव्याहृतीनाम् is not present'; end if;

  -- Dandas stripped: they belong in Tamil mantras. See 0048.
  select count(*) into n from public.pooja_steps
   where pooja_id = 'sandhyavandanam'
     and translate(coalesce(mantra_tamil, ''), '।॥', '') ~ '[ऀ-ॿ꣠-ꣿ]';
  if n > 0 then raise exception '% Tamil mantra(s) carry Devanagari', n; end if;

  -- Published, and the planned-with-steps gate is satisfied.
  select count(*) into n from public.poojas where id = 'sandhyavandanam' and status = 'published';
  if n <> 1 then raise exception 'sandhyavandanam was not published'; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
