-- =============================================================================
-- 0052_sandhyavandanam_self_contained.sql
--
-- GENERATED by scripts/build-sandhya-selfcontained.mjs. Do not hand-edit.
--
-- Two faults, both of which make the reader do work the app exists to do.
--
-- STEPS THAT RECITE ALL THREE SITTINGS AT ONCE. Arghya Pradanam said "THREE
-- times in the morning and in the evening; TWICE at noon"; Gayatri Japa said
-- "MORNING 108 ... NOON 32 ... EVENING 64". The reader has already said which
-- sitting they are keeping and is then handed all three to pick from -- at the
-- one moment in the rite when they are counting on their fingers rather than
-- reading. Each becomes three mode-tagged steps.
--
-- Not a new convention: Sankalpam, Apaam Prashanam, Japa Sankalpam, Gayatri
-- Upasthanam and the Surya/Varuna Prarthana already split exactly this way.
-- These two were left as prose because what differs is the COUNT and not the
-- words -- which is precisely why prose fails here. A count buried in a
-- sentence is easier to misread than a mantra that is plainly not yours.
--
-- STEPS THAT NAME ANOTHER STEP INSTEAD OF BEING ONE. Japasthanam Prokshanam
-- opened "Do Achamanam and Anga Vandanam once", and the Navagraha tarpanam
-- closed the same way. Someone who knows the rite reads that as an
-- instruction; someone learning it has to leave the step, find step one, and
-- come back. The book says only "(do aachamanam & angavandanam once)" because
-- it is a reference card for someone who already knows. This app is not.
--
-- So the pair is inserted as real steps at both places the book asks for them.
-- Also not new: Vighneshwara Dhyanam and Pranayamam are already repeated in
-- full as "(japa)" variants rather than back-referenced.
--
-- THE CLONES ARE INSERT...SELECT. Each repeated step copies its mantra and
-- meaning from the row it repeats rather than retyping Devanagari to say the
-- same thing twice, which is how an error gets into one of two places and then
-- has to be found by eye.
--
-- 53 steps in all, 39 in any one sitting (was 45 and 35).
-- =============================================================================

begin;

-- Park every step clear of the numbers about to be assigned. Renumbering in
-- place would collide the moment a step moves onto a number still occupied,
-- and the order of the updates would silently decide the outcome.
update public.pooja_steps set step_number = step_number + 1000 where pooja_id = 'sandhyavandanam';

-- --- the two steps that recited all three sittings ---------------------------
-- Arghya Pradanam: the existing row becomes the morning variant, keeping its id
-- and anything that hangs off it; the other two are cloned from it.
update public.pooja_steps set
  step_title_en = 'Arghya Pradanam — morning',
  step_title_ta = 'அர்க்ய ப்ரதானம் — காலை',
  instruction_en = 'Take water in both cupped hands and let it fall from the fingertips at the end of the mantra. Do this THREE times. Then do one pranayama.',
  instruction_ta = 'இரு உள்ளங்கைகளிலும் நீர் ஏந்தி, மந்திரம் முடியும்போது விரல் நுனிகள் வழியே கீழே விடவும். இதை மூன்று முறை செய்யவும். பின் ஒரு ப்ராணாயாமம்.',
  modes = array['pratah']::text[],
  updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Arghya Pradanam';

insert into public.pooja_steps (
  pooja_id, step_number, step_title_en, step_title_ta, instruction_en, instruction_ta,
  mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
  philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes)
select pooja_id, 3001, 'Arghya Pradanam — noon', 'அர்க்ய ப்ரதானம் — உச்சி',
       'Take water in both cupped hands and let it fall from the fingertips at the end of the mantra. Do this TWICE. Then do one pranayama.',
       'இரு உள்ளங்கைகளிலும் நீர் ஏந்தி, மந்திரம் முடியும்போது விரல் நுனிகள் வழியே கீழே விடவும். இதை இரண்டு முறை செய்யவும். பின் ஒரு ப்ராணாயாமம்.',
       mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
       philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref,
       array['madhyahnika']::text[]
  from public.pooja_steps
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Arghya Pradanam — morning';

insert into public.pooja_steps (
  pooja_id, step_number, step_title_en, step_title_ta, instruction_en, instruction_ta,
  mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
  philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes)
select pooja_id, 3002, 'Arghya Pradanam — evening', 'அர்க்ய ப்ரதானம் — மாலை',
       'Take water in both cupped hands and let it fall from the fingertips at the end of the mantra. Do this THREE times. Then do one pranayama.',
       'இரு உள்ளங்கைகளிலும் நீர் ஏந்தி, மந்திரம் முடியும்போது விரல் நுனிகள் வழியே கீழே விடவும். இதை மூன்று முறை செய்யவும். பின் ஒரு ப்ராணாயாமம்.',
       mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
       philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref,
       array['sayam']::text[]
  from public.pooja_steps
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Arghya Pradanam — morning';

-- Gayatri Japa: the existing row becomes the morning variant, keeping its id
-- and anything that hangs off it; the other two are cloned from it.
update public.pooja_steps set
  step_title_en = 'Gayatri Japa — morning',
  step_title_ta = 'காயத்ரி ஜபம் — காலை',
  instruction_en = 'Count on the joints of the fingers: hold both palms together sideways before the face and begin with the right thumb on the middle line of the ring finger, moving down, across and up in a clockwise circuit of ten, then anticlockwise back for the next ten. Recite the Gayatri 108 times, facing east. Then do one pranayama.',
  instruction_ta = 'விரல் கணுக்களில் எண்ணவும்: இரு உள்ளங்கைகளையும் முகத்திற்கு முன் பக்கவாட்டில் சேர்த்து, வலது கட்டைவிரலை மோதிர விரலின் நடுக்கோட்டில் வைத்துத் தொடங்கி, வலமாகச் சுற்றி பத்து; பின் இடமாகத் திரும்பி அடுத்த பத்து. காயத்ரியை 108 முறை, கிழக்கு நோக்கிச் சொல்லவும். பின் ஒரு ப்ராணாயாமம்.',
  modes = array['pratah']::text[],
  updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Japa';

insert into public.pooja_steps (
  pooja_id, step_number, step_title_en, step_title_ta, instruction_en, instruction_ta,
  mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
  philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes)
select pooja_id, 3003, 'Gayatri Japa — noon', 'காயத்ரி ஜபம் — உச்சி',
       'Count on the joints of the fingers: hold both palms together sideways before the face and begin with the right thumb on the middle line of the ring finger, moving down, across and up in a clockwise circuit of ten, then anticlockwise back for the next ten. Recite the Gayatri 32 times, facing east. Then do one pranayama.',
       'விரல் கணுக்களில் எண்ணவும்: இரு உள்ளங்கைகளையும் முகத்திற்கு முன் பக்கவாட்டில் சேர்த்து, வலது கட்டைவிரலை மோதிர விரலின் நடுக்கோட்டில் வைத்துத் தொடங்கி, வலமாகச் சுற்றி பத்து; பின் இடமாகத் திரும்பி அடுத்த பத்து. காயத்ரியை 32 முறை, கிழக்கு நோக்கிச் சொல்லவும். பின் ஒரு ப்ராணாயாமம்.',
       mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
       philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref,
       array['madhyahnika']::text[]
  from public.pooja_steps
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Japa — morning';

insert into public.pooja_steps (
  pooja_id, step_number, step_title_en, step_title_ta, instruction_en, instruction_ta,
  mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
  philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes)
select pooja_id, 3004, 'Gayatri Japa — evening', 'காயத்ரி ஜபம் — மாலை',
       'Count on the joints of the fingers: hold both palms together sideways before the face and begin with the right thumb on the middle line of the ring finger, moving down, across and up in a clockwise circuit of ten, then anticlockwise back for the next ten. Recite the Gayatri 64 times, facing west if the sun has not yet set and east once it has. Then do one pranayama.',
       'விரல் கணுக்களில் எண்ணவும்: இரு உள்ளங்கைகளையும் முகத்திற்கு முன் பக்கவாட்டில் சேர்த்து, வலது கட்டைவிரலை மோதிர விரலின் நடுக்கோட்டில் வைத்துத் தொடங்கி, வலமாகச் சுற்றி பத்து; பின் இடமாகத் திரும்பி அடுத்த பத்து. காயத்ரியை 64 முறை சொல்லவும்; சூரியன் மறையும் முன் மேற்கு நோக்கியும், மறைந்த பின் கிழக்கு நோக்கியும். பின் ஒரு ப்ராணாயாமம்.',
       mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
       philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref,
       array['sayam']::text[]
  from public.pooja_steps
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Japa — morning';

-- --- the pair the book asks for twice more ------------------------------------
-- Achamanam (after tarpanam), carrying Achamanam's mantra by copy rather than by retyping.
insert into public.pooja_steps (
  pooja_id, step_number, step_title_en, step_title_ta, instruction_en, instruction_ta,
  mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
  philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes)
select pooja_id, 2000, 'Achamanam (after tarpanam)', 'ஆசமனம் (தர்ப்பணத்திற்குப் பின்)',
       'The same three sips again, closing the tarpanam. Fold the forefinger of the right hand against the thumb, hold a spoonful of water in the palm, and sip once at each of the three names.',
       'தர்ப்பணத்தை நிறைவு செய்ய மீண்டும் அதே மூன்று முறை நீர் உள்கொள்ளல். வலது கையின் ஆட்காட்டி விரலை கட்டைவிரலுடன் சேர்த்து, உள்ளங்கையில் ஒரு உத்தரிணி நீர் வைத்து, மூன்று நாமங்களிலும் ஒவ்வொரு முறை உள்கொள்ளவும்.',
       mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
       philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes
  from public.pooja_steps
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Achamanam';

-- Anga Vandanam (after tarpanam), carrying Anga Vandanam's mantra by copy rather than by retyping.
insert into public.pooja_steps (
  pooja_id, step_number, step_title_en, step_title_ta, instruction_en, instruction_ta,
  mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
  philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes)
select pooja_id, 2001, 'Anga Vandanam (after tarpanam)', 'அங்க வந்தனம் (தர்ப்பணத்திற்குப் பின்)',
       'And the twelve names again, two at a time: thumb to the cheeks, ring finger to the eyes, forefinger to the nostrils, little finger to the ears, middle finger to the shoulders, and all the fingers to the heart and the crown.',
       'பின் மீண்டும் பன்னிரண்டு நாமங்கள், இரண்டிரண்டாக — கட்டைவிரலால் கன்னங்கள், மோதிர விரலால் கண்கள், ஆட்காட்டி விரலால் நாசிகள், சுண்டு விரலால் காதுகள், நடுவிரலால் தோள்கள், அனைத்து விரல்களாலும் இதயமும் உச்சந்தலையும்.',
       mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
       philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes
  from public.pooja_steps
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Anga Vandanam';

-- Achamanam (before prokshanam), carrying Achamanam's mantra by copy rather than by retyping.
insert into public.pooja_steps (
  pooja_id, step_number, step_title_en, step_title_ta, instruction_en, instruction_ta,
  mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
  philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes)
select pooja_id, 2002, 'Achamanam (before prokshanam)', 'ஆசமனம் (ப்ரோக்ஷணத்திற்கு முன்)',
       'The three sips once more, before the place of japa is sprinkled. Hold a spoonful of water in the palm as before and sip once at each of the three names.',
       'ஜபஸ்தானம் ப்ரோக்ஷணத்திற்கு முன் மீண்டும் மூன்று முறை நீர் உள்கொள்ளல். முன்பு போலவே உள்ளங்கையில் ஒரு உத்தரிணி நீர் வைத்து, மூன்று நாமங்களிலும் ஒவ்வொரு முறை உள்கொள்ளவும்.',
       mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
       philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes
  from public.pooja_steps
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Achamanam';

-- Anga Vandanam (before prokshanam), carrying Anga Vandanam's mantra by copy rather than by retyping.
insert into public.pooja_steps (
  pooja_id, step_number, step_title_en, step_title_ta, instruction_en, instruction_ta,
  mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
  philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes)
select pooja_id, 2003, 'Anga Vandanam (before prokshanam)', 'அங்க வந்தனம் (ப்ரோக்ஷணத்திற்கு முன்)',
       'And the twelve names once more, touching each pair to its place: cheeks, eyes, nostrils, ears, shoulders, then the heart and the crown.',
       'பின் மீண்டும் பன்னிரண்டு நாமங்கள், ஒவ்வொரு ஜோடியையும் அதன் இடத்தில் தொட்டு — கன்னங்கள், கண்கள், நாசிகள், காதுகள், தோள்கள், பின் இதயமும் உச்சந்தலையும்.',
       mantra_sanskrit, mantra_tamil, mantra_translit, meaning_en, is_dynamic_sankalpam,
       philosophy_en, philosophy_ta, phase, scripts_generated, gender_rule, source_ref, modes
  from public.pooja_steps
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Anga Vandanam';

-- --- instructions that pointed at another step --------------------------------
update public.pooja_steps set
  instruction_en = 'Take water in the hand and let it fall from the fingertips once after each name. Achamanam and Anga Vandanam follow, once each, as the next two steps.',
  instruction_ta = 'கையில் நீர் எடுத்து, ஒவ்வொரு நாமத்திற்குப் பின்னும் விரல் நுனிகள் வழியே ஒரு முறை விடவும். அடுத்த இரு படிகளாக ஆசமனமும் அங்கவந்தனமும் ஒரு முறை வரும்.',
  updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Navagraha Deva Tarpanam';

update public.pooja_steps set
  instruction_en = 'Hold the hands as for the Sankalpam and recite. Then take water in both cupped hands and let it fall from the fingertips once more, and pass water around the head reciting the closing line.',
  instruction_ta = 'ஸங்கல்பத்தில் செய்தது போல கைகளை வைத்துச் சொல்லவும். பின் இரு உள்ளங்கைகளிலும் நீர் ஏந்தி, விரல் நுனிகள் வழியே மீண்டும் ஒரு முறை விடவும்; இறுதி வரியைச் சொல்லியபடி தலையைச் சுற்றி நீர் சுழற்றவும்.',
  updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Prayashchitta Arghyam';

update public.pooja_steps set
  instruction_en = 'Take water in the hand, pour it down at the end of the mantra, and make a tilak with it. Finally pour water onto the plate as an offering while saying the closing line.',
  instruction_ta = 'கையில் நீர் எடுத்து, மந்திரம் முடியும்போது கீழே விட்டு, அந்த நீரால் திலகம் இடவும். இறுதியாக, இறுதி வரியைச் சொல்லியபடி தாம்பாளத்தில் நீரை அர்ப்பணமாக விடவும்.',
  updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Japasthanam Prokshanam';

update public.pooja_steps set
  instruction_en = 'Fold the index and middle fingers. Close the right nostril with the thumb and the left with the ring and little fingers. Breathe IN through the left through the seven worlds, HOLD through the Gayatri, and breathe OUT through the right through om aapo jyoti.',
  instruction_ta = 'ஆட்காட்டி, நடுவிரல்களை மடக்கவும். வலது நாசியைக் கட்டைவிரலாலும், இடது நாசியை மோதிர, சுண்டு விரல்களாலும் அடைக்கவும். இடது நாசி வழியே ஏழு லோகங்களுடன் மூச்சை இழுக்கவும்; காயத்ரியுடன் நிறுத்தவும்; வலது நாசி வழியே "ஓம் ஆபோ ஜ்யோதி" உடன் வெளியிடவும்.',
  updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Pranayamam (japa)';

-- --- the rite, in order -------------------------------------------------------
update public.pooja_steps set step_number = 1, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Achamanam';
update public.pooja_steps set step_number = 2, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Anga Vandanam';
update public.pooja_steps set step_number = 3, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Vighneshwara Dhyanam';
update public.pooja_steps set step_number = 4, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Pranayamam';
update public.pooja_steps set step_number = 5, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Sankalpam — morning';
update public.pooja_steps set step_number = 6, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Sankalpam — noon';
update public.pooja_steps set step_number = 7, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Sankalpam — evening';
update public.pooja_steps set step_number = 8, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Jala Prarthana';
update public.pooja_steps set step_number = 9, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Marjanam';
update public.pooja_steps set step_number = 10, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Apaam Prashanam — morning';
update public.pooja_steps set step_number = 11, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Apaam Prashanam — noon';
update public.pooja_steps set step_number = 12, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Apaam Prashanam — evening';
update public.pooja_steps set step_number = 13, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Punar Marjanam';
update public.pooja_steps set step_number = 14, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Arghya Pradanam — morning';
update public.pooja_steps set step_number = 15, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Arghya Pradanam — noon';
update public.pooja_steps set step_number = 16, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Arghya Pradanam — evening';
update public.pooja_steps set step_number = 17, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Prayashchitta Arghyam';
update public.pooja_steps set step_number = 18, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Aikyanusandhanam';
update public.pooja_steps set step_number = 19, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Navagraha Deva Tarpanam';
update public.pooja_steps set step_number = 20, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Achamanam (after tarpanam)';
update public.pooja_steps set step_number = 21, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Anga Vandanam (after tarpanam)';
update public.pooja_steps set step_number = 22, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Conclusion of the First Part';
update public.pooja_steps set step_number = 23, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Namaskara Mantras';
update public.pooja_steps set step_number = 24, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Prarthana';
update public.pooja_steps set step_number = 25, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Asana Mantra';
update public.pooja_steps set step_number = 26, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Vighneshwara Dhyanam (japa)';
update public.pooja_steps set step_number = 27, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Pranayamam (japa)';
update public.pooja_steps set step_number = 28, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Japa Sankalpam — morning';
update public.pooja_steps set step_number = 29, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Japa Sankalpam — noon';
update public.pooja_steps set step_number = 30, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Japa Sankalpam — evening';
update public.pooja_steps set step_number = 31, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Pranava Japa';
update public.pooja_steps set step_number = 32, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Avahanam';
update public.pooja_steps set step_number = 33, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Nyasa';
update public.pooja_steps set step_number = 34, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Dhyanam';
update public.pooja_steps set step_number = 35, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Japa — morning';
update public.pooja_steps set step_number = 36, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Japa — noon';
update public.pooja_steps set step_number = 37, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Japa — evening';
update public.pooja_steps set step_number = 38, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Upasthanam — morning';
update public.pooja_steps set step_number = 39, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Upasthanam — noon';
update public.pooja_steps set step_number = 40, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Gayatri Upasthanam — evening';
update public.pooja_steps set step_number = 41, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Surya Prarthana — morning';
update public.pooja_steps set step_number = 42, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Surya Prarthana — noon';
update public.pooja_steps set step_number = 43, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Varuna Prarthana — evening';
update public.pooja_steps set step_number = 44, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Samashti Abhivadanam';
update public.pooja_steps set step_number = 45, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Abhivadanam';
update public.pooja_steps set step_number = 46, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Dig Devata Vandanam';
update public.pooja_steps set step_number = 47, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Yama Vandanam';
update public.pooja_steps set step_number = 48, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Harihara Vandanam';
update public.pooja_steps set step_number = 49, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Suryanarayana Vandanam';
update public.pooja_steps set step_number = 50, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Samarpanam';
update public.pooja_steps set step_number = 51, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Achamanam (before prokshanam)';
update public.pooja_steps set step_number = 52, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Anga Vandanam (before prokshanam)';
update public.pooja_steps set step_number = 53, updated_at = now()
 where pooja_id = 'sandhyavandanam' and step_title_en = 'Japasthanam Prokshanam';

-- --- assert ------------------------------------------------------------------
do $$
declare n int; t text;
begin
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam';
  if n <> 53 then raise exception 'rite has % steps, expected 53', n; end if;

  -- Nothing was left parked. A step still above 1000 is one ORDER does not
  -- name, which means it would sort to the end of the rite rather than vanish
  -- -- the kind of fault that shows up as a stray step at the bottom and not
  -- as an error.
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number > 1000;
  if n > 0 then raise exception '% step(s) were never renumbered', n; end if;

  -- Dense 1..n, so the step sheet has no gaps and no two steps collide.
  select count(*) into n from (
    select step_number from public.pooja_steps where pooja_id = 'sandhyavandanam'
     group by step_number having count(*) > 1) d;
  if n > 0 then raise exception '% duplicated step_number(s)', n; end if;
  select count(*) into n from generate_series(1, 53) g
   where not exists (select 1 from public.pooja_steps where pooja_id = 'sandhyavandanam' and step_number = g);
  if n > 0 then raise exception '% gap(s) in step_number', n; end if;

  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and 'pratah' = any(modes);
  if n <> 39 then raise exception 'morning has % steps, expected 39', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and 'madhyahnika' = any(modes);
  if n <> 39 then raise exception 'noon has % steps, expected 39', n; end if;
  select count(*) into n from public.pooja_steps where pooja_id = 'sandhyavandanam' and 'sayam' = any(modes);
  if n <> 39 then raise exception 'evening has % steps, expected 39', n; end if;

  -- THE ACTUAL POINT OF THE MIGRATION, and neither half of it is a count.
  --
  -- No surviving instruction may name two different sittings. Checked against
  -- the stored rows rather than the generator: the generator validates its own
  -- strings, which proves nothing about what a renumber or a clone put in the
  -- table.
  select string_agg(step_title_en, likeN) into t from (
    select step_title_en, chr(10) || '    ' as likeN from public.pooja_steps
     where pooja_id = 'sandhyavandanam'
       and (case when instruction_en ~* '\mmorning\M' then 1 else 0 end
          + case when instruction_en ~* '\m(noon|midday)\M' then 1 else 0 end
          + case when instruction_en ~* '\mevening\M' then 1 else 0 end) > 1) x;
  if t is not null then raise exception 'step(s) still recite more than one sitting: %', t; end if;

  -- And none may hand the reader a homework assignment.
  select string_agg(step_title_en, ', ') into t from public.pooja_steps
   where pooja_id = 'sandhyavandanam' and instruction_en ~* 'do achamanam|do anga vandanam';
  if t is not null then raise exception 'step(s) still refer the reader elsewhere: %', t; end if;

  -- Each repeated step carries the SAME mantra as the step it repeats. The
  -- clone is an INSERT...SELECT so this holds by construction -- which is
  -- exactly why it is worth asserting: if someone later edits one of the two by
  -- hand, the construction no longer holds and nothing else would notice.
  select count(*) into n from public.pooja_steps a, public.pooja_steps b
   where a.pooja_id = 'sandhyavandanam' and a.step_title_en = 'Achamanam (after tarpanam)'
     and b.pooja_id = 'sandhyavandanam' and b.step_title_en = 'Achamanam'
     and a.mantra_sanskrit is not distinct from b.mantra_sanskrit
     and a.mantra_tamil is not distinct from b.mantra_tamil
     and a.mantra_translit is not distinct from b.mantra_translit;
  if n <> 1 then raise exception 'Achamanam (after tarpanam) does not carry Achamanam''s mantra'; end if;
  select count(*) into n from public.pooja_steps a, public.pooja_steps b
   where a.pooja_id = 'sandhyavandanam' and a.step_title_en = 'Anga Vandanam (after tarpanam)'
     and b.pooja_id = 'sandhyavandanam' and b.step_title_en = 'Anga Vandanam'
     and a.mantra_sanskrit is not distinct from b.mantra_sanskrit
     and a.mantra_tamil is not distinct from b.mantra_tamil
     and a.mantra_translit is not distinct from b.mantra_translit;
  if n <> 1 then raise exception 'Anga Vandanam (after tarpanam) does not carry Anga Vandanam''s mantra'; end if;
  select count(*) into n from public.pooja_steps a, public.pooja_steps b
   where a.pooja_id = 'sandhyavandanam' and a.step_title_en = 'Achamanam (before prokshanam)'
     and b.pooja_id = 'sandhyavandanam' and b.step_title_en = 'Achamanam'
     and a.mantra_sanskrit is not distinct from b.mantra_sanskrit
     and a.mantra_tamil is not distinct from b.mantra_tamil
     and a.mantra_translit is not distinct from b.mantra_translit;
  if n <> 1 then raise exception 'Achamanam (before prokshanam) does not carry Achamanam''s mantra'; end if;
  select count(*) into n from public.pooja_steps a, public.pooja_steps b
   where a.pooja_id = 'sandhyavandanam' and a.step_title_en = 'Anga Vandanam (before prokshanam)'
     and b.pooja_id = 'sandhyavandanam' and b.step_title_en = 'Anga Vandanam'
     and a.mantra_sanskrit is not distinct from b.mantra_sanskrit
     and a.mantra_tamil is not distinct from b.mantra_tamil
     and a.mantra_translit is not distinct from b.mantra_translit;
  if n <> 1 then raise exception 'Anga Vandanam (before prokshanam) does not carry Anga Vandanam''s mantra'; end if;

  -- Every step has Tamil, which is the 0048 lesson: that migration shipped
  -- eighteen steps with instruction_ta empty while every other pooja had Tamil
  -- on every row, and the step count did not notice.
  select string_agg(step_title_en, ', ') into t from public.pooja_steps
   where pooja_id = 'sandhyavandanam'
     and (coalesce(trim(step_title_ta), '') = '' or coalesce(trim(instruction_ta), '') = '');
  if t is not null then raise exception 'step(s) have no Tamil: %', t; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
