-- =============================================================================
-- 0053_samagri_in_english.sql
--
-- GENERATED by scripts/build-samagri-english.mjs. Do not hand-edit.
--
-- THE ENGLISH COLUMN WAS OFTEN NOT ENGLISH. samagri_items has item_en and
-- item_ta; item_ta is proper Tamil script, so item_en is the column that has
-- to answer "what am I actually buying". For about half the rows it did not --
-- it was the Tamil or Sanskrit word in roman letters. Chandanam. Akshadai.
-- Vetrilai. Bilvam. A reader who does not already know the rite got a list of
-- words they cannot shop with, which is exactly the reader this app is for,
-- and the appearance of a translation is worse than an obvious gap because
-- there is nothing to click.
--
-- THE CONVENTION IS ALREADY IN THE DATA. 27 of 90 rows do this properly --
-- "Mani (pooja bell)", "Vilakku (lamp)" -- so this follows that rather than
-- inventing a format. Traditional name first, because that is what you say in
-- the shop and what every other source calls it; English in brackets after.
-- Nothing is renamed, nothing is dropped, a gloss is added where none was.
--
-- SANDHYAVANDANAM KEPT ITS GLOSSES IN THE WRONG COLUMN: "Uddharani
-- (Aachamani)" with quantity "1 - the spoon". The English existed but sat in
-- the quantity field, so the item list read as transliteration and the
-- quantity column read as a glossary. Both go back to their own jobs.
--
-- AND TWO ITEMS THAT ARE NOT SAMAGRI: a recording of the mantras, and a
-- printed text "or this app". Learning aids, not ritual material -- you cannot
-- forget to bring them and have to stop -- and a checklist listing itself is
-- faintly silly. Both were optional, so nothing required is lost.
-- =============================================================================

begin;

-- Every change below asserts the row still says what the generator thought it
-- said. An UPDATE whose WHERE matches nothing is the quietest failure there
-- is: it reports success, changes nothing, and the next person reads the
-- migration rather than the table and believes it.
do $$
declare n int;
begin
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 1 and item_en = 'Pancha pathram and uddharani';
  if n <> 1 then raise exception 'ganesha_standard/1 does not read %', 'Pancha pathram and uddharani'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 6 and item_en = 'Clay or turmeric Pillaiyar';
  if n <> 1 then raise exception 'ganesha_standard/6 does not read %', 'Clay or turmeric Pillaiyar'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 7 and item_en = 'Vasthram for Ganapati';
  if n <> 1 then raise exception 'ganesha_standard/7 does not read %', 'Vasthram for Ganapati'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 8 and item_en = 'Poonal, a single one for Ganapati';
  if n <> 1 then raise exception 'ganesha_standard/8 does not read %', 'Poonal, a single one for Ganapati'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 10 and item_en = 'Manjal powder';
  if n <> 1 then raise exception 'ganesha_standard/10 does not read %', 'Manjal powder'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 11 and item_en = 'Chandanam';
  if n <> 1 then raise exception 'ganesha_standard/11 does not read %', 'Chandanam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 12 and item_en = 'Kumkumam';
  if n <> 1 then raise exception 'ganesha_standard/12 does not read %', 'Kumkumam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 13 and item_en = 'Akshadai';
  if n <> 1 then raise exception 'ganesha_standard/13 does not read %', 'Akshadai'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 14 and item_en = 'Panchamirtham';
  if n <> 1 then raise exception 'ganesha_standard/14 does not read %', 'Panchamirtham'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 15 and item_en = 'Agarbatti';
  if n <> 1 then raise exception 'ganesha_standard/15 does not read %', 'Agarbatti'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 16 and item_en = 'Kalpooram';
  if n <> 1 then raise exception 'ganesha_standard/16 does not read %', 'Kalpooram'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 18 and item_en = 'Til oil for the lamp';
  if n <> 1 then raise exception 'ganesha_standard/18 does not read %', 'Til oil for the lamp'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 20 and item_en = 'Vetrilai';
  if n <> 1 then raise exception 'ganesha_standard/20 does not read %', 'Vetrilai'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 21 and item_en = 'Paakku';
  if n <> 1 then raise exception 'ganesha_standard/21 does not read %', 'Paakku'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 26 and item_en = 'Maalai';
  if n <> 1 then raise exception 'ganesha_standard/26 does not read %', 'Maalai'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 27 and item_en = 'Thoduttha pushpam';
  if n <> 1 then raise exception 'ganesha_standard/27 does not read %', 'Thoduttha pushpam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 28 and item_en = 'Arugampul';
  if n <> 1 then raise exception 'ganesha_standard/28 does not read %', 'Arugampul'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 30 and item_en = 'Thulasi';
  if n <> 1 then raise exception 'ganesha_standard/30 does not read %', 'Thulasi'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 31 and item_en = 'Bilvam';
  if n <> 1 then raise exception 'ganesha_standard/31 does not read %', 'Bilvam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 2 and item_en = 'Shalagrama for Vishnu';
  if n <> 1 then raise exception 'nitya_panchayatana/2 does not read %', 'Shalagrama for Vishnu'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 6 and item_en = 'Pancha pathram and uddharani';
  if n <> 1 then raise exception 'nitya_panchayatana/6 does not read %', 'Pancha pathram and uddharani'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 10 and item_en = 'Karpoora thattu';
  if n <> 1 then raise exception 'nitya_panchayatana/10 does not read %', 'Karpoora thattu'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 11 and item_en = 'Chandanam';
  if n <> 1 then raise exception 'nitya_panchayatana/11 does not read %', 'Chandanam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 12 and item_en = 'Kumkumam';
  if n <> 1 then raise exception 'nitya_panchayatana/12 does not read %', 'Kumkumam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 13 and item_en = 'Akshadai';
  if n <> 1 then raise exception 'nitya_panchayatana/13 does not read %', 'Akshadai'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 14 and item_en = 'Manjal powder';
  if n <> 1 then raise exception 'nitya_panchayatana/14 does not read %', 'Manjal powder'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 15 and item_en = 'Agarbatti and karpooram';
  if n <> 1 then raise exception 'nitya_panchayatana/15 does not read %', 'Agarbatti and karpooram'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 17 and item_en = 'Vetrilai and paakku';
  if n <> 1 then raise exception 'nitya_panchayatana/17 does not read %', 'Vetrilai and paakku'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 18 and item_en = 'Doorvai (arugampul), for Vinayaka';
  if n <> 1 then raise exception 'nitya_panchayatana/18 does not read %', 'Doorvai (arugampul), for Vinayaka'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 19 and item_en = 'Thulasi, for Vishnu';
  if n <> 1 then raise exception 'nitya_panchayatana/19 does not read %', 'Thulasi, for Vishnu'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 20 and item_en = 'Bilvam, for Shiva';
  if n <> 1 then raise exception 'nitya_panchayatana/20 does not read %', 'Bilvam, for Shiva'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 21 and item_en = 'Thamarai poo, for Surya';
  if n <> 1 then raise exception 'nitya_panchayatana/21 does not read %', 'Thamarai poo, for Surya'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 22 and item_en = 'Red aparajita, for Devi';
  if n <> 1 then raise exception 'nitya_panchayatana/22 does not read %', 'Red aparajita, for Devi'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 1 and item_en = 'Panchapatram';
  if n <> 1 then raise exception 'sandhyavandanam/1 does not read %', 'Panchapatram'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 2 and item_en = 'Uddharani (Aachamani)';
  if n <> 1 then raise exception 'sandhyavandanam/2 does not read %', 'Uddharani (Aachamani)'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 3 and item_en = 'Theertha patram (thambalam)';
  if n <> 1 then raise exception 'sandhyavandanam/3 does not read %', 'Theertha patram (thambalam)'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 4 and item_en = 'Aasanam';
  if n <> 1 then raise exception 'sandhyavandanam/4 does not read %', 'Aasanam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 5 and item_en = 'Jalapatram';
  if n <> 1 then raise exception 'sandhyavandanam/5 does not read %', 'Jalapatram'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 6 and item_en = 'Yajnopaveetam (poonal)';
  if n <> 1 then raise exception 'sandhyavandanam/6 does not read %', 'Yajnopaveetam (poonal)'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 8 and item_en = 'Upavastram (uttareeyam)';
  if n <> 1 then raise exception 'sandhyavandanam/8 does not read %', 'Upavastram (uttareeyam)'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 1 and item_en = 'Kalasham with a Lakshmi face';
  if n <> 1 then raise exception 'varalakshmi_vratham/1 does not read %', 'Kalasham with a Lakshmi face'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 2 and item_en = 'Pancha pathram and uddharani';
  if n <> 1 then raise exception 'varalakshmi_vratham/2 does not read %', 'Pancha pathram and uddharani'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 6 and item_en = 'Karpoora thattu';
  if n <> 1 then raise exception 'varalakshmi_vratham/6 does not read %', 'Karpoora thattu'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 7 and item_en = 'Eka aarathi and pancha aarathi';
  if n <> 1 then raise exception 'varalakshmi_vratham/7 does not read %', 'Eka aarathi and pancha aarathi'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 8 and item_en = 'Nonbu sharadu, nine strands with nine knots';
  if n <> 1 then raise exception 'varalakshmi_vratham/8 does not read %', 'Nonbu sharadu, nine strands with nine knots'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 9 and item_en = 'Chandanam';
  if n <> 1 then raise exception 'varalakshmi_vratham/9 does not read %', 'Chandanam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 10 and item_en = 'Kumkumam';
  if n <> 1 then raise exception 'varalakshmi_vratham/10 does not read %', 'Kumkumam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 11 and item_en = 'Akshadai';
  if n <> 1 then raise exception 'varalakshmi_vratham/11 does not read %', 'Akshadai'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 12 and item_en = 'Manjal powder';
  if n <> 1 then raise exception 'varalakshmi_vratham/12 does not read %', 'Manjal powder'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 13 and item_en = 'Agarbatti and karpooram';
  if n <> 1 then raise exception 'varalakshmi_vratham/13 does not read %', 'Agarbatti and karpooram'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 14 and item_en = 'Thamarai poo';
  if n <> 1 then raise exception 'varalakshmi_vratham/14 does not read %', 'Thamarai poo'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 16 and item_en = 'Thazam poo';
  if n <> 1 then raise exception 'varalakshmi_vratham/16 does not read %', 'Thazam poo'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 17 and item_en = 'Maalai or kadambam';
  if n <> 1 then raise exception 'varalakshmi_vratham/17 does not read %', 'Maalai or kadambam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 18 and item_en = 'Doorvai (arugampul) and thulasi';
  if n <> 1 then raise exception 'varalakshmi_vratham/18 does not read %', 'Doorvai (arugampul) and thulasi'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 19 and item_en = 'Bilvam';
  if n <> 1 then raise exception 'varalakshmi_vratham/19 does not read %', 'Bilvam'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 20 and item_en = 'Vetrilai and paakku';
  if n <> 1 then raise exception 'varalakshmi_vratham/20 does not read %', 'Vetrilai and paakku'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 2 and quantity = '1 — the spoon';
  if n <> 1 then raise exception 'sandhyavandanam/2 quantity does not read %', '1 — the spoon'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 5 and quantity = '1 — for the spare water';
  if n <> 1 then raise exception 'sandhyavandanam/5 quantity does not read %', '1 — for the spare water'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 6 and quantity = '1 — the sacred thread';
  if n <> 1 then raise exception 'sandhyavandanam/6 quantity does not read %', '1 — the sacred thread'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 8 and quantity = '1 — the upper cloth';
  if n <> 1 then raise exception 'sandhyavandanam/8 quantity does not read %', '1 — the upper cloth'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 9 and item_en = 'A recording of the mantras';
  if n <> 1 then raise exception 'sandhyavandanam/9 does not read %', 'A recording of the mantras'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 10 and item_en = 'A printed sandhyavandanam text';
  if n <> 1 then raise exception 'sandhyavandanam/10 does not read %', 'A printed sandhyavandanam text'; end if;
end $$;

-- --- the English the list was missing ----------------------------------------
update public.samagri_items set item_en = 'Pancha pathram and uddharani (water vessel and spoon)'
 where pooja_id = 'ganesha_standard' and seq = 1;
update public.samagri_items set item_en = 'Clay or turmeric Pillaiyar (the Ganesha idol)'
 where pooja_id = 'ganesha_standard' and seq = 6;
update public.samagri_items set item_en = 'Vasthram for Ganapati (a cloth for the idol)'
 where pooja_id = 'ganesha_standard' and seq = 7;
update public.samagri_items set item_en = 'Poonal, a single one for Ganapati (sacred thread)'
 where pooja_id = 'ganesha_standard' and seq = 8;
update public.samagri_items set item_en = 'Manjal (turmeric) powder'
 where pooja_id = 'ganesha_standard' and seq = 10;
update public.samagri_items set item_en = 'Chandanam (sandalwood paste)'
 where pooja_id = 'ganesha_standard' and seq = 11;
update public.samagri_items set item_en = 'Kumkumam (vermilion)'
 where pooja_id = 'ganesha_standard' and seq = 12;
update public.samagri_items set item_en = 'Akshadai (rice with turmeric)'
 where pooja_id = 'ganesha_standard' and seq = 13;
update public.samagri_items set item_en = 'Panchamirtham (the five-food mixture)'
 where pooja_id = 'ganesha_standard' and seq = 14;
update public.samagri_items set item_en = 'Agarbatti (incense sticks)'
 where pooja_id = 'ganesha_standard' and seq = 15;
update public.samagri_items set item_en = 'Kalpooram (camphor)'
 where pooja_id = 'ganesha_standard' and seq = 16;
update public.samagri_items set item_en = 'Til (sesame) oil for the lamp'
 where pooja_id = 'ganesha_standard' and seq = 18;
update public.samagri_items set item_en = 'Vetrilai (betel leaves)'
 where pooja_id = 'ganesha_standard' and seq = 20;
update public.samagri_items set item_en = 'Paakku (areca nut)'
 where pooja_id = 'ganesha_standard' and seq = 21;
update public.samagri_items set item_en = 'Maalai (flower garland)'
 where pooja_id = 'ganesha_standard' and seq = 26;
update public.samagri_items set item_en = 'Thoduttha pushpam (strung flowers)'
 where pooja_id = 'ganesha_standard' and seq = 27;
update public.samagri_items set item_en = 'Arugampul (durva grass)'
 where pooja_id = 'ganesha_standard' and seq = 28;
update public.samagri_items set item_en = 'Thulasi (holy basil)'
 where pooja_id = 'ganesha_standard' and seq = 30;
update public.samagri_items set item_en = 'Bilvam (bael leaves)'
 where pooja_id = 'ganesha_standard' and seq = 31;
update public.samagri_items set item_en = 'Shalagrama for Vishnu (the sacred stone)'
 where pooja_id = 'nitya_panchayatana' and seq = 2;
update public.samagri_items set item_en = 'Pancha pathram and uddharani (water vessel and spoon)'
 where pooja_id = 'nitya_panchayatana' and seq = 6;
update public.samagri_items set item_en = 'Karpoora thattu (camphor tray)'
 where pooja_id = 'nitya_panchayatana' and seq = 10;
update public.samagri_items set item_en = 'Chandanam (sandalwood paste)'
 where pooja_id = 'nitya_panchayatana' and seq = 11;
update public.samagri_items set item_en = 'Kumkumam (vermilion)'
 where pooja_id = 'nitya_panchayatana' and seq = 12;
update public.samagri_items set item_en = 'Akshadai (rice with turmeric)'
 where pooja_id = 'nitya_panchayatana' and seq = 13;
update public.samagri_items set item_en = 'Manjal (turmeric) powder'
 where pooja_id = 'nitya_panchayatana' and seq = 14;
update public.samagri_items set item_en = 'Agarbatti and karpooram (incense sticks and camphor)'
 where pooja_id = 'nitya_panchayatana' and seq = 15;
update public.samagri_items set item_en = 'Vetrilai and paakku (betel leaves and areca nut)'
 where pooja_id = 'nitya_panchayatana' and seq = 17;
update public.samagri_items set item_en = 'Doorvai or arugampul (durva grass), for Vinayaka'
 where pooja_id = 'nitya_panchayatana' and seq = 18;
update public.samagri_items set item_en = 'Thulasi (holy basil), for Vishnu'
 where pooja_id = 'nitya_panchayatana' and seq = 19;
update public.samagri_items set item_en = 'Bilvam (bael leaves), for Shiva'
 where pooja_id = 'nitya_panchayatana' and seq = 20;
update public.samagri_items set item_en = 'Thamarai poo (lotus), for Surya'
 where pooja_id = 'nitya_panchayatana' and seq = 21;
update public.samagri_items set item_en = 'Red aparajita (butterfly pea), for Devi'
 where pooja_id = 'nitya_panchayatana' and seq = 22;
update public.samagri_items set item_en = 'Panchapatram (the water vessel)'
 where pooja_id = 'sandhyavandanam' and seq = 1;
update public.samagri_items set item_en = 'Uddharani (the spoon water is sipped from)'
 where pooja_id = 'sandhyavandanam' and seq = 2;
update public.samagri_items set item_en = 'Theertha patram (the broad plate)'
 where pooja_id = 'sandhyavandanam' and seq = 3;
update public.samagri_items set item_en = 'Aasanam (the seat)'
 where pooja_id = 'sandhyavandanam' and seq = 4;
update public.samagri_items set item_en = 'Jalapatram (vessel for the spare water)'
 where pooja_id = 'sandhyavandanam' and seq = 5;
update public.samagri_items set item_en = 'Yajnopaveetam (the sacred thread)'
 where pooja_id = 'sandhyavandanam' and seq = 6;
update public.samagri_items set item_en = 'Upavastram (the upper cloth)'
 where pooja_id = 'sandhyavandanam' and seq = 8;
update public.samagri_items set item_en = 'Kalasham (the pot) with a Lakshmi face'
 where pooja_id = 'varalakshmi_vratham' and seq = 1;
update public.samagri_items set item_en = 'Pancha pathram and uddharani (water vessel and spoon)'
 where pooja_id = 'varalakshmi_vratham' and seq = 2;
update public.samagri_items set item_en = 'Karpoora thattu (camphor tray)'
 where pooja_id = 'varalakshmi_vratham' and seq = 6;
update public.samagri_items set item_en = 'Eka aarathi and pancha aarathi (single-wick and five-wick camphor lamps)'
 where pooja_id = 'varalakshmi_vratham' and seq = 7;
update public.samagri_items set item_en = 'Nonbu sharadu (the vow thread), nine strands with nine knots'
 where pooja_id = 'varalakshmi_vratham' and seq = 8;
update public.samagri_items set item_en = 'Chandanam (sandalwood paste)'
 where pooja_id = 'varalakshmi_vratham' and seq = 9;
update public.samagri_items set item_en = 'Kumkumam (vermilion)'
 where pooja_id = 'varalakshmi_vratham' and seq = 10;
update public.samagri_items set item_en = 'Akshadai (rice with turmeric)'
 where pooja_id = 'varalakshmi_vratham' and seq = 11;
update public.samagri_items set item_en = 'Manjal (turmeric) powder'
 where pooja_id = 'varalakshmi_vratham' and seq = 12;
update public.samagri_items set item_en = 'Agarbatti and karpooram (incense sticks and camphor)'
 where pooja_id = 'varalakshmi_vratham' and seq = 13;
update public.samagri_items set item_en = 'Thamarai poo (lotus flowers)'
 where pooja_id = 'varalakshmi_vratham' and seq = 14;
update public.samagri_items set item_en = 'Thazam poo (screwpine flower)'
 where pooja_id = 'varalakshmi_vratham' and seq = 16;
update public.samagri_items set item_en = 'Maalai or kadambam (flower garland)'
 where pooja_id = 'varalakshmi_vratham' and seq = 17;
update public.samagri_items set item_en = 'Doorvai (durva grass) and thulasi (holy basil)'
 where pooja_id = 'varalakshmi_vratham' and seq = 18;
update public.samagri_items set item_en = 'Bilvam (bael leaves)'
 where pooja_id = 'varalakshmi_vratham' and seq = 19;
update public.samagri_items set item_en = 'Vetrilai and paakku (betel leaves and areca nut)'
 where pooja_id = 'varalakshmi_vratham' and seq = 20;

-- --- quantities that had become a glossary -----------------------------------
update public.samagri_items set quantity = '1'
 where pooja_id = 'sandhyavandanam' and seq = 2;
update public.samagri_items set quantity = '1'
 where pooja_id = 'sandhyavandanam' and seq = 5;
update public.samagri_items set quantity = '1'
 where pooja_id = 'sandhyavandanam' and seq = 6;
update public.samagri_items set quantity = '1'
 where pooja_id = 'sandhyavandanam' and seq = 8;

-- --- things that are not ritual material --------------------------------------
delete from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 9;
delete from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 10;

-- --- assert ------------------------------------------------------------------
do $$
declare n int; t text;
begin
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam';
  if n <> 8 then raise exception 'sandhyavandanam has % samagri items, expected 8', n; end if;

  -- Nothing REQUIRED was removed. The two that went were both optional, and a
  -- migration that trimmed a required item would be taking something off the
  -- list that the rite cannot be performed without.
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and is_required;
  if n <> 8 then raise exception 'sandhyavandanam has % required items, expected 8', n; end if;

  -- THE POINT OF THE MIGRATION. Every row this touched now carries English in
  -- brackets, checked against the stored value rather than the generator list.
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 1 and item_en = 'Pancha pathram and uddharani (water vessel and spoon)';
  if n <> 1 then raise exception 'ganesha_standard/1 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 6 and item_en = 'Clay or turmeric Pillaiyar (the Ganesha idol)';
  if n <> 1 then raise exception 'ganesha_standard/6 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 7 and item_en = 'Vasthram for Ganapati (a cloth for the idol)';
  if n <> 1 then raise exception 'ganesha_standard/7 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 8 and item_en = 'Poonal, a single one for Ganapati (sacred thread)';
  if n <> 1 then raise exception 'ganesha_standard/8 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 10 and item_en = 'Manjal (turmeric) powder';
  if n <> 1 then raise exception 'ganesha_standard/10 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 11 and item_en = 'Chandanam (sandalwood paste)';
  if n <> 1 then raise exception 'ganesha_standard/11 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 12 and item_en = 'Kumkumam (vermilion)';
  if n <> 1 then raise exception 'ganesha_standard/12 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 13 and item_en = 'Akshadai (rice with turmeric)';
  if n <> 1 then raise exception 'ganesha_standard/13 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 14 and item_en = 'Panchamirtham (the five-food mixture)';
  if n <> 1 then raise exception 'ganesha_standard/14 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 15 and item_en = 'Agarbatti (incense sticks)';
  if n <> 1 then raise exception 'ganesha_standard/15 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 16 and item_en = 'Kalpooram (camphor)';
  if n <> 1 then raise exception 'ganesha_standard/16 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 18 and item_en = 'Til (sesame) oil for the lamp';
  if n <> 1 then raise exception 'ganesha_standard/18 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 20 and item_en = 'Vetrilai (betel leaves)';
  if n <> 1 then raise exception 'ganesha_standard/20 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 21 and item_en = 'Paakku (areca nut)';
  if n <> 1 then raise exception 'ganesha_standard/21 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 26 and item_en = 'Maalai (flower garland)';
  if n <> 1 then raise exception 'ganesha_standard/26 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 27 and item_en = 'Thoduttha pushpam (strung flowers)';
  if n <> 1 then raise exception 'ganesha_standard/27 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 28 and item_en = 'Arugampul (durva grass)';
  if n <> 1 then raise exception 'ganesha_standard/28 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 30 and item_en = 'Thulasi (holy basil)';
  if n <> 1 then raise exception 'ganesha_standard/30 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'ganesha_standard' and seq = 31 and item_en = 'Bilvam (bael leaves)';
  if n <> 1 then raise exception 'ganesha_standard/31 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 2 and item_en = 'Shalagrama for Vishnu (the sacred stone)';
  if n <> 1 then raise exception 'nitya_panchayatana/2 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 6 and item_en = 'Pancha pathram and uddharani (water vessel and spoon)';
  if n <> 1 then raise exception 'nitya_panchayatana/6 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 10 and item_en = 'Karpoora thattu (camphor tray)';
  if n <> 1 then raise exception 'nitya_panchayatana/10 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 11 and item_en = 'Chandanam (sandalwood paste)';
  if n <> 1 then raise exception 'nitya_panchayatana/11 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 12 and item_en = 'Kumkumam (vermilion)';
  if n <> 1 then raise exception 'nitya_panchayatana/12 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 13 and item_en = 'Akshadai (rice with turmeric)';
  if n <> 1 then raise exception 'nitya_panchayatana/13 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 14 and item_en = 'Manjal (turmeric) powder';
  if n <> 1 then raise exception 'nitya_panchayatana/14 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 15 and item_en = 'Agarbatti and karpooram (incense sticks and camphor)';
  if n <> 1 then raise exception 'nitya_panchayatana/15 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 17 and item_en = 'Vetrilai and paakku (betel leaves and areca nut)';
  if n <> 1 then raise exception 'nitya_panchayatana/17 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 18 and item_en = 'Doorvai or arugampul (durva grass), for Vinayaka';
  if n <> 1 then raise exception 'nitya_panchayatana/18 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 19 and item_en = 'Thulasi (holy basil), for Vishnu';
  if n <> 1 then raise exception 'nitya_panchayatana/19 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 20 and item_en = 'Bilvam (bael leaves), for Shiva';
  if n <> 1 then raise exception 'nitya_panchayatana/20 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 21 and item_en = 'Thamarai poo (lotus), for Surya';
  if n <> 1 then raise exception 'nitya_panchayatana/21 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'nitya_panchayatana' and seq = 22 and item_en = 'Red aparajita (butterfly pea), for Devi';
  if n <> 1 then raise exception 'nitya_panchayatana/22 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 1 and item_en = 'Panchapatram (the water vessel)';
  if n <> 1 then raise exception 'sandhyavandanam/1 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 2 and item_en = 'Uddharani (the spoon water is sipped from)';
  if n <> 1 then raise exception 'sandhyavandanam/2 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 3 and item_en = 'Theertha patram (the broad plate)';
  if n <> 1 then raise exception 'sandhyavandanam/3 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 4 and item_en = 'Aasanam (the seat)';
  if n <> 1 then raise exception 'sandhyavandanam/4 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 5 and item_en = 'Jalapatram (vessel for the spare water)';
  if n <> 1 then raise exception 'sandhyavandanam/5 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 6 and item_en = 'Yajnopaveetam (the sacred thread)';
  if n <> 1 then raise exception 'sandhyavandanam/6 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'sandhyavandanam' and seq = 8 and item_en = 'Upavastram (the upper cloth)';
  if n <> 1 then raise exception 'sandhyavandanam/8 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 1 and item_en = 'Kalasham (the pot) with a Lakshmi face';
  if n <> 1 then raise exception 'varalakshmi_vratham/1 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 2 and item_en = 'Pancha pathram and uddharani (water vessel and spoon)';
  if n <> 1 then raise exception 'varalakshmi_vratham/2 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 6 and item_en = 'Karpoora thattu (camphor tray)';
  if n <> 1 then raise exception 'varalakshmi_vratham/6 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 7 and item_en = 'Eka aarathi and pancha aarathi (single-wick and five-wick camphor lamps)';
  if n <> 1 then raise exception 'varalakshmi_vratham/7 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 8 and item_en = 'Nonbu sharadu (the vow thread), nine strands with nine knots';
  if n <> 1 then raise exception 'varalakshmi_vratham/8 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 9 and item_en = 'Chandanam (sandalwood paste)';
  if n <> 1 then raise exception 'varalakshmi_vratham/9 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 10 and item_en = 'Kumkumam (vermilion)';
  if n <> 1 then raise exception 'varalakshmi_vratham/10 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 11 and item_en = 'Akshadai (rice with turmeric)';
  if n <> 1 then raise exception 'varalakshmi_vratham/11 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 12 and item_en = 'Manjal (turmeric) powder';
  if n <> 1 then raise exception 'varalakshmi_vratham/12 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 13 and item_en = 'Agarbatti and karpooram (incense sticks and camphor)';
  if n <> 1 then raise exception 'varalakshmi_vratham/13 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 14 and item_en = 'Thamarai poo (lotus flowers)';
  if n <> 1 then raise exception 'varalakshmi_vratham/14 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 16 and item_en = 'Thazam poo (screwpine flower)';
  if n <> 1 then raise exception 'varalakshmi_vratham/16 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 17 and item_en = 'Maalai or kadambam (flower garland)';
  if n <> 1 then raise exception 'varalakshmi_vratham/17 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 18 and item_en = 'Doorvai (durva grass) and thulasi (holy basil)';
  if n <> 1 then raise exception 'varalakshmi_vratham/18 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 19 and item_en = 'Bilvam (bael leaves)';
  if n <> 1 then raise exception 'varalakshmi_vratham/19 did not take its gloss'; end if;
  select count(*) into n from public.samagri_items where pooja_id = 'varalakshmi_vratham' and seq = 20 and item_en = 'Vetrilai and paakku (betel leaves and areca nut)';
  if n <> 1 then raise exception 'varalakshmi_vratham/20 did not take its gloss'; end if;

  -- And no quantity field is a glossary any more: a quantity starts with a
  -- number or says how much, it does not explain what the thing is.
  select string_agg(pooja_id || '/' || seq, ', ') into t from public.samagri_items
   where quantity is not null and quantity ~ '^[0-9].* — (the|for the) ';
  if t is not null then raise exception 'quantity still glosses the item on: %', t; end if;
end $$;


-- Carriage returns, from pasting this file into a browser SQL editor. See
-- scripts/_migration.mjs.
do $$
declare
  r record;
  n bigint;
begin
  for r in
    select c.table_name, c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and t.table_type = 'BASE TABLE'
       and c.data_type in ('text', 'character varying', 'character')
  loop
    execute format(
      'update public.%I set %I = replace(%I, chr(13), %L)'
      || ' where position(chr(13) in %I) > 0',
      r.table_name, r.column_name, r.column_name, '', r.column_name
    );
    get diagnostics n = row_count;
    if n > 0 then
      raise notice 'stripped CR from % row(s) of %.%', n, r.table_name, r.column_name;
    end if;
  end loop;
end $$;

commit;
